FFTFilter Class Reference
FFTFilter Class Reference
Processes and normalizes FFT data.
#include <FFTFilter.h>
Public Member Functions
FFTFilter ()
Constructs an FFTFilter instance with default configurations.
float GetOutput ()
Retrieves the current filtered and normalized output value.
float Filter (float value)
Filters and normalizes the input value for FFT data processing.
Private Attributes
RunningAverageFilter< 20 > minKF = RunningAverageFilter<20>(0.05f)
Running average filter for baseline normalization.
float outputValue = 0.0f
Stores the most recent filtered output value.
Detailed Description
Processes and normalizes FFT data.
The FFTFilter applies a running average filter to FFT input values, removes a baseline minimum value, and normalizes the output for stability and usability in other FFT-based functionalities.
Definition at line 26 of file FFTFilter.h.
Constructor & Destructor Documentation
FFTFilter()
FFTFilter ()
Constructs an FFTFilter instance with default configurations.
Definition at line 3 of file FFTFilter.cpp.
Member Function Documentation
Filter()
float Filter (float value)
Filters and normalizes the input value for FFT data processing.
Parameters
value The current FFT input value.
Returns
The filtered and normalized FFT value.
Definition at line 9 of file FFTFilter.cpp.
References Mathematics::Constrain(), RunningAverageFilter< memory >::Filter(), minKF, and outputValue.
Referenced by MicrophoneFourier::Update(), and MicrophoneFourier::UpdateDMA().
GetOutput()
float GetOutput ()
Retrieves the current filtered and normalized output value.
Returns
The most recent filtered output value.
Definition at line 5 of file FFTFilter.cpp.
References outputValue.
Member Data Documentation
minKF
RunningAverageFilter<20> minKF = RunningAverageFilter<20>(0.05f) private
Running average filter for baseline normalization.
Definition at line 28 of file FFTFilter.h.
Referenced by Filter().
outputValue
float outputValue = 0.0f private
Stores the most recent filtered output value.
Definition at line 29 of file FFTFilter.h.
Referenced by Filter(), and GetOutput().
The documentation for this class was generated from the following files:
FFTFilter.h
FFTFilter.cpp