SerialInterpreter Class Reference
SerialInterpreter Class Reference
#include <SerialInterpreter.h>
Classes
struct ESP32Data
Static Public Member Functions
static void Initialize ()
static RGBColor GetColor ()
static Quaternion GetOrientation ()
static float GetRatio ()
static uint8_t GetMode ()
static uint8_t GetMorph ()
static void Update ()
Static Private Attributes
static Quaternion baseRotation
static bool baseRotationSet
static struct SerialInterpreter::ESP32Data e32Data
static SerialTransfer dataTransfer
Detailed Description
Definition at line 7 of file SerialInterpreter.h.
Member Function Documentation
GetColor()
RGBColor GetColor () static
Definition at line 15 of file SerialInterpreter.cpp.
References SerialInterpreter::ESP32Data::b, e32Data, SerialInterpreter::ESP32Data::g, and SerialInterpreter::ESP32Data::r.
Referenced by SpyroRotateAnimation::Update().
GetMode()
uint8_t GetMode () static
Definition at line 34 of file SerialInterpreter.cpp.
References e32Data, and SerialInterpreter::ESP32Data::mode.
GetMorph()
uint8_t GetMorph () static
Definition at line 38 of file SerialInterpreter.cpp.
References e32Data, and SerialInterpreter::ESP32Data::m.
GetOrientation()
Quaternion GetOrientation () static
Definition at line 19 of file SerialInterpreter.cpp.
References baseRotation, baseRotationSet, Quaternion::Conjugate(), e32Data, Quaternion::Multiply(), SerialInterpreter::ESP32Data::oW, SerialInterpreter::ESP32Data::oX, SerialInterpreter::ESP32Data::oY, and SerialInterpreter::ESP32Data::oZ.
Referenced by SpyroRotateAnimation::Update().
GetRatio()
float GetRatio () static
Definition at line 30 of file SerialInterpreter.cpp.
References e32Data, and SerialInterpreter::ESP32Data::ratio.
Initialize()
void Initialize () static
Definition at line 9 of file SerialInterpreter.cpp.
References baseRotationSet, and dataTransfer.
Referenced by SpyroRotateAnimation::SpyroRotateAnimation().
Update()
void Update () static
Definition at line 42 of file SerialInterpreter.cpp.
References dataTransfer, and e32Data.
Referenced by SpyroRotateAnimation::Update().
Member Data Documentation
baseRotation
Quaternion baseRotation static private
Definition at line 9 of file SerialInterpreter.h.
Referenced by GetOrientation().
baseRotationSet
bool baseRotationSet static private
Definition at line 10 of file SerialInterpreter.h.
Referenced by GetOrientation(), and Initialize().
dataTransfer
SerialTransfer dataTransfer static private
Definition at line 27 of file SerialInterpreter.h.
Referenced by Initialize(), and Update().
e32Data
SerialInterpreter::ESP32Data e32Data static private
Definition at line 7 of file SerialInterpreter.cpp.
Referenced by GetColor(), GetMode(), GetMorph(), GetOrientation(), GetRatio(), and Update().
The documentation for this class was generated from the following files:
SerialInterpreter.h
SerialInterpreter.cpp