VesperAnimation Class Reference
VesperAnimation Class Reference
#include <VesperAnimation.h>
Public Member Functions
VesperAnimation ()
void UpdateKeyFrameTracks ()
void Default ()
void Angry ()
void Sad ()
void Surprised ()
void Doubt ()
void Frown ()
void LookUp ()
void LookDown ()
void SpectrumAnalyzerFace ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
Object3D * GetObject ()
void UpdateFFTVisemes ()
void Update (float ratio) override
Private Member Functions
void LinkEasyEase ()
void LinkParameters ()
void ChangeInterpolationMethods ()
void SetMaterials ()
Private Attributes
NukudeFace pM
Background background
EasyEaseAnimator< 20 > eEA = EasyEaseAnimator<20>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f)
RainbowNoise rainbowNoise
RainbowSpiral rainbowSpiral
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0))
RGBColor gradientSpectrum [2] = {RGBColor(25, 50, 255), RGBColor(50, 255, 50)}
GradientMaterial< 2 > gradientMat = GradientMaterial<2>(gradientSpectrum, 350.0f, false)
CombineMaterial< 4 > faceMaterial
SpectrumAnalyzer sA = SpectrumAnalyzer(22, Vector2D(250, 200), Vector2D(120, 100), true, true)
BlinkTrack< 1 > blink
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f)
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f)
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f)
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.5f, 2.5f, 5.3f)
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.5f, 2.5f, 6.7f)
BoopSensor boop
float rainbowFaceMix = 0.0f
float angryFaceMix = 0.0f
uint8_t rainbowFaceIndex = 50
uint8_t angryFaceIndex = 51
FFTVoiceDetection< 128 > voiceDetection
Detailed Description
Definition at line 23 of file VesperAnimation.h.
Constructor & Destructor Documentation
VesperAnimation()
VesperAnimation () inline
Definition at line 110 of file VesperAnimation.h.
References background, boop, ChangeInterpolationMethods(), faceMaterial, LinkEasyEase(), LinkParameters(), pM, sA, and SetMaterials().
Member Function Documentation
Angry()
void Angry () inline
Definition at line 135 of file VesperAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), angryFaceIndex, and eEA.
Referenced by Update().
ChangeInterpolationMethods()
void ChangeInterpolationMethods () inline private
Definition at line 86 of file VesperAnimation.h.
References angryFaceIndex, eEA, rainbowFaceIndex, and EasyEaseAnimator< maxParameters >::SetInterpolationMethod().
Referenced by VesperAnimation().
Default()
void Default () inline
Definition at line 133 of file VesperAnimation.h.
Referenced by Update().
Doubt()
void Doubt () inline
Definition at line 151 of file VesperAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
Referenced by Update().
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 172 of file VesperAnimation.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 173 of file VesperAnimation.h.
Frown()
void Frown () inline
Definition at line 155 of file VesperAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
Referenced by Update().
GetObject()
Object3D * GetObject () inline
Definition at line 175 of file VesperAnimation.h.
References pM.
LinkEasyEase()
void LinkEasyEase () inline private
Definition at line 58 of file VesperAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameter(), angryFaceIndex, angryFaceMix, eEA, pM, rainbowFaceIndex, and rainbowFaceMix.
Referenced by VesperAnimation().
LinkParameters()
void LinkParameters () inline private
Definition at line 82 of file VesperAnimation.h.
References AnimationTrack< maxParameters, maxKeyFrames >::AddParameter(), blink, and pM.
Referenced by VesperAnimation().
LookDown()
void LookDown () inline
Definition at line 163 of file VesperAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
LookUp()
void LookUp () inline
Definition at line 159 of file VesperAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
Referenced by Update().
Sad()
void Sad () inline
Definition at line 140 of file VesperAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
Referenced by Update().
SetMaterials()
void SetMaterials () inline private
Definition at line 102 of file VesperAnimation.h.
References Material::Add, CombineMaterial< materialCount >::AddMaterial(), faceMaterial, gradientMat, Material::Lighten, rainbowNoise, rainbowSpiral, redMaterial, and Material::Replace.
Referenced by VesperAnimation().
SpectrumAnalyzerFace()
void SpectrumAnalyzerFace () inline
Definition at line 167 of file VesperAnimation.h.
References background, and pM.
Referenced by Update().
Surprised()
void Surprised () inline
Definition at line 145 of file VesperAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, and rainbowFaceIndex.
Referenced by Update().
Update()
void Update (float ratio) inline override
Definition at line 197 of file VesperAnimation.h.
References Angry(), angryFaceMix, background, boop, Default(), Doubt(), eEA, faceMaterial, fGenMatXMove, fGenMatYMove, Frown(), MicrophoneFourierBase::GetFourierFiltered(), LookUp(), pM, rainbowFaceMix, rainbowNoise, rainbowSpiral, sA, Sad(), SpectrumAnalyzer::SetFlipYState(), SpectrumAnalyzer::SetHueAngle(), SpectrumAnalyzer::SetMirrorYState(), CombineMaterial< materialCount >::SetOpacity(), SpectrumAnalyzerFace(), Surprised(), MicrophoneFourier::Update(), FunctionGenerator::Update(), EasyEaseAnimator< maxParameters >::Update(), SpectrumAnalyzer::Update(), RainbowNoise::Update(), RainbowSpiral::Update(), UpdateFFTVisemes(), and UpdateKeyFrameTracks().
UpdateFFTVisemes()
void UpdateFFTVisemes () inline
Definition at line 179 of file VesperAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), Viseme::AH, Viseme::AR, Viseme::EE, eEA, Viseme::ER, MicrophoneFourierBase::GetCurrentMagnitude(), MicrophoneFourierBase::GetFourierFiltered(), MicrophoneFourierBase::GetSampleRate(), FFTVoiceDetection< peakCount >::GetViseme(), Viseme::OO, Viseme::UH, FFTVoiceDetection< peakCount >::Update(), and voiceDetection.
Referenced by Update().
UpdateKeyFrameTracks()
void UpdateKeyFrameTracks () inline
Definition at line 129 of file VesperAnimation.h.
References blink, and AnimationTrack< maxParameters, maxKeyFrames >::Update().
Referenced by Update().
Member Data Documentation
angryFaceIndex
uint8_t angryFaceIndex = 51 private
Definition at line 54 of file VesperAnimation.h.
Referenced by Angry(), ChangeInterpolationMethods(), and LinkEasyEase().
angryFaceMix
float angryFaceMix = 0.0f private
Definition at line 52 of file VesperAnimation.h.
Referenced by LinkEasyEase(), and Update().
background
Background background private
Definition at line 26 of file VesperAnimation.h.
Referenced by SpectrumAnalyzerFace(), Update(), and VesperAnimation().
blink
BlinkTrack<1> blink private
Definition at line 42 of file VesperAnimation.h.
Referenced by LinkParameters(), and UpdateKeyFrameTracks().
boop
BoopSensor boop private
Definition at line 50 of file VesperAnimation.h.
Referenced by Update(), and VesperAnimation().
eEA
EasyEaseAnimator<20> eEA = EasyEaseAnimator<20>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f) private
Definition at line 27 of file VesperAnimation.h.
Referenced by Angry(), ChangeInterpolationMethods(), Doubt(), Frown(), LinkEasyEase(), LookDown(), LookUp(), Sad(), Surprised(), Update(), and UpdateFFTVisemes().
faceMaterial
CombineMaterial<4> faceMaterial private
Definition at line 37 of file VesperAnimation.h.
Referenced by SetMaterials(), Update(), and VesperAnimation().
fGenMatPos
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f) private
Definition at line 44 of file VesperAnimation.h.
fGenMatXMove
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.5f, 2.5f, 5.3f) private
Definition at line 47 of file VesperAnimation.h.
Referenced by Update().
fGenMatYMove
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.5f, 2.5f, 6.7f) private
Definition at line 48 of file VesperAnimation.h.
Referenced by Update().
fGenRotation
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f) private
Definition at line 45 of file VesperAnimation.h.
fGenScale
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f) private
Definition at line 46 of file VesperAnimation.h.
gradientMat
GradientMaterial<2> gradientMat = GradientMaterial<2>(gradientSpectrum, 350.0f, false) private
Definition at line 35 of file VesperAnimation.h.
Referenced by SetMaterials().
gradientSpectrum
RGBColor gradientSpectrum[2] = {RGBColor(25, 50, 255), RGBColor(50, 255, 50)} private
Definition at line 34 of file VesperAnimation.h.
pM
NukudeFace pM private
Definition at line 25 of file VesperAnimation.h.
Referenced by GetObject(), LinkEasyEase(), LinkParameters(), SpectrumAnalyzerFace(), Update(), and VesperAnimation().
rainbowFaceIndex
uint8_t rainbowFaceIndex = 50 private
Definition at line 53 of file VesperAnimation.h.
Referenced by ChangeInterpolationMethods(), LinkEasyEase(), and Surprised().
rainbowFaceMix
float rainbowFaceMix = 0.0f private
Definition at line 51 of file VesperAnimation.h.
Referenced by LinkEasyEase(), and Update().
rainbowNoise
RainbowNoise rainbowNoise private
Definition at line 30 of file VesperAnimation.h.
Referenced by SetMaterials(), and Update().
rainbowSpiral
RainbowSpiral rainbowSpiral private
Definition at line 31 of file VesperAnimation.h.
Referenced by SetMaterials(), and Update().
redMaterial
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0)) private
Definition at line 32 of file VesperAnimation.h.
Referenced by SetMaterials().
sA
SpectrumAnalyzer sA = SpectrumAnalyzer(22, Vector2D(250, 200), Vector2D(120, 100), true, true) private
Definition at line 39 of file VesperAnimation.h.
Referenced by Update(), and VesperAnimation().
voiceDetection
FFTVoiceDetection<128> voiceDetection private
Definition at line 56 of file VesperAnimation.h.
Referenced by UpdateFFTVisemes().
The documentation for this class was generated from the following file:
VesperAnimation.h