ProtobottAnimation Class Reference
ProtobottAnimation Class Reference
#include <ProtobottAnimation.h>
Public Member Functions
ProtobottAnimation ()
void UpdateKeyFrameTracks ()
void Default ()
void Angry ()
void Sad ()
void Surprised ()
void Doubt ()
void Frown ()
void LookUp ()
void LookDown ()
void SpectrumAnalyzerFace ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
Object3D * GetObject ()
void UpdateFFTVisemes ()
void Update (float ratio) override
Private Member Functions
void LinkEasyEase ()
void LinkParameters ()
void ChangeInterpolationMethods ()
void SetMaterials ()
Private Attributes
NukudeFace pM
Background background
EasyEaseAnimator< 20 > eEA = EasyEaseAnimator<20>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f)
RainbowNoise rainbowNoise
RainbowSpiral rainbowSpiral
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0))
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255))
RGBColor gradientSpectrum [2] = {RGBColor(255, 0, 0), RGBColor(255, 255, 0)}
GradientMaterial< 2 > gradientMat = GradientMaterial<2>(gradientSpectrum, 350.0f, false)
CombineMaterial< 5 > faceMaterial
SpectrumAnalyzer sA = SpectrumAnalyzer(A0, Vector2D(200, 100), Vector2D(100, 50), true, true)
BlinkTrack< 1 > blink
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f)
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f)
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f)
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 5.3f)
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 6.7f)
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f)
BoopSensor boop
float rainbowFaceMix = 0.0f
float angryFaceMix = 0.0f
float sadFaceMix = 0.0f
uint8_t rainbowFaceIndex = 50
uint8_t angryFaceIndex = 51
uint8_t sadFaceIndex = 52
FFTVoiceDetection< 128 > voiceDetection
Detailed Description
Definition at line 23 of file ProtobottAnimation.h.
Constructor & Destructor Documentation
ProtobottAnimation()
ProtobottAnimation () inline
Definition at line 117 of file ProtobottAnimation.h.
References background, boop, ChangeInterpolationMethods(), faceMaterial, LinkEasyEase(), LinkParameters(), pM, sA, and SetMaterials().
Member Function Documentation
Angry()
void Angry () inline
Definition at line 142 of file ProtobottAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), angryFaceIndex, and eEA.
Referenced by Update().
ChangeInterpolationMethods()
void ChangeInterpolationMethods () inline private
Definition at line 91 of file ProtobottAnimation.h.
References angryFaceIndex, eEA, rainbowFaceIndex, sadFaceIndex, and EasyEaseAnimator< maxParameters >::SetInterpolationMethod().
Referenced by ProtobottAnimation().
Default()
void Default () inline
Definition at line 140 of file ProtobottAnimation.h.
Referenced by Update().
Doubt()
void Doubt () inline
Definition at line 159 of file ProtobottAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
Referenced by Update().
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 180 of file ProtobottAnimation.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 181 of file ProtobottAnimation.h.
Frown()
void Frown () inline
Definition at line 163 of file ProtobottAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
Referenced by Update().
GetObject()
Object3D * GetObject () inline
Definition at line 183 of file ProtobottAnimation.h.
References pM.
LinkEasyEase()
void LinkEasyEase () inline private
Definition at line 62 of file ProtobottAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameter(), angryFaceIndex, angryFaceMix, eEA, pM, rainbowFaceIndex, rainbowFaceMix, sadFaceIndex, and sadFaceMix.
Referenced by ProtobottAnimation().
LinkParameters()
void LinkParameters () inline private
Definition at line 87 of file ProtobottAnimation.h.
References AnimationTrack< maxParameters, maxKeyFrames >::AddParameter(), blink, and pM.
Referenced by ProtobottAnimation().
LookDown()
void LookDown () inline
Definition at line 171 of file ProtobottAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
LookUp()
void LookUp () inline
Definition at line 167 of file ProtobottAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
Referenced by Update().
Sad()
void Sad () inline
Definition at line 147 of file ProtobottAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, and sadFaceIndex.
Referenced by Update().
SetMaterials()
void SetMaterials () inline private
Definition at line 108 of file ProtobottAnimation.h.
References Material::Add, CombineMaterial< materialCount >::AddMaterial(), blueMaterial, faceMaterial, gradientMat, Material::Lighten, rainbowNoise, rainbowSpiral, redMaterial, and Material::Replace.
Referenced by ProtobottAnimation().
SpectrumAnalyzerFace()
void SpectrumAnalyzerFace () inline
Definition at line 175 of file ProtobottAnimation.h.
References background, and pM.
Referenced by Update().
Surprised()
void Surprised () inline
Definition at line 153 of file ProtobottAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, and rainbowFaceIndex.
Referenced by Update().
Update()
void Update (float ratio) inline override
Definition at line 205 of file ProtobottAnimation.h.
References Angry(), angryFaceMix, background, boop, Default(), Doubt(), eEA, faceMaterial, fGenMatHue, fGenMatXMove, fGenMatYMove, Frown(), MicrophoneFourierBase::GetFourierFiltered(), gradientMat, GradientMaterial< colorCount >::HueShift(), LookUp(), pM, rainbowFaceMix, rainbowNoise, rainbowSpiral, sA, Sad(), sadFaceMix, SpectrumAnalyzer::SetFlipYState(), SpectrumAnalyzer::SetHueAngle(), SpectrumAnalyzer::SetMirrorYState(), CombineMaterial< materialCount >::SetOpacity(), SpectrumAnalyzerFace(), Surprised(), MicrophoneFourier::Update(), FunctionGenerator::Update(), EasyEaseAnimator< maxParameters >::Update(), SpectrumAnalyzer::Update(), RainbowNoise::Update(), RainbowSpiral::Update(), UpdateFFTVisemes(), and UpdateKeyFrameTracks().
UpdateFFTVisemes()
void UpdateFFTVisemes () inline
Definition at line 187 of file ProtobottAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), Viseme::AH, Viseme::AR, Viseme::EE, eEA, Viseme::ER, MicrophoneFourierBase::GetCurrentMagnitude(), MicrophoneFourierBase::GetFourierFiltered(), MicrophoneFourierBase::GetSampleRate(), FFTVoiceDetection< peakCount >::GetViseme(), Viseme::OO, Viseme::UH, FFTVoiceDetection< peakCount >::Update(), and voiceDetection.
Referenced by Update().
UpdateKeyFrameTracks()
void UpdateKeyFrameTracks () inline
Definition at line 136 of file ProtobottAnimation.h.
References blink, and AnimationTrack< maxParameters, maxKeyFrames >::Update().
Referenced by Update().
Member Data Documentation
angryFaceIndex
uint8_t angryFaceIndex = 51 private
Definition at line 57 of file ProtobottAnimation.h.
Referenced by Angry(), ChangeInterpolationMethods(), and LinkEasyEase().
angryFaceMix
float angryFaceMix = 0.0f private
Definition at line 54 of file ProtobottAnimation.h.
Referenced by LinkEasyEase(), and Update().
background
Background background private
Definition at line 26 of file ProtobottAnimation.h.
Referenced by ProtobottAnimation(), SpectrumAnalyzerFace(), and Update().
blink
BlinkTrack<1> blink private
Definition at line 43 of file ProtobottAnimation.h.
Referenced by LinkParameters(), and UpdateKeyFrameTracks().
blueMaterial
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255)) private
Definition at line 33 of file ProtobottAnimation.h.
Referenced by SetMaterials().
boop
BoopSensor boop private
Definition at line 52 of file ProtobottAnimation.h.
Referenced by ProtobottAnimation(), and Update().
eEA
EasyEaseAnimator<20> eEA = EasyEaseAnimator<20>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f) private
Definition at line 27 of file ProtobottAnimation.h.
Referenced by Angry(), ChangeInterpolationMethods(), Doubt(), Frown(), LinkEasyEase(), LookDown(), LookUp(), Sad(), Surprised(), Update(), and UpdateFFTVisemes().
faceMaterial
CombineMaterial<5> faceMaterial private
Definition at line 38 of file ProtobottAnimation.h.
Referenced by ProtobottAnimation(), SetMaterials(), and Update().
fGenMatHue
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f) private
Definition at line 50 of file ProtobottAnimation.h.
Referenced by Update().
fGenMatPos
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f) private
Definition at line 45 of file ProtobottAnimation.h.
fGenMatXMove
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 5.3f) private
Definition at line 48 of file ProtobottAnimation.h.
Referenced by Update().
fGenMatYMove
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 6.7f) private
Definition at line 49 of file ProtobottAnimation.h.
Referenced by Update().
fGenRotation
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f) private
Definition at line 46 of file ProtobottAnimation.h.
fGenScale
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f) private
Definition at line 47 of file ProtobottAnimation.h.
gradientMat
GradientMaterial<2> gradientMat = GradientMaterial<2>(gradientSpectrum, 350.0f, false) private
Definition at line 36 of file ProtobottAnimation.h.
Referenced by SetMaterials(), and Update().
gradientSpectrum
RGBColor gradientSpectrum[2] = {RGBColor(255, 0, 0), RGBColor(255, 255, 0)} private
Definition at line 35 of file ProtobottAnimation.h.
pM
NukudeFace pM private
Definition at line 25 of file ProtobottAnimation.h.
Referenced by GetObject(), LinkEasyEase(), LinkParameters(), ProtobottAnimation(), SpectrumAnalyzerFace(), and Update().
rainbowFaceIndex
uint8_t rainbowFaceIndex = 50 private
Definition at line 56 of file ProtobottAnimation.h.
Referenced by ChangeInterpolationMethods(), LinkEasyEase(), and Surprised().
rainbowFaceMix
float rainbowFaceMix = 0.0f private
Definition at line 53 of file ProtobottAnimation.h.
Referenced by LinkEasyEase(), and Update().
rainbowNoise
RainbowNoise rainbowNoise private
Definition at line 30 of file ProtobottAnimation.h.
Referenced by SetMaterials(), and Update().
rainbowSpiral
RainbowSpiral rainbowSpiral private
Definition at line 31 of file ProtobottAnimation.h.
Referenced by SetMaterials(), and Update().
redMaterial
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0)) private
Definition at line 32 of file ProtobottAnimation.h.
Referenced by SetMaterials().
sA
SpectrumAnalyzer sA = SpectrumAnalyzer(A0, Vector2D(200, 100), Vector2D(100, 50), true, true) private
Definition at line 40 of file ProtobottAnimation.h.
Referenced by ProtobottAnimation(), and Update().
sadFaceIndex
uint8_t sadFaceIndex = 52 private
Definition at line 58 of file ProtobottAnimation.h.
Referenced by ChangeInterpolationMethods(), LinkEasyEase(), and Sad().
sadFaceMix
float sadFaceMix = 0.0f private
Definition at line 55 of file ProtobottAnimation.h.
Referenced by LinkEasyEase(), and Update().
voiceDetection
FFTVoiceDetection<128> voiceDetection private
Definition at line 60 of file ProtobottAnimation.h.
Referenced by UpdateFFTVisemes().
The documentation for this class was generated from the following file:
ProtobottAnimation.h