ESP32DevKitV1 Class Reference
ESP32DevKitV1 Class Reference
#include <ESP32DevKitV1.h>
Public Member Functions
ESP32DevKitV1 (uint8_t maxBrightness)
void Initialize () override
Initializes the controller.
void Display () override
Updates and displays content on the lighting system.
Public Member Functions inherited from Controller
uint8_t GetBrightness ()
Retrieves the current brightness level.
uint8_t GetAccentBrightness ()
Retrieves the current accent brightness level.
virtual void SetBrightness (uint8_t maxBrightness)=0
Sets the maximum brightness for the controller.
virtual void SetAccentBrightness (uint8_t maxAccentBrightness)=0
Sets the maximum accent brightness for the controller.
Private Attributes
Transform camTransform1 = Transform(Vector3D(), Vector3D(0, 0.0f, 0), Vector3D(1, 1, 1))
Transform camTransform2 = Transform(Vector3D(), Vector3D(0, 96.0f, 0), Vector3D(1, 1, 1))
Vector2D size = Vector2D(192.0f, 96.0f)
Vector2D position = Vector2D(0.0f, 0.0f)
PixelGroup camPixels1 = PixelGroup(size, position, 64, 2048)
PixelGroup camPixels2 = PixelGroup(size, position, 64, 2048)
Camera camMain1 = Camera(&camTransform1, &camPixels1)
Camera camMain2 = Camera(&camTransform2, &camPixels2)
Camera * cameras [2] = { &camMain1, &camMain2 }
Additional Inherited Members
Protected Member Functions inherited from Controller
Controller (CameraManager *cameras, uint8_t maxBrightness, uint8_t maxAccentBrightness)
Constructs a Controller with specified parameters.
void UpdateBrightness ()
Updates the brightness based on internal logic.
Protected Attributes inherited from Controller
CameraManager * cameras
Pointer to the CameraManager for managing camera data.
uint8_t brightness
Current brightness level.
uint8_t accentBrightness
Current accent brightness level.
uint8_t maxBrightness
Maximum allowed brightness level.
uint8_t maxAccentBrightness
Maximum allowed accent brightness level.
bool isOn = false
Indicates if the controller is active.
bool startTime = false
Indicates if the start time has been recorded.
Detailed Description
Definition at line 28 of file ESP32DevKitV1.h.
Constructor & Destructor Documentation
ESP32DevKitV1()
ESP32DevKitV1 (uint8_t maxBrightness) inline
Definition at line 46 of file ESP32DevKitV1.h.
Member Function Documentation
Display()
void Display () inline override virtual
Updates and displays content on the lighting system.
Implements Controller.
Definition at line 73 of file ESP32DevKitV1.h.
References RGBColor::B, Controller::brightness, camPixels1, camPixels2, dma_display, RGBColor::G, PixelGroup< pixelCount >::GetColor(), RGBColor::R, and virtualDisp.
Initialize()
void Initialize () inline override virtual
Initializes the controller.
Implements Controller.
Definition at line 48 of file ESP32DevKitV1.h.
References dma_display, NUM_COLS, NUM_ROWS, PANEL_CHAIN, PANEL_RES_X, PANEL_RES_Y, SERPENT, and virtualDisp.
Member Data Documentation
cameras
Camera* cameras[2] = { &camMain1, &camMain2 } private
Definition at line 43 of file ESP32DevKitV1.h.
camMain1
Camera camMain1 = Camera(&camTransform1, &camPixels1) private
Definition at line 39 of file ESP32DevKitV1.h.
camMain2
Camera camMain2 = Camera(&camTransform2, &camPixels2) private
Definition at line 40 of file ESP32DevKitV1.h.
camPixels1
PixelGroup camPixels1 = PixelGroup(size, position, 64, 2048) private
Definition at line 36 of file ESP32DevKitV1.h.
Referenced by Display().
camPixels2
PixelGroup camPixels2 = PixelGroup(size, position, 64, 2048) private
Definition at line 37 of file ESP32DevKitV1.h.
Referenced by Display().
camTransform1
Transform camTransform1 = Transform(Vector3D(), Vector3D(0, 0.0f, 0), Vector3D(1, 1, 1)) private
Definition at line 30 of file ESP32DevKitV1.h.
camTransform2
Transform camTransform2 = Transform(Vector3D(), Vector3D(0, 96.0f, 0), Vector3D(1, 1, 1)) private
Definition at line 31 of file ESP32DevKitV1.h.
position
Vector2D position = Vector2D(0.0f, 0.0f) private
Definition at line 34 of file ESP32DevKitV1.h.
size
Vector2D size = Vector2D(192.0f, 96.0f) private
Definition at line 33 of file ESP32DevKitV1.h.
The documentation for this class was generated from the following file:
ESP32DevKitV1.h