ClockAnimation Class Reference
ClockAnimation Class Reference
#include <ClockProject.h>
Public Member Functions
ClockAnimation ()
void Initialize () override
uint8_t GetAccentBrightness ()
uint8_t GetBrightness ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
Object3D * GetObject ()
void Update (float ratio) override
Private Member Functions
void LinkEasyEase ()
void ChangeInterpolationMethods ()
void SetMaterialLayers ()
Private Attributes
Background background
RunningAverageFilter< 25 > rAF = RunningAverageFilter<25>()
APDS9960 apds
Clock clock = Clock(false)
float brightness = 255.0f
RainbowNoise rainbowNoise
RainbowNoise2 rainbowNoise2
RainbowSpiral rainbowSpiral
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0))
SimpleMaterial orangeMaterial = SimpleMaterial(RGBColor(255, 165, 0))
SimpleMaterial whiteMaterial = SimpleMaterial(RGBColor(255, 255, 255))
SimpleMaterial greenMaterial = SimpleMaterial(RGBColor(0, 255, 0))
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255))
SimpleMaterial yellowMaterial = SimpleMaterial(RGBColor(255, 255, 0))
SimpleMaterial purpleMaterial = SimpleMaterial(RGBColor(255, 0, 255))
SimpleMaterial pinkMaterial = SimpleMaterial(RGBColor(227, 11, 92))
SimpleMaterial blackMaterial = SimpleMaterial(RGBColor(0, 0, 0))
Rectangle sadRect = Rectangle(Vector2D(48.0f, 48.0f), Vector2D(140.0f, 100.0f), 0.0f)
MaterialMask sadMaterial = MaterialMask(&blackMaterial, &rainbowNoise, &sadRect)
CombineMaterial< 4 > material
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -20.0f, 20.0f, 16.0f)
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f)
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 1.0f, 1.1f, 4.2f)
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -1.0f, 1.0f, 4.3f)
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -1.0f, 1.0f, 4.7f)
FunctionGenerator fGenMatRot = FunctionGenerator(FunctionGenerator::Sine, -5.0f, 5.0f, 1.63f)
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f)
FunctionGenerator fGenMatFade = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 15.63f)
Detailed Description
Definition at line 29 of file ClockProject.h.
Constructor & Destructor Documentation
ClockAnimation()
ClockAnimation () inline
Definition at line 83 of file ClockProject.h.
References background, ChangeInterpolationMethods(), clock, getTeensy3Time(), LinkEasyEase(), material, rainbowNoise, Clock::SetMaterial(), and SetMaterialLayers().
Member Function Documentation
ChangeInterpolationMethods()
void ChangeInterpolationMethods () inline private
Definition at line 73 of file ClockProject.h.
Referenced by ClockAnimation().
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 113 of file ClockProject.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 114 of file ClockProject.h.
GetAccentBrightness()
uint8_t GetAccentBrightness () inline
Definition at line 103 of file ClockProject.h.
GetBrightness()
uint8_t GetBrightness () inline
Definition at line 107 of file ClockProject.h.
References brightness.
GetObject()
Object3D * GetObject () inline
Definition at line 116 of file ClockProject.h.
References background.
Initialize()
void Initialize () inline override
Definition at line 99 of file ClockProject.h.
References apds, and APDS9960::Initialize().
LinkEasyEase()
void LinkEasyEase () inline private
Definition at line 69 of file ClockProject.h.
Referenced by ClockAnimation().
SetMaterialLayers()
void SetMaterialLayers () inline private
Definition at line 77 of file ClockProject.h.
References CombineMaterial< materialCount >::AddMaterial(), Material::Base, clock, material, rainbowNoise2, and Material::Replace.
Referenced by ClockAnimation().
Update()
void Update (float ratio) inline override
Definition at line 120 of file ClockProject.h.
References apds, brightness, clock, Mathematics::Constrain(), fGenMatFade, RunningAverageFilter< memory >::Filter(), APDS9960::GetBrightness(), Mathematics::Map(), material, rAF, rainbowNoise, rainbowNoise2, rainbowSpiral, Clock::SetDate(), CombineMaterial< materialCount >::SetOpacity(), Clock::SetPosition(), Clock::SetRotation(), Clock::SetSize(), Clock::SetTime(), Clock::Update(), FunctionGenerator::Update(), RainbowNoise::Update(), RainbowNoise2::Update(), and RainbowSpiral::Update().
Member Data Documentation
apds
APDS9960 apds private
Definition at line 34 of file ClockProject.h.
Referenced by Initialize(), and Update().
background
Background background private
Definition at line 31 of file ClockProject.h.
Referenced by ClockAnimation(), and GetObject().
blackMaterial
SimpleMaterial blackMaterial = SimpleMaterial(RGBColor(0, 0, 0)) private
Definition at line 50 of file ClockProject.h.
blueMaterial
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255)) private
Definition at line 46 of file ClockProject.h.
brightness
float brightness = 255.0f private
Definition at line 36 of file ClockProject.h.
Referenced by GetBrightness(), and Update().
clock
Clock clock = Clock(false) private
Definition at line 35 of file ClockProject.h.
Referenced by ClockAnimation(), SetMaterialLayers(), and Update().
fGenMatFade
FunctionGenerator fGenMatFade = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 15.63f) private
Definition at line 67 of file ClockProject.h.
Referenced by Update().
fGenMatHue
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f) private
Definition at line 64 of file ClockProject.h.
fGenMatPos
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -20.0f, 20.0f, 16.0f) private
Definition at line 58 of file ClockProject.h.
fGenMatRot
FunctionGenerator fGenMatRot = FunctionGenerator(FunctionGenerator::Sine, -5.0f, 5.0f, 1.63f) private
Definition at line 63 of file ClockProject.h.
fGenMatXMove
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -1.0f, 1.0f, 4.3f) private
Definition at line 61 of file ClockProject.h.
fGenMatYMove
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -1.0f, 1.0f, 4.7f) private
Definition at line 62 of file ClockProject.h.
fGenRotation
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f) private
Definition at line 59 of file ClockProject.h.
fGenScale
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 1.0f, 1.1f, 4.2f) private
Definition at line 60 of file ClockProject.h.
greenMaterial
SimpleMaterial greenMaterial = SimpleMaterial(RGBColor(0, 255, 0)) private
Definition at line 45 of file ClockProject.h.
material
CombineMaterial<4> material private
Definition at line 56 of file ClockProject.h.
Referenced by ClockAnimation(), SetMaterialLayers(), and Update().
orangeMaterial
SimpleMaterial orangeMaterial = SimpleMaterial(RGBColor(255, 165, 0)) private
Definition at line 43 of file ClockProject.h.
pinkMaterial
SimpleMaterial pinkMaterial = SimpleMaterial(RGBColor(227, 11, 92)) private
Definition at line 49 of file ClockProject.h.
purpleMaterial
SimpleMaterial purpleMaterial = SimpleMaterial(RGBColor(255, 0, 255)) private
Definition at line 48 of file ClockProject.h.
rAF
RunningAverageFilter<25> rAF = RunningAverageFilter<25>() private
Definition at line 33 of file ClockProject.h.
Referenced by Update().
rainbowNoise
RainbowNoise rainbowNoise private
Definition at line 39 of file ClockProject.h.
Referenced by ClockAnimation(), and Update().
rainbowNoise2
RainbowNoise2 rainbowNoise2 private
Definition at line 40 of file ClockProject.h.
Referenced by SetMaterialLayers(), and Update().
rainbowSpiral
RainbowSpiral rainbowSpiral private
Definition at line 41 of file ClockProject.h.
Referenced by Update().
redMaterial
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0)) private
Definition at line 42 of file ClockProject.h.
sadMaterial
MaterialMask sadMaterial = MaterialMask(&blackMaterial, &rainbowNoise, &sadRect) private
Definition at line 54 of file ClockProject.h.
sadRect
Rectangle sadRect = Rectangle(Vector2D(48.0f, 48.0f), Vector2D(140.0f, 100.0f), 0.0f) private
Definition at line 52 of file ClockProject.h.
whiteMaterial
SimpleMaterial whiteMaterial = SimpleMaterial(RGBColor(255, 255, 255)) private
Definition at line 44 of file ClockProject.h.
yellowMaterial
SimpleMaterial yellowMaterial = SimpleMaterial(RGBColor(255, 255, 0)) private
Definition at line 47 of file ClockProject.h.
The documentation for this class was generated from the following file:
ClockProject.h