TechSaneAnimation Class Reference
TechSaneAnimation Class Reference
#include <TechSaneAnimation.h>
Public Member Functions
TechSaneAnimation ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
Object3D * GetObject ()
void SetCameraMirror (bool mirror)
void Update (float ratio) override
Private Member Functions
void LinkEasyEase ()
void LinkParameters ()
void ChangeInterpolationMethods ()
void SetMaterialLayers ()
void UpdateKeyFrameTracks ()
void Default ()
void Angry ()
void Sad ()
void Surprised ()
void Doubt ()
void Frown ()
void LookUp ()
void LookDown ()
void SpectrumAnalyzerFace ()
void AudioReactiveGradientFace ()
void OscilloscopeFace ()
void TechSaneFace ()
void UpdateFFTVisemes ()
void SetMaterialColor ()
Private Attributes
NukudeFace pM
TechSane tS
TechSaneM tSM
Background background
EasyEaseAnimator< 25 > eEA = EasyEaseAnimator<25>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f)
RainbowNoise rainbowNoise
FlowNoise flowNoise
RainbowSpiral rainbowSpiral
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0))
SimpleMaterial orangeMaterial = SimpleMaterial(RGBColor(255, 165, 0))
SimpleMaterial whiteMaterial = SimpleMaterial(RGBColor(255, 255, 255))
SimpleMaterial greenMaterial = SimpleMaterial(RGBColor(0, 255, 0))
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255))
SimpleMaterial yellowMaterial = SimpleMaterial(RGBColor(255, 255, 0))
SimpleMaterial purpleMaterial = SimpleMaterial(RGBColor(255, 0, 255))
RGBColor gradientSpectrum [2] = {RGBColor(255, 0, 0), RGBColor(0, 0, 255)}
GradientMaterial< 2 > gradientMat = GradientMaterial<2>(gradientSpectrum, 350.0f, false)
MaterialAnimator< 10 > materialAnimator
MaterialAnimator< 4 > backgroundMaterial
SpectrumAnalyzer sA = SpectrumAnalyzer(Vector2D(200, 100), Vector2D(100, 50), true, true)
AudioReactiveGradient aRG = AudioReactiveGradient(Vector2D(160, 160), Vector2D(0, 0), true, true)
Oscilloscope oSC = Oscilloscope(Vector2D(200, 100), Vector2D(0, 0))
BlinkTrack< 1 > blink
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f)
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f)
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f)
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 5.3f)
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 6.7f)
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f)
FunctionGenerator fGenMatXMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 1.1f)
FunctionGenerator fGenMatYMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 2.7f)
FunctionGenerator fGenMatRMenu = FunctionGenerator(FunctionGenerator::Sine, -5.0f, 5.0f, 1.7f)
BoopSensor boop
FFTVoiceDetection< 128 > voiceDetection
float offsetFaceSA = 0.0f
float offsetFaceARG = 0.0f
float offsetFaceOSC = 0.0f
float techSaneLogo = 0.0f
uint8_t offsetFaceIndSA = 50
uint8_t offsetFaceIndARG = 51
uint8_t offsetFaceIndOSC = 52
uint8_t techSaneLogoInd = 53
bool mirror = false
float xOffset = 0.0f
float yOffset = 0.0f
float adjustTS = 0.0f
Detailed Description
Definition at line 30 of file TechSaneAnimation.h.
Constructor & Destructor Documentation
TechSaneAnimation()
TechSaneAnimation () inline
Definition at line 250 of file TechSaneAnimation.h.
References background, backgroundMaterial, boop, ChangeInterpolationMethods(), flowNoise, Menu::Initialize(), MicrophoneFourier::Initialize(), LinkEasyEase(), LinkParameters(), materialAnimator, pM, SetMaterialLayers(), tS, and tSM.
Member Function Documentation
Angry()
void Angry () inline private
Definition at line 161 of file TechSaneAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, materialAnimator, and redMaterial.
Referenced by Update().
AudioReactiveGradientFace()
void AudioReactiveGradientFace () inline private
Definition at line 200 of file TechSaneAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), aRG, backgroundMaterial, eEA, offsetFaceARG, and offsetFaceIndARG.
Referenced by Update().
ChangeInterpolationMethods()
void ChangeInterpolationMethods () inline private
Definition at line 123 of file TechSaneAnimation.h.
References eEA, and EasyEaseAnimator< maxParameters >::SetInterpolationMethod().
Referenced by TechSaneAnimation().
Default()
void Default () inline private
Definition at line 159 of file TechSaneAnimation.h.
Referenced by Update().
Doubt()
void Doubt () inline private
Definition at line 178 of file TechSaneAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
Referenced by Update().
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 274 of file TechSaneAnimation.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 275 of file TechSaneAnimation.h.
Frown()
void Frown () inline private
Definition at line 182 of file TechSaneAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
Referenced by Update().
GetObject()
Object3D * GetObject () inline
Definition at line 277 of file TechSaneAnimation.h.
References pM.
LinkEasyEase()
void LinkEasyEase () inline private
Definition at line 92 of file TechSaneAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameter(), eEA, offsetFaceARG, offsetFaceIndARG, offsetFaceIndOSC, offsetFaceIndSA, offsetFaceOSC, offsetFaceSA, pM, techSaneLogo, and techSaneLogoInd.
Referenced by TechSaneAnimation().
LinkParameters()
void LinkParameters () inline private
Definition at line 119 of file TechSaneAnimation.h.
References AnimationTrack< maxParameters, maxKeyFrames >::AddParameter(), blink, and pM.
Referenced by TechSaneAnimation().
LookDown()
void LookDown () inline private
Definition at line 190 of file TechSaneAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
LookUp()
void LookUp () inline private
Definition at line 186 of file TechSaneAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
Referenced by Update().
OscilloscopeFace()
void OscilloscopeFace () inline private
Definition at line 206 of file TechSaneAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), backgroundMaterial, eEA, offsetFaceIndOSC, offsetFaceOSC, and oSC.
Referenced by Update().
Sad()
void Sad () inline private
Definition at line 166 of file TechSaneAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blueMaterial, eEA, and materialAnimator.
Referenced by Update().
SetCameraMirror()
void SetCameraMirror (bool mirror) inline
Definition at line 281 of file TechSaneAnimation.h.
References mirror.
SetMaterialColor()
void SetMaterialColor () inline private
Definition at line 234 of file TechSaneAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), blueMaterial, Menu::GetFaceColor(), greenMaterial, materialAnimator, orangeMaterial, purpleMaterial, rainbowNoise, rainbowSpiral, redMaterial, whiteMaterial, and yellowMaterial.
Referenced by Update().
SetMaterialLayers()
void SetMaterialLayers () inline private
Definition at line 137 of file TechSaneAnimation.h.
References Material::Add, MaterialAnimator< materialCount >::AddMaterial(), aRG, backgroundMaterial, blueMaterial, flowNoise, Menu::GetMaterial(), greenMaterial, Material::Lighten, materialAnimator, orangeMaterial, oSC, purpleMaterial, rainbowNoise, rainbowSpiral, redMaterial, Material::Replace, sA, MaterialAnimator< materialCount >::SetBaseMaterial(), whiteMaterial, and yellowMaterial.
Referenced by TechSaneAnimation().
SpectrumAnalyzerFace()
void SpectrumAnalyzerFace () inline private
Definition at line 194 of file TechSaneAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), backgroundMaterial, eEA, offsetFaceIndSA, offsetFaceSA, and sA.
Referenced by Update().
Surprised()
void Surprised () inline private
Definition at line 172 of file TechSaneAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, materialAnimator, and rainbowSpiral.
Referenced by Update().
TechSaneFace()
void TechSaneFace () inline private
Definition at line 212 of file TechSaneAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, and techSaneLogoInd.
Referenced by Update().
Update()
void Update (float ratio) inline override
Definition at line 285 of file TechSaneAnimation.h.
References adjustTS, Angry(), aRG, AudioReactiveGradientFace(), backgroundMaterial, boop, Default(), Doubt(), eEA, fGenMatXMove, fGenMatYMove, flowNoise, Frown(), Menu::GetFaceState(), MicrophoneFourierBase::GetFourierFiltered(), MicrophoneFourierBase::GetSamples(), gradientMat, gradientSpectrum, LookUp(), materialAnimator, mirror, Menu::MirrorSpectrumAnalyzer(), offsetFaceARG, offsetFaceOSC, offsetFaceSA, oSC, OscilloscopeFace(), pM, rainbowNoise, rainbowSpiral, sA, Sad(), RGBColor::SetColor(), SpectrumAnalyzer::SetFlipYState(), AudioReactiveGradient::SetHueAngle(), Oscilloscope::SetHueAngle(), SpectrumAnalyzer::SetHueAngle(), SetMaterialColor(), SpectrumAnalyzer::SetMirrorYState(), AudioReactiveGradient::SetPosition(), Oscilloscope::SetPosition(), AudioReactiveGradient::SetRadius(), AudioReactiveGradient::SetRotation(), AudioReactiveGradient::SetSize(), Oscilloscope::SetSize(), Menu::ShowMenu(), SpectrumAnalyzerFace(), Surprised(), TechSaneFace(), techSaneLogo, tS, tSM, MicrophoneFourier::Update(), MaterialAnimator< materialCount >::Update(), FunctionGenerator::Update(), EasyEaseAnimator< maxParameters >::Update(), Oscilloscope::Update(), AudioReactiveGradient::Update(), SpectrumAnalyzer::Update(), Menu::Update(), FlowNoise::Update(), RainbowNoise::Update(), RainbowSpiral::Update(), UpdateFFTVisemes(), UpdateKeyFrameTracks(), GradientMaterial< colorCount >::UpdateRGB(), Menu::UseBoopSensor(), xOffset, and yOffset.
UpdateFFTVisemes()
void UpdateFFTVisemes () inline private
Definition at line 216 of file TechSaneAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), Viseme::AH, Viseme::AR, Viseme::EE, eEA, Viseme::ER, MicrophoneFourierBase::GetCurrentMagnitude(), MicrophoneFourierBase::GetFourierFiltered(), MicrophoneFourierBase::GetSampleRate(), FFTVoiceDetection< peakCount >::GetViseme(), Viseme::OO, Viseme::UH, FFTVoiceDetection< peakCount >::Update(), Menu::UseMicrophone(), and voiceDetection.
Referenced by Update().
UpdateKeyFrameTracks()
void UpdateKeyFrameTracks () inline private
Definition at line 155 of file TechSaneAnimation.h.
References blink, and AnimationTrack< maxParameters, maxKeyFrames >::Update().
Referenced by Update().
Member Data Documentation
adjustTS
float adjustTS = 0.0f private
Definition at line 90 of file TechSaneAnimation.h.
Referenced by Update().
aRG
AudioReactiveGradient aRG = AudioReactiveGradient(Vector2D(160, 160), Vector2D(0, 0), true, true) private
Definition at line 57 of file TechSaneAnimation.h.
Referenced by AudioReactiveGradientFace(), SetMaterialLayers(), and Update().
background
Background background private
Definition at line 35 of file TechSaneAnimation.h.
Referenced by TechSaneAnimation().
backgroundMaterial
MaterialAnimator<4> backgroundMaterial private
Definition at line 54 of file TechSaneAnimation.h.
Referenced by AudioReactiveGradientFace(), OscilloscopeFace(), SetMaterialLayers(), SpectrumAnalyzerFace(), TechSaneAnimation(), and Update().
blink
BlinkTrack<1> blink private
Definition at line 61 of file TechSaneAnimation.h.
Referenced by LinkParameters(), and UpdateKeyFrameTracks().
blueMaterial
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255)) private
Definition at line 46 of file TechSaneAnimation.h.
Referenced by Sad(), SetMaterialColor(), and SetMaterialLayers().
boop
BoopSensor boop private
Definition at line 74 of file TechSaneAnimation.h.
Referenced by TechSaneAnimation(), and Update().
eEA
EasyEaseAnimator<25> eEA = EasyEaseAnimator<25>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f) private
Definition at line 36 of file TechSaneAnimation.h.
Referenced by Angry(), AudioReactiveGradientFace(), ChangeInterpolationMethods(), Doubt(), Frown(), LinkEasyEase(), LookDown(), LookUp(), OscilloscopeFace(), Sad(), SpectrumAnalyzerFace(), Surprised(), TechSaneFace(), Update(), and UpdateFFTVisemes().
fGenMatHue
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f) private
Definition at line 68 of file TechSaneAnimation.h.
fGenMatPos
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f) private
Definition at line 63 of file TechSaneAnimation.h.
fGenMatRMenu
FunctionGenerator fGenMatRMenu = FunctionGenerator(FunctionGenerator::Sine, -5.0f, 5.0f, 1.7f) private
Definition at line 72 of file TechSaneAnimation.h.
fGenMatXMenu
FunctionGenerator fGenMatXMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 1.1f) private
Definition at line 70 of file TechSaneAnimation.h.
fGenMatXMove
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 5.3f) private
Definition at line 66 of file TechSaneAnimation.h.
Referenced by Update().
fGenMatYMenu
FunctionGenerator fGenMatYMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 2.7f) private
Definition at line 71 of file TechSaneAnimation.h.
fGenMatYMove
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 6.7f) private
Definition at line 67 of file TechSaneAnimation.h.
Referenced by Update().
fGenRotation
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f) private
Definition at line 64 of file TechSaneAnimation.h.
fGenScale
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f) private
Definition at line 65 of file TechSaneAnimation.h.
flowNoise
FlowNoise flowNoise private
Definition at line 40 of file TechSaneAnimation.h.
Referenced by SetMaterialLayers(), TechSaneAnimation(), and Update().
gradientMat
GradientMaterial<2> gradientMat = GradientMaterial<2>(gradientSpectrum, 350.0f, false) private
Definition at line 51 of file TechSaneAnimation.h.
Referenced by Update().
gradientSpectrum
RGBColor gradientSpectrum[2] = {RGBColor(255, 0, 0), RGBColor(0, 0, 255)} private
Definition at line 50 of file TechSaneAnimation.h.
Referenced by Update().
greenMaterial
SimpleMaterial greenMaterial = SimpleMaterial(RGBColor(0, 255, 0)) private
Definition at line 45 of file TechSaneAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
materialAnimator
MaterialAnimator<10> materialAnimator private
Definition at line 53 of file TechSaneAnimation.h.
Referenced by Angry(), Sad(), SetMaterialColor(), SetMaterialLayers(), Surprised(), TechSaneAnimation(), and Update().
mirror
bool mirror = false private
Definition at line 86 of file TechSaneAnimation.h.
Referenced by SetCameraMirror(), and Update().
offsetFaceARG
float offsetFaceARG = 0.0f private
Definition at line 79 of file TechSaneAnimation.h.
Referenced by AudioReactiveGradientFace(), LinkEasyEase(), and Update().
offsetFaceIndARG
uint8_t offsetFaceIndARG = 51 private
Definition at line 83 of file TechSaneAnimation.h.
Referenced by AudioReactiveGradientFace(), and LinkEasyEase().
offsetFaceIndOSC
uint8_t offsetFaceIndOSC = 52 private
Definition at line 84 of file TechSaneAnimation.h.
Referenced by LinkEasyEase(), and OscilloscopeFace().
offsetFaceIndSA
uint8_t offsetFaceIndSA = 50 private
Definition at line 82 of file TechSaneAnimation.h.
Referenced by LinkEasyEase(), and SpectrumAnalyzerFace().
offsetFaceOSC
float offsetFaceOSC = 0.0f private
Definition at line 80 of file TechSaneAnimation.h.
Referenced by LinkEasyEase(), OscilloscopeFace(), and Update().
offsetFaceSA
float offsetFaceSA = 0.0f private
Definition at line 78 of file TechSaneAnimation.h.
Referenced by LinkEasyEase(), SpectrumAnalyzerFace(), and Update().
orangeMaterial
SimpleMaterial orangeMaterial = SimpleMaterial(RGBColor(255, 165, 0)) private
Definition at line 43 of file TechSaneAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
oSC
Oscilloscope oSC = Oscilloscope(Vector2D(200, 100), Vector2D(0, 0)) private
Definition at line 58 of file TechSaneAnimation.h.
Referenced by OscilloscopeFace(), SetMaterialLayers(), and Update().
pM
NukudeFace pM private
Definition at line 32 of file TechSaneAnimation.h.
Referenced by GetObject(), LinkEasyEase(), LinkParameters(), TechSaneAnimation(), and Update().
purpleMaterial
SimpleMaterial purpleMaterial = SimpleMaterial(RGBColor(255, 0, 255)) private
Definition at line 48 of file TechSaneAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
rainbowNoise
RainbowNoise rainbowNoise private
Definition at line 39 of file TechSaneAnimation.h.
Referenced by SetMaterialColor(), SetMaterialLayers(), and Update().
rainbowSpiral
RainbowSpiral rainbowSpiral private
Definition at line 41 of file TechSaneAnimation.h.
Referenced by SetMaterialColor(), SetMaterialLayers(), Surprised(), and Update().
redMaterial
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0)) private
Definition at line 42 of file TechSaneAnimation.h.
Referenced by Angry(), SetMaterialColor(), and SetMaterialLayers().
sA
SpectrumAnalyzer sA = SpectrumAnalyzer(Vector2D(200, 100), Vector2D(100, 50), true, true) private
Definition at line 56 of file TechSaneAnimation.h.
Referenced by SetMaterialLayers(), SpectrumAnalyzerFace(), and Update().
techSaneLogo
float techSaneLogo = 0.0f private
Definition at line 81 of file TechSaneAnimation.h.
Referenced by LinkEasyEase(), and Update().
techSaneLogoInd
uint8_t techSaneLogoInd = 53 private
Definition at line 85 of file TechSaneAnimation.h.
Referenced by LinkEasyEase(), and TechSaneFace().
tS
TechSane tS private
Definition at line 33 of file TechSaneAnimation.h.
Referenced by TechSaneAnimation(), and Update().
tSM
TechSaneM tSM private
Definition at line 34 of file TechSaneAnimation.h.
Referenced by TechSaneAnimation(), and Update().
voiceDetection
FFTVoiceDetection<128> voiceDetection private
Definition at line 76 of file TechSaneAnimation.h.
Referenced by UpdateFFTVisemes().
whiteMaterial
SimpleMaterial whiteMaterial = SimpleMaterial(RGBColor(255, 255, 255)) private
Definition at line 44 of file TechSaneAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
xOffset
float xOffset = 0.0f private
Definition at line 88 of file TechSaneAnimation.h.
Referenced by Update().
yellowMaterial
SimpleMaterial yellowMaterial = SimpleMaterial(RGBColor(255, 255, 0)) private
Definition at line 47 of file TechSaneAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
yOffset
float yOffset = 0.0f private
Definition at line 89 of file TechSaneAnimation.h.
Referenced by Update().
The documentation for this class was generated from the following file:
TechSaneAnimation.h