ProtogenArtleckAnimation Class Reference
ProtogenArtleckAnimation Class Reference
#include <ArtleckAnimation.h>
Public Member Functions
ProtogenArtleckAnimation ()
void UpdateKeyFrameTracks ()
void Default ()
void Angry ()
void Sad ()
void Surprised ()
void Doubt ()
void Frown ()
void LookUp ()
void LookDown ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
Object3D * GetObject ()
void Update (float ratio) override
Public Attributes
float offset = 0.0f
Private Member Functions
void LinkEasyEase ()
void LinkParameters ()
void AddBlinkKeyFrames ()
void AddMouthKeyFrames ()
void ChangeInterpolationMethods ()
Private Attributes
float colorMix
ProtoArtleck pM
EasyEaseAnimator< 20 > eEA = EasyEaseAnimator<20>(EasyEaseInterpolation::Overshoot, 1.0f, 0.5f)
RGBColor noiseSpectrum [4] = {RGBColor(0, 255, 0), RGBColor(255, 0, 0), RGBColor(0, 255, 0), RGBColor(0, 0, 255)}
GradientMaterial gNoiseMat = GradientMaterial(4, noiseSpectrum, 2.0f, false)
SimplexNoise sNoise = SimplexNoise(1, &gNoiseMat)
RGBColor gradientSpectrum [2] = {RGBColor(255, 255, 0), RGBColor(255, 128, 0)}
GradientMaterial gradientMat = GradientMaterial(2, gradientSpectrum, 350.0f, false)
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0))
Material * noiseMaterials [2] = {&gradientMat, &sNoise}
CombineMaterial noiseMaterial = CombineMaterial(CombineMaterial::Lighten, 2, noiseMaterials)
Material * faceMaterials [2] = {&redMaterial, &noiseMaterial}
CombineMaterial faceMaterial = CombineMaterial(CombineMaterial::Replace, 2, faceMaterials)
KeyFrameTrack blink = KeyFrameTrack(1, 0.0f, 1.0f, 10, KeyFrameTrack::Cosine)
KeyFrameTrack mouth = KeyFrameTrack(1, 0.0f, 1.0f, 5, KeyFrameTrack::Cosine)
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f)
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f)
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f)
MicrophoneSimple mic = MicrophoneSimple(14)
BoopSensor boop
bool talk = true
Detailed Description
Definition at line 19 of file ArtleckAnimation.h.
Constructor & Destructor Documentation
ProtogenArtleckAnimation()
ProtogenArtleckAnimation () inline
Definition at line 102 of file ArtleckAnimation.h.
References AddBlinkKeyFrames(), AddMouthKeyFrames(), boop, ChangeInterpolationMethods(), faceMaterial, ButtonHandler::Initialize(), LinkEasyEase(), LinkParameters(), noiseMaterial, and pM.
Member Function Documentation
AddBlinkKeyFrames()
void AddBlinkKeyFrames () inline private
Definition at line 75 of file ArtleckAnimation.h.
References KeyFrameTrack< maxParameters, maxKeyFrames >::AddKeyFrame(), and blink.
Referenced by ProtogenArtleckAnimation().
AddMouthKeyFrames()
void AddMouthKeyFrames () inline private
Definition at line 89 of file ArtleckAnimation.h.
References KeyFrameTrack< maxParameters, maxKeyFrames >::AddKeyFrame(), and mouth.
Referenced by ProtogenArtleckAnimation().
Angry()
void Angry () inline
Definition at line 132 of file ArtleckAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
Referenced by Update().
ChangeInterpolationMethods()
void ChangeInterpolationMethods () inline private
Definition at line 95 of file ArtleckAnimation.h.
References eEA, and EasyEaseAnimator< maxParameters >::SetInterpolationMethod().
Referenced by ProtogenArtleckAnimation().
Default()
void Default () inline
Definition at line 124 of file ArtleckAnimation.h.
References blink, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
Referenced by Update().
Doubt()
void Doubt () inline
Definition at line 163 of file ArtleckAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
Referenced by Update().
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 205 of file ArtleckAnimation.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 206 of file ArtleckAnimation.h.
Frown()
void Frown () inline
Definition at line 174 of file ArtleckAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
Referenced by Update().
GetObject()
Object3D * GetObject () inline
Definition at line 208 of file ArtleckAnimation.h.
References pM.
LinkEasyEase()
void LinkEasyEase () inline private
Definition at line 55 of file ArtleckAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameter(), colorMix, eEA, and pM.
Referenced by ProtogenArtleckAnimation().
LinkParameters()
void LinkParameters () inline private
Definition at line 70 of file ArtleckAnimation.h.
References KeyFrameTrack< maxParameters, maxKeyFrames >::AddParameter(), blink, mouth, and pM.
Referenced by ProtogenArtleckAnimation().
LookDown()
void LookDown () inline
Definition at line 195 of file ArtleckAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
LookUp()
void LookUp () inline
Definition at line 185 of file ArtleckAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
Referenced by Update().
Sad()
void Sad () inline
Definition at line 143 of file ArtleckAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
Referenced by Update().
Surprised()
void Surprised () inline
Definition at line 153 of file ArtleckAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
Referenced by Update().
Update()
void Update (float ratio) inline override
Definition at line 214 of file ArtleckAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), Angry(), boop, colorMix, Default(), Doubt(), eEA, faceMaterial, Frown(), ButtonHandler::GetValue(), gNoiseMat, GradientMaterial< colorCount >::HueShift(), LookUp(), mic, pM, Sad(), GradientMaterial< colorCount >::SetGradientPeriod(), SimplexNoise< colors >::SetScale(), SimplexNoise< colors >::SetZPosition(), sNoise, Surprised(), talk, MicrophoneSimple::Update(), EasyEaseAnimator< maxParameters >::Update(), and UpdateKeyFrameTracks().
UpdateKeyFrameTracks()
void UpdateKeyFrameTracks () inline
Definition at line 119 of file ArtleckAnimation.h.
References blink, mouth, and KeyFrameTrack< maxParameters, maxKeyFrames >::Update().
Referenced by Update().
Member Data Documentation
blink
KeyFrameTrack blink = KeyFrameTrack(1, 0.0f, 1.0f, 10, KeyFrameTrack::Cosine) private
Definition at line 44 of file ArtleckAnimation.h.
Referenced by AddBlinkKeyFrames(), Angry(), Default(), Doubt(), Frown(), LinkParameters(), LookDown(), LookUp(), Sad(), Surprised(), and UpdateKeyFrameTracks().
boop
BoopSensor boop private
Definition at line 52 of file ArtleckAnimation.h.
Referenced by ProtogenArtleckAnimation(), and Update().
colorMix
float colorMix private
Definition at line 21 of file ArtleckAnimation.h.
Referenced by LinkEasyEase(), and Update().
eEA
EasyEaseAnimator<20> eEA = EasyEaseAnimator<20>(EasyEaseInterpolation::Overshoot, 1.0f, 0.5f) private
Definition at line 24 of file ArtleckAnimation.h.
Referenced by Angry(), ChangeInterpolationMethods(), Doubt(), Frown(), LinkEasyEase(), LookDown(), LookUp(), Sad(), Surprised(), and Update().
faceMaterial
CombineMaterial faceMaterial = CombineMaterial(CombineMaterial::Replace, 2, faceMaterials) private
Definition at line 41 of file ArtleckAnimation.h.
Referenced by ProtogenArtleckAnimation(), and Update().
faceMaterials
Material* faceMaterials[2] = {&redMaterial, &noiseMaterial} private
Definition at line 40 of file ArtleckAnimation.h.
fGenMatPos
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f) private
Definition at line 47 of file ArtleckAnimation.h.
fGenRotation
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f) private
Definition at line 48 of file ArtleckAnimation.h.
fGenScale
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f) private
Definition at line 49 of file ArtleckAnimation.h.
gNoiseMat
GradientMaterial gNoiseMat = GradientMaterial(4, noiseSpectrum, 2.0f, false) private
Definition at line 27 of file ArtleckAnimation.h.
Referenced by Update().
gradientMat
GradientMaterial gradientMat = GradientMaterial(2, gradientSpectrum, 350.0f, false) private
Definition at line 31 of file ArtleckAnimation.h.
gradientSpectrum
RGBColor gradientSpectrum[2] = {RGBColor(255, 255, 0), RGBColor(255, 128, 0)} private
Definition at line 30 of file ArtleckAnimation.h.
mic
MicrophoneSimple mic = MicrophoneSimple(14) private
Definition at line 51 of file ArtleckAnimation.h.
Referenced by Update().
mouth
KeyFrameTrack mouth = KeyFrameTrack(1, 0.0f, 1.0f, 5, KeyFrameTrack::Cosine) private
Definition at line 45 of file ArtleckAnimation.h.
Referenced by AddMouthKeyFrames(), Angry(), Default(), Doubt(), Frown(), LinkParameters(), LookDown(), LookUp(), Sad(), Surprised(), and UpdateKeyFrameTracks().
noiseMaterial
CombineMaterial noiseMaterial = CombineMaterial(CombineMaterial::Lighten, 2, noiseMaterials) private
Definition at line 37 of file ArtleckAnimation.h.
Referenced by ProtogenArtleckAnimation().
noiseMaterials
Material* noiseMaterials[2] = {&gradientMat, &sNoise} private
Definition at line 36 of file ArtleckAnimation.h.
noiseSpectrum
RGBColor noiseSpectrum[4] = {RGBColor(0, 255, 0), RGBColor(255, 0, 0), RGBColor(0, 255, 0), RGBColor(0, 0, 255)} private
Definition at line 26 of file ArtleckAnimation.h.
offset
float offset = 0.0f
Definition at line 212 of file ArtleckAnimation.h.
pM
ProtoArtleck pM private
Definition at line 23 of file ArtleckAnimation.h.
Referenced by Angry(), Default(), Doubt(), Frown(), GetObject(), LinkEasyEase(), LinkParameters(), LookDown(), LookUp(), ProtogenArtleckAnimation(), Sad(), Surprised(), and Update().
redMaterial
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0)) private
Definition at line 33 of file ArtleckAnimation.h.
sNoise
SimplexNoise sNoise = SimplexNoise(1, &gNoiseMat) private
Definition at line 28 of file ArtleckAnimation.h.
Referenced by Update().
talk
bool talk = true private
Definition at line 53 of file ArtleckAnimation.h.
Referenced by Angry(), Default(), Doubt(), Frown(), LookDown(), LookUp(), Sad(), Surprised(), and Update().
The documentation for this class was generated from the following file:
ArtleckAnimation.h