HUB75ControllerSquare Class Reference
HUB75ControllerSquare Class Reference
Manages a square display composed of two vertical HUB75 panels.
#include <HUB75ControllerSquare.h>
Public Member Functions
HUB75ControllerSquare (CameraManager *cameras, uint8_t maxBrightness, uint8_t maxAccentBrightness)
Constructs a HUB75ControllerSquare with specified parameters.
void Initialize () override
Initializes the HUB75ControllerSquare and sets up the square display.
void Display () override
Updates and displays the content on the square display.
void SetBrightness (uint8_t maxBrightness) override
Sets the maximum brightness of the square display.
void SetAccentBrightness (uint8_t maxAccentBrightness) override
Sets the maximum brightness for any secondary accent lighting.
Public Member Functions inherited from Controller
uint8_t GetBrightness ()
Retrieves the current brightness level.
uint8_t GetAccentBrightness ()
Retrieves the current accent brightness level.
Additional Inherited Members
Protected Member Functions inherited from Controller
Controller (CameraManager *cameras, uint8_t maxBrightness, uint8_t maxAccentBrightness)
Constructs a Controller with specified parameters.
void UpdateBrightness ()
Updates the brightness based on internal logic.
Protected Attributes inherited from Controller
CameraManager * cameras
Pointer to the CameraManager for managing camera data.
uint8_t brightness
Current brightness level.
uint8_t accentBrightness
Current accent brightness level.
uint8_t maxBrightness
Maximum allowed brightness level.
uint8_t maxAccentBrightness
Maximum allowed accent brightness level.
bool isOn = false
Indicates if the controller is active.
bool startTime = false
Indicates if the start time has been recorded.
Detailed Description
Manages a square display composed of two vertical HUB75 panels.
The HUB75ControllerSquare class extends the Controller base class to provide specific functionality for initializing, controlling, and displaying content on a square display created by combining two vertical HUB75 panels.
Definition at line 29 of file HUB75ControllerSquare.h.
Constructor & Destructor Documentation
HUB75ControllerSquare()
HUB75ControllerSquare (CameraManager * cameras, uint8_t maxBrightness, uint8_t maxAccentBrightness)
Constructs a HUB75ControllerSquare with specified parameters.
Parameters
cameras Pointer to the CameraManager for managing camera data.
maxBrightness Maximum brightness for the square display.
maxAccentBrightness Maximum brightness for any secondary accent lighting.
Definition at line 10 of file HUB75ControllerSquare.cpp.
Member Function Documentation
Display()
void Display () override virtual
Updates and displays the content on the square display.
Implements Controller.
Definition at line 20 of file HUB75ControllerSquare.cpp.
References RGBColor::B, Controller::brightness, Controller::cameras, RGBColor::G, CameraManager::GetCameras(), IPixelGroup::GetColor(), CameraBase::GetPixelGroup(), RGBColor::R, and Controller::UpdateBrightness().
Initialize()
void Initialize () override virtual
Initializes the HUB75ControllerSquare and sets up the square display.
Implements Controller.
Definition at line 12 of file HUB75ControllerSquare.cpp.
SetAccentBrightness()
void SetAccentBrightness (uint8_t maxAccentBrightness) override virtual
Sets the maximum brightness for any secondary accent lighting.
Parameters
maxAccentBrightness The maximum brightness value (0-255).
Implements Controller.
Definition at line 51 of file HUB75ControllerSquare.cpp.
References Controller::accentBrightness, Controller::isOn, and Controller::maxAccentBrightness.
SetBrightness()
void SetBrightness (uint8_t maxBrightness) override virtual
Sets the maximum brightness of the square display.
Parameters
maxBrightness The maximum brightness value (0-255).
Implements Controller.
Definition at line 43 of file HUB75ControllerSquare.cpp.
References Controller::brightness, Controller::isOn, and Controller::maxBrightness.
The documentation for this class was generated from the following files:
HUB75ControllerSquare.h
HUB75ControllerSquare.cpp