VectorFieldAnimation Class Reference
VectorFieldAnimation Class Reference
#include <VectorFieldAnimation.h>
Public Member Functions
VectorFieldAnimation ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
void Update (float ratio) override
Private Attributes
ProtoDR pM
SolidCube cube
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 1.5f)
FunctionGenerator fGenMatSize = FunctionGenerator(FunctionGenerator::Sine, 400.0f, 550.0f, 2.1f)
FunctionGenerator fGenMatRot = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 360.0f, 15.0f)
FunctionGenerator fGenMatPeriod = FunctionGenerator(FunctionGenerator::Sine, 0.1f, 1.0f, 8.0f)
FunctionGenerator fGenMatAmpl = FunctionGenerator(FunctionGenerator::Sine, 0.1f, 1.0f, 4.3f)
RGBColor spectrum1 [6] = {RGBColor(255, 255, 0), RGBColor(0, 0, 0), RGBColor(0, 255, 255), RGBColor(0, 0, 0), RGBColor(255, 0, 255), RGBColor(0, 0, 0)}
RGBColor spectrum2 [6] = {RGBColor(255, 0, 0), RGBColor(0, 0, 0), RGBColor(0, 255, 0), RGBColor(0, 0, 0), RGBColor(0, 0, 255), RGBColor(0, 0, 0)}
RGBColor spectrum3 [7] = {RGBColor(255, 0, 0), RGBColor(255, 255, 0), RGBColor(0, 255, 0), RGBColor(0, 255, 255), RGBColor(0, 0, 255), RGBColor(255, 0, 255), RGBColor(255, 0, 0)}
GradientMaterial colorDirection = GradientMaterial(7, spectrum3, 1.0f, false)
VectorField2D vectorField = VectorField2D(100, 70, &colorDirection)
Detailed Description
Definition at line 10 of file VectorFieldAnimation.h.
Constructor & Destructor Documentation
VectorFieldAnimation()
VectorFieldAnimation () inline
Definition at line 28 of file VectorFieldAnimation.h.
References cube, and vectorField.
Member Function Documentation
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 34 of file VectorFieldAnimation.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 35 of file VectorFieldAnimation.h.
Update()
void Update (float ratio) inline override
Definition at line 37 of file VectorFieldAnimation.h.
References VectorField2D::Advect(), cube, VectorField2D::Diffuse(), fGenMatAmpl, fGenMatPeriod, fGenMatPos, VectorField2D::ObjectField(), pM, VectorField2D::RenderDensity(), VectorField2D::SetPosition(), VectorField2D::SetSize(), FunctionGenerator::Update(), and vectorField.
Member Data Documentation
colorDirection
GradientMaterial colorDirection = GradientMaterial(7, spectrum3, 1.0f, false) private
Definition at line 24 of file VectorFieldAnimation.h.
cube
SolidCube cube private
Definition at line 14 of file VectorFieldAnimation.h.
Referenced by Update(), and VectorFieldAnimation().
fGenMatAmpl
FunctionGenerator fGenMatAmpl = FunctionGenerator(FunctionGenerator::Sine, 0.1f, 1.0f, 4.3f) private
Definition at line 19 of file VectorFieldAnimation.h.
Referenced by Update().
fGenMatPeriod
FunctionGenerator fGenMatPeriod = FunctionGenerator(FunctionGenerator::Sine, 0.1f, 1.0f, 8.0f) private
Definition at line 18 of file VectorFieldAnimation.h.
Referenced by Update().
fGenMatPos
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 1.5f) private
Definition at line 15 of file VectorFieldAnimation.h.
Referenced by Update().
fGenMatRot
FunctionGenerator fGenMatRot = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 360.0f, 15.0f) private
Definition at line 17 of file VectorFieldAnimation.h.
fGenMatSize
FunctionGenerator fGenMatSize = FunctionGenerator(FunctionGenerator::Sine, 400.0f, 550.0f, 2.1f) private
Definition at line 16 of file VectorFieldAnimation.h.
pM
ProtoDR pM private
Definition at line 12 of file VectorFieldAnimation.h.
Referenced by Update().
spectrum1
RGBColor spectrum1[6] = {RGBColor(255, 255, 0), RGBColor(0, 0, 0), RGBColor(0, 255, 255), RGBColor(0, 0, 0), RGBColor(255, 0, 255), RGBColor(0, 0, 0)} private
Definition at line 21 of file VectorFieldAnimation.h.
spectrum2
RGBColor spectrum2[6] = {RGBColor(255, 0, 0), RGBColor(0, 0, 0), RGBColor(0, 255, 0), RGBColor(0, 0, 0), RGBColor(0, 0, 255), RGBColor(0, 0, 0)} private
Definition at line 22 of file VectorFieldAnimation.h.
spectrum3
RGBColor spectrum3[7] = {RGBColor(255, 0, 0), RGBColor(255, 255, 0), RGBColor(0, 255, 0), RGBColor(0, 255, 255), RGBColor(0, 0, 255), RGBColor(255, 0, 255), RGBColor(255, 0, 0)} private
Definition at line 23 of file VectorFieldAnimation.h.
vectorField
VectorField2D vectorField = VectorField2D(100, 70, &colorDirection) private
Definition at line 25 of file VectorFieldAnimation.h.
Referenced by Update(), and VectorFieldAnimation().
The documentation for this class was generated from the following file:
VectorFieldAnimation.h