WaffleDaProtoAnimation Class Reference
WaffleDaProtoAnimation Class Reference
#include <DatBlueHuskyAnimation.h>
Public Member Functions
WaffleDaProtoAnimation ()
void UpdateKeyFrameTracks ()
void Default ()
void Angry ()
void Sad ()
void Surprised ()
void Doubt ()
void Frown ()
void LookUp ()
void LookDown ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
Object3D * GetObject ()
void Update (float ratio) override
WaffleDaProtoAnimation ()
void UpdateKeyFrameTracks ()
void Default ()
void Angry ()
void Sad ()
void Surprised ()
void Doubt ()
void Frown ()
void LookUp ()
void LookDown ()
void SpectrumAnalyzerFace ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
Object3D * GetObject ()
void UpdateFFTVisemes ()
void Update (float ratio) override
Public Attributes
float offset = 0.0f
Private Member Functions
void LinkEasyEase ()
void LinkParameters ()
void AddBlinkKeyFrames ()
void AddMouthKeyFrames ()
void ChangeInterpolationMethods ()
void LinkEasyEase ()
void LinkParameters ()
void ChangeInterpolationMethods ()
void SetMaterials ()
Private Attributes
float colorMix
NukudeFace pM
EasyEaseAnimator< 20 > eEA = EasyEaseAnimator<20>(EasyEaseInterpolation::Overshoot)
RGBColor noiseSpectrum [4] = {RGBColor(0, 255, 0), RGBColor(255, 0, 0), RGBColor(0, 255, 0), RGBColor(0, 0, 255)}
GradientMaterial gNoiseMat = GradientMaterial(4, noiseSpectrum, 2.0f, false)
SimplexNoise sNoise = SimplexNoise(1, &gNoiseMat)
RGBColor gradientSpectrum [2] = {RGBColor(0, 0, 255), RGBColor(0, 128, 255)}
GradientMaterial gradientMat = GradientMaterial(2, gradientSpectrum, 350.0f, false)
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0))
FunctionGenerator fGenMatBend = FunctionGenerator(FunctionGenerator::Sine, 0.8f, 0.9f, 6.7f)
RGBColor rainbowSpectrum [6] = {RGBColor(255, 0, 0), RGBColor(255, 255, 0), RGBColor(0, 255, 0), RGBColor(0, 255, 255), RGBColor(0, 0, 255), RGBColor(255, 0, 255)}
SpiralMaterial spiralMaterial = SpiralMaterial(6, rainbowSpectrum, 3.0f, 7.0f)
Material * noiseMaterials [2] = {&gradientMat, &sNoise}
CombineMaterial noiseMaterial = CombineMaterial(CombineMaterial::Lighten, 2, noiseMaterials)
Material * faceMaterials [2] = {&spiralMaterial, &noiseMaterial}
CombineMaterial faceMaterial = CombineMaterial(CombineMaterial::Replace, 2, faceMaterials)
KeyFrameTrack blink = KeyFrameTrack(1, 0.0f, 1.0f, 10, KeyFrameTrack::Cosine)
KeyFrameTrack mouth = KeyFrameTrack(1, 0.0f, 1.0f, 5, KeyFrameTrack::Cosine)
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f)
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f)
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f)
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 7.3f)
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 9.7f)
MicrophoneSimple mic = MicrophoneSimple(22, 0.4f)
BoopSensor boop
bool talk = true
Background background
RainbowNoise rainbowNoise
RainbowSpiral rainbowSpiral
GradientMaterial< 2 > gradientMat = GradientMaterial<2>(gradientSpectrum, 350.0f, false)
CombineMaterial< 4 > faceMaterial
SpectrumAnalyzer sA = SpectrumAnalyzer(22, Vector2D(250, 200), Vector2D(120, 100), true, true)
BlinkTrack< 1 > blink
float rainbowFaceMix = 0.0f
float angryFaceMix = 0.0f
uint8_t rainbowFaceIndex = 50
uint8_t angryFaceIndex = 51
FFTVoiceDetection< 128 > voiceDetection
Detailed Description
Definition at line 20 of file DatBlueHuskyAnimation.h.
Constructor & Destructor Documentation
WaffleDaProtoAnimation() [1/2]
WaffleDaProtoAnimation () inline
Definition at line 114 of file DatBlueHuskyAnimation.h.
References AddBlinkKeyFrames(), AddMouthKeyFrames(), boop, ChangeInterpolationMethods(), faceMaterial, ButtonHandler::Initialize(), LinkEasyEase(), LinkParameters(), noiseMaterial, and pM.
WaffleDaProtoAnimation() [2/2]
WaffleDaProtoAnimation () inline
Definition at line 110 of file WaffleDaProtoAnimation.h.
References background, boop, ChangeInterpolationMethods(), faceMaterial, LinkEasyEase(), LinkParameters(), pM, sA, and SetMaterials().
Member Function Documentation
AddBlinkKeyFrames()
void AddBlinkKeyFrames () inline private
Definition at line 88 of file DatBlueHuskyAnimation.h.
References KeyFrameTrack< maxParameters, maxKeyFrames >::AddKeyFrame(), and blink.
Referenced by WaffleDaProtoAnimation().
AddMouthKeyFrames()
void AddMouthKeyFrames () inline private
Definition at line 102 of file DatBlueHuskyAnimation.h.
References KeyFrameTrack< maxParameters, maxKeyFrames >::AddKeyFrame(), and mouth.
Referenced by WaffleDaProtoAnimation().
Angry() [1/2]
void Angry () inline
Definition at line 147 of file DatBlueHuskyAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
Referenced by Update().
Angry() [2/2]
void Angry () inline
Definition at line 135 of file WaffleDaProtoAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), angryFaceIndex, and eEA.
ChangeInterpolationMethods() [1/2]
void ChangeInterpolationMethods () inline private
Definition at line 108 of file DatBlueHuskyAnimation.h.
References eEA, and EasyEaseAnimator< maxParameters >::SetInterpolationMethod().
Referenced by WaffleDaProtoAnimation().
ChangeInterpolationMethods() [2/2]
void ChangeInterpolationMethods () inline private
Definition at line 86 of file WaffleDaProtoAnimation.h.
References angryFaceIndex, eEA, rainbowFaceIndex, and EasyEaseAnimator< maxParameters >::SetInterpolationMethod().
Default() [1/2]
void Default () inline
Definition at line 137 of file DatBlueHuskyAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
Referenced by Update().
Default() [2/2]
void Default () inline
Definition at line 133 of file WaffleDaProtoAnimation.h.
Doubt() [1/2]
void Doubt () inline
Definition at line 181 of file DatBlueHuskyAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
Referenced by Update().
Doubt() [2/2]
void Doubt () inline
Definition at line 151 of file WaffleDaProtoAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
FadeIn() [1/2]
void FadeIn (float stepRatio) inline override
Definition at line 225 of file DatBlueHuskyAnimation.h.
FadeIn() [2/2]
void FadeIn (float stepRatio) inline override
Definition at line 172 of file WaffleDaProtoAnimation.h.
FadeOut() [1/2]
void FadeOut (float stepRatio) inline override
Definition at line 226 of file DatBlueHuskyAnimation.h.
FadeOut() [2/2]
void FadeOut (float stepRatio) inline override
Definition at line 173 of file WaffleDaProtoAnimation.h.
Frown() [1/2]
void Frown () inline
Definition at line 192 of file DatBlueHuskyAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
Referenced by Update().
Frown() [2/2]
void Frown () inline
Definition at line 155 of file WaffleDaProtoAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
GetObject() [1/2]
Object3D * GetObject () inline
Definition at line 228 of file DatBlueHuskyAnimation.h.
References pM.
GetObject() [2/2]
Object3D * GetObject () inline
Definition at line 175 of file WaffleDaProtoAnimation.h.
References pM.
LinkEasyEase() [1/2]
void LinkEasyEase () inline private
Definition at line 62 of file DatBlueHuskyAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameter(), colorMix, eEA, and pM.
Referenced by WaffleDaProtoAnimation().
LinkEasyEase() [2/2]
void LinkEasyEase () inline private
Definition at line 58 of file WaffleDaProtoAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameter(), angryFaceIndex, angryFaceMix, eEA, pM, rainbowFaceIndex, and rainbowFaceMix.
LinkParameters() [1/2]
void LinkParameters () inline private
Definition at line 83 of file DatBlueHuskyAnimation.h.
References KeyFrameTrack< maxParameters, maxKeyFrames >::AddParameter(), blink, mouth, and pM.
Referenced by WaffleDaProtoAnimation().
LinkParameters() [2/2]
void LinkParameters () inline private
Definition at line 82 of file WaffleDaProtoAnimation.h.
References KeyFrameTrack< maxParameters, maxKeyFrames >::AddParameter(), blink, and pM.
LookDown() [1/2]
void LookDown () inline
Definition at line 214 of file DatBlueHuskyAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
LookDown() [2/2]
void LookDown () inline
Definition at line 163 of file WaffleDaProtoAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
LookUp() [1/2]
void LookUp () inline
Definition at line 203 of file DatBlueHuskyAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
Referenced by Update().
LookUp() [2/2]
void LookUp () inline
Definition at line 159 of file WaffleDaProtoAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
Sad() [1/2]
void Sad () inline
Definition at line 158 of file DatBlueHuskyAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
Referenced by Update().
Sad() [2/2]
void Sad () inline
Definition at line 140 of file WaffleDaProtoAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
SetMaterials()
void SetMaterials () inline private
Definition at line 102 of file WaffleDaProtoAnimation.h.
References Material::Add, CombineMaterial< materialCount >::AddMaterial(), faceMaterial, gradientMat, Material::Lighten, rainbowNoise, rainbowSpiral, redMaterial, and Material::Replace.
Referenced by WaffleDaProtoAnimation().
SpectrumAnalyzerFace()
void SpectrumAnalyzerFace () inline
Definition at line 167 of file WaffleDaProtoAnimation.h.
References background, and pM.
Referenced by Update().
Surprised() [1/2]
void Surprised () inline
Definition at line 169 of file DatBlueHuskyAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
Referenced by Update().
Surprised() [2/2]
void Surprised () inline
Definition at line 145 of file WaffleDaProtoAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, and rainbowFaceIndex.
Update() [1/2]
void Update (float ratio) inline override
Definition at line 234 of file DatBlueHuskyAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), Angry(), boop, colorMix, Default(), Doubt(), eEA, faceMaterial, fGenMatBend, fGenMatXMove, fGenMatYMove, Frown(), ButtonHandler::GetValue(), gNoiseMat, GradientMaterial< colorCount >::HueShift(), LookUp(), mic, pM, Sad(), SpiralMaterial::SetBend(), GradientMaterial< colorCount >::SetGradientPeriod(), SpiralMaterial::SetPositionOffset(), SpiralMaterial::SetRotationAngle(), SimplexNoise< colors >::SetScale(), SimplexNoise< colors >::SetZPosition(), sNoise, spiralMaterial, Surprised(), talk, MicrophoneSimple::Update(), FunctionGenerator::Update(), EasyEaseAnimator< maxParameters >::Update(), and UpdateKeyFrameTracks().
Update() [2/2]
void Update (float ratio) inline override
Definition at line 197 of file WaffleDaProtoAnimation.h.
References Angry(), angryFaceMix, background, boop, Default(), Doubt(), eEA, faceMaterial, fGenMatXMove, fGenMatYMove, Frown(), MicrophoneFourierBase::GetFourierFiltered(), LookUp(), pM, rainbowFaceMix, rainbowNoise, rainbowSpiral, sA, Sad(), SpectrumAnalyzer::SetFlipYState(), SpectrumAnalyzer::SetHueAngle(), SpectrumAnalyzer::SetMirrorYState(), CombineMaterial< materialCount >::SetOpacity(), SpectrumAnalyzerFace(), Surprised(), MicrophoneFourier::Update(), FunctionGenerator::Update(), EasyEaseAnimator< maxParameters >::Update(), SpectrumAnalyzer::Update(), RainbowNoise::Update(), RainbowSpiral::Update(), UpdateFFTVisemes(), and UpdateKeyFrameTracks().
UpdateFFTVisemes()
void UpdateFFTVisemes () inline
Definition at line 179 of file WaffleDaProtoAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), Viseme::AH, Viseme::AR, Viseme::EE, eEA, Viseme::ER, MicrophoneFourierBase::GetCurrentMagnitude(), MicrophoneFourierBase::GetFourierFiltered(), MicrophoneFourierBase::GetSampleRate(), FFTVoiceDetection< peakCount >::GetViseme(), Viseme::OO, Viseme::UH, FFTVoiceDetection< peakCount >::Update(), and voiceDetection.
Referenced by Update().
UpdateKeyFrameTracks() [1/2]
void UpdateKeyFrameTracks () inline
Definition at line 132 of file DatBlueHuskyAnimation.h.
References blink, mouth, and KeyFrameTrack< maxParameters, maxKeyFrames >::Update().
Referenced by Update().
UpdateKeyFrameTracks() [2/2]
void UpdateKeyFrameTracks () inline
Definition at line 129 of file WaffleDaProtoAnimation.h.
References blink, and KeyFrameTrack< maxParameters, maxKeyFrames >::Update().
Member Data Documentation
angryFaceIndex
uint8_t angryFaceIndex = 51 private
Definition at line 54 of file WaffleDaProtoAnimation.h.
Referenced by Angry(), ChangeInterpolationMethods(), and LinkEasyEase().
angryFaceMix
float angryFaceMix = 0.0f private
Definition at line 52 of file WaffleDaProtoAnimation.h.
Referenced by LinkEasyEase(), and Update().
background
Background background private
Definition at line 26 of file WaffleDaProtoAnimation.h.
Referenced by SpectrumAnalyzerFace(), Update(), and WaffleDaProtoAnimation().
blink [1/2]
KeyFrameTrack blink = KeyFrameTrack(1, 0.0f, 1.0f, 10, KeyFrameTrack::Cosine) private
Definition at line 49 of file DatBlueHuskyAnimation.h.
Referenced by AddBlinkKeyFrames(), Angry(), Default(), Doubt(), Frown(), LinkParameters(), LookDown(), LookUp(), Sad(), Surprised(), and UpdateKeyFrameTracks().
blink [2/2]
BlinkTrack<1> blink private
Definition at line 42 of file WaffleDaProtoAnimation.h.
boop
BoopSensor boop private
Definition at line 59 of file DatBlueHuskyAnimation.h.
Referenced by Update(), and WaffleDaProtoAnimation().
colorMix
float colorMix private
Definition at line 22 of file DatBlueHuskyAnimation.h.
Referenced by LinkEasyEase(), and Update().
eEA
EasyEaseAnimator< 20 > eEA = EasyEaseAnimator<20>(EasyEaseInterpolation::Overshoot) private
Definition at line 25 of file DatBlueHuskyAnimation.h.
Referenced by Angry(), ChangeInterpolationMethods(), Default(), Doubt(), Frown(), LinkEasyEase(), LookDown(), LookUp(), Sad(), Surprised(), Update(), and UpdateFFTVisemes().
faceMaterial [1/2]
CombineMaterial faceMaterial = CombineMaterial(CombineMaterial::Replace, 2, faceMaterials) private
Definition at line 47 of file DatBlueHuskyAnimation.h.
Referenced by SetMaterials(), Update(), and WaffleDaProtoAnimation().
faceMaterial [2/2]
CombineMaterial<4> faceMaterial private
Definition at line 37 of file WaffleDaProtoAnimation.h.
faceMaterials
Material* faceMaterials[2] = {&spiralMaterial, &noiseMaterial} private
Definition at line 46 of file DatBlueHuskyAnimation.h.
fGenMatBend
FunctionGenerator fGenMatBend = FunctionGenerator(FunctionGenerator::Sine, 0.8f, 0.9f, 6.7f) private
Definition at line 37 of file DatBlueHuskyAnimation.h.
Referenced by Update().
fGenMatPos
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f) private
Definition at line 52 of file DatBlueHuskyAnimation.h.
fGenMatXMove
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 7.3f) private
Definition at line 55 of file DatBlueHuskyAnimation.h.
Referenced by Update().
fGenMatYMove
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 9.7f) private
Definition at line 56 of file DatBlueHuskyAnimation.h.
Referenced by Update().
fGenRotation
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f) private
Definition at line 53 of file DatBlueHuskyAnimation.h.
fGenScale
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f) private
Definition at line 54 of file DatBlueHuskyAnimation.h.
gNoiseMat
GradientMaterial gNoiseMat = GradientMaterial(4, noiseSpectrum, 2.0f, false) private
Definition at line 28 of file DatBlueHuskyAnimation.h.
Referenced by Update().
gradientMat [1/2]
GradientMaterial gradientMat = GradientMaterial(2, gradientSpectrum, 350.0f, false) private
Definition at line 32 of file DatBlueHuskyAnimation.h.
Referenced by SetMaterials().
gradientMat [2/2]
GradientMaterial<2> gradientMat = GradientMaterial<2>(gradientSpectrum, 350.0f, false) private
Definition at line 35 of file WaffleDaProtoAnimation.h.
gradientSpectrum
RGBColor gradientSpectrum = {RGBColor(0, 0, 255), RGBColor(0, 128, 255)} private
Definition at line 31 of file DatBlueHuskyAnimation.h.
mic
MicrophoneSimple mic = MicrophoneSimple(22, 0.4f) private
Definition at line 58 of file DatBlueHuskyAnimation.h.
Referenced by Update().
mouth
KeyFrameTrack mouth = KeyFrameTrack(1, 0.0f, 1.0f, 5, KeyFrameTrack::Cosine) private
Definition at line 50 of file DatBlueHuskyAnimation.h.
Referenced by AddMouthKeyFrames(), Angry(), Default(), Doubt(), Frown(), LinkParameters(), LookDown(), LookUp(), Sad(), Surprised(), and UpdateKeyFrameTracks().
noiseMaterial
CombineMaterial noiseMaterial = CombineMaterial(CombineMaterial::Lighten, 2, noiseMaterials) private
Definition at line 43 of file DatBlueHuskyAnimation.h.
Referenced by WaffleDaProtoAnimation().
noiseMaterials
Material* noiseMaterials[2] = {&gradientMat, &sNoise} private
Definition at line 42 of file DatBlueHuskyAnimation.h.
noiseSpectrum
RGBColor noiseSpectrum[4] = {RGBColor(0, 255, 0), RGBColor(255, 0, 0), RGBColor(0, 255, 0), RGBColor(0, 0, 255)} private
Definition at line 27 of file DatBlueHuskyAnimation.h.
offset
float offset = 0.0f
Definition at line 232 of file DatBlueHuskyAnimation.h.
pM
NukudeFace pM private
Definition at line 24 of file DatBlueHuskyAnimation.h.
Referenced by Angry(), Default(), Doubt(), Frown(), GetObject(), LinkEasyEase(), LinkParameters(), LookDown(), LookUp(), Sad(), SpectrumAnalyzerFace(), Surprised(), Update(), and WaffleDaProtoAnimation().
rainbowFaceIndex
uint8_t rainbowFaceIndex = 50 private
Definition at line 53 of file WaffleDaProtoAnimation.h.
Referenced by ChangeInterpolationMethods(), LinkEasyEase(), and Surprised().
rainbowFaceMix
float rainbowFaceMix = 0.0f private
Definition at line 51 of file WaffleDaProtoAnimation.h.
Referenced by LinkEasyEase(), and Update().
rainbowNoise
RainbowNoise rainbowNoise private
Definition at line 30 of file WaffleDaProtoAnimation.h.
Referenced by SetMaterials(), and Update().
rainbowSpectrum
RGBColor rainbowSpectrum[6] = {RGBColor(255, 0, 0), RGBColor(255, 255, 0), RGBColor(0, 255, 0), RGBColor(0, 255, 255), RGBColor(0, 0, 255), RGBColor(255, 0, 255)} private
Definition at line 38 of file DatBlueHuskyAnimation.h.
rainbowSpiral
RainbowSpiral rainbowSpiral private
Definition at line 31 of file WaffleDaProtoAnimation.h.
Referenced by SetMaterials(), and Update().
redMaterial
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0)) private
Definition at line 34 of file DatBlueHuskyAnimation.h.
Referenced by SetMaterials().
sA
SpectrumAnalyzer sA = SpectrumAnalyzer(22, Vector2D(250, 200), Vector2D(120, 100), true, true) private
Definition at line 39 of file WaffleDaProtoAnimation.h.
Referenced by Update(), and WaffleDaProtoAnimation().
sNoise
SimplexNoise sNoise = SimplexNoise(1, &gNoiseMat) private
Definition at line 29 of file DatBlueHuskyAnimation.h.
Referenced by Update().
spiralMaterial
SpiralMaterial spiralMaterial = SpiralMaterial(6, rainbowSpectrum, 3.0f, 7.0f) private
Definition at line 39 of file DatBlueHuskyAnimation.h.
Referenced by Update().
talk
bool talk = true private
Definition at line 60 of file DatBlueHuskyAnimation.h.
Referenced by Angry(), Default(), Doubt(), Frown(), LookDown(), LookUp(), Sad(), Surprised(), and Update().
voiceDetection
FFTVoiceDetection<128> voiceDetection private
Definition at line 56 of file WaffleDaProtoAnimation.h.
Referenced by UpdateFFTVisemes().
The documentation for this class was generated from the following files:
DatBlueHuskyAnimation.h
WaffleDaProtoAnimation.h