KaiborgV1D1Controller Class Reference
KaiborgV1D1Controller Class Reference
#include <KaiborgV1D1Xenrax.h>
Public Member Functions
KaiborgV1D1Controller (uint8_t maxBrightness)
void Initialize () override
Initializes the controller.
void Display () override
Updates and displays content on the lighting system.
void SetPixels (uint8_t strip, uint16_t led, RGBColor rgb)
Public Member Functions inherited from Controller
uint8_t GetBrightness ()
Retrieves the current brightness level.
uint8_t GetAccentBrightness ()
Retrieves the current accent brightness level.
virtual void SetBrightness (uint8_t maxBrightness)=0
Sets the maximum brightness for the controller.
virtual void SetAccentBrightness (uint8_t maxAccentBrightness)=0
Sets the maximum accent brightness for the controller.
Private Attributes
CameraLayout cameraLayout = CameraLayout(CameraLayout::ZForward, CameraLayout::YUp)
Transform camRghtTransform = Transform(Vector3D(), Vector3D(0, 0, -500.0f), Vector3D(1, 1, 1))
Transform camLeftTransform = Transform(Vector3D(), Vector3D(0, 0, -500.0f), Vector3D(1, 1, 1))
Transform camFinTransform = Transform(Vector3D(0.0f, 0.0f, 1.0f), Vector3D(180.0f, 0, -500.0f), Vector3D(1, 1, 1))
Transform camSquTransform = Transform(Vector3D(0.0f, 0.0f, 1.0f), Vector3D(180.0f, 0, -500.0f), Vector3D(1, 1, 1))
Transform camRinTransform = Transform(Vector3D(0.0f, 0.0f, 1.0f), Vector3D(180.0f, 0, -500.0f), Vector3D(1, 1, 1))
PixelGroup< 571 > camRghtPixels = PixelGroup<571>(KaiborgV1Pixels, IPixelGroup::ZEROTOMAX)
PixelGroup< 571 > camLeftPixels = PixelGroup<571>(KaiborgV1Pixels, IPixelGroup::MAXTOZERO)
PixelGroup< 27 > camFinPixels = PixelGroup<27>(XenraxStrip, IPixelGroup::ZEROTOMAX)
PixelGroup< 36 > camSquPixels = PixelGroup<36>(XenraxSquare, IPixelGroup::ZEROTOMAX)
PixelGroup< 36 > camRinPixels = PixelGroup<36>(XenraxRing, IPixelGroup::ZEROTOMAX)
Camera< 571 > camRght = Camera<571>(&camRghtTransform, &cameraLayout, &camRghtPixels)
Camera< 571 > camLeft = Camera<571>(&camLeftTransform, &cameraLayout, &camLeftPixels)
Camera< 27 > camFin = Camera<27>(&camFinTransform, &cameraLayout, &camFinPixels)
Camera< 36 > camSqu = Camera<36>(&camSquTransform, &cameraLayout, &camSquPixels)
Camera< 36 > camRin = Camera<36>(&camRinTransform, &cameraLayout, &camRinPixels)
CameraBase * cameras [5] = { &camRght, &camLeft, &camFin, &camSqu, &camRin }
Additional Inherited Members
Protected Member Functions inherited from Controller
Controller (CameraManager *cameras, uint8_t maxBrightness, uint8_t maxAccentBrightness)
Constructs a Controller with specified parameters.
void UpdateBrightness ()
Updates the brightness based on internal logic.
Protected Attributes inherited from Controller
CameraManager * cameras
Pointer to the CameraManager for managing camera data.
uint8_t brightness
Current brightness level.
uint8_t accentBrightness
Current accent brightness level.
uint8_t maxBrightness
Maximum allowed brightness level.
uint8_t maxAccentBrightness
Maximum allowed accent brightness level.
bool isOn = false
Indicates if the controller is active.
bool startTime = false
Indicates if the start time has been recorded.
Detailed Description
Definition at line 18 of file KaiborgV1D1Xenrax.h.
Constructor & Destructor Documentation
KaiborgV1D1Controller()
KaiborgV1D1Controller (uint8_t maxBrightness) inline
Definition at line 44 of file KaiborgV1D1Xenrax.h.
Member Function Documentation
Display()
void Display () inline override virtual
Updates and displays content on the lighting system.
Implements Controller.
Definition at line 51 of file KaiborgV1D1Xenrax.h.
References Controller::accentBrightness, RGBColor::B, Controller::brightness, camFinPixels, camLeftPixels, camRghtPixels, camRinPixels, camSquPixels, RGBColor::G, PixelGroup< pixelCount >::GetColor(), leds(), RGBColor::R, and RGBColor::Scale().
Initialize()
void Initialize () inline override virtual
Initializes the controller.
Implements Controller.
Definition at line 46 of file KaiborgV1D1Xenrax.h.
References leds().
SetPixels()
void SetPixels (uint8_t strip, uint16_t led, RGBColor rgb) inline
Definition at line 96 of file KaiborgV1D1Xenrax.h.
References RGBColor::B, RGBColor::G, leds(), and RGBColor::R.
Member Data Documentation
cameraLayout
CameraLayout cameraLayout = CameraLayout(CameraLayout::ZForward, CameraLayout::YUp) private
Definition at line 20 of file KaiborgV1D1Xenrax.h.
cameras
CameraBase* cameras[5] = { &camRght, &camLeft, &camFin, &camSqu, &camRin } private
Definition at line 41 of file KaiborgV1D1Xenrax.h.
camFin
Camera<27> camFin = Camera<27>(&camFinTransform, &cameraLayout, &camFinPixels) private
Definition at line 37 of file KaiborgV1D1Xenrax.h.
camFinPixels
PixelGroup<27> camFinPixels = PixelGroup<27>(XenraxStrip, IPixelGroup::ZEROTOMAX) private
Definition at line 31 of file KaiborgV1D1Xenrax.h.
Referenced by Display().
camFinTransform
Transform camFinTransform = Transform(Vector3D(0.0f, 0.0f, 1.0f), Vector3D(180.0f, 0, -500.0f), Vector3D(1, 1, 1)) private
Definition at line 25 of file KaiborgV1D1Xenrax.h.
camLeft
Camera<571> camLeft = Camera<571>(&camLeftTransform, &cameraLayout, &camLeftPixels) private
Definition at line 36 of file KaiborgV1D1Xenrax.h.
camLeftPixels
PixelGroup<571> camLeftPixels = PixelGroup<571>(KaiborgV1Pixels, IPixelGroup::MAXTOZERO) private
Definition at line 30 of file KaiborgV1D1Xenrax.h.
Referenced by Display().
camLeftTransform
Transform camLeftTransform = Transform(Vector3D(), Vector3D(0, 0, -500.0f), Vector3D(1, 1, 1)) private
Definition at line 24 of file KaiborgV1D1Xenrax.h.
camRght
Camera<571> camRght = Camera<571>(&camRghtTransform, &cameraLayout, &camRghtPixels) private
Definition at line 35 of file KaiborgV1D1Xenrax.h.
camRghtPixels
PixelGroup<571> camRghtPixels = PixelGroup<571>(KaiborgV1Pixels, IPixelGroup::ZEROTOMAX) private
Definition at line 29 of file KaiborgV1D1Xenrax.h.
Referenced by Display().
camRghtTransform
Transform camRghtTransform = Transform(Vector3D(), Vector3D(0, 0, -500.0f), Vector3D(1, 1, 1)) private
Definition at line 23 of file KaiborgV1D1Xenrax.h.
camRin
Camera<36> camRin = Camera<36>(&camRinTransform, &cameraLayout, &camRinPixels) private
Definition at line 39 of file KaiborgV1D1Xenrax.h.
camRinPixels
PixelGroup<36> camRinPixels = PixelGroup<36>(XenraxRing, IPixelGroup::ZEROTOMAX) private
Definition at line 33 of file KaiborgV1D1Xenrax.h.
Referenced by Display().
camRinTransform
Transform camRinTransform = Transform(Vector3D(0.0f, 0.0f, 1.0f), Vector3D(180.0f, 0, -500.0f), Vector3D(1, 1, 1)) private
Definition at line 27 of file KaiborgV1D1Xenrax.h.
camSqu
Camera<36> camSqu = Camera<36>(&camSquTransform, &cameraLayout, &camSquPixels) private
Definition at line 38 of file KaiborgV1D1Xenrax.h.
camSquPixels
PixelGroup<36> camSquPixels = PixelGroup<36>(XenraxSquare, IPixelGroup::ZEROTOMAX) private
Definition at line 32 of file KaiborgV1D1Xenrax.h.
Referenced by Display().
camSquTransform
Transform camSquTransform = Transform(Vector3D(0.0f, 0.0f, 1.0f), Vector3D(180.0f, 0, -500.0f), Vector3D(1, 1, 1)) private
Definition at line 26 of file KaiborgV1D1Xenrax.h.
The documentation for this class was generated from the following file:
KaiborgV1D1Xenrax.h