GammaAnimation Class Reference
GammaAnimation Class Reference
#include <GammaProject.h>
Public Member Functions
GammaAnimation ()
void Initialize () override
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
Object3D * GetObject ()
void Update (float ratio) override
Private Member Functions
void LinkEasyEase ()
void LinkParameters ()
void ChangeInterpolationMethods ()
void SetMaterialLayers ()
void UpdateKeyFrameTracks ()
void Default ()
void OwO ()
void Sad ()
void Dead ()
void Heart ()
void OwO2 ()
void AlphaGenCircle ()
void AngryFace ()
void SpectrumAnalyzerFace ()
void AudioReactiveGradientFace ()
void OscilloscopeFace ()
void UpdateFFTVisemes ()
void SetMaterialColor ()
Private Attributes
GammaFace pM
Background background
EasyEaseAnimator< 30 > eEA = EasyEaseAnimator<30>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f)
RainbowNoise rainbowNoise
RainbowSpiral rainbowSpiral
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0))
SimpleMaterial orangeMaterial = SimpleMaterial(RGBColor(255, 165, 0))
SimpleMaterial whiteMaterial = SimpleMaterial(RGBColor(255, 255, 255))
SimpleMaterial greenMaterial = SimpleMaterial(RGBColor(0, 255, 0))
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255))
SimpleMaterial yellowMaterial = SimpleMaterial(RGBColor(255, 255, 0))
SimpleMaterial purpleMaterial = SimpleMaterial(RGBColor(255, 0, 255))
RGBColor gradientSpectrum [6] = {RGBColor(255, 0, 0), RGBColor(255, 255, 0), RGBColor(0, 255, 0), RGBColor(0, 255, 255), RGBColor(0, 0, 255), RGBColor(255, 0, 255)}
GradientMaterial< 6 > gradientMat = GradientMaterial<6>(gradientSpectrum, 350.0f, false)
MaterialAnimator< 10 > materialAnimator
MaterialAnimator< 4 > backgroundMaterial
SpectrumAnalyzer sA = SpectrumAnalyzer(Vector2D(400, 250), Vector2D(-150, 130), true, true)
AudioReactiveGradient aRG = AudioReactiveGradient(Vector2D(160, 160), Vector2D(-200, 100), true, true)
Oscilloscope oSC = Oscilloscope(Vector2D(200, 100), Vector2D(-200, 100))
BlinkTrack< 1 > blink
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f)
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f)
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f)
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 5.3f)
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 6.7f)
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f)
FunctionGenerator fGenMatXMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 1.1f)
FunctionGenerator fGenMatYMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 2.7f)
FunctionGenerator fGenMatRMenu = FunctionGenerator(FunctionGenerator::Sine, -5.0f, 5.0f, 1.7f)
KalmanFilter< 25 > ratioCompensation = KalmanFilter<25>(0.1f)
APDS9960 forehead
SHARPGP2Y boop = SHARPGP2Y(A9)
FFTVoiceDetection< 128 > voiceDetection
float offsetFace = 0.0f
float offsetFaceSA = 0.0f
float offsetFaceARG = 0.0f
float offsetFaceOSC = 0.0f
uint8_t offsetFaceInd = 50
uint8_t offsetFaceIndSA = 51
uint8_t offsetFaceIndARG = 52
uint8_t offsetFaceIndOSC = 53
Detailed Description
Definition at line 40 of file GammaProject.h.
Constructor & Destructor Documentation
GammaAnimation()
GammaAnimation () inline
Definition at line 305 of file GammaProject.h.
References background, backgroundMaterial, ChangeInterpolationMethods(), LinkEasyEase(), LinkParameters(), materialAnimator, pM, and SetMaterialLayers().
Member Function Documentation
AlphaGenCircle()
void AlphaGenCircle () inline private
Definition at line 228 of file GammaProject.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, AnimationTrack< maxParameters, maxKeyFrames >::Play(), and pM.
Referenced by Update().
AngryFace()
void AngryFace () inline private
Definition at line 237 of file GammaProject.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, materialAnimator, AnimationTrack< maxParameters, maxKeyFrames >::Play(), pM, and redMaterial.
Referenced by Update().
AudioReactiveGradientFace()
void AudioReactiveGradientFace () inline private
Definition at line 257 of file GammaProject.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), aRG, backgroundMaterial, eEA, offsetFaceARG, offsetFaceInd, and offsetFaceIndARG.
Referenced by Update().
ChangeInterpolationMethods()
void ChangeInterpolationMethods () inline private
Definition at line 134 of file GammaProject.h.
References eEA, and EasyEaseAnimator< maxParameters >::SetInterpolationMethod().
Referenced by GammaAnimation().
Dead()
void Dead () inline private
Definition at line 198 of file GammaProject.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, materialAnimator, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), and redMaterial.
Referenced by Update().
Default()
void Default () inline private
Definition at line 167 of file GammaProject.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, AnimationTrack< maxParameters, maxKeyFrames >::Play(), and pM.
Referenced by Update().
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 340 of file GammaProject.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 341 of file GammaProject.h.
GetObject()
Object3D * GetObject () inline
Definition at line 343 of file GammaProject.h.
References pM.
Heart()
void Heart () inline private
Definition at line 208 of file GammaProject.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, materialAnimator, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), and rainbowSpiral.
Referenced by Update().
Initialize()
void Initialize () inline override
Definition at line 320 of file GammaProject.h.
References forehead, SerialSync::Initialize(), Menu::Initialize(), and APDS9960::Initialize().
LinkEasyEase()
void LinkEasyEase () inline private
Definition at line 100 of file GammaProject.h.
References EasyEaseAnimator< maxParameters >::AddParameter(), eEA, offsetFace, offsetFaceARG, offsetFaceInd, offsetFaceIndARG, offsetFaceIndOSC, offsetFaceIndSA, offsetFaceOSC, offsetFaceSA, and pM.
Referenced by GammaAnimation().
LinkParameters()
void LinkParameters () inline private
Definition at line 130 of file GammaProject.h.
References AnimationTrack< maxParameters, maxKeyFrames >::AddParameter(), blink, and pM.
Referenced by GammaAnimation().
OscilloscopeFace()
void OscilloscopeFace () inline private
Definition at line 264 of file GammaProject.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), backgroundMaterial, eEA, offsetFaceInd, offsetFaceIndOSC, offsetFaceOSC, and oSC.
Referenced by Update().
OwO()
void OwO () inline private
Definition at line 175 of file GammaProject.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, materialAnimator, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), and rainbowSpiral.
Referenced by Update().
OwO2()
void OwO2 () inline private
Definition at line 219 of file GammaProject.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, materialAnimator, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), and rainbowSpiral.
Referenced by Update().
Sad()
void Sad () inline private
Definition at line 187 of file GammaProject.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, blueMaterial, eEA, materialAnimator, and AnimationTrack< maxParameters, maxKeyFrames >::Play().
Referenced by Update().
SetMaterialColor()
void SetMaterialColor () inline private
Definition at line 289 of file GammaProject.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), blueMaterial, Menu::GetFaceColor(), greenMaterial, materialAnimator, orangeMaterial, purpleMaterial, rainbowNoise, rainbowSpiral, redMaterial, whiteMaterial, and yellowMaterial.
Referenced by Update().
SetMaterialLayers()
void SetMaterialLayers () inline private
Definition at line 145 of file GammaProject.h.
References Material::Add, MaterialAnimator< materialCount >::AddMaterial(), aRG, backgroundMaterial, blueMaterial, Menu::GetMaterial(), gradientMat, greenMaterial, Material::Lighten, materialAnimator, orangeMaterial, oSC, purpleMaterial, rainbowNoise, rainbowSpiral, redMaterial, Material::Replace, sA, MaterialAnimator< materialCount >::SetBaseMaterial(), whiteMaterial, and yellowMaterial.
Referenced by GammaAnimation().
SpectrumAnalyzerFace()
void SpectrumAnalyzerFace () inline private
Definition at line 250 of file GammaProject.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), backgroundMaterial, eEA, offsetFaceInd, offsetFaceIndSA, offsetFaceSA, and sA.
Referenced by Update().
Update()
void Update (float ratio) inline override
Definition at line 347 of file GammaProject.h.
References AlphaGenCircle(), AngryFace(), aRG, AudioReactiveGradientFace(), backgroundMaterial, boop, Dead(), Default(), eEA, fGenMatXMove, fGenMatYMove, KalmanFilter< T >::Filter(), forehead, Menu::GetAccentBrightness(), SerialSync::GetAccentBrightness(), SerialSync::GetBoop(), Menu::GetBrightness(), SerialSync::GetBrightness(), MenuHandler< menuCount >::GetCurrentMenu(), SerialSync::GetCurrentMenu(), SerialSync::GetDead(), Menu::GetFaceColor(), SerialSync::GetFaceColor(), Menu::GetFaceSize(), SerialSync::GetFaceSize(), Menu::GetFaceState(), SerialSync::GetFaceState(), Menu::GetMicLevel(), SerialSync::GetMicLevel(), SerialSync::GetMouthMove(), SerialSync::GetRatio(), APDS9960::GetValue(), Heart(), materialAnimator, Menu::MirrorSpectrumAnalyzer(), SerialSync::MirrorSpectrumAnalyzer(), offsetFace, oSC, OscilloscopeFace(), OwO(), OwO2(), pM, rainbowNoise, rainbowSpiral, ratioCompensation, SerialSync::Read(), sA, Sad(), SerialSync::Send(), Menu::SetAccentBrightness(), SerialSync::SetAccentBrightness(), SerialSync::SetBoop(), Menu::SetBrightness(), SerialSync::SetBrightness(), Menu::SetCurrentMenu(), SerialSync::SetCurrentMenu(), SerialSync::SetDead(), Menu::SetFaceColor(), SerialSync::SetFaceColor(), Menu::SetFaceSize(), SerialSync::SetFaceSize(), Menu::SetFaceState(), SerialSync::SetFaceState(), SpectrumAnalyzer::SetFlipYState(), AudioReactiveGradient::SetHueAngle(), Oscilloscope::SetHueAngle(), SpectrumAnalyzer::SetHueAngle(), SetMaterialColor(), Menu::SetMicLevel(), SerialSync::SetMicLevel(), Menu::SetMirrorSpectrumAnalyzer(), SerialSync::SetMirrorSpectrumAnalyzer(), SpectrumAnalyzer::SetMirrorYState(), SerialSync::SetMode(), SerialSync::SetMouthMove(), AudioReactiveGradient::SetPosition(), Oscilloscope::SetPosition(), Menu::SetPositionOffset(), AudioReactiveGradient::SetRadius(), SerialSync::SetRatio(), AudioReactiveGradient::SetRotation(), Oscilloscope::SetRotation(), AudioReactiveGradient::SetSize(), Oscilloscope::SetSize(), FFTVoiceDetection< peakCount >::SetThreshold(), Menu::SetUseBoopSensor(), SerialSync::SetUseBoopSensor(), Menu::SetUseMicrophone(), SerialSync::SetUseMicrophone(), Menu::ShowMenu(), SpectrumAnalyzerFace(), SHARPGP2Y::Update(), MaterialAnimator< materialCount >::Update(), FunctionGenerator::Update(), EasyEaseAnimator< maxParameters >::Update(), Oscilloscope::Update(), AudioReactiveGradient::Update(), SpectrumAnalyzer::Update(), Menu::Update(), RainbowNoise::Update(), RainbowSpiral::Update(), UpdateFFTVisemes(), UpdateKeyFrameTracks(), Menu::UseBoopSensor(), SerialSync::UseBoopSensor(), Menu::UseMicrophone(), SerialSync::UseMicrophone(), and voiceDetection.
UpdateFFTVisemes()
void UpdateFFTVisemes () inline private
Definition at line 271 of file GammaProject.h.
References FFTVoiceDetection< peakCount >::Update(), Menu::UseMicrophone(), and voiceDetection.
Referenced by Update().
UpdateKeyFrameTracks()
void UpdateKeyFrameTracks () inline private
Definition at line 163 of file GammaProject.h.
References blink, and AnimationTrack< maxParameters, maxKeyFrames >::Update().
Referenced by Update().
Member Data Documentation
aRG
AudioReactiveGradient aRG = AudioReactiveGradient(Vector2D(160, 160), Vector2D(-200, 100), true, true) private
Definition at line 64 of file GammaProject.h.
Referenced by AudioReactiveGradientFace(), SetMaterialLayers(), and Update().
background
Background background private
Definition at line 43 of file GammaProject.h.
Referenced by GammaAnimation().
backgroundMaterial
MaterialAnimator<4> backgroundMaterial private
Definition at line 61 of file GammaProject.h.
Referenced by AudioReactiveGradientFace(), GammaAnimation(), OscilloscopeFace(), SetMaterialLayers(), SpectrumAnalyzerFace(), and Update().
blink
BlinkTrack<1> blink private
Definition at line 68 of file GammaProject.h.
Referenced by AlphaGenCircle(), AngryFace(), Dead(), Default(), Heart(), LinkParameters(), OwO(), OwO2(), Sad(), and UpdateKeyFrameTracks().
blueMaterial
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255)) private
Definition at line 53 of file GammaProject.h.
Referenced by Sad(), SetMaterialColor(), and SetMaterialLayers().
boop
SHARPGP2Y boop = SHARPGP2Y(A9) private
Definition at line 84 of file GammaProject.h.
Referenced by Update().
eEA
EasyEaseAnimator<30> eEA = EasyEaseAnimator<30>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f) private
Definition at line 44 of file GammaProject.h.
Referenced by AlphaGenCircle(), AngryFace(), AudioReactiveGradientFace(), ChangeInterpolationMethods(), Dead(), Default(), Heart(), LinkEasyEase(), OscilloscopeFace(), OwO(), OwO2(), Sad(), SpectrumAnalyzerFace(), and Update().
fGenMatHue
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f) private
Definition at line 75 of file GammaProject.h.
fGenMatPos
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f) private
Definition at line 70 of file GammaProject.h.
fGenMatRMenu
FunctionGenerator fGenMatRMenu = FunctionGenerator(FunctionGenerator::Sine, -5.0f, 5.0f, 1.7f) private
Definition at line 79 of file GammaProject.h.
fGenMatXMenu
FunctionGenerator fGenMatXMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 1.1f) private
Definition at line 77 of file GammaProject.h.
fGenMatXMove
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 5.3f) private
Definition at line 73 of file GammaProject.h.
Referenced by Update().
fGenMatYMenu
FunctionGenerator fGenMatYMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 2.7f) private
Definition at line 78 of file GammaProject.h.
fGenMatYMove
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 6.7f) private
Definition at line 74 of file GammaProject.h.
Referenced by Update().
fGenRotation
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f) private
Definition at line 71 of file GammaProject.h.
fGenScale
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f) private
Definition at line 72 of file GammaProject.h.
forehead
APDS9960 forehead private
Definition at line 83 of file GammaProject.h.
Referenced by Initialize(), and Update().
gradientMat
GradientMaterial<6> gradientMat = GradientMaterial<6>(gradientSpectrum, 350.0f, false) private
Definition at line 58 of file GammaProject.h.
Referenced by SetMaterialLayers().
gradientSpectrum
RGBColor gradientSpectrum[6] = {RGBColor(255, 0, 0), RGBColor(255, 255, 0), RGBColor(0, 255, 0), RGBColor(0, 255, 255), RGBColor(0, 0, 255), RGBColor(255, 0, 255)} private
Definition at line 57 of file GammaProject.h.
greenMaterial
SimpleMaterial greenMaterial = SimpleMaterial(RGBColor(0, 255, 0)) private
Definition at line 52 of file GammaProject.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
materialAnimator
MaterialAnimator<10> materialAnimator private
Definition at line 60 of file GammaProject.h.
Referenced by AngryFace(), Dead(), GammaAnimation(), Heart(), OwO(), OwO2(), Sad(), SetMaterialColor(), SetMaterialLayers(), and Update().
offsetFace
float offsetFace = 0.0f private
Definition at line 91 of file GammaProject.h.
Referenced by LinkEasyEase(), and Update().
offsetFaceARG
float offsetFaceARG = 0.0f private
Definition at line 93 of file GammaProject.h.
Referenced by AudioReactiveGradientFace(), and LinkEasyEase().
offsetFaceInd
uint8_t offsetFaceInd = 50 private
Definition at line 95 of file GammaProject.h.
Referenced by AudioReactiveGradientFace(), LinkEasyEase(), OscilloscopeFace(), and SpectrumAnalyzerFace().
offsetFaceIndARG
uint8_t offsetFaceIndARG = 52 private
Definition at line 97 of file GammaProject.h.
Referenced by AudioReactiveGradientFace(), and LinkEasyEase().
offsetFaceIndOSC
uint8_t offsetFaceIndOSC = 53 private
Definition at line 98 of file GammaProject.h.
Referenced by LinkEasyEase(), and OscilloscopeFace().
offsetFaceIndSA
uint8_t offsetFaceIndSA = 51 private
Definition at line 96 of file GammaProject.h.
Referenced by LinkEasyEase(), and SpectrumAnalyzerFace().
offsetFaceOSC
float offsetFaceOSC = 0.0f private
Definition at line 94 of file GammaProject.h.
Referenced by LinkEasyEase(), and OscilloscopeFace().
offsetFaceSA
float offsetFaceSA = 0.0f private
Definition at line 92 of file GammaProject.h.
Referenced by LinkEasyEase(), and SpectrumAnalyzerFace().
orangeMaterial
SimpleMaterial orangeMaterial = SimpleMaterial(RGBColor(255, 165, 0)) private
Definition at line 50 of file GammaProject.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
oSC
Oscilloscope oSC = Oscilloscope(Vector2D(200, 100), Vector2D(-200, 100)) private
Definition at line 65 of file GammaProject.h.
Referenced by OscilloscopeFace(), SetMaterialLayers(), and Update().
pM
GammaFace pM private
Definition at line 42 of file GammaProject.h.
Referenced by AlphaGenCircle(), AngryFace(), Default(), GammaAnimation(), GetObject(), LinkEasyEase(), LinkParameters(), and Update().
purpleMaterial
SimpleMaterial purpleMaterial = SimpleMaterial(RGBColor(255, 0, 255)) private
Definition at line 55 of file GammaProject.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
rainbowNoise
RainbowNoise rainbowNoise private
Definition at line 47 of file GammaProject.h.
Referenced by SetMaterialColor(), SetMaterialLayers(), and Update().
rainbowSpiral
RainbowSpiral rainbowSpiral private
Definition at line 48 of file GammaProject.h.
Referenced by Heart(), OwO(), OwO2(), SetMaterialColor(), SetMaterialLayers(), and Update().
ratioCompensation
KalmanFilter<25> ratioCompensation = KalmanFilter<25>(0.1f) private
Definition at line 81 of file GammaProject.h.
Referenced by Update().
redMaterial
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0)) private
Definition at line 49 of file GammaProject.h.
Referenced by AngryFace(), Dead(), SetMaterialColor(), and SetMaterialLayers().
sA
SpectrumAnalyzer sA = SpectrumAnalyzer(Vector2D(400, 250), Vector2D(-150, 130), true, true) private
Definition at line 63 of file GammaProject.h.
Referenced by SetMaterialLayers(), SpectrumAnalyzerFace(), and Update().
voiceDetection
FFTVoiceDetection<128> voiceDetection private
Definition at line 89 of file GammaProject.h.
Referenced by Update(), and UpdateFFTVisemes().
whiteMaterial
SimpleMaterial whiteMaterial = SimpleMaterial(RGBColor(255, 255, 255)) private
Definition at line 51 of file GammaProject.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
yellowMaterial
SimpleMaterial yellowMaterial = SimpleMaterial(RGBColor(255, 255, 0)) private
Definition at line 54 of file GammaProject.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
The documentation for this class was generated from the following file:
GammaProject.h