BetaProtoController Class Reference
BetaProtoController Class Reference
#include <BetaProtoController.h>
Public Member Functions
BetaProtoController (uint8_t maxBrightness, uint8_t maxAccentBrightness)
void Initialize () override
Initializes the controller.
void Display () override
Updates and displays content on the lighting system.
Public Member Functions inherited from Controller
uint8_t GetBrightness ()
Retrieves the current brightness level.
uint8_t GetAccentBrightness ()
Retrieves the current accent brightness level.
virtual void SetBrightness (uint8_t maxBrightness)=0
Sets the maximum brightness for the controller.
virtual void SetAccentBrightness (uint8_t maxAccentBrightness)=0
Sets the maximum accent brightness for the controller.
Private Attributes
CameraLayout cameraLayout = CameraLayout(CameraLayout::ZForward, CameraLayout::YUp)
Transform camRghtFrntTransform = Transform(Vector3D(0.0f, 0.0f, 0.0f), Vector3D(0.0f, 0, -500.0f), Vector3D(1, 1, 1))
Transform camRghtRearTransform = Transform(Vector3D(0.0f, 0.0f, 159.0f), Vector3D(387.0f, 190.0f, -500.0f), Vector3D(1, 1, 1))
PixelGroup< 571 > camRghtFrntPixels = PixelGroup<571>(KaiborgV1Pixels, PixelGroup<571>::ZEROTOMAX)
PixelGroup< 571 > camRghtRearPixels = PixelGroup<571>(KaiborgV1Pixels, PixelGroup<571>::ZEROTOMAX)
Camera< 571 > camRghtFrnt = Camera<571>(&camRghtFrntTransform, &cameraLayout, &camRghtFrntPixels)
Camera< 571 > camRghtRear = Camera<571>(&camRghtRearTransform, &cameraLayout, &camRghtRearPixels)
CameraBase * cameras [2] = { &camRghtFrnt, &camRghtRear }
uint8_t maxBrightness
uint8_t maxAccentBrightness
Additional Inherited Members
Protected Member Functions inherited from Controller
Controller (CameraManager *cameras, uint8_t maxBrightness, uint8_t maxAccentBrightness)
Constructs a Controller with specified parameters.
void UpdateBrightness ()
Updates the brightness based on internal logic.
Protected Attributes inherited from Controller
CameraManager * cameras
Pointer to the CameraManager for managing camera data.
uint8_t brightness
Current brightness level.
uint8_t accentBrightness
Current accent brightness level.
uint8_t maxBrightness
Maximum allowed brightness level.
uint8_t maxAccentBrightness
Maximum allowed accent brightness level.
bool isOn = false
Indicates if the controller is active.
bool startTime = false
Indicates if the start time has been recorded.
Detailed Description
Definition at line 16 of file BetaProtoController.h.
Constructor & Destructor Documentation
BetaProtoController()
BetaProtoController (uint8_t maxBrightness, uint8_t maxAccentBrightness) inline
Definition at line 34 of file BetaProtoController.h.
References maxAccentBrightness, and maxBrightness.
Member Function Documentation
Display()
void Display () inline override virtual
Updates and displays content on the lighting system.
Implements Controller.
Definition at line 44 of file BetaProtoController.h.
References Controller::accentBrightness, RGBColor::B, Controller::brightness, camRghtFrntPixels, camRghtRearPixels, RGBColor::G, PixelGroup< pixelCount >::GetColor(), leds(), RGBColor::R, and RGBColor::Scale().
Initialize()
void Initialize () inline override virtual
Initializes the controller.
Implements Controller.
Definition at line 39 of file BetaProtoController.h.
References leds().
Member Data Documentation
cameraLayout
CameraLayout cameraLayout = CameraLayout(CameraLayout::ZForward, CameraLayout::YUp) private
Definition at line 18 of file BetaProtoController.h.
cameras
CameraBase* cameras[2] = { &camRghtFrnt, &camRghtRear } private
Definition at line 29 of file BetaProtoController.h.
camRghtFrnt
Camera<571> camRghtFrnt = Camera<571>(&camRghtFrntTransform, &cameraLayout, &camRghtFrntPixels) private
Definition at line 26 of file BetaProtoController.h.
camRghtFrntPixels
PixelGroup<571> camRghtFrntPixels = PixelGroup<571>(KaiborgV1Pixels, PixelGroup<571>::ZEROTOMAX) private
Definition at line 23 of file BetaProtoController.h.
Referenced by Display().
camRghtFrntTransform
Transform camRghtFrntTransform = Transform(Vector3D(0.0f, 0.0f, 0.0f), Vector3D(0.0f, 0, -500.0f), Vector3D(1, 1, 1)) private
Definition at line 20 of file BetaProtoController.h.
camRghtRear
Camera<571> camRghtRear = Camera<571>(&camRghtRearTransform, &cameraLayout, &camRghtRearPixels) private
Definition at line 27 of file BetaProtoController.h.
camRghtRearPixels
PixelGroup<571> camRghtRearPixels = PixelGroup<571>(KaiborgV1Pixels, PixelGroup<571>::ZEROTOMAX) private
Definition at line 24 of file BetaProtoController.h.
Referenced by Display().
camRghtRearTransform
Transform camRghtRearTransform = Transform(Vector3D(0.0f, 0.0f, 159.0f), Vector3D(387.0f, 190.0f, -500.0f), Vector3D(1, 1, 1)) private
Definition at line 21 of file BetaProtoController.h.
maxAccentBrightness
uint8_t maxAccentBrightness private
Definition at line 31 of file BetaProtoController.h.
Referenced by BetaProtoController().
maxBrightness
uint8_t maxBrightness private
Definition at line 30 of file BetaProtoController.h.
Referenced by BetaProtoController().
The documentation for this class was generated from the following file:
BetaProtoController.h