ITriangleGroup Class Reference
ITriangleGroup Class Reference abstract
Interface for managing a dynamic group of 3D triangles and associated data.
#include <ITriangleGroup.h>
Public Member Functions
virtual const IndexGroup * GetIndexGroup ()=0
Retrieves the index group for the triangle group.
virtual int GetTriangleCount ()=0
Retrieves the total number of triangles in the group.
virtual Vector3D * GetVertices ()=0
Retrieves the array of mutable vertices in the triangle group.
virtual int GetVertexCount ()=0
Retrieves the total number of vertices in the group.
virtual Triangle3D * GetTriangles ()=0
Retrieves the array of Triangle3D objects representing the triangles.
virtual const Vector2D * GetUVVertices ()=0
Retrieves the array of UV vertices in the triangle group.
virtual const IndexGroup * GetUVIndexGroup ()=0
Retrieves the index group for the UV vertices.
Detailed Description
Interface for managing a dynamic group of 3D triangles and associated data.
Definition at line 23 of file ITriangleGroup.h.
Member Function Documentation
GetIndexGroup()
virtual const IndexGroup * GetIndexGroup () pure virtual
Retrieves the index group for the triangle group.
Returns
A pointer to the IndexGroup array.
Implemented in TriangleGroup< vertexCount, triangleCount >.
GetTriangleCount()
virtual int GetTriangleCount () pure virtual
Retrieves the total number of triangles in the group.
Returns
The number of triangles.
Implemented in TriangleGroup< vertexCount, triangleCount >.
Referenced by Rasterizer::Rasterize().
GetTriangles()
virtual Triangle3D * GetTriangles () pure virtual
Retrieves the array of Triangle3D objects representing the triangles.
Returns
A pointer to the array of Triangle3D objects.
Implemented in TriangleGroup< vertexCount, triangleCount >.
Referenced by ObjectAlign::GetPlaneNormal(), VectorField2D::ObjectField(), and Rasterizer::Rasterize().
GetUVIndexGroup()
virtual const IndexGroup * GetUVIndexGroup () pure virtual
Retrieves the index group for the UV vertices.
Returns
A pointer to the IndexGroup array for UV vertices.
Implemented in TriangleGroup< vertexCount, triangleCount >.
GetUVVertices()
virtual const Vector2D * GetUVVertices () pure virtual
Retrieves the array of UV vertices in the triangle group.
Returns
A pointer to the array of Vector2D UV vertices.
Implemented in TriangleGroup< vertexCount, triangleCount >.
GetVertexCount()
virtual int GetVertexCount () pure virtual
Retrieves the total number of vertices in the group.
Returns
The number of vertices.
Implemented in TriangleGroup< vertexCount, triangleCount >.
Referenced by ObjectAlign::AlignObjects(), TriangleGroupDeformer::AxisZeroClipping(), TriangleGroupDeformer::CosineInterpolationDeformer(), TriangleGroupDeformer::DropwaveDeform(), Object3D::GetCenterOffset(), Object3D::GetMinMaxDimensions(), ObjectAlign::GetObjectPlanarityRatio(), Object3D::ResetVertices(), TriangleGroupDeformer::SineWaveSurfaceDeform(), TriangleGroupDeformer::SinusoidalDeform(), and Object3D::UpdateTransform().
GetVertices()
virtual Vector3D * GetVertices () pure virtual
Retrieves the array of mutable vertices in the triangle group.
Returns
A pointer to the array of Vector3D vertices.
Implemented in TriangleGroup< vertexCount, triangleCount >.
Referenced by ObjectAlign::AlignObjects(), ObjectAlign::AlignObjectsNoScale(), TriangleGroupDeformer::AxisZeroClipping(), ObjectDeformer::AxisZeroClipping(), TriangleGroupDeformer::CosineInterpolationDeformer(), ObjectDeformer::CosineInterpolationDeformer(), TriangleGroupDeformer::DropwaveDeform(), ObjectDeformer::DropwaveDeform(), Object3D::GetCenterOffset(), ObjectAlign::GetCentroid(), Object3D::GetMinMaxDimensions(), ObjectAlign::GetObjectCenter(), ObjectAlign::GetObjectPlanarityRatio(), ObjectAlign::GetObjectSize(), ObjectAlign::GetPlaneOrientation(), ObjectAlign::NormalizeObjectCenter(), ObjectAlign::NormalizeObjectPlane(), ObjectDeformer::PerspectiveDeform(), Object3D::ResetVertices(), TriangleGroupDeformer::SineWaveSurfaceDeform(), ObjectDeformer::SineWaveSurfaceDeform(), TriangleGroupDeformer::SinusoidalDeform(), ObjectDeformer::SinusoidalDeform(), and Object3D::UpdateTransform().
The documentation for this class was generated from the following file:
ITriangleGroup.h