RocksAnimation Class Reference
RocksAnimation Class Reference
#include <RocksAnimation.h>
Public Member Functions
RocksAnimation ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
void Update (float ratio) override
Private Attributes
Rocks rocks
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 0.0f, 2.6f)
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 5.0f * 25.0f, 7.5f * 25.0f, 4.2f)
Detailed Description
Definition at line 7 of file RocksAnimation.h.
Constructor & Destructor Documentation
RocksAnimation()
RocksAnimation () inline
Definition at line 14 of file RocksAnimation.h.
References rocks.
Member Function Documentation
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 18 of file RocksAnimation.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 19 of file RocksAnimation.h.
Update()
void Update (float ratio) inline override
Definition at line 21 of file RocksAnimation.h.
References EulerConstants::EulerOrderXZYS, fGenRotation, fGenScale, Rotation::GetQuaternion(), rocks, and FunctionGenerator::Update().
Member Data Documentation
fGenRotation
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 0.0f, 2.6f) private
Definition at line 10 of file RocksAnimation.h.
Referenced by Update().
fGenScale
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 5.0f * 25.0f, 7.5f * 25.0f, 4.2f) private
Definition at line 11 of file RocksAnimation.h.
Referenced by Update().
rocks
Rocks rocks private
Definition at line 9 of file RocksAnimation.h.
Referenced by RocksAnimation(), and Update().
The documentation for this class was generated from the following file:
RocksAnimation.h