CoelaNerdAnimation Class Reference
CoelaNerdAnimation Class Reference
#include <CoelaNerdAnimation.h>
Public Member Functions
CoelaNerdAnimation ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
void Reset ()
void Update (float ratio) override
Private Attributes
SolidCube cube
FunctionGenerator fGenObjRotation = FunctionGenerator(FunctionGenerator::Sine, -360.0f, 360.0f, 6.0f)
FunctionGenerator fGenObjScale = FunctionGenerator(FunctionGenerator::Sine, 10.0f, 10.0f, 4.0f)
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 1.5f)
FunctionGenerator fGenMatSize = FunctionGenerator(FunctionGenerator::Sine, 250.0f, 350.0f, 2.1f)
FunctionGenerator fGenMatRot = FunctionGenerator(FunctionGenerator::Sine, -5.0f, 5.0f, 3.2f)
NerdSequence gif = NerdSequence(Vector2D(200, 145), Vector2D(100, 70), 30)
Detailed Description
Definition at line 12 of file CoelaNerdAnimation.h.
Constructor & Destructor Documentation
CoelaNerdAnimation()
CoelaNerdAnimation () inline
Definition at line 23 of file CoelaNerdAnimation.h.
References cube, and gif.
Member Function Documentation
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 29 of file CoelaNerdAnimation.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 30 of file CoelaNerdAnimation.h.
Reset()
void Reset () inline
Definition at line 32 of file CoelaNerdAnimation.h.
References gif.
Update()
void Update (float ratio) inline override
Definition at line 36 of file CoelaNerdAnimation.h.
References cube, EulerConstants::EulerOrderXZYS, fGenMatPos, fGenMatRot, fGenMatSize, fGenObjRotation, fGenObjScale, Rotation::GetQuaternion(), gif, and FunctionGenerator::Update().
Member Data Documentation
cube
SolidCube cube private
Definition at line 14 of file CoelaNerdAnimation.h.
Referenced by CoelaNerdAnimation(), and Update().
fGenMatPos
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 1.5f) private
Definition at line 17 of file CoelaNerdAnimation.h.
Referenced by Update().
fGenMatRot
FunctionGenerator fGenMatRot = FunctionGenerator(FunctionGenerator::Sine, -5.0f, 5.0f, 3.2f) private
Definition at line 19 of file CoelaNerdAnimation.h.
Referenced by Update().
fGenMatSize
FunctionGenerator fGenMatSize = FunctionGenerator(FunctionGenerator::Sine, 250.0f, 350.0f, 2.1f) private
Definition at line 18 of file CoelaNerdAnimation.h.
Referenced by Update().
fGenObjRotation
FunctionGenerator fGenObjRotation = FunctionGenerator(FunctionGenerator::Sine, -360.0f, 360.0f, 6.0f) private
Definition at line 15 of file CoelaNerdAnimation.h.
Referenced by Update().
fGenObjScale
FunctionGenerator fGenObjScale = FunctionGenerator(FunctionGenerator::Sine, 10.0f, 10.0f, 4.0f) private
Definition at line 16 of file CoelaNerdAnimation.h.
Referenced by Update().
gif
NerdSequence gif = NerdSequence(Vector2D(200, 145), Vector2D(100, 70), 30) private
Definition at line 20 of file CoelaNerdAnimation.h.
Referenced by CoelaNerdAnimation(), Reset(), and Update().
The documentation for this class was generated from the following file:
CoelaNerdAnimation.h