WarzoneAnimation Class Reference
WarzoneAnimation Class Reference
#include <WarzoneAnimation.h>
Public Member Functions
WarzoneAnimation ()
void UpdateKeyFrameTracks ()
void Default ()
void Angry ()
void Sad ()
void Surprised ()
void Doubt ()
void Frown ()
void LookUp ()
void LookDown ()
void SpectrumAnalyzerFace ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
Object3D * GetObject ()
void UpdateFFTVisemes ()
void Update (float ratio) override
Private Member Functions
void LinkEasyEase ()
void LinkParameters ()
void ChangeInterpolationMethods ()
void SetMaterialLayers ()
Private Attributes
NukudeFace pM
Background background
EasyEaseAnimator< 20 > eEA = EasyEaseAnimator<20>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f)
RainbowNoise rainbowNoise
RainbowSpiral rainbowSpiral
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0))
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255))
RGBColor gradientSpectrum [2] = {RGBColor(218, 173, 116), RGBColor(4, 191, 163)}
GradientMaterial< 2 > gradientMat = GradientMaterial<2>(gradientSpectrum, 350.0f, false)
MaterialAnimator< 5 > materialAnimator
SpectrumAnalyzer sA = SpectrumAnalyzer(A0, Vector2D(200, 100), Vector2D(100, 50), true, true)
BlinkTrack< 1 > blink
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f)
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f)
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f)
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 5.3f)
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 6.7f)
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f)
BoopSensor boop
FFTVoiceDetection< 128 > voiceDetection
Detailed Description
Definition at line 23 of file WarzoneAnimation.h.
Constructor & Destructor Documentation
WarzoneAnimation()
WarzoneAnimation () inline
Definition at line 104 of file WarzoneAnimation.h.
References background, boop, ChangeInterpolationMethods(), LinkEasyEase(), LinkParameters(), materialAnimator, pM, sA, and SetMaterialLayers().
Member Function Documentation
Angry()
void Angry () inline
Definition at line 129 of file WarzoneAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, materialAnimator, and redMaterial.
Referenced by Update().
ChangeInterpolationMethods()
void ChangeInterpolationMethods () inline private
Definition at line 81 of file WarzoneAnimation.h.
References eEA, and EasyEaseAnimator< maxParameters >::SetInterpolationMethod().
Referenced by WarzoneAnimation().
Default()
void Default () inline
Definition at line 127 of file WarzoneAnimation.h.
Referenced by Update().
Doubt()
void Doubt () inline
Definition at line 147 of file WarzoneAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
Referenced by Update().
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 168 of file WarzoneAnimation.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 169 of file WarzoneAnimation.h.
Frown()
void Frown () inline
Definition at line 151 of file WarzoneAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
Referenced by Update().
GetObject()
Object3D * GetObject () inline
Definition at line 171 of file WarzoneAnimation.h.
References pM.
LinkEasyEase()
void LinkEasyEase () inline private
Definition at line 56 of file WarzoneAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameter(), eEA, and pM.
Referenced by WarzoneAnimation().
LinkParameters()
void LinkParameters () inline private
Definition at line 77 of file WarzoneAnimation.h.
References AnimationTrack< maxParameters, maxKeyFrames >::AddParameter(), blink, and pM.
Referenced by WarzoneAnimation().
LookDown()
void LookDown () inline
Definition at line 159 of file WarzoneAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
LookUp()
void LookUp () inline
Definition at line 155 of file WarzoneAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
Referenced by Update().
Sad()
void Sad () inline
Definition at line 135 of file WarzoneAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blueMaterial, eEA, and materialAnimator.
Referenced by Update().
SetMaterialLayers()
void SetMaterialLayers () inline private
Definition at line 95 of file WarzoneAnimation.h.
References Material::Add, MaterialAnimator< materialCount >::AddMaterial(), blueMaterial, gradientMat, Material::Lighten, materialAnimator, rainbowNoise, rainbowSpiral, redMaterial, Material::Replace, and MaterialAnimator< materialCount >::SetBaseMaterial().
Referenced by WarzoneAnimation().
SpectrumAnalyzerFace()
void SpectrumAnalyzerFace () inline
Definition at line 163 of file WarzoneAnimation.h.
References background, and pM.
Referenced by Update().
Surprised()
void Surprised () inline
Definition at line 141 of file WarzoneAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, materialAnimator, and rainbowSpiral.
Referenced by Update().
Update()
void Update (float ratio) inline override
Definition at line 193 of file WarzoneAnimation.h.
References Angry(), background, boop, Default(), Doubt(), eEA, fGenMatXMove, fGenMatYMove, Frown(), MicrophoneFourierBase::GetFourierFiltered(), LookUp(), materialAnimator, pM, rainbowNoise, rainbowSpiral, sA, Sad(), SpectrumAnalyzer::SetFlipYState(), SpectrumAnalyzer::SetHueAngle(), SpectrumAnalyzer::SetMirrorYState(), SpectrumAnalyzerFace(), Surprised(), MicrophoneFourier::Update(), MaterialAnimator< materialCount >::Update(), FunctionGenerator::Update(), EasyEaseAnimator< maxParameters >::Update(), SpectrumAnalyzer::Update(), RainbowNoise::Update(), RainbowSpiral::Update(), UpdateFFTVisemes(), and UpdateKeyFrameTracks().
UpdateFFTVisemes()
void UpdateFFTVisemes () inline
Definition at line 175 of file WarzoneAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), Viseme::AH, Viseme::AR, Viseme::EE, eEA, Viseme::ER, MicrophoneFourierBase::GetCurrentMagnitude(), MicrophoneFourierBase::GetFourierFiltered(), MicrophoneFourierBase::GetSampleRate(), FFTVoiceDetection< peakCount >::GetViseme(), Viseme::OO, Viseme::UH, FFTVoiceDetection< peakCount >::Update(), and voiceDetection.
Referenced by Update().
UpdateKeyFrameTracks()
void UpdateKeyFrameTracks () inline
Definition at line 123 of file WarzoneAnimation.h.
References blink, and AnimationTrack< maxParameters, maxKeyFrames >::Update().
Referenced by Update().
Member Data Documentation
background
Background background private
Definition at line 26 of file WarzoneAnimation.h.
Referenced by SpectrumAnalyzerFace(), Update(), and WarzoneAnimation().
blink
BlinkTrack<1> blink private
Definition at line 43 of file WarzoneAnimation.h.
Referenced by LinkParameters(), and UpdateKeyFrameTracks().
blueMaterial
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255)) private
Definition at line 33 of file WarzoneAnimation.h.
Referenced by Sad(), and SetMaterialLayers().
boop
BoopSensor boop private
Definition at line 52 of file WarzoneAnimation.h.
Referenced by Update(), and WarzoneAnimation().
eEA
EasyEaseAnimator<20> eEA = EasyEaseAnimator<20>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f) private
Definition at line 27 of file WarzoneAnimation.h.
Referenced by Angry(), ChangeInterpolationMethods(), Doubt(), Frown(), LinkEasyEase(), LookDown(), LookUp(), Sad(), Surprised(), Update(), and UpdateFFTVisemes().
fGenMatHue
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f) private
Definition at line 50 of file WarzoneAnimation.h.
fGenMatPos
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f) private
Definition at line 45 of file WarzoneAnimation.h.
fGenMatXMove
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 5.3f) private
Definition at line 48 of file WarzoneAnimation.h.
Referenced by Update().
fGenMatYMove
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 6.7f) private
Definition at line 49 of file WarzoneAnimation.h.
Referenced by Update().
fGenRotation
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f) private
Definition at line 46 of file WarzoneAnimation.h.
fGenScale
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f) private
Definition at line 47 of file WarzoneAnimation.h.
gradientMat
GradientMaterial<2> gradientMat = GradientMaterial<2>(gradientSpectrum, 350.0f, false) private
Definition at line 36 of file WarzoneAnimation.h.
Referenced by SetMaterialLayers().
gradientSpectrum
RGBColor gradientSpectrum[2] = {RGBColor(218, 173, 116), RGBColor(4, 191, 163)} private
Definition at line 35 of file WarzoneAnimation.h.
materialAnimator
MaterialAnimator<5> materialAnimator private
Definition at line 38 of file WarzoneAnimation.h.
Referenced by Angry(), Sad(), SetMaterialLayers(), Surprised(), Update(), and WarzoneAnimation().
pM
NukudeFace pM private
Definition at line 25 of file WarzoneAnimation.h.
Referenced by GetObject(), LinkEasyEase(), LinkParameters(), SpectrumAnalyzerFace(), Update(), and WarzoneAnimation().
rainbowNoise
RainbowNoise rainbowNoise private
Definition at line 30 of file WarzoneAnimation.h.
Referenced by SetMaterialLayers(), and Update().
rainbowSpiral
RainbowSpiral rainbowSpiral private
Definition at line 31 of file WarzoneAnimation.h.
Referenced by SetMaterialLayers(), Surprised(), and Update().
redMaterial
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0)) private
Definition at line 32 of file WarzoneAnimation.h.
Referenced by Angry(), and SetMaterialLayers().
sA
SpectrumAnalyzer sA = SpectrumAnalyzer(A0, Vector2D(200, 100), Vector2D(100, 50), true, true) private
Definition at line 40 of file WarzoneAnimation.h.
Referenced by Update(), and WarzoneAnimation().
voiceDetection
FFTVoiceDetection<128> voiceDetection private
Definition at line 54 of file WarzoneAnimation.h.
Referenced by UpdateFFTVisemes().
The documentation for this class was generated from the following file:
WarzoneAnimation.h