Warzone2Animation Class Reference
Warzone2Animation Class Reference
#include <WarzoneAnimationV2.h>
Public Member Functions
Warzone2Animation ()
void Initialize () override
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
Object3D * GetObject ()
uint8_t GetAccentBrightness ()
uint8_t GetBrightness ()
void Update (float ratio) override
Private Member Functions
void LinkEasyEase ()
void LinkParameters ()
void ChangeInterpolationMethods ()
void SetMaterialLayers ()
void UpdateKeyFrameTracks ()
void Default ()
void UwU ()
void Spiral ()
void Happy ()
void Dead ()
void HappyClosed ()
void Sleep ()
void Circle ()
void Blush ()
void Upset ()
void SpectrumAnalyzerFace ()
void AudioReactiveGradientFace ()
void OscilloscopeFace ()
void UpdateFFTVisemes ()
void SetMaterialColor ()
Private Attributes
WarzoneFace pM
WarzoneExtras pME
Background background
LEDStripBackground ledStripBackground
EasyEaseAnimator< 30 > eEA = EasyEaseAnimator<30>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f)
RainbowNoise rainbowNoise
RainbowSpiral rainbowSpiral
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0))
SimpleMaterial orangeMaterial = SimpleMaterial(RGBColor(255, 165, 0))
SimpleMaterial whiteMaterial = SimpleMaterial(RGBColor(255, 255, 255))
SimpleMaterial greenMaterial = SimpleMaterial(RGBColor(0, 255, 0))
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255))
SimpleMaterial yellowMaterial = SimpleMaterial(RGBColor(255, 255, 0))
SimpleMaterial purpleMaterial = SimpleMaterial(RGBColor(255, 0, 255))
RGBColor gradientSpectrum [2] = {RGBColor(246, 176, 194), RGBColor(207, 148, 163)}
GradientMaterial< 2 > gradientMat = GradientMaterial<2>(gradientSpectrum, 200.0f, false)
MaterialAnimator< 10 > materialAnimator
MaterialAnimator< 4 > backgroundMaterial
SpectrumAnalyzer sA = SpectrumAnalyzer(Vector2D(200, 100), Vector2D(100, 50), true, true)
AudioReactiveGradient aRG = AudioReactiveGradient(Vector2D(160, 160), Vector2D(0, 0), true, true)
Oscilloscope oSC = Oscilloscope(Vector2D(200, 100), Vector2D(0, 0))
BlinkTrack< 1 > blink
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f)
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f)
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f)
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 5.3f)
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 6.7f)
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f)
FunctionGenerator fGenMatXMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 1.1f)
FunctionGenerator fGenMatYMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 2.7f)
FunctionGenerator fGenMatRMenu = FunctionGenerator(FunctionGenerator::Sine, -5.0f, 5.0f, 1.7f)
FunctionGenerator fGenMatM1Sleep = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 5.3f)
FunctionGenerator fGenMatM2Sleep = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 6.7f)
FunctionGenerator fGenMatS1Sleep = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 4.6f)
APDS9960 boop
FFTVoiceDetection< 128 > voiceDetection
ObjectAlign objA = ObjectAlign(Vector2D(0.0f, 0.0f), Vector2D(189.0f, 93.0f), Quaternion())
float offsetFace = 0.0f
float offsetFaceSA = 0.0f
float offsetFaceARG = 0.0f
float offsetFaceOSC = 0.0f
float offsetFaceZZZ = 0.0f
uint8_t offsetFaceInd = 50
uint8_t offsetFaceIndSA = 51
uint8_t offsetFaceIndARG = 52
uint8_t offsetFaceIndOSC = 53
uint8_t offsetFaceIndZZZ = 54
Detailed Description
Definition at line 26 of file WarzoneAnimationV2.h.
Constructor & Destructor Documentation
Warzone2Animation()
Warzone2Animation () inline
Definition at line 293 of file WarzoneAnimationV2.h.
References background, backgroundMaterial, ChangeInterpolationMethods(), gradientMat, ledStripBackground, LinkEasyEase(), LinkParameters(), materialAnimator, objA, pM, pME, ObjectAlign::SetJustification(), SetMaterialLayers(), ObjectAlign::SetMirrorX(), GradientMaterial< colorCount >::SetRotationAngle(), and ObjectAlign::Stretch.
Member Function Documentation
AudioReactiveGradientFace()
void AudioReactiveGradientFace () inline private
Definition at line 245 of file WarzoneAnimationV2.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), aRG, backgroundMaterial, eEA, offsetFaceARG, offsetFaceInd, and offsetFaceIndARG.
Referenced by Update().
Blush()
void Blush () inline private
Definition at line 223 of file WarzoneAnimationV2.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, materialAnimator, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), and rainbowSpiral.
Referenced by Update().
ChangeInterpolationMethods()
void ChangeInterpolationMethods () inline private
Definition at line 127 of file WarzoneAnimationV2.h.
References eEA, and EasyEaseAnimator< maxParameters >::SetInterpolationMethod().
Referenced by Warzone2Animation().
Circle()
void Circle () inline private
Definition at line 217 of file WarzoneAnimationV2.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, and AnimationTrack< maxParameters, maxKeyFrames >::Pause().
Referenced by Update().
Dead()
void Dead () inline private
Definition at line 193 of file WarzoneAnimationV2.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, materialAnimator, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), and redMaterial.
Referenced by Update().
Default()
void Default () inline private
Definition at line 168 of file WarzoneAnimationV2.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, and AnimationTrack< maxParameters, maxKeyFrames >::Play().
Referenced by Update().
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 328 of file WarzoneAnimationV2.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 329 of file WarzoneAnimationV2.h.
GetAccentBrightness()
uint8_t GetAccentBrightness () inline
Definition at line 335 of file WarzoneAnimationV2.h.
References Menu::GetAccentBrightness().
GetBrightness()
uint8_t GetBrightness () inline
Definition at line 339 of file WarzoneAnimationV2.h.
References Menu::GetBrightness().
GetObject()
Object3D * GetObject () inline
Definition at line 331 of file WarzoneAnimationV2.h.
References pM.
Happy()
void Happy () inline private
Definition at line 186 of file WarzoneAnimationV2.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, and AnimationTrack< maxParameters, maxKeyFrames >::Play().
Referenced by Update().
HappyClosed()
void HappyClosed () inline private
Definition at line 200 of file WarzoneAnimationV2.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, and AnimationTrack< maxParameters, maxKeyFrames >::Play().
Referenced by Update().
Initialize()
void Initialize () inline override
Definition at line 320 of file WarzoneAnimationV2.h.
References boop, Menu::Initialize(), and APDS9960::Initialize().
LinkEasyEase()
void LinkEasyEase () inline private
Definition at line 90 of file WarzoneAnimationV2.h.
References EasyEaseAnimator< maxParameters >::AddParameter(), eEA, offsetFace, offsetFaceARG, offsetFaceInd, offsetFaceIndARG, offsetFaceIndOSC, offsetFaceIndSA, offsetFaceIndZZZ, offsetFaceOSC, offsetFaceSA, offsetFaceZZZ, pM, and pME.
Referenced by Warzone2Animation().
LinkParameters()
void LinkParameters () inline private
Definition at line 123 of file WarzoneAnimationV2.h.
References AnimationTrack< maxParameters, maxKeyFrames >::AddParameter(), blink, and pM.
Referenced by Warzone2Animation().
OscilloscopeFace()
void OscilloscopeFace () inline private
Definition at line 252 of file WarzoneAnimationV2.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), backgroundMaterial, eEA, offsetFaceInd, offsetFaceIndOSC, offsetFaceOSC, and oSC.
Referenced by Update().
SetMaterialColor()
void SetMaterialColor () inline private
Definition at line 277 of file WarzoneAnimationV2.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), blueMaterial, Menu::GetFaceColor(), greenMaterial, materialAnimator, orangeMaterial, purpleMaterial, rainbowNoise, rainbowSpiral, redMaterial, whiteMaterial, and yellowMaterial.
Referenced by Update().
SetMaterialLayers()
void SetMaterialLayers () inline private
Definition at line 146 of file WarzoneAnimationV2.h.
References Material::Add, MaterialAnimator< materialCount >::AddMaterial(), aRG, backgroundMaterial, blueMaterial, Menu::GetMaterial(), gradientMat, greenMaterial, Material::Lighten, materialAnimator, orangeMaterial, oSC, purpleMaterial, rainbowNoise, rainbowSpiral, redMaterial, Material::Replace, sA, MaterialAnimator< materialCount >::SetBaseMaterial(), whiteMaterial, and yellowMaterial.
Referenced by Warzone2Animation().
Sleep()
void Sleep () inline private
Definition at line 205 of file WarzoneAnimationV2.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, fGenMatM1Sleep, fGenMatM2Sleep, fGenMatS1Sleep, offsetFaceIndZZZ, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), pME, and FunctionGenerator::Update().
Referenced by Update().
SpectrumAnalyzerFace()
void SpectrumAnalyzerFace () inline private
Definition at line 238 of file WarzoneAnimationV2.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), backgroundMaterial, eEA, offsetFaceInd, offsetFaceIndSA, offsetFaceSA, and sA.
Referenced by Update().
Spiral()
void Spiral () inline private
Definition at line 179 of file WarzoneAnimationV2.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, materialAnimator, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), and rainbowSpiral.
Referenced by Update().
Update()
void Update (float ratio) inline override
Definition at line 343 of file WarzoneAnimationV2.h.
References ObjectAlign::AlignObjects(), aRG, AudioReactiveGradientFace(), backgroundMaterial, Blush(), boop, Circle(), Dead(), Default(), eEA, fGenMatXMove, fGenMatYMove, Menu::GetFaceSize(), Menu::GetFaceState(), Menu::GetMicLevel(), Happy(), HappyClosed(), APDS9960::isBooped(), materialAnimator, Menu::MirrorSpectrumAnalyzer(), objA, offsetFace, oSC, OscilloscopeFace(), pM, pME, rainbowNoise, rainbowSpiral, sA, ObjectAlign::SetCameraMax(), ObjectAlign::SetEdgeMargin(), SpectrumAnalyzer::SetFlipYState(), AudioReactiveGradient::SetHueAngle(), Oscilloscope::SetHueAngle(), SpectrumAnalyzer::SetHueAngle(), SetMaterialColor(), SpectrumAnalyzer::SetMirrorYState(), ObjectAlign::SetPlaneOffsetAngle(), AudioReactiveGradient::SetPosition(), Oscilloscope::SetPosition(), AudioReactiveGradient::SetRadius(), AudioReactiveGradient::SetRotation(), AudioReactiveGradient::SetSize(), Oscilloscope::SetSize(), FFTVoiceDetection< peakCount >::SetThreshold(), Menu::ShowMenu(), Sleep(), SpectrumAnalyzerFace(), Spiral(), MaterialAnimator< materialCount >::Update(), FunctionGenerator::Update(), EasyEaseAnimator< maxParameters >::Update(), Oscilloscope::Update(), AudioReactiveGradient::Update(), SpectrumAnalyzer::Update(), Menu::Update(), RainbowNoise::Update(), RainbowSpiral::Update(), UpdateFFTVisemes(), UpdateKeyFrameTracks(), Upset(), Menu::UseBoopSensor(), UwU(), and voiceDetection.
UpdateFFTVisemes()
void UpdateFFTVisemes () inline private
Definition at line 259 of file WarzoneAnimationV2.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), Viseme::AH, Viseme::AR, Viseme::EE, eEA, Viseme::ER, FFTVoiceDetection< peakCount >::GetViseme(), Viseme::OO, Viseme::UH, FFTVoiceDetection< peakCount >::Update(), Menu::UseMicrophone(), and voiceDetection.
Referenced by Update().
UpdateKeyFrameTracks()
void UpdateKeyFrameTracks () inline private
Definition at line 164 of file WarzoneAnimationV2.h.
References blink, and AnimationTrack< maxParameters, maxKeyFrames >::Update().
Referenced by Update().
Upset()
void Upset () inline private
Definition at line 231 of file WarzoneAnimationV2.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, materialAnimator, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), and redMaterial.
Referenced by Update().
UwU()
void UwU () inline private
Definition at line 173 of file WarzoneAnimationV2.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, and AnimationTrack< maxParameters, maxKeyFrames >::Pause().
Referenced by Update().
Member Data Documentation
aRG
AudioReactiveGradient aRG = AudioReactiveGradient(Vector2D(160, 160), Vector2D(0, 0), true, true) private
Definition at line 52 of file WarzoneAnimationV2.h.
Referenced by AudioReactiveGradientFace(), SetMaterialLayers(), and Update().
background
Background background private
Definition at line 30 of file WarzoneAnimationV2.h.
Referenced by Warzone2Animation().
backgroundMaterial
MaterialAnimator<4> backgroundMaterial private
Definition at line 49 of file WarzoneAnimationV2.h.
Referenced by AudioReactiveGradientFace(), OscilloscopeFace(), SetMaterialLayers(), SpectrumAnalyzerFace(), Update(), and Warzone2Animation().
blink
BlinkTrack<1> blink private
Definition at line 56 of file WarzoneAnimationV2.h.
Referenced by Blush(), Circle(), Dead(), Default(), Happy(), HappyClosed(), LinkParameters(), Sleep(), Spiral(), UpdateKeyFrameTracks(), Upset(), and UwU().
blueMaterial
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255)) private
Definition at line 41 of file WarzoneAnimationV2.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
boop
APDS9960 boop private
Definition at line 73 of file WarzoneAnimationV2.h.
Referenced by Initialize(), and Update().
eEA
EasyEaseAnimator<30> eEA = EasyEaseAnimator<30>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f) private
Definition at line 32 of file WarzoneAnimationV2.h.
Referenced by AudioReactiveGradientFace(), Blush(), ChangeInterpolationMethods(), Circle(), Dead(), Default(), Happy(), HappyClosed(), LinkEasyEase(), OscilloscopeFace(), Sleep(), SpectrumAnalyzerFace(), Spiral(), Update(), UpdateFFTVisemes(), Upset(), and UwU().
fGenMatHue
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f) private
Definition at line 63 of file WarzoneAnimationV2.h.
fGenMatM1Sleep
FunctionGenerator fGenMatM1Sleep = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 5.3f) private
Definition at line 69 of file WarzoneAnimationV2.h.
Referenced by Sleep().
fGenMatM2Sleep
FunctionGenerator fGenMatM2Sleep = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 6.7f) private
Definition at line 70 of file WarzoneAnimationV2.h.
Referenced by Sleep().
fGenMatPos
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f) private
Definition at line 58 of file WarzoneAnimationV2.h.
fGenMatRMenu
FunctionGenerator fGenMatRMenu = FunctionGenerator(FunctionGenerator::Sine, -5.0f, 5.0f, 1.7f) private
Definition at line 67 of file WarzoneAnimationV2.h.
fGenMatS1Sleep
FunctionGenerator fGenMatS1Sleep = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 4.6f) private
Definition at line 71 of file WarzoneAnimationV2.h.
Referenced by Sleep().
fGenMatXMenu
FunctionGenerator fGenMatXMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 1.1f) private
Definition at line 65 of file WarzoneAnimationV2.h.
fGenMatXMove
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 5.3f) private
Definition at line 61 of file WarzoneAnimationV2.h.
Referenced by Update().
fGenMatYMenu
FunctionGenerator fGenMatYMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 2.7f) private
Definition at line 66 of file WarzoneAnimationV2.h.
fGenMatYMove
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 6.7f) private
Definition at line 62 of file WarzoneAnimationV2.h.
Referenced by Update().
fGenRotation
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f) private
Definition at line 59 of file WarzoneAnimationV2.h.
fGenScale
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f) private
Definition at line 60 of file WarzoneAnimationV2.h.
gradientMat
GradientMaterial<2> gradientMat = GradientMaterial<2>(gradientSpectrum, 200.0f, false) private
Definition at line 46 of file WarzoneAnimationV2.h.
Referenced by SetMaterialLayers(), and Warzone2Animation().
gradientSpectrum
RGBColor gradientSpectrum[2] = {RGBColor(246, 176, 194), RGBColor(207, 148, 163)} private
Definition at line 45 of file WarzoneAnimationV2.h.
greenMaterial
SimpleMaterial greenMaterial = SimpleMaterial(RGBColor(0, 255, 0)) private
Definition at line 40 of file WarzoneAnimationV2.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
ledStripBackground
LEDStripBackground ledStripBackground private
Definition at line 31 of file WarzoneAnimationV2.h.
Referenced by Warzone2Animation().
materialAnimator
MaterialAnimator<10> materialAnimator private
Definition at line 48 of file WarzoneAnimationV2.h.
Referenced by Blush(), Dead(), SetMaterialColor(), SetMaterialLayers(), Spiral(), Update(), Upset(), and Warzone2Animation().
objA
ObjectAlign objA = ObjectAlign(Vector2D(0.0f, 0.0f), Vector2D(189.0f, 93.0f), Quaternion()) private
Definition at line 77 of file WarzoneAnimationV2.h.
Referenced by Update(), and Warzone2Animation().
offsetFace
float offsetFace = 0.0f private
Definition at line 79 of file WarzoneAnimationV2.h.
Referenced by LinkEasyEase(), and Update().
offsetFaceARG
float offsetFaceARG = 0.0f private
Definition at line 81 of file WarzoneAnimationV2.h.
Referenced by AudioReactiveGradientFace(), and LinkEasyEase().
offsetFaceInd
uint8_t offsetFaceInd = 50 private
Definition at line 84 of file WarzoneAnimationV2.h.
Referenced by AudioReactiveGradientFace(), LinkEasyEase(), OscilloscopeFace(), and SpectrumAnalyzerFace().
offsetFaceIndARG
uint8_t offsetFaceIndARG = 52 private
Definition at line 86 of file WarzoneAnimationV2.h.
Referenced by AudioReactiveGradientFace(), and LinkEasyEase().
offsetFaceIndOSC
uint8_t offsetFaceIndOSC = 53 private
Definition at line 87 of file WarzoneAnimationV2.h.
Referenced by LinkEasyEase(), and OscilloscopeFace().
offsetFaceIndSA
uint8_t offsetFaceIndSA = 51 private
Definition at line 85 of file WarzoneAnimationV2.h.
Referenced by LinkEasyEase(), and SpectrumAnalyzerFace().
offsetFaceIndZZZ
uint8_t offsetFaceIndZZZ = 54 private
Definition at line 88 of file WarzoneAnimationV2.h.
Referenced by LinkEasyEase(), and Sleep().
offsetFaceOSC
float offsetFaceOSC = 0.0f private
Definition at line 82 of file WarzoneAnimationV2.h.
Referenced by LinkEasyEase(), and OscilloscopeFace().
offsetFaceSA
float offsetFaceSA = 0.0f private
Definition at line 80 of file WarzoneAnimationV2.h.
Referenced by LinkEasyEase(), and SpectrumAnalyzerFace().
offsetFaceZZZ
float offsetFaceZZZ = 0.0f private
Definition at line 83 of file WarzoneAnimationV2.h.
Referenced by LinkEasyEase().
orangeMaterial
SimpleMaterial orangeMaterial = SimpleMaterial(RGBColor(255, 165, 0)) private
Definition at line 38 of file WarzoneAnimationV2.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
oSC
Oscilloscope oSC = Oscilloscope(Vector2D(200, 100), Vector2D(0, 0)) private
Definition at line 53 of file WarzoneAnimationV2.h.
Referenced by OscilloscopeFace(), SetMaterialLayers(), and Update().
pM
WarzoneFace pM private
Definition at line 28 of file WarzoneAnimationV2.h.
Referenced by GetObject(), LinkEasyEase(), LinkParameters(), Update(), and Warzone2Animation().
pME
WarzoneExtras pME private
Definition at line 29 of file WarzoneAnimationV2.h.
Referenced by LinkEasyEase(), Sleep(), Update(), and Warzone2Animation().
purpleMaterial
SimpleMaterial purpleMaterial = SimpleMaterial(RGBColor(255, 0, 255)) private
Definition at line 43 of file WarzoneAnimationV2.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
rainbowNoise
RainbowNoise rainbowNoise private
Definition at line 35 of file WarzoneAnimationV2.h.
Referenced by SetMaterialColor(), SetMaterialLayers(), and Update().
rainbowSpiral
RainbowSpiral rainbowSpiral private
Definition at line 36 of file WarzoneAnimationV2.h.
Referenced by Blush(), SetMaterialColor(), SetMaterialLayers(), Spiral(), and Update().
redMaterial
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0)) private
Definition at line 37 of file WarzoneAnimationV2.h.
Referenced by Dead(), SetMaterialColor(), SetMaterialLayers(), and Upset().
sA
SpectrumAnalyzer sA = SpectrumAnalyzer(Vector2D(200, 100), Vector2D(100, 50), true, true) private
Definition at line 51 of file WarzoneAnimationV2.h.
Referenced by SetMaterialLayers(), SpectrumAnalyzerFace(), and Update().
voiceDetection
FFTVoiceDetection<128> voiceDetection private
Definition at line 75 of file WarzoneAnimationV2.h.
Referenced by Update(), and UpdateFFTVisemes().
whiteMaterial
SimpleMaterial whiteMaterial = SimpleMaterial(RGBColor(255, 255, 255)) private
Definition at line 39 of file WarzoneAnimationV2.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
yellowMaterial
SimpleMaterial yellowMaterial = SimpleMaterial(RGBColor(255, 255, 0)) private
Definition at line 42 of file WarzoneAnimationV2.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
The documentation for this class was generated from the following file:
WarzoneAnimationV2.h