BeeAnimation Class Reference
BeeAnimation Class Reference
#include <BeeAnimation.h>
Public Member Functions
BeeAnimation ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
void Update (float ratio) override
Private Attributes
Bee bee
FunctionGenerator fGenRotationX = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f)
FunctionGenerator fGenRotationY = FunctionGenerator(FunctionGenerator::Sine, -90.0f, 90.0f, 1.3f)
Detailed Description
Definition at line 8 of file BeeAnimation.h.
Constructor & Destructor Documentation
BeeAnimation()
BeeAnimation () inline
Definition at line 15 of file BeeAnimation.h.
References bee.
Member Function Documentation
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 19 of file BeeAnimation.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 20 of file BeeAnimation.h.
Update()
void Update (float ratio) inline override
Definition at line 22 of file BeeAnimation.h.
References bee, EulerConstants::EulerOrderXZYS, fGenRotationX, fGenRotationY, Rotation::GetQuaternion(), and FunctionGenerator::Update().
Member Data Documentation
bee
Bee bee private
Definition at line 10 of file BeeAnimation.h.
Referenced by BeeAnimation(), and Update().
fGenRotationX
FunctionGenerator fGenRotationX = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f) private
Definition at line 11 of file BeeAnimation.h.
Referenced by Update().
fGenRotationY
FunctionGenerator fGenRotationY = FunctionGenerator(FunctionGenerator::Sine, -90.0f, 90.0f, 1.3f) private
Definition at line 12 of file BeeAnimation.h.
Referenced by Update().
The documentation for this class was generated from the following file:
BeeAnimation.h