HardwareTest Class Reference
HardwareTest Class Reference
#include <ProtogenHardwareTest.h>
Static Public Member Functions
static void TestMicrophone ()
static void TestButton ()
static void TestUART ()
static void TestHUD ()
static void TestBoopSensor ()
static void TestNeoTrellis ()
static void ScanDevices ()
static void ResetI2CBus ()
Static Private Member Functions
static void PrintAddress (uint8_t address, const String &text)
static void PrintAddressValue (uint8_t address, const String &text, int value)
static bool TestI2CConnection (uint8_t address, String name, bool flip)
static void TestAPDS9960 (uint8_t address, bool flip)
static void TestAPDS9930 (uint8_t address, bool flip)
static void TestSSD1306 (uint8_t address, bool flip)
static TrellisCallback blink (keyEvent evt)
static uint32_t Wheel (byte WheelPos)
static void TestTrellisHardware (bool flip)
Static Private Attributes
static Adafruit_NeoTrellis trellis
Detailed Description
Definition at line 10 of file ProtogenHardwareTest.h.
Member Function Documentation
blink()
static TrellisCallback blink (keyEvent evt) inline static private
Definition at line 189 of file ProtogenHardwareTest.h.
References trellis, and Wheel().
Referenced by TestTrellisHardware().
PrintAddress()
static void PrintAddress (uint8_t address, const String & text) inline static private
Definition at line 12 of file ProtogenHardwareTest.h.
Referenced by TestI2CConnection().
PrintAddressValue()
static void PrintAddressValue (uint8_t address, const String & text, int value) inline static private
Definition at line 18 of file ProtogenHardwareTest.h.
Referenced by TestAPDS9930(), and TestAPDS9960().
ResetI2CBus()
static void ResetI2CBus () inline static
Definition at line 323 of file ProtogenHardwareTest.h.
ScanDevices()
static void ScanDevices () inline static
Definition at line 295 of file ProtogenHardwareTest.h.
Referenced by setup().
TestAPDS9930()
static void TestAPDS9930 (uint8_t address, bool flip) inline static private
Definition at line 103 of file ProtogenHardwareTest.h.
References PrintAddressValue().
TestAPDS9960()
static void TestAPDS9960 (uint8_t address, bool flip) inline static private
Definition at line 71 of file ProtogenHardwareTest.h.
References PrintAddressValue().
Referenced by TestBoopSensor().
TestBoopSensor()
static void TestBoopSensor () inline static
Definition at line 278 of file ProtogenHardwareTest.h.
References TestAPDS9960(), and TestI2CConnection().
Referenced by setup().
TestButton()
static void TestButton () inline static
Definition at line 264 of file ProtogenHardwareTest.h.
TestHUD()
static void TestHUD () inline static
Definition at line 272 of file ProtogenHardwareTest.h.
References TestI2CConnection(), and TestSSD1306().
Referenced by setup().
TestI2CConnection()
static bool TestI2CConnection (uint8_t address, String name, bool flip) inline static private
Definition at line 26 of file ProtogenHardwareTest.h.
References PrintAddress().
Referenced by TestBoopSensor(), and TestHUD().
TestMicrophone()
static void TestMicrophone () inline static
Definition at line 260 of file ProtogenHardwareTest.h.
TestNeoTrellis()
static void TestNeoTrellis () inline static
Definition at line 286 of file ProtogenHardwareTest.h.
References TestTrellisHardware(), and trellis.
Referenced by setup().
TestSSD1306()
static void TestSSD1306 (uint8_t address, bool flip) inline static private
Definition at line 147 of file ProtogenHardwareTest.h.
Referenced by TestHUD().
TestTrellisHardware()
static void TestTrellisHardware (bool flip) inline static private
Definition at line 217 of file ProtogenHardwareTest.h.
References blink(), trellis, and Wheel().
Referenced by TestNeoTrellis().
TestUART()
static void TestUART () inline static
Definition at line 268 of file ProtogenHardwareTest.h.
Wheel()
static uint32_t Wheel (byte WheelPos) inline static private
Definition at line 204 of file ProtogenHardwareTest.h.
References trellis.
Referenced by blink(), and TestTrellisHardware().
Member Data Documentation
trellis
Adafruit_NeoTrellis trellis static private
Definition at line 186 of file ProtogenHardwareTest.h.
Referenced by blink(), TestNeoTrellis(), TestTrellisHardware(), and Wheel().
The documentation for this class was generated from the following file:
ProtogenHardwareTest.h