ArtleckAnimationV2 Class Reference
ArtleckAnimationV2 Class Reference
#include <ArtleckAnimationV2.h>
Public Member Functions
ArtleckAnimationV2 ()
void UpdateKeyFrameTracks ()
void Default ()
void Angry ()
void Sad ()
void Surprised ()
void Doubt ()
void Frown ()
void LookUp ()
void LookDown ()
void SpectrumAnalyzerFace ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
Object3D * GetObject ()
void UpdateFFTVisemes ()
void Update (float ratio) override
Private Member Functions
void LinkEasyEase ()
void LinkParameters ()
void ChangeInterpolationMethods ()
void SetMaterials ()
Private Attributes
ArtleckFace pM
Background background
EasyEaseAnimator< 20 > eEA = EasyEaseAnimator<20>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f)
RainbowNoise rainbowNoise
RainbowSpiral rainbowSpiral
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0))
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255))
SimpleMaterial purpleMaterial = SimpleMaterial(RGBColor(255, 0, 255))
RGBColor gradientSpectrum [2] = {RGBColor(255, 255, 0), RGBColor(255, 128, 0)}
GradientMaterial< 2 > gradientMat = GradientMaterial<2>(gradientSpectrum, 350.0f, false)
CombineMaterial< 6 > faceMaterial
SpectrumAnalyzer sA = SpectrumAnalyzer(A0, Vector2D(200, 100), Vector2D(100, 50), true, true)
BlinkTrack< 1 > blink
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f)
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f)
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f)
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 5.3f)
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 6.7f)
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f)
BoopSensor boop
float rainbowFaceMix = 0.0f
float angryFaceMix = 0.0f
float sadFaceMix = 0.0f
float purpleFaceMix = 0.0f
uint8_t rainbowFaceIndex = 50
uint8_t angryFaceIndex = 51
uint8_t sadFaceIndex = 52
uint8_t purpleFaceIndex = 53
FFTVoiceDetection< 128 > voiceDetection
Detailed Description
Definition at line 23 of file ArtleckAnimationV2.h.
Constructor & Destructor Documentation
ArtleckAnimationV2()
ArtleckAnimationV2 () inline
Definition at line 120 of file ArtleckAnimationV2.h.
References background, boop, ChangeInterpolationMethods(), faceMaterial, LinkEasyEase(), LinkParameters(), pM, sA, and SetMaterials().
Member Function Documentation
Angry()
void Angry () inline
Definition at line 145 of file ArtleckAnimationV2.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), angryFaceIndex, and eEA.
Referenced by Update().
ChangeInterpolationMethods()
void ChangeInterpolationMethods () inline private
Definition at line 93 of file ArtleckAnimationV2.h.
References angryFaceIndex, eEA, purpleFaceIndex, rainbowFaceIndex, sadFaceIndex, and EasyEaseAnimator< maxParameters >::SetInterpolationMethod().
Referenced by ArtleckAnimationV2().
Default()
void Default () inline
Definition at line 143 of file ArtleckAnimationV2.h.
Referenced by Update().
Doubt()
void Doubt () inline
Definition at line 161 of file ArtleckAnimationV2.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
Referenced by Update().
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 182 of file ArtleckAnimationV2.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 183 of file ArtleckAnimationV2.h.
Frown()
void Frown () inline
Definition at line 165 of file ArtleckAnimationV2.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
Referenced by Update().
GetObject()
Object3D * GetObject () inline
Definition at line 185 of file ArtleckAnimationV2.h.
References pM.
LinkEasyEase()
void LinkEasyEase () inline private
Definition at line 65 of file ArtleckAnimationV2.h.
References EasyEaseAnimator< maxParameters >::AddParameter(), angryFaceIndex, angryFaceMix, eEA, pM, purpleFaceIndex, purpleFaceMix, rainbowFaceIndex, rainbowFaceMix, sadFaceIndex, and sadFaceMix.
Referenced by ArtleckAnimationV2().
LinkParameters()
void LinkParameters () inline private
Definition at line 89 of file ArtleckAnimationV2.h.
References AnimationTrack< maxParameters, maxKeyFrames >::AddParameter(), blink, and pM.
Referenced by ArtleckAnimationV2().
LookDown()
void LookDown () inline
Definition at line 173 of file ArtleckAnimationV2.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
LookUp()
void LookUp () inline
Definition at line 169 of file ArtleckAnimationV2.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
Referenced by Update().
Sad()
void Sad () inline
Definition at line 150 of file ArtleckAnimationV2.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, and sadFaceIndex.
Referenced by Update().
SetMaterials()
void SetMaterials () inline private
Definition at line 110 of file ArtleckAnimationV2.h.
References Material::Add, CombineMaterial< materialCount >::AddMaterial(), blueMaterial, faceMaterial, gradientMat, Material::Lighten, purpleMaterial, rainbowNoise, rainbowSpiral, redMaterial, and Material::Replace.
Referenced by ArtleckAnimationV2().
SpectrumAnalyzerFace()
void SpectrumAnalyzerFace () inline
Definition at line 177 of file ArtleckAnimationV2.h.
References background, and pM.
Referenced by Update().
Surprised()
void Surprised () inline
Definition at line 156 of file ArtleckAnimationV2.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, and purpleFaceIndex.
Referenced by Update().
Update()
void Update (float ratio) inline override
Definition at line 207 of file ArtleckAnimationV2.h.
References Angry(), angryFaceMix, background, boop, Default(), Doubt(), eEA, faceMaterial, fGenMatXMove, fGenMatYMove, Frown(), MicrophoneFourierBase::GetFourierFiltered(), LookUp(), pM, purpleFaceMix, rainbowFaceMix, rainbowNoise, rainbowSpiral, sA, Sad(), sadFaceMix, SpectrumAnalyzer::SetFlipYState(), SpectrumAnalyzer::SetHueAngle(), SpectrumAnalyzer::SetMirrorYState(), CombineMaterial< materialCount >::SetOpacity(), SpectrumAnalyzerFace(), Surprised(), MicrophoneFourier::Update(), FunctionGenerator::Update(), EasyEaseAnimator< maxParameters >::Update(), SpectrumAnalyzer::Update(), RainbowNoise::Update(), RainbowSpiral::Update(), UpdateFFTVisemes(), and UpdateKeyFrameTracks().
UpdateFFTVisemes()
void UpdateFFTVisemes () inline
Definition at line 189 of file ArtleckAnimationV2.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), Viseme::AH, Viseme::AR, Viseme::EE, eEA, Viseme::ER, MicrophoneFourierBase::GetCurrentMagnitude(), MicrophoneFourierBase::GetFourierFiltered(), MicrophoneFourierBase::GetSampleRate(), FFTVoiceDetection< peakCount >::GetViseme(), Viseme::OO, Viseme::UH, FFTVoiceDetection< peakCount >::Update(), and voiceDetection.
Referenced by Update().
UpdateKeyFrameTracks()
void UpdateKeyFrameTracks () inline
Definition at line 139 of file ArtleckAnimationV2.h.
References blink, and AnimationTrack< maxParameters, maxKeyFrames >::Update().
Referenced by Update().
Member Data Documentation
angryFaceIndex
uint8_t angryFaceIndex = 51 private
Definition at line 59 of file ArtleckAnimationV2.h.
Referenced by Angry(), ChangeInterpolationMethods(), and LinkEasyEase().
angryFaceMix
float angryFaceMix = 0.0f private
Definition at line 55 of file ArtleckAnimationV2.h.
Referenced by LinkEasyEase(), and Update().
background
Background background private
Definition at line 26 of file ArtleckAnimationV2.h.
Referenced by ArtleckAnimationV2(), SpectrumAnalyzerFace(), and Update().
blink
BlinkTrack<1> blink private
Definition at line 44 of file ArtleckAnimationV2.h.
Referenced by LinkParameters(), and UpdateKeyFrameTracks().
blueMaterial
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255)) private
Definition at line 33 of file ArtleckAnimationV2.h.
Referenced by SetMaterials().
boop
BoopSensor boop private
Definition at line 53 of file ArtleckAnimationV2.h.
Referenced by ArtleckAnimationV2(), and Update().
eEA
EasyEaseAnimator<20> eEA = EasyEaseAnimator<20>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f) private
Definition at line 27 of file ArtleckAnimationV2.h.
Referenced by Angry(), ChangeInterpolationMethods(), Doubt(), Frown(), LinkEasyEase(), LookDown(), LookUp(), Sad(), Surprised(), Update(), and UpdateFFTVisemes().
faceMaterial
CombineMaterial<6> faceMaterial private
Definition at line 39 of file ArtleckAnimationV2.h.
Referenced by ArtleckAnimationV2(), SetMaterials(), and Update().
fGenMatHue
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f) private
Definition at line 51 of file ArtleckAnimationV2.h.
fGenMatPos
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f) private
Definition at line 46 of file ArtleckAnimationV2.h.
fGenMatXMove
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 5.3f) private
Definition at line 49 of file ArtleckAnimationV2.h.
Referenced by Update().
fGenMatYMove
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 6.7f) private
Definition at line 50 of file ArtleckAnimationV2.h.
Referenced by Update().
fGenRotation
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f) private
Definition at line 47 of file ArtleckAnimationV2.h.
fGenScale
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f) private
Definition at line 48 of file ArtleckAnimationV2.h.
gradientMat
GradientMaterial<2> gradientMat = GradientMaterial<2>(gradientSpectrum, 350.0f, false) private
Definition at line 37 of file ArtleckAnimationV2.h.
Referenced by SetMaterials().
gradientSpectrum
RGBColor gradientSpectrum[2] = {RGBColor(255, 255, 0), RGBColor(255, 128, 0)} private
Definition at line 36 of file ArtleckAnimationV2.h.
pM
ArtleckFace pM private
Definition at line 25 of file ArtleckAnimationV2.h.
Referenced by ArtleckAnimationV2(), GetObject(), LinkEasyEase(), LinkParameters(), SpectrumAnalyzerFace(), and Update().
purpleFaceIndex
uint8_t purpleFaceIndex = 53 private
Definition at line 61 of file ArtleckAnimationV2.h.
Referenced by ChangeInterpolationMethods(), LinkEasyEase(), and Surprised().
purpleFaceMix
float purpleFaceMix = 0.0f private
Definition at line 57 of file ArtleckAnimationV2.h.
Referenced by LinkEasyEase(), and Update().
purpleMaterial
SimpleMaterial purpleMaterial = SimpleMaterial(RGBColor(255, 0, 255)) private
Definition at line 34 of file ArtleckAnimationV2.h.
Referenced by SetMaterials().
rainbowFaceIndex
uint8_t rainbowFaceIndex = 50 private
Definition at line 58 of file ArtleckAnimationV2.h.
Referenced by ChangeInterpolationMethods(), and LinkEasyEase().
rainbowFaceMix
float rainbowFaceMix = 0.0f private
Definition at line 54 of file ArtleckAnimationV2.h.
Referenced by LinkEasyEase(), and Update().
rainbowNoise
RainbowNoise rainbowNoise private
Definition at line 30 of file ArtleckAnimationV2.h.
Referenced by SetMaterials(), and Update().
rainbowSpiral
RainbowSpiral rainbowSpiral private
Definition at line 31 of file ArtleckAnimationV2.h.
Referenced by SetMaterials(), and Update().
redMaterial
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0)) private
Definition at line 32 of file ArtleckAnimationV2.h.
Referenced by SetMaterials().
sA
SpectrumAnalyzer sA = SpectrumAnalyzer(A0, Vector2D(200, 100), Vector2D(100, 50), true, true) private
Definition at line 41 of file ArtleckAnimationV2.h.
Referenced by ArtleckAnimationV2(), and Update().
sadFaceIndex
uint8_t sadFaceIndex = 52 private
Definition at line 60 of file ArtleckAnimationV2.h.
Referenced by ChangeInterpolationMethods(), LinkEasyEase(), and Sad().
sadFaceMix
float sadFaceMix = 0.0f private
Definition at line 56 of file ArtleckAnimationV2.h.
Referenced by LinkEasyEase(), and Update().
voiceDetection
FFTVoiceDetection<128> voiceDetection private
Definition at line 63 of file ArtleckAnimationV2.h.
Referenced by UpdateFFTVisemes().
The documentation for this class was generated from the following file:
ArtleckAnimationV2.h