InfraredAnimation Class Reference
InfraredAnimation Class Reference
#include <InfraredAnimation.h>
Public Member Functions
InfraredAnimation ()
void UpdateKeyFrameTracks ()
void Default ()
void Angry ()
void Sad ()
void Surprised ()
void Happy ()
void Determination ()
void Calm ()
void Mad ()
void SpectrumAnalyzerFace ()
void AudioReactiveGradientFace ()
void OscilloscopeFace ()
uint8_t GetAccentBrightness ()
uint8_t GetBrightness ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
Object3D * GetObject ()
void UpdateFFTVisemes ()
void Update (float ratio) override
Private Member Functions
void LinkEasyEase ()
void LinkParameters ()
void ChangeInterpolationMethods ()
void SetMaterialLayers ()
Private Attributes
InfraredFace pM
Background background
LEDStripBackground ledStripBackground
EasyEaseAnimator< 21 > eEA = EasyEaseAnimator<21>(EasyEaseInterpolation::Cosine, 1.0f, 0.35f)
RainbowNoise rainbowNoise
RainbowSpiral rainbowSpiral
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0))
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255))
RGBColor gradientSpectrum [2] = {RGBColor(255, 0, 0), RGBColor(255, 255, 0)}
GradientMaterial< 2 > gradientMat = GradientMaterial<2>(gradientSpectrum, 350.0f, false)
MaterialAnimator< 5 > materialAnimator
MaterialAnimator< 4 > backgroundMaterial
SpectrumAnalyzer sA = SpectrumAnalyzer(Vector2D(200, 100), Vector2D(100, 50), true, true)
AudioReactiveGradient aRG = AudioReactiveGradient(Vector2D(160, 160), Vector2D(0, 0), true, true)
Oscilloscope oSC = Oscilloscope(Vector2D(200, 100), Vector2D(0, 0))
BlinkTrack< 1 > blink
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f)
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f)
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f)
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 5.3f)
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 6.7f)
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f)
APDS9960 boop
FFTVoiceDetection< 128 > voiceDetection
float offsetFaceSA = 0.0f
float offsetFaceARG = 0.0f
float offsetFaceOSC = 0.0f
uint8_t offsetFaceIndSA = 50
uint8_t offsetFaceIndARG = 51
uint8_t offsetFaceIndOSC = 52
Detailed Description
Definition at line 28 of file InfraredAnimation.h.
Constructor & Destructor Documentation
InfraredAnimation()
InfraredAnimation () inline
Definition at line 115 of file InfraredAnimation.h.
References background, backgroundMaterial, boop, ChangeInterpolationMethods(), Menu::Initialize(), APDS9960::Initialize(), ledStripBackground, LinkEasyEase(), LinkParameters(), materialAnimator, pM, and SetMaterialLayers().
Member Function Documentation
Angry()
void Angry () inline
Definition at line 150 of file InfraredAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, materialAnimator, AnimationTrack< maxParameters, maxKeyFrames >::Play(), pM, and redMaterial.
Referenced by Update().
AudioReactiveGradientFace()
void AudioReactiveGradientFace () inline
Definition at line 227 of file InfraredAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), aRG, backgroundMaterial, blink, eEA, offsetFaceARG, offsetFaceIndARG, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), and pM.
Referenced by Update().
Calm()
void Calm () inline
Definition at line 197 of file InfraredAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, blueMaterial, eEA, materialAnimator, AnimationTrack< maxParameters, maxKeyFrames >::Play(), and pM.
Referenced by Update().
ChangeInterpolationMethods()
void ChangeInterpolationMethods () inline private
Definition at line 96 of file InfraredAnimation.h.
References eEA, and EasyEaseAnimator< maxParameters >::SetInterpolationMethod().
Referenced by InfraredAnimation().
Default()
void Default () inline
Definition at line 141 of file InfraredAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), blink, materialAnimator, AnimationTrack< maxParameters, maxKeyFrames >::Play(), pM, and redMaterial.
Referenced by Update().
Determination()
void Determination () inline
Definition at line 188 of file InfraredAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, materialAnimator, AnimationTrack< maxParameters, maxKeyFrames >::Play(), pM, and redMaterial.
Referenced by Update().
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 259 of file InfraredAnimation.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 260 of file InfraredAnimation.h.
GetAccentBrightness()
uint8_t GetAccentBrightness () inline
Definition at line 251 of file InfraredAnimation.h.
References Menu::GetAccentBrightness().
GetBrightness()
uint8_t GetBrightness () inline
Definition at line 255 of file InfraredAnimation.h.
References Menu::GetBrightness().
GetObject()
Object3D * GetObject () inline
Definition at line 262 of file InfraredAnimation.h.
References pM.
Happy()
void Happy () inline
Definition at line 179 of file InfraredAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, materialAnimator, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), pM, and redMaterial.
Referenced by Update().
LinkEasyEase()
void LinkEasyEase () inline private
Definition at line 72 of file InfraredAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameter(), eEA, offsetFaceARG, offsetFaceIndARG, offsetFaceIndOSC, offsetFaceIndSA, offsetFaceOSC, offsetFaceSA, and pM.
Referenced by InfraredAnimation().
LinkParameters()
void LinkParameters () inline private
Definition at line 92 of file InfraredAnimation.h.
References AnimationTrack< maxParameters, maxKeyFrames >::AddParameter(), blink, and pM.
Referenced by InfraredAnimation().
Mad()
void Mad () inline
Definition at line 206 of file InfraredAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, materialAnimator, AnimationTrack< maxParameters, maxKeyFrames >::Play(), pM, and redMaterial.
Referenced by Update().
OscilloscopeFace()
void OscilloscopeFace () inline
Definition at line 239 of file InfraredAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), backgroundMaterial, blink, eEA, offsetFaceIndOSC, offsetFaceOSC, oSC, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), and pM.
Referenced by Update().
Sad()
void Sad () inline
Definition at line 160 of file InfraredAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, blueMaterial, eEA, materialAnimator, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), and pM.
Referenced by Update().
SetMaterialLayers()
void SetMaterialLayers () inline private
Definition at line 102 of file InfraredAnimation.h.
References Material::Add, MaterialAnimator< materialCount >::AddMaterial(), aRG, backgroundMaterial, blueMaterial, Menu::GetMaterial(), Material::Lighten, materialAnimator, oSC, rainbowNoise, rainbowSpiral, redMaterial, Material::Replace, sA, and MaterialAnimator< materialCount >::SetBaseMaterial().
Referenced by InfraredAnimation().
SpectrumAnalyzerFace()
void SpectrumAnalyzerFace () inline
Definition at line 215 of file InfraredAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), backgroundMaterial, blink, eEA, offsetFaceIndSA, offsetFaceSA, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), pM, and sA.
Referenced by Update().
Surprised()
void Surprised () inline
Definition at line 169 of file InfraredAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, materialAnimator, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), pM, rainbowSpiral, and redMaterial.
Referenced by Update().
Update()
void Update (float ratio) inline override
Definition at line 283 of file InfraredAnimation.h.
References Angry(), aRG, AudioReactiveGradientFace(), background, backgroundMaterial, boop, Calm(), Default(), Determination(), eEA, fGenMatHue, fGenMatXMove, fGenMatYMove, Menu::GetFaceSize(), Menu::GetFaceState(), Menu::GetMicLevel(), gradientMat, Happy(), GradientMaterial< colorCount >::HueShift(), APDS9960::isBooped(), Mad(), materialAnimator, Menu::MirrorSpectrumAnalyzer(), offsetFaceARG, offsetFaceOSC, offsetFaceSA, oSC, OscilloscopeFace(), pM, rainbowNoise, rainbowSpiral, sA, Sad(), SpectrumAnalyzer::SetFlipYState(), AudioReactiveGradient::SetHueAngle(), Oscilloscope::SetHueAngle(), SpectrumAnalyzer::SetHueAngle(), SpectrumAnalyzer::SetMirrorYState(), AudioReactiveGradient::SetPosition(), Oscilloscope::SetPosition(), AudioReactiveGradient::SetRadius(), AudioReactiveGradient::SetRotation(), AudioReactiveGradient::SetSize(), Oscilloscope::SetSize(), FFTVoiceDetection< peakCount >::SetThreshold(), Menu::ShowMenu(), SpectrumAnalyzerFace(), Surprised(), MaterialAnimator< materialCount >::Update(), FunctionGenerator::Update(), EasyEaseAnimator< maxParameters >::Update(), Oscilloscope::Update(), AudioReactiveGradient::Update(), SpectrumAnalyzer::Update(), Menu::Update(), RainbowNoise::Update(), RainbowSpiral::Update(), UpdateFFTVisemes(), UpdateKeyFrameTracks(), Menu::UseBoopSensor(), and voiceDetection.
UpdateFFTVisemes()
void UpdateFFTVisemes () inline
Definition at line 266 of file InfraredAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), Viseme::EE, eEA, FFTVoiceDetection< peakCount >::GetViseme(), Viseme::OO, FFTVoiceDetection< peakCount >::Update(), Menu::UseMicrophone(), and voiceDetection.
Referenced by Update().
UpdateKeyFrameTracks()
void UpdateKeyFrameTracks () inline
Definition at line 137 of file InfraredAnimation.h.
References blink, and AnimationTrack< maxParameters, maxKeyFrames >::Update().
Referenced by Update().
Member Data Documentation
aRG
AudioReactiveGradient aRG = AudioReactiveGradient(Vector2D(160, 160), Vector2D(0, 0), true, true) private
Definition at line 48 of file InfraredAnimation.h.
Referenced by AudioReactiveGradientFace(), SetMaterialLayers(), and Update().
background
Background background private
Definition at line 31 of file InfraredAnimation.h.
Referenced by InfraredAnimation(), and Update().
backgroundMaterial
MaterialAnimator<4> backgroundMaterial private
Definition at line 45 of file InfraredAnimation.h.
Referenced by AudioReactiveGradientFace(), InfraredAnimation(), OscilloscopeFace(), SetMaterialLayers(), SpectrumAnalyzerFace(), and Update().
blink
BlinkTrack<1> blink private
Definition at line 52 of file InfraredAnimation.h.
Referenced by Angry(), AudioReactiveGradientFace(), Calm(), Default(), Determination(), Happy(), LinkParameters(), Mad(), OscilloscopeFace(), Sad(), SpectrumAnalyzerFace(), Surprised(), and UpdateKeyFrameTracks().
blueMaterial
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255)) private
Definition at line 39 of file InfraredAnimation.h.
Referenced by Calm(), Sad(), and SetMaterialLayers().
boop
APDS9960 boop private
Definition at line 61 of file InfraredAnimation.h.
Referenced by InfraredAnimation(), and Update().
eEA
EasyEaseAnimator<21> eEA = EasyEaseAnimator<21>(EasyEaseInterpolation::Cosine, 1.0f, 0.35f) private
Definition at line 33 of file InfraredAnimation.h.
Referenced by Angry(), AudioReactiveGradientFace(), Calm(), ChangeInterpolationMethods(), Determination(), Happy(), LinkEasyEase(), Mad(), OscilloscopeFace(), Sad(), SpectrumAnalyzerFace(), Surprised(), Update(), and UpdateFFTVisemes().
fGenMatHue
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f) private
Definition at line 59 of file InfraredAnimation.h.
Referenced by Update().
fGenMatPos
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f) private
Definition at line 54 of file InfraredAnimation.h.
fGenMatXMove
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 5.3f) private
Definition at line 57 of file InfraredAnimation.h.
Referenced by Update().
fGenMatYMove
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 6.7f) private
Definition at line 58 of file InfraredAnimation.h.
Referenced by Update().
fGenRotation
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f) private
Definition at line 55 of file InfraredAnimation.h.
fGenScale
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f) private
Definition at line 56 of file InfraredAnimation.h.
gradientMat
GradientMaterial<2> gradientMat = GradientMaterial<2>(gradientSpectrum, 350.0f, false) private
Definition at line 42 of file InfraredAnimation.h.
Referenced by Update().
gradientSpectrum
RGBColor gradientSpectrum[2] = {RGBColor(255, 0, 0), RGBColor(255, 255, 0)} private
Definition at line 41 of file InfraredAnimation.h.
ledStripBackground
LEDStripBackground ledStripBackground private
Definition at line 32 of file InfraredAnimation.h.
Referenced by InfraredAnimation().
materialAnimator
MaterialAnimator<5> materialAnimator private
Definition at line 44 of file InfraredAnimation.h.
Referenced by Angry(), Calm(), Default(), Determination(), Happy(), InfraredAnimation(), Mad(), Sad(), SetMaterialLayers(), Surprised(), and Update().
offsetFaceARG
float offsetFaceARG = 0.0f private
Definition at line 66 of file InfraredAnimation.h.
Referenced by AudioReactiveGradientFace(), LinkEasyEase(), and Update().
offsetFaceIndARG
uint8_t offsetFaceIndARG = 51 private
Definition at line 69 of file InfraredAnimation.h.
Referenced by AudioReactiveGradientFace(), and LinkEasyEase().
offsetFaceIndOSC
uint8_t offsetFaceIndOSC = 52 private
Definition at line 70 of file InfraredAnimation.h.
Referenced by LinkEasyEase(), and OscilloscopeFace().
offsetFaceIndSA
uint8_t offsetFaceIndSA = 50 private
Definition at line 68 of file InfraredAnimation.h.
Referenced by LinkEasyEase(), and SpectrumAnalyzerFace().
offsetFaceOSC
float offsetFaceOSC = 0.0f private
Definition at line 67 of file InfraredAnimation.h.
Referenced by LinkEasyEase(), OscilloscopeFace(), and Update().
offsetFaceSA
float offsetFaceSA = 0.0f private
Definition at line 65 of file InfraredAnimation.h.
Referenced by LinkEasyEase(), SpectrumAnalyzerFace(), and Update().
oSC
Oscilloscope oSC = Oscilloscope(Vector2D(200, 100), Vector2D(0, 0)) private
Definition at line 49 of file InfraredAnimation.h.
Referenced by OscilloscopeFace(), SetMaterialLayers(), and Update().
pM
InfraredFace pM private
Definition at line 30 of file InfraredAnimation.h.
Referenced by Angry(), AudioReactiveGradientFace(), Calm(), Default(), Determination(), GetObject(), Happy(), InfraredAnimation(), LinkEasyEase(), LinkParameters(), Mad(), OscilloscopeFace(), Sad(), SpectrumAnalyzerFace(), Surprised(), and Update().
rainbowNoise
RainbowNoise rainbowNoise private
Definition at line 36 of file InfraredAnimation.h.
Referenced by SetMaterialLayers(), and Update().
rainbowSpiral
RainbowSpiral rainbowSpiral private
Definition at line 37 of file InfraredAnimation.h.
Referenced by SetMaterialLayers(), Surprised(), and Update().
redMaterial
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0)) private
Definition at line 38 of file InfraredAnimation.h.
Referenced by Angry(), Default(), Determination(), Happy(), Mad(), SetMaterialLayers(), and Surprised().
sA
SpectrumAnalyzer sA = SpectrumAnalyzer(Vector2D(200, 100), Vector2D(100, 50), true, true) private
Definition at line 47 of file InfraredAnimation.h.
Referenced by SetMaterialLayers(), SpectrumAnalyzerFace(), and Update().
voiceDetection
FFTVoiceDetection<128> voiceDetection private
Definition at line 63 of file InfraredAnimation.h.
Referenced by Update(), and UpdateFFTVisemes().
The documentation for this class was generated from the following file:
InfraredAnimation.h