ProtoV2Controller Class Reference
ProtoV2Controller Class Reference
#include <BetaProtoControllerOctoWS2811.h>
Public Member Functions
ProtoV2Controller (uint8_t maxBrightness)
void Initialize () override
Initializes the controller.
void Display () override
Updates and displays content on the lighting system.
Public Member Functions inherited from Controller
uint8_t GetBrightness ()
Retrieves the current brightness level.
uint8_t GetAccentBrightness ()
Retrieves the current accent brightness level.
virtual void SetBrightness (uint8_t maxBrightness)=0
Sets the maximum brightness for the controller.
virtual void SetAccentBrightness (uint8_t maxAccentBrightness)=0
Sets the maximum accent brightness for the controller.
Private Attributes
CameraLayout cameraLayout = CameraLayout(CameraLayout::ZForward, CameraLayout::YUp)
Transform camRghtFrntTransform = Transform(Vector3D(0.0f, 27.0f, 0.0f), Vector3D(1.0f, 0, -500.0f+14.0f), Vector3D(1, 1, 1))
Transform camLeftFrntTransform = Transform(Vector3D(0.0f, -27.0f, 0.0f), Vector3D(1.0f, 0, -500.0f-14.0f), Vector3D(1, 1, 1))
Transform camRghtRearTransform = Transform(Vector3D(-5.631f, -1.508f, 164.057f), Vector3D(460.0f, 290.0f, -500.0f+111.0f), Vector3D(1, 1, 1))
Transform camLeftRearTransform = Transform(Vector3D(5.631f, 1.508f, 164.057f), Vector3D(460.0f, 290.0f, -500.0f-111.0f), Vector3D(1, 1, 1))
Transform camRghtChinTransform = Transform(Vector3D(52.014f, 9.825f, 28.423f), Vector3D(19.0f + 30.0f, 30.0f, -500.0f-19.0f), Vector3D(1, 1, 1))
Transform camLeftChinTransform = Transform(Vector3D(-163.947f, -52.151f, 130.883f), Vector3D(145.0f + 30.0f, 30.0f, -500.0f+81.0f), Vector3D(1, 1, 1))
Transform camRghtMiniTransform = Transform(Vector3D(-5.631f, -1.508f, 164.057f), Vector3D(420.0f, 230.0f, -500.0f+111.0f), Vector3D(1, 1, 1))
Transform camLeftMiniTransform = Transform(Vector3D(5.631f, 1.508f, 164.057f), Vector3D(420.0f, 230.0f, -500.0f-111.0f), Vector3D(1, 1, 1))
PixelGroup camRghtFrntPixels = PixelGroup(KaiborgV1Pixels, 571, PixelGroup::ZEROTOMAX)
PixelGroup camLeftFrntPixels = PixelGroup(KaiborgV1Pixels, 571, PixelGroup::MAXTOZERO)
PixelGroup camRghtRearPixels = PixelGroup(KaiborgV1Pixels, 571, PixelGroup::ZEROTOMAX)
PixelGroup camLeftRearPixels = PixelGroup(KaiborgV1Pixels, 571, PixelGroup::MAXTOZERO)
PixelGroup camRghtChinPixels = PixelGroup(ProtoDRMini, 89)
PixelGroup camLeftChinPixels = PixelGroup(ProtoDRMini, 89)
PixelGroup camRghtMiniPixels = PixelGroup(HertzMiniCamera, 4)
PixelGroup camLeftMiniPixels = PixelGroup(HertzMiniCamera, 4)
Camera camRghtFrnt = Camera(&camRghtFrntTransform, &cameraLayout, &camRghtFrntPixels)
Camera camLeftFrnt = Camera(&camLeftFrntTransform, &cameraLayout, &camLeftFrntPixels)
Camera camRghtRear = Camera(&camRghtRearTransform, &cameraLayout, &camRghtRearPixels)
Camera camLeftRear = Camera(&camLeftRearTransform, &cameraLayout, &camLeftRearPixels)
Camera camRghtChin = Camera(&camRghtChinTransform, &cameraLayout, &camRghtChinPixels)
Camera camLeftChin = Camera(&camLeftChinTransform, &cameraLayout, &camLeftChinPixels)
Camera camRghtMini = Camera(&camRghtMiniTransform, &cameraLayout, &camRghtMiniPixels)
Camera camLeftMini = Camera(&camLeftMiniTransform, &cameraLayout, &camLeftMiniPixels)
Camera * cameras [8] = { &camRghtFrnt, &camLeftFrnt, &camRghtRear, &camLeftRear, &camRghtChin, &camLeftChin, &camRghtMini, &camLeftMini }
uint8_t maxBrightness
Additional Inherited Members
Protected Member Functions inherited from Controller
Controller (CameraManager *cameras, uint8_t maxBrightness, uint8_t maxAccentBrightness)
Constructs a Controller with specified parameters.
void UpdateBrightness ()
Updates the brightness based on internal logic.
Protected Attributes inherited from Controller
CameraManager * cameras
Pointer to the CameraManager for managing camera data.
uint8_t brightness
Current brightness level.
uint8_t accentBrightness
Current accent brightness level.
uint8_t maxBrightness
Maximum allowed brightness level.
uint8_t maxAccentBrightness
Maximum allowed accent brightness level.
bool isOn = false
Indicates if the controller is active.
bool startTime = false
Indicates if the start time has been recorded.
Detailed Description
Definition at line 17 of file BetaProtoControllerOctoWS2811.h.
Constructor & Destructor Documentation
ProtoV2Controller()
ProtoV2Controller (uint8_t maxBrightness) inline
Definition at line 52 of file BetaProtoControllerOctoWS2811.h.
References maxBrightness.
Member Function Documentation
Display()
void Display () inline override virtual
Updates and displays content on the lighting system.
Implements Controller.
Definition at line 61 of file BetaProtoControllerOctoWS2811.h.
References Controller::brightness, camLeftChinPixels, camLeftFrntPixels, camLeftMiniPixels, camLeftRearPixels, camRghtChinPixels, camRghtFrntPixels, camRghtMiniPixels, camRghtRearPixels, and leds().
Initialize()
void Initialize () inline override virtual
Initializes the controller.
Implements Controller.
Definition at line 56 of file BetaProtoControllerOctoWS2811.h.
References leds().
Member Data Documentation
cameraLayout
CameraLayout cameraLayout = CameraLayout(CameraLayout::ZForward, CameraLayout::YUp) private
Definition at line 19 of file BetaProtoControllerOctoWS2811.h.
cameras
Camera* cameras[8] = { &camRghtFrnt, &camLeftFrnt, &camRghtRear, &camLeftRear, &camRghtChin, &camLeftChin, &camRghtMini, &camLeftMini } private
Definition at line 48 of file BetaProtoControllerOctoWS2811.h.
camLeftChin
Camera camLeftChin = Camera(&camLeftChinTransform, &cameraLayout, &camLeftChinPixels) private
Definition at line 44 of file BetaProtoControllerOctoWS2811.h.
camLeftChinPixels
PixelGroup camLeftChinPixels = PixelGroup(ProtoDRMini, 89) private
Definition at line 35 of file BetaProtoControllerOctoWS2811.h.
Referenced by Display().
camLeftChinTransform
Transform camLeftChinTransform = Transform(Vector3D(-163.947f, -52.151f, 130.883f), Vector3D(145.0f + 30.0f, 30.0f, -500.0f+81.0f), Vector3D(1, 1, 1)) private
Definition at line 26 of file BetaProtoControllerOctoWS2811.h.
camLeftFrnt
Camera camLeftFrnt = Camera(&camLeftFrntTransform, &cameraLayout, &camLeftFrntPixels) private
Definition at line 40 of file BetaProtoControllerOctoWS2811.h.
camLeftFrntPixels
PixelGroup camLeftFrntPixels = PixelGroup(KaiborgV1Pixels, 571, PixelGroup::MAXTOZERO) private
Definition at line 31 of file BetaProtoControllerOctoWS2811.h.
Referenced by Display().
camLeftFrntTransform
Transform camLeftFrntTransform = Transform(Vector3D(0.0f, -27.0f, 0.0f), Vector3D(1.0f, 0, -500.0f-14.0f), Vector3D(1, 1, 1)) private
Definition at line 22 of file BetaProtoControllerOctoWS2811.h.
camLeftMini
Camera camLeftMini = Camera(&camLeftMiniTransform, &cameraLayout, &camLeftMiniPixels) private
Definition at line 46 of file BetaProtoControllerOctoWS2811.h.
camLeftMiniPixels
PixelGroup camLeftMiniPixels = PixelGroup(HertzMiniCamera, 4) private
Definition at line 37 of file BetaProtoControllerOctoWS2811.h.
Referenced by Display().
camLeftMiniTransform
Transform camLeftMiniTransform = Transform(Vector3D(5.631f, 1.508f, 164.057f), Vector3D(420.0f, 230.0f, -500.0f-111.0f), Vector3D(1, 1, 1)) private
Definition at line 28 of file BetaProtoControllerOctoWS2811.h.
camLeftRear
Camera camLeftRear = Camera(&camLeftRearTransform, &cameraLayout, &camLeftRearPixels) private
Definition at line 42 of file BetaProtoControllerOctoWS2811.h.
camLeftRearPixels
PixelGroup camLeftRearPixels = PixelGroup(KaiborgV1Pixels, 571, PixelGroup::MAXTOZERO) private
Definition at line 33 of file BetaProtoControllerOctoWS2811.h.
Referenced by Display().
camLeftRearTransform
Transform camLeftRearTransform = Transform(Vector3D(5.631f, 1.508f, 164.057f), Vector3D(460.0f, 290.0f, -500.0f-111.0f), Vector3D(1, 1, 1)) private
Definition at line 24 of file BetaProtoControllerOctoWS2811.h.
camRghtChin
Camera camRghtChin = Camera(&camRghtChinTransform, &cameraLayout, &camRghtChinPixels) private
Definition at line 43 of file BetaProtoControllerOctoWS2811.h.
camRghtChinPixels
PixelGroup camRghtChinPixels = PixelGroup(ProtoDRMini, 89) private
Definition at line 34 of file BetaProtoControllerOctoWS2811.h.
Referenced by Display().
camRghtChinTransform
Transform camRghtChinTransform = Transform(Vector3D(52.014f, 9.825f, 28.423f), Vector3D(19.0f + 30.0f, 30.0f, -500.0f-19.0f), Vector3D(1, 1, 1)) private
Definition at line 25 of file BetaProtoControllerOctoWS2811.h.
camRghtFrnt
Camera camRghtFrnt = Camera(&camRghtFrntTransform, &cameraLayout, &camRghtFrntPixels) private
Definition at line 39 of file BetaProtoControllerOctoWS2811.h.
camRghtFrntPixels
PixelGroup camRghtFrntPixels = PixelGroup(KaiborgV1Pixels, 571, PixelGroup::ZEROTOMAX) private
Definition at line 30 of file BetaProtoControllerOctoWS2811.h.
Referenced by Display().
camRghtFrntTransform
Transform camRghtFrntTransform = Transform(Vector3D(0.0f, 27.0f, 0.0f), Vector3D(1.0f, 0, -500.0f+14.0f), Vector3D(1, 1, 1)) private
Definition at line 21 of file BetaProtoControllerOctoWS2811.h.
camRghtMini
Camera camRghtMini = Camera(&camRghtMiniTransform, &cameraLayout, &camRghtMiniPixels) private
Definition at line 45 of file BetaProtoControllerOctoWS2811.h.
camRghtMiniPixels
PixelGroup camRghtMiniPixels = PixelGroup(HertzMiniCamera, 4) private
Definition at line 36 of file BetaProtoControllerOctoWS2811.h.
Referenced by Display().
camRghtMiniTransform
Transform camRghtMiniTransform = Transform(Vector3D(-5.631f, -1.508f, 164.057f), Vector3D(420.0f, 230.0f, -500.0f+111.0f), Vector3D(1, 1, 1)) private
Definition at line 27 of file BetaProtoControllerOctoWS2811.h.
camRghtRear
Camera camRghtRear = Camera(&camRghtRearTransform, &cameraLayout, &camRghtRearPixels) private
Definition at line 41 of file BetaProtoControllerOctoWS2811.h.
camRghtRearPixels
PixelGroup camRghtRearPixels = PixelGroup(KaiborgV1Pixels, 571, PixelGroup::ZEROTOMAX) private
Definition at line 32 of file BetaProtoControllerOctoWS2811.h.
Referenced by Display().
camRghtRearTransform
Transform camRghtRearTransform = Transform(Vector3D(-5.631f, -1.508f, 164.057f), Vector3D(460.0f, 290.0f, -500.0f+111.0f), Vector3D(1, 1, 1)) private
Definition at line 23 of file BetaProtoControllerOctoWS2811.h.
maxBrightness
uint8_t maxBrightness private
Definition at line 49 of file BetaProtoControllerOctoWS2811.h.
Referenced by ProtoV2Controller().
The documentation for this class was generated from the following file:
BetaProtoControllerOctoWS2811.h