BroookAnimation Class Reference
BroookAnimation Class Reference
#include <BroookAnimation.h>
Public Member Functions
BroookAnimation ()
void Initialize () override
uint8_t GetAccentBrightness ()
uint8_t GetBrightness ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
Object3D * GetObject ()
void Update (float ratio) override
Private Member Functions
void LinkEasyEase ()
void LinkParameters ()
void ChangeInterpolationMethods ()
void SetMaterialLayers ()
void UpdateKeyFrameTracks ()
void Default ()
void Determined ()
void Upset ()
void Sleepy ()
void Sad ()
void Happy ()
void Flustered ()
void Dot ()
void Heart ()
void Dead ()
void Question ()
void SpectrumAnalyzerFace ()
void AudioReactiveGradientFace ()
void OscilloscopeFace ()
void BadAppleFace ()
void UpdateFFTVisemes ()
void SetMaterialColor ()
Private Attributes
BroookFace pM
BroookExtras pME
Background background
LEDStripBackground ledStripBackground
EasyEaseAnimator< 25 > eEA = EasyEaseAnimator<25>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f)
bool boopExists = false
RainbowNoise rainbowNoise
RainbowSpiral rainbowSpiral
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0))
SimpleMaterial orangeMaterial = SimpleMaterial(RGBColor(255, 165, 0))
SimpleMaterial whiteMaterial = SimpleMaterial(RGBColor(255, 255, 255))
SimpleMaterial greenMaterial = SimpleMaterial(RGBColor(0, 255, 0))
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255))
SimpleMaterial yellowMaterial = SimpleMaterial(RGBColor(255, 255, 0))
SimpleMaterial purpleMaterial = SimpleMaterial(RGBColor(255, 0, 255))
RGBColor gradientSpectrum [2] = {RGBColor(222, 217, 141), RGBColor(100, 120, 211)}
GradientMaterial< 2 > gradientMat = GradientMaterial<2>(gradientSpectrum, 50.0f, false)
MaterialAnimator< 10 > materialAnimator
MaterialAnimator< 5 > backgroundMaterial
SpectrumAnalyzer sA = SpectrumAnalyzer(Vector2D(200, 100), Vector2D(100, 50), true, true)
AudioReactiveGradient aRG = AudioReactiveGradient(Vector2D(160, 160), Vector2D(0, 0), true, true)
Oscilloscope oSC = Oscilloscope(Vector2D(200, 100), Vector2D(0, 0))
BadAppleSequence gif = BadAppleSequence(Vector2D(200, 145), Vector2D(100, 70), 18)
BlinkTrack< 1 > blink
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f)
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f)
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f)
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 5.3f)
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 6.7f)
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f)
FunctionGenerator fGenMatXMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 1.1f)
FunctionGenerator fGenMatYMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 2.7f)
FunctionGenerator fGenMatRMenu = FunctionGenerator(FunctionGenerator::Sine, -5.0f, 5.0f, 1.7f)
APDS9960 boop
FFTVoiceDetection< 128 > voiceDetection
ObjectAlign objA = ObjectAlign(Vector2D(0.0f, 0.0f), Vector2D(189.0f, 93.0f), Quaternion())
float offsetFace = 0.0f
float offsetFaceSA = 0.0f
float offsetFaceARG = 0.0f
float offsetFaceOSC = 0.0f
float offsetFaceBad = 0.0f
uint8_t offsetFaceInd = 50
uint8_t offsetFaceIndSA = 51
uint8_t offsetFaceIndARG = 52
uint8_t offsetFaceIndOSC = 53
uint8_t offsetFaceIndBad = 54
Detailed Description
Definition at line 33 of file BroookAnimation.h.
Constructor & Destructor Documentation
BroookAnimation()
BroookAnimation () inline
Definition at line 313 of file BroookAnimation.h.
References background, backgroundMaterial, ChangeInterpolationMethods(), gradientMat, ledStripBackground, LinkEasyEase(), LinkParameters(), materialAnimator, objA, pM, pME, ObjectAlign::SetJustification(), SetMaterialLayers(), ObjectAlign::SetMirrorX(), ObjectAlign::SetMirrorY(), GradientMaterial< colorCount >::SetRotationAngle(), and ObjectAlign::Stretch.
Member Function Documentation
AudioReactiveGradientFace()
void AudioReactiveGradientFace () inline private
Definition at line 258 of file BroookAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), aRG, backgroundMaterial, eEA, offsetFaceARG, offsetFaceInd, and offsetFaceIndARG.
Referenced by Update().
BadAppleFace()
void BadAppleFace () inline private
Definition at line 272 of file BroookAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), backgroundMaterial, eEA, gif, offsetFaceBad, offsetFaceInd, and offsetFaceIndBad.
Referenced by Update().
ChangeInterpolationMethods()
void ChangeInterpolationMethods () inline private
Definition at line 130 of file BroookAnimation.h.
References eEA, and EasyEaseAnimator< maxParameters >::SetInterpolationMethod().
Referenced by BroookAnimation().
Dead()
void Dead () inline private
Definition at line 238 of file BroookAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, materialAnimator, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), and redMaterial.
Referenced by Update().
Default()
void Default () inline private
Definition at line 177 of file BroookAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, and AnimationTrack< maxParameters, maxKeyFrames >::Play().
Referenced by Update().
Determined()
void Determined () inline private
Definition at line 182 of file BroookAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, and AnimationTrack< maxParameters, maxKeyFrames >::Play().
Referenced by Update().
Dot()
void Dot () inline private
Definition at line 225 of file BroookAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, and AnimationTrack< maxParameters, maxKeyFrames >::Play().
Referenced by Update().
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 353 of file BroookAnimation.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 354 of file BroookAnimation.h.
Flustered()
void Flustered () inline private
Definition at line 215 of file BroookAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, and AnimationTrack< maxParameters, maxKeyFrames >::Pause().
Referenced by Update().
GetAccentBrightness()
uint8_t GetAccentBrightness () inline
Definition at line 345 of file BroookAnimation.h.
References Menu::GetAccentBrightness().
GetBrightness()
uint8_t GetBrightness () inline
Definition at line 349 of file BroookAnimation.h.
References Menu::GetBrightness().
GetObject()
Object3D * GetObject () inline
Definition at line 356 of file BroookAnimation.h.
References pM.
Happy()
void Happy () inline private
Definition at line 208 of file BroookAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, materialAnimator, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), and rainbowSpiral.
Referenced by Update().
Heart()
void Heart () inline private
Definition at line 231 of file BroookAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, materialAnimator, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), and rainbowSpiral.
Referenced by Update().
Initialize()
void Initialize () inline override
Definition at line 338 of file BroookAnimation.h.
References boop, Menu::Initialize(), and APDS9960::Initialize().
LinkEasyEase()
void LinkEasyEase () inline private
Definition at line 96 of file BroookAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameter(), eEA, offsetFace, offsetFaceARG, offsetFaceBad, offsetFaceInd, offsetFaceIndARG, offsetFaceIndBad, offsetFaceIndOSC, offsetFaceIndSA, offsetFaceOSC, offsetFaceSA, pM, and pME.
Referenced by BroookAnimation().
LinkParameters()
void LinkParameters () inline private
Definition at line 126 of file BroookAnimation.h.
References AnimationTrack< maxParameters, maxKeyFrames >::AddParameter(), blink, and pM.
Referenced by BroookAnimation().
OscilloscopeFace()
void OscilloscopeFace () inline private
Definition at line 265 of file BroookAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), backgroundMaterial, eEA, offsetFaceInd, offsetFaceIndOSC, offsetFaceOSC, and oSC.
Referenced by Update().
Question()
void Question () inline private
Definition at line 245 of file BroookAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, and AnimationTrack< maxParameters, maxKeyFrames >::Pause().
Referenced by Update().
Sad()
void Sad () inline private
Definition at line 201 of file BroookAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, blueMaterial, eEA, materialAnimator, and AnimationTrack< maxParameters, maxKeyFrames >::Play().
Referenced by Update().
SetMaterialColor()
void SetMaterialColor () inline private
Definition at line 297 of file BroookAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), blueMaterial, Menu::GetFaceColor(), greenMaterial, materialAnimator, orangeMaterial, purpleMaterial, rainbowNoise, rainbowSpiral, redMaterial, whiteMaterial, and yellowMaterial.
Referenced by Update().
SetMaterialLayers()
void SetMaterialLayers () inline private
Definition at line 154 of file BroookAnimation.h.
References Material::Add, MaterialAnimator< materialCount >::AddMaterial(), aRG, backgroundMaterial, blueMaterial, Menu::GetMaterial(), gif, gradientMat, greenMaterial, Material::Lighten, materialAnimator, orangeMaterial, oSC, purpleMaterial, rainbowNoise, rainbowSpiral, redMaterial, Material::Replace, sA, MaterialAnimator< materialCount >::SetBaseMaterial(), whiteMaterial, and yellowMaterial.
Referenced by BroookAnimation().
Sleepy()
void Sleepy () inline private
Definition at line 195 of file BroookAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, and AnimationTrack< maxParameters, maxKeyFrames >::Pause().
Referenced by Update().
SpectrumAnalyzerFace()
void SpectrumAnalyzerFace () inline private
Definition at line 251 of file BroookAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), backgroundMaterial, eEA, offsetFaceInd, offsetFaceIndSA, offsetFaceSA, and sA.
Referenced by Update().
Update()
void Update (float ratio) inline override
Definition at line 360 of file BroookAnimation.h.
References ObjectAlign::AlignObjects(), aRG, AudioReactiveGradientFace(), backgroundMaterial, BadAppleFace(), boop, Dead(), Default(), Determined(), Dot(), eEA, fGenMatXMove, fGenMatYMove, Flustered(), Menu::GetFaceSize(), Menu::GetFaceState(), Menu::GetMicLevel(), gif, Happy(), Heart(), APDS9960::isBooped(), materialAnimator, Menu::MirrorSpectrumAnalyzer(), objA, offsetFace, oSC, OscilloscopeFace(), pM, pME, Question(), rainbowNoise, rainbowSpiral, sA, Sad(), ObjectAlign::SetCameraMax(), ObjectAlign::SetEdgeMargin(), SpectrumAnalyzer::SetFlipYState(), AudioReactiveGradient::SetHueAngle(), Oscilloscope::SetHueAngle(), SpectrumAnalyzer::SetHueAngle(), SetMaterialColor(), SpectrumAnalyzer::SetMirrorYState(), ObjectAlign::SetPlaneOffsetAngle(), AudioReactiveGradient::SetPosition(), Oscilloscope::SetPosition(), AudioReactiveGradient::SetRadius(), AudioReactiveGradient::SetRotation(), AudioReactiveGradient::SetSize(), Oscilloscope::SetSize(), FFTVoiceDetection< peakCount >::SetThreshold(), Menu::ShowMenu(), Sleepy(), SpectrumAnalyzerFace(), MaterialAnimator< materialCount >::Update(), FunctionGenerator::Update(), EasyEaseAnimator< maxParameters >::Update(), Oscilloscope::Update(), AudioReactiveGradient::Update(), SpectrumAnalyzer::Update(), Menu::Update(), RainbowNoise::Update(), RainbowSpiral::Update(), UpdateFFTVisemes(), UpdateKeyFrameTracks(), Upset(), Menu::UseBoopSensor(), and voiceDetection.
UpdateFFTVisemes()
void UpdateFFTVisemes () inline private
Definition at line 279 of file BroookAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), Viseme::AH, Viseme::AR, Viseme::EE, eEA, Viseme::ER, FFTVoiceDetection< peakCount >::GetViseme(), Viseme::OO, Viseme::UH, FFTVoiceDetection< peakCount >::Update(), Menu::UseMicrophone(), and voiceDetection.
Referenced by Update().
UpdateKeyFrameTracks()
void UpdateKeyFrameTracks () inline private
Definition at line 173 of file BroookAnimation.h.
References blink, and AnimationTrack< maxParameters, maxKeyFrames >::Update().
Referenced by Update().
Upset()
void Upset () inline private
Definition at line 188 of file BroookAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, materialAnimator, AnimationTrack< maxParameters, maxKeyFrames >::Play(), and redMaterial.
Referenced by Update().
Member Data Documentation
aRG
AudioReactiveGradient aRG = AudioReactiveGradient(Vector2D(160, 160), Vector2D(0, 0), true, true) private
Definition at line 61 of file BroookAnimation.h.
Referenced by AudioReactiveGradientFace(), SetMaterialLayers(), and Update().
background
Background background private
Definition at line 37 of file BroookAnimation.h.
Referenced by BroookAnimation().
backgroundMaterial
MaterialAnimator<5> backgroundMaterial private
Definition at line 58 of file BroookAnimation.h.
Referenced by AudioReactiveGradientFace(), BadAppleFace(), BroookAnimation(), OscilloscopeFace(), SetMaterialLayers(), SpectrumAnalyzerFace(), and Update().
blink
BlinkTrack<1> blink private
Definition at line 66 of file BroookAnimation.h.
Referenced by Dead(), Default(), Determined(), Dot(), Flustered(), Happy(), Heart(), LinkParameters(), Question(), Sad(), Sleepy(), UpdateKeyFrameTracks(), and Upset().
blueMaterial
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255)) private
Definition at line 50 of file BroookAnimation.h.
Referenced by Sad(), SetMaterialColor(), and SetMaterialLayers().
boop
APDS9960 boop private
Definition at line 79 of file BroookAnimation.h.
Referenced by Initialize(), and Update().
boopExists
bool boopExists = false private
Definition at line 41 of file BroookAnimation.h.
eEA
EasyEaseAnimator<25> eEA = EasyEaseAnimator<25>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f) private
Definition at line 39 of file BroookAnimation.h.
Referenced by AudioReactiveGradientFace(), BadAppleFace(), ChangeInterpolationMethods(), Dead(), Default(), Determined(), Dot(), Flustered(), Happy(), Heart(), LinkEasyEase(), OscilloscopeFace(), Question(), Sad(), Sleepy(), SpectrumAnalyzerFace(), Update(), UpdateFFTVisemes(), and Upset().
fGenMatHue
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f) private
Definition at line 73 of file BroookAnimation.h.
fGenMatPos
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f) private
Definition at line 68 of file BroookAnimation.h.
fGenMatRMenu
FunctionGenerator fGenMatRMenu = FunctionGenerator(FunctionGenerator::Sine, -5.0f, 5.0f, 1.7f) private
Definition at line 77 of file BroookAnimation.h.
fGenMatXMenu
FunctionGenerator fGenMatXMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 1.1f) private
Definition at line 75 of file BroookAnimation.h.
fGenMatXMove
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 5.3f) private
Definition at line 71 of file BroookAnimation.h.
Referenced by Update().
fGenMatYMenu
FunctionGenerator fGenMatYMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 2.7f) private
Definition at line 76 of file BroookAnimation.h.
fGenMatYMove
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 6.7f) private
Definition at line 72 of file BroookAnimation.h.
Referenced by Update().
fGenRotation
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f) private
Definition at line 69 of file BroookAnimation.h.
fGenScale
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f) private
Definition at line 70 of file BroookAnimation.h.
gif
BadAppleSequence gif = BadAppleSequence(Vector2D(200, 145), Vector2D(100, 70), 18) private
Definition at line 63 of file BroookAnimation.h.
Referenced by BadAppleFace(), SetMaterialLayers(), and Update().
gradientMat
GradientMaterial<2> gradientMat = GradientMaterial<2>(gradientSpectrum, 50.0f, false) private
Definition at line 55 of file BroookAnimation.h.
Referenced by BroookAnimation(), and SetMaterialLayers().
gradientSpectrum
RGBColor gradientSpectrum[2] = {RGBColor(222, 217, 141), RGBColor(100, 120, 211)} private
Definition at line 54 of file BroookAnimation.h.
greenMaterial
SimpleMaterial greenMaterial = SimpleMaterial(RGBColor(0, 255, 0)) private
Definition at line 49 of file BroookAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
ledStripBackground
LEDStripBackground ledStripBackground private
Definition at line 38 of file BroookAnimation.h.
Referenced by BroookAnimation().
materialAnimator
MaterialAnimator<10> materialAnimator private
Definition at line 57 of file BroookAnimation.h.
Referenced by BroookAnimation(), Dead(), Happy(), Heart(), Sad(), SetMaterialColor(), SetMaterialLayers(), Update(), and Upset().
objA
ObjectAlign objA = ObjectAlign(Vector2D(0.0f, 0.0f), Vector2D(189.0f, 93.0f), Quaternion()) private
Definition at line 83 of file BroookAnimation.h.
Referenced by BroookAnimation(), and Update().
offsetFace
float offsetFace = 0.0f private
Definition at line 85 of file BroookAnimation.h.
Referenced by LinkEasyEase(), and Update().
offsetFaceARG
float offsetFaceARG = 0.0f private
Definition at line 87 of file BroookAnimation.h.
Referenced by AudioReactiveGradientFace(), and LinkEasyEase().
offsetFaceBad
float offsetFaceBad = 0.0f private
Definition at line 89 of file BroookAnimation.h.
Referenced by BadAppleFace(), and LinkEasyEase().
offsetFaceInd
uint8_t offsetFaceInd = 50 private
Definition at line 90 of file BroookAnimation.h.
Referenced by AudioReactiveGradientFace(), BadAppleFace(), LinkEasyEase(), OscilloscopeFace(), and SpectrumAnalyzerFace().
offsetFaceIndARG
uint8_t offsetFaceIndARG = 52 private
Definition at line 92 of file BroookAnimation.h.
Referenced by AudioReactiveGradientFace(), and LinkEasyEase().
offsetFaceIndBad
uint8_t offsetFaceIndBad = 54 private
Definition at line 94 of file BroookAnimation.h.
Referenced by BadAppleFace(), and LinkEasyEase().
offsetFaceIndOSC
uint8_t offsetFaceIndOSC = 53 private
Definition at line 93 of file BroookAnimation.h.
Referenced by LinkEasyEase(), and OscilloscopeFace().
offsetFaceIndSA
uint8_t offsetFaceIndSA = 51 private
Definition at line 91 of file BroookAnimation.h.
Referenced by LinkEasyEase(), and SpectrumAnalyzerFace().
offsetFaceOSC
float offsetFaceOSC = 0.0f private
Definition at line 88 of file BroookAnimation.h.
Referenced by LinkEasyEase(), and OscilloscopeFace().
offsetFaceSA
float offsetFaceSA = 0.0f private
Definition at line 86 of file BroookAnimation.h.
Referenced by LinkEasyEase(), and SpectrumAnalyzerFace().
orangeMaterial
SimpleMaterial orangeMaterial = SimpleMaterial(RGBColor(255, 165, 0)) private
Definition at line 47 of file BroookAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
oSC
Oscilloscope oSC = Oscilloscope(Vector2D(200, 100), Vector2D(0, 0)) private
Definition at line 62 of file BroookAnimation.h.
Referenced by OscilloscopeFace(), SetMaterialLayers(), and Update().
pM
BroookFace pM private
Definition at line 35 of file BroookAnimation.h.
Referenced by BroookAnimation(), GetObject(), LinkEasyEase(), LinkParameters(), and Update().
pME
BroookExtras pME private
Definition at line 36 of file BroookAnimation.h.
Referenced by BroookAnimation(), LinkEasyEase(), and Update().
purpleMaterial
SimpleMaterial purpleMaterial = SimpleMaterial(RGBColor(255, 0, 255)) private
Definition at line 52 of file BroookAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
rainbowNoise
RainbowNoise rainbowNoise private
Definition at line 44 of file BroookAnimation.h.
Referenced by SetMaterialColor(), SetMaterialLayers(), and Update().
rainbowSpiral
RainbowSpiral rainbowSpiral private
Definition at line 45 of file BroookAnimation.h.
Referenced by Happy(), Heart(), SetMaterialColor(), SetMaterialLayers(), and Update().
redMaterial
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0)) private
Definition at line 46 of file BroookAnimation.h.
Referenced by Dead(), SetMaterialColor(), SetMaterialLayers(), and Upset().
sA
SpectrumAnalyzer sA = SpectrumAnalyzer(Vector2D(200, 100), Vector2D(100, 50), true, true) private
Definition at line 60 of file BroookAnimation.h.
Referenced by SetMaterialLayers(), SpectrumAnalyzerFace(), and Update().
voiceDetection
FFTVoiceDetection<128> voiceDetection private
Definition at line 81 of file BroookAnimation.h.
Referenced by Update(), and UpdateFFTVisemes().
whiteMaterial
SimpleMaterial whiteMaterial = SimpleMaterial(RGBColor(255, 255, 255)) private
Definition at line 48 of file BroookAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
yellowMaterial
SimpleMaterial yellowMaterial = SimpleMaterial(RGBColor(255, 255, 0)) private
Definition at line 51 of file BroookAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
The documentation for this class was generated from the following file:
BroookAnimation.h