CubeAnimation Class Reference
CubeAnimation Class Reference
#include <CubeAnimation.h>
Public Member Functions
CubeAnimation ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
void Update (float ratio) override
Private Attributes
Cube cube
DepthMaterial dMat = DepthMaterial(DepthMaterial::Z, 100.0f, 600.0f)
LightMaterial lMat = LightMaterial()
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -360.0f, 360.0f, 6.0f)
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 0.25f, 0.75f, 4.0f)
Detailed Description
Definition at line 9 of file CubeAnimation.h.
Constructor & Destructor Documentation
CubeAnimation()
CubeAnimation () inline
Definition at line 18 of file CubeAnimation.h.
References cube, and dMat.
Member Function Documentation
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 24 of file CubeAnimation.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 25 of file CubeAnimation.h.
Update()
void Update (float ratio) inline override
Definition at line 27 of file CubeAnimation.h.
References cube, EulerConstants::EulerOrderXZYS, fGenRotation, fGenScale, Rotation::GetQuaternion(), and FunctionGenerator::Update().
Member Data Documentation
cube
Cube cube private
Definition at line 11 of file CubeAnimation.h.
Referenced by CubeAnimation(), and Update().
dMat
DepthMaterial dMat = DepthMaterial(DepthMaterial::Z, 100.0f, 600.0f) private
Definition at line 12 of file CubeAnimation.h.
Referenced by CubeAnimation().
fGenRotation
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -360.0f, 360.0f, 6.0f) private
Definition at line 14 of file CubeAnimation.h.
Referenced by Update().
fGenScale
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 0.25f, 0.75f, 4.0f) private
Definition at line 15 of file CubeAnimation.h.
Referenced by Update().
lMat
LightMaterial lMat = LightMaterial() private
Definition at line 13 of file CubeAnimation.h.
The documentation for this class was generated from the following file:
CubeAnimation.h