NukudeFaceAnimation Class Reference
NukudeFaceAnimation Class Reference
#include <NukudeFaceAnimation.h>
Public Member Functions
NukudeFaceAnimation ()
void UpdateKeyFrameTracks ()
void Default ()
void Angry ()
void Sad ()
void Surprised ()
void Doubt ()
void Frown ()
void LookUp ()
void LookDown ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
Object3D * GetObject ()
void Update (float ratio) override
Public Attributes
float offset = 0.0f
Private Member Functions
void LinkEasyEase ()
void LinkParameters ()
void AddBlinkKeyFrames ()
void AddMouthKeyFrames ()
Private Attributes
NukudeFace pM
EasyEaseAnimator eEA = EasyEaseAnimator(15, EasyEaseAnimator::Cosine)
RGBColor spectrum [4] = {RGBColor(0, 255, 0), RGBColor(255, 0, 0), RGBColor(0, 255, 0), RGBColor(0, 0, 255)}
GradientMaterial gNoiseMat = GradientMaterial(4, spectrum, 2.0f, false)
SimplexNoise sNoise = SimplexNoise(1, &gNoiseMat)
NormalMaterial normalMaterial
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f)
RainbowSequence gif = RainbowSequence(Vector2D(200, 145), Vector2D(100, 70), 60)
KeyFrameTrack blink = KeyFrameTrack(1, 0.0f, 1.0f, 10, KeyFrameTrack::Cosine)
KeyFrameTrack mouth = KeyFrameTrack(1, 0.0f, 1.0f, 5, KeyFrameTrack::Cosine)
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f)
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f)
MicrophoneSimple mic = MicrophoneSimple(22)
bool talk = true
Detailed Description
Definition at line 18 of file NukudeFaceAnimation.h.
Constructor & Destructor Documentation
NukudeFaceAnimation()
NukudeFaceAnimation () inline
Definition at line 77 of file NukudeFaceAnimation.h.
References AddBlinkKeyFrames(), AddMouthKeyFrames(), gif, SerialSync::Initialize(), ButtonHandler::Initialize(), LinkEasyEase(), LinkParameters(), and pM.
Member Function Documentation
AddBlinkKeyFrames()
void AddBlinkKeyFrames () inline private
Definition at line 56 of file NukudeFaceAnimation.h.
References KeyFrameTrack< maxParameters, maxKeyFrames >::AddKeyFrame(), and blink.
Referenced by NukudeFaceAnimation().
AddMouthKeyFrames()
void AddMouthKeyFrames () inline private
Definition at line 70 of file NukudeFaceAnimation.h.
References KeyFrameTrack< maxParameters, maxKeyFrames >::AddKeyFrame(), and mouth.
Referenced by NukudeFaceAnimation().
Angry()
void Angry () inline
Definition at line 105 of file NukudeFaceAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
Referenced by Update().
Default()
void Default () inline
Definition at line 97 of file NukudeFaceAnimation.h.
References blink, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
Referenced by Update().
Doubt()
void Doubt () inline
Definition at line 135 of file NukudeFaceAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
Referenced by Update().
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 175 of file NukudeFaceAnimation.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 176 of file NukudeFaceAnimation.h.
Frown()
void Frown () inline
Definition at line 145 of file NukudeFaceAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
Referenced by Update().
GetObject()
Object3D * GetObject () inline
Definition at line 178 of file NukudeFaceAnimation.h.
References pM.
LinkEasyEase()
void LinkEasyEase () inline private
Definition at line 41 of file NukudeFaceAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameter(), eEA, and pM.
Referenced by NukudeFaceAnimation().
LinkParameters()
void LinkParameters () inline private
Definition at line 51 of file NukudeFaceAnimation.h.
References KeyFrameTrack< maxParameters, maxKeyFrames >::AddParameter(), blink, mouth, and pM.
Referenced by NukudeFaceAnimation().
LookDown()
void LookDown () inline
Definition at line 165 of file NukudeFaceAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
Referenced by Update().
LookUp()
void LookUp () inline
Definition at line 155 of file NukudeFaceAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
Referenced by Update().
Sad()
void Sad () inline
Definition at line 115 of file NukudeFaceAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
Referenced by Update().
Surprised()
void Surprised () inline
Definition at line 125 of file NukudeFaceAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, and talk.
Referenced by Update().
Update()
void Update (float ratio) inline override
Definition at line 185 of file NukudeFaceAnimation.h.
References Angry(), Default(), Doubt(), eEA, fGenMatPos, Frown(), SerialSync::GetMode(), SerialSync::GetMouthMove(), SerialSync::GetRatio(), gif, gNoiseMat, GradientMaterial< colorCount >::HueShift(), LookDown(), LookUp(), mic, offset, pM, SerialSync::Read(), Sad(), SerialSync::Send(), GradientMaterial< colorCount >::SetGradientPeriod(), SerialSync::SetMode(), SerialSync::SetMouthMove(), SerialSync::SetRatio(), SimplexNoise< colors >::SetScale(), SimplexNoise< colors >::SetZPosition(), sNoise, Surprised(), talk, MicrophoneSimple::Update(), FunctionGenerator::Update(), EasyEaseAnimator< maxParameters >::Update(), and UpdateKeyFrameTracks().
UpdateKeyFrameTracks()
void UpdateKeyFrameTracks () inline
Definition at line 92 of file NukudeFaceAnimation.h.
References blink, mouth, and KeyFrameTrack< maxParameters, maxKeyFrames >::Update().
Referenced by Update().
Member Data Documentation
blink
KeyFrameTrack blink = KeyFrameTrack(1, 0.0f, 1.0f, 10, KeyFrameTrack::Cosine) private
Definition at line 32 of file NukudeFaceAnimation.h.
Referenced by AddBlinkKeyFrames(), Angry(), Default(), Doubt(), Frown(), LinkParameters(), LookDown(), LookUp(), Sad(), Surprised(), and UpdateKeyFrameTracks().
eEA
EasyEaseAnimator eEA = EasyEaseAnimator(15, EasyEaseAnimator::Cosine) private
Definition at line 21 of file NukudeFaceAnimation.h.
Referenced by Angry(), Doubt(), Frown(), LinkEasyEase(), LookDown(), LookUp(), Sad(), Surprised(), and Update().
fGenMatPos
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f) private
Definition at line 29 of file NukudeFaceAnimation.h.
Referenced by Update().
fGenRotation
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f) private
Definition at line 35 of file NukudeFaceAnimation.h.
fGenScale
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f) private
Definition at line 36 of file NukudeFaceAnimation.h.
gif
RainbowSequence gif = RainbowSequence(Vector2D(200, 145), Vector2D(100, 70), 60) private
Definition at line 30 of file NukudeFaceAnimation.h.
Referenced by NukudeFaceAnimation(), and Update().
gNoiseMat
GradientMaterial gNoiseMat = GradientMaterial(4, spectrum, 2.0f, false) private
Definition at line 24 of file NukudeFaceAnimation.h.
Referenced by Update().
mic
MicrophoneSimple mic = MicrophoneSimple(22) private
Definition at line 38 of file NukudeFaceAnimation.h.
Referenced by Update().
mouth
KeyFrameTrack mouth = KeyFrameTrack(1, 0.0f, 1.0f, 5, KeyFrameTrack::Cosine) private
Definition at line 33 of file NukudeFaceAnimation.h.
Referenced by AddMouthKeyFrames(), Angry(), Default(), Doubt(), Frown(), LinkParameters(), LookDown(), LookUp(), Sad(), Surprised(), and UpdateKeyFrameTracks().
normalMaterial
NormalMaterial normalMaterial private
Definition at line 27 of file NukudeFaceAnimation.h.
offset
float offset = 0.0f
Definition at line 182 of file NukudeFaceAnimation.h.
Referenced by Update().
pM
NukudeFace pM private
Definition at line 20 of file NukudeFaceAnimation.h.
Referenced by Angry(), Default(), Doubt(), Frown(), GetObject(), LinkEasyEase(), LinkParameters(), LookDown(), LookUp(), NukudeFaceAnimation(), Sad(), Surprised(), and Update().
sNoise
SimplexNoise sNoise = SimplexNoise(1, &gNoiseMat) private
Definition at line 25 of file NukudeFaceAnimation.h.
Referenced by Update().
spectrum
RGBColor spectrum[4] = {RGBColor(0, 255, 0), RGBColor(255, 0, 0), RGBColor(0, 255, 0), RGBColor(0, 0, 255)} private
Definition at line 23 of file NukudeFaceAnimation.h.
talk
bool talk = true private
Definition at line 39 of file NukudeFaceAnimation.h.
Referenced by Angry(), Default(), Doubt(), Frown(), LookDown(), LookUp(), Sad(), Surprised(), and Update().
The documentation for this class was generated from the following file:
NukudeFaceAnimation.h