RenderingEngine Class Reference
RenderingEngine Class Reference
Provides static methods for rendering and display operations.
#include <Engine.h>
Static Public Member Functions
static void Rasterize (Scene *scene, CameraManager *cameraManager)
Rasterizes the given scene using the cameras managed by the CameraManager.
static void DisplayWhite (CameraManager *cameraManager)
Fills the display with white for all cameras in the CameraManager.
Detailed Description
Provides static methods for rendering and display operations.
The RenderingEngine class offers functionality for rasterizing scenes using cameras and managing display operations such as filling the screen with a white color.
Definition at line 26 of file Engine.h.
Member Function Documentation
DisplayWhite()
void DisplayWhite (CameraManager * cameraManager) static
Fills the display with white for all cameras in the CameraManager.
This method iterates through all cameras in the CameraManager and fills their displays with white using the DisplayTest utility.
Parameters
cameraManager Pointer to the CameraManager managing the cameras.
Definition at line 13 of file Engine.cpp.
References DisplayTest::FillWhite(), CameraManager::GetCameraCount(), and CameraManager::GetCameras().
Rasterize()
void Rasterize (Scene * scene, CameraManager * cameraManager) static
Rasterizes the given scene using the cameras managed by the CameraManager.
This method iterates through all cameras in the CameraManager and rasterizes the scene for each camera. If the scene includes a post-processing effect, it applies the effect to the corresponding pixel group.
Parameters
scene Pointer to the Scene to be rasterized.
cameraManager Pointer to the CameraManager managing the cameras.
Definition at line 3 of file Engine.cpp.
References Effect::ApplyEffect(), CameraManager::GetCameraCount(), CameraManager::GetCameras(), Scene::GetEffect(), CameraBase::GetPixelGroup(), Rasterizer::Rasterize(), and Scene::UseEffect().
Referenced by Project::Render().
The documentation for this class was generated from the following files:
Engine.h
Engine.cpp