Test Class Reference
Test Class Reference
A debugging effect used to identify memory issues in pixel rendering.
#include <Test.h>
Public Member Functions
Test ()
Constructs a Test effect instance.
void ApplyEffect (IPixelGroup *pixelGroup) override
Applies the debugging effect to the given pixel group.
Public Member Functions inherited from Effect
Effect ()
Default constructor for the Effect class.
void SetRatio (float ratio)
Sets the scaling ratio for the effect.
Private Attributes
FunctionGenerator fGenD = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 255.0f, 0.5f)
Function generator for the debug intensity values.
Additional Inherited Members
Protected Attributes inherited from Effect
float ratio = 0.0f
A scaling ratio used for dynamic effect adjustments.
Detailed Description
A debugging effect used to identify memory issues in pixel rendering.
The Test effect applies a simple pattern to the pixel group to help detect and troubleshoot memory-related issues during development.
Definition at line 25 of file Test.h.
Constructor & Destructor Documentation
Test()
Test ()
Constructs a Test effect instance.
Definition at line 3 of file Test.cpp.
Member Function Documentation
ApplyEffect()
void ApplyEffect (IPixelGroup * pixelGroup) override virtual
Applies the debugging effect to the given pixel group.
The effect generates a simple pattern with directional indices to highlight memory allocation or access issues.
Parameters
pixelGroup Pointer to the IPixelGroup to which the effect will be applied.
Implements Effect.
Definition at line 5 of file Test.cpp.
References RGBColor::B, fGenD, RGBColor::G, IPixelGroup::GetColorBuffer(), IPixelGroup::GetColors(), IPixelGroup::GetDownIndex(), IPixelGroup::GetLeftIndex(), IPixelGroup::GetPixelCount(), IPixelGroup::GetRightIndex(), IPixelGroup::GetUpIndex(), RGBColor::R, and FunctionGenerator::Update().
Member Data Documentation
fGenD
FunctionGenerator fGenD = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 255.0f, 0.5f) private
Function generator for the debug intensity values.
Definition at line 28 of file Test.h.
Referenced by ApplyEffect().
The documentation for this class was generated from the following files:
Test.h
Test.cpp