SerialSync Class Reference
SerialSync Class Reference
#include <SerialSync.h>
Classes
struct Data
Static Public Member Functions
static void Initialize ()
static float GetRatio ()
static uint8_t GetMode ()
static float GetMouthMove ()
static void Read ()
static void SetRatio (float ratio)
static void SetMode (uint8_t mode)
static void SetMouthMove (float ratio)
static void Send ()
static void SetFaceState (uint8_t faceState)
static uint8_t GetFaceState ()
static void SetBrightness (uint8_t bright)
static uint8_t GetBrightness ()
static void SetAccentBrightness (uint8_t accentBright)
static uint8_t GetAccentBrightness ()
static void SetUseMicrophone (uint8_t microphone)
static uint8_t UseMicrophone ()
static void SetMicLevel (uint8_t micLevel)
static uint8_t GetMicLevel ()
static void SetUseBoopSensor (uint8_t boopSensor)
static uint8_t UseBoopSensor ()
static void SetMirrorSpectrumAnalyzer (uint8_t spectrumMirror)
static uint8_t MirrorSpectrumAnalyzer ()
static void SetFaceSize (uint8_t faceSize)
static uint8_t GetFaceSize ()
static void SetFaceColor (uint8_t color)
static uint8_t GetFaceColor ()
static void SetCurrentMenu (uint8_t currentMenu)
static uint8_t GetCurrentMenu ()
static void SetDead (bool dead)
static bool GetDead ()
static void SetBoop (bool boop)
static bool GetBoop ()
Static Private Attributes
static struct SerialSync::Data data
static SerialTransfer dataTransfer
Detailed Description
Definition at line 6 of file SerialSync.h.
Member Function Documentation
GetAccentBrightness()
uint8_t GetAccentBrightness () static
Definition at line 68 of file SerialSync.cpp.
References SerialSync::Data::accentBright, and data.
Referenced by GammaAnimation::Update().
GetBoop()
bool GetBoop () static
Definition at line 140 of file SerialSync.cpp.
References SerialSync::Data::boop, and data.
Referenced by GammaAnimation::Update().
GetBrightness()
uint8_t GetBrightness () static
Definition at line 60 of file SerialSync.cpp.
References SerialSync::Data::bright, and data.
Referenced by GammaAnimation::Update().
GetCurrentMenu()
uint8_t GetCurrentMenu () static
Definition at line 124 of file SerialSync.cpp.
References SerialSync::Data::currentMenu, and data.
Referenced by GammaAnimation::Update().
GetDead()
bool GetDead () static
Definition at line 132 of file SerialSync.cpp.
References data, and SerialSync::Data::dead.
Referenced by GammaAnimation::Update().
GetFaceColor()
uint8_t GetFaceColor () static
Definition at line 116 of file SerialSync.cpp.
References SerialSync::Data::color, and data.
Referenced by GammaAnimation::Update().
GetFaceSize()
uint8_t GetFaceSize () static
Definition at line 108 of file SerialSync.cpp.
References data, and SerialSync::Data::faceSize.
Referenced by GammaAnimation::Update().
GetFaceState()
uint8_t GetFaceState () static
Definition at line 52 of file SerialSync.cpp.
References data, and SerialSync::Data::faceState.
Referenced by GammaAnimation::Update().
GetMicLevel()
uint8_t GetMicLevel () static
Definition at line 84 of file SerialSync.cpp.
References data, and SerialSync::Data::micLevel.
Referenced by GammaAnimation::Update().
GetMode()
uint8_t GetMode () static
Definition at line 15 of file SerialSync.cpp.
References data, and SerialSync::Data::mode.
Referenced by AlphaAnimation::Update(), and NukudeFaceAnimation::Update().
GetMouthMove()
float GetMouthMove () static
Definition at line 19 of file SerialSync.cpp.
References data, and SerialSync::Data::mouthMove.
Referenced by AlphaAnimation::Update(), GammaAnimation::Update(), and NukudeFaceAnimation::Update().
GetRatio()
float GetRatio () static
Definition at line 11 of file SerialSync.cpp.
References data, and SerialSync::Data::ratio.
Referenced by AlphaAnimation::Update(), GammaAnimation::Update(), and NukudeFaceAnimation::Update().
Initialize()
void Initialize () static
Definition at line 6 of file SerialSync.cpp.
References dataTransfer.
Referenced by AlphaAnimation::Initialize(), GammaAnimation::Initialize(), and NukudeFaceAnimation::NukudeFaceAnimation().
MirrorSpectrumAnalyzer()
uint8_t MirrorSpectrumAnalyzer () static
Definition at line 100 of file SerialSync.cpp.
References data, and SerialSync::Data::spectrumMirror.
Referenced by GammaAnimation::Update().
Read()
void Read () static
Definition at line 23 of file SerialSync.cpp.
References data, and dataTransfer.
Referenced by AlphaAnimation::Update(), GammaAnimation::Update(), and NukudeFaceAnimation::Update().
Send()
void Send () static
Definition at line 42 of file SerialSync.cpp.
References data, and dataTransfer.
Referenced by AlphaAnimation::Update(), GammaAnimation::Update(), and NukudeFaceAnimation::Update().
SetAccentBrightness()
void SetAccentBrightness (uint8_t accentBright) static
Definition at line 64 of file SerialSync.cpp.
References SerialSync::Data::accentBright, and data.
Referenced by GammaAnimation::Update().
SetBoop()
void SetBoop (bool boop) static
Definition at line 136 of file SerialSync.cpp.
References SerialSync::Data::boop, and data.
Referenced by GammaAnimation::Update().
SetBrightness()
void SetBrightness (uint8_t bright) static
Definition at line 56 of file SerialSync.cpp.
References SerialSync::Data::bright, and data.
Referenced by GammaAnimation::Update().
SetCurrentMenu()
void SetCurrentMenu (uint8_t currentMenu) static
Definition at line 120 of file SerialSync.cpp.
References SerialSync::Data::currentMenu, and data.
Referenced by GammaAnimation::Update().
SetDead()
void SetDead (bool dead) static
Definition at line 128 of file SerialSync.cpp.
References data, and SerialSync::Data::dead.
Referenced by GammaAnimation::Update().
SetFaceColor()
void SetFaceColor (uint8_t color) static
Definition at line 112 of file SerialSync.cpp.
References SerialSync::Data::color, and data.
Referenced by GammaAnimation::Update().
SetFaceSize()
void SetFaceSize (uint8_t faceSize) static
Definition at line 104 of file SerialSync.cpp.
References data, and SerialSync::Data::faceSize.
Referenced by GammaAnimation::Update().
SetFaceState()
void SetFaceState (uint8_t faceState) static
Definition at line 48 of file SerialSync.cpp.
References data, and SerialSync::Data::faceState.
Referenced by GammaAnimation::Update().
SetMicLevel()
void SetMicLevel (uint8_t micLevel) static
Definition at line 80 of file SerialSync.cpp.
References data, and SerialSync::Data::micLevel.
Referenced by GammaAnimation::Update().
SetMirrorSpectrumAnalyzer()
void SetMirrorSpectrumAnalyzer (uint8_t spectrumMirror) static
Definition at line 96 of file SerialSync.cpp.
References data, and SerialSync::Data::spectrumMirror.
Referenced by GammaAnimation::Update().
SetMode()
void SetMode (uint8_t mode) static
Definition at line 34 of file SerialSync.cpp.
References data, and SerialSync::Data::mode.
Referenced by AlphaAnimation::Update(), GammaAnimation::Update(), and NukudeFaceAnimation::Update().
SetMouthMove()
void SetMouthMove (float ratio) static
Definition at line 38 of file SerialSync.cpp.
References data, and SerialSync::Data::mouthMove.
Referenced by AlphaAnimation::Update(), GammaAnimation::Update(), and NukudeFaceAnimation::Update().
SetRatio()
void SetRatio (float ratio) static
Definition at line 30 of file SerialSync.cpp.
References data, and SerialSync::Data::ratio.
Referenced by AlphaAnimation::Update(), GammaAnimation::Update(), and NukudeFaceAnimation::Update().
SetUseBoopSensor()
void SetUseBoopSensor (uint8_t boopSensor) static
Definition at line 88 of file SerialSync.cpp.
References SerialSync::Data::boopSensor, and data.
Referenced by GammaAnimation::Update().
SetUseMicrophone()
void SetUseMicrophone (uint8_t microphone) static
Definition at line 72 of file SerialSync.cpp.
References data, and SerialSync::Data::microphone.
Referenced by GammaAnimation::Update().
UseBoopSensor()
uint8_t UseBoopSensor () static
Definition at line 92 of file SerialSync.cpp.
References SerialSync::Data::boopSensor, and data.
Referenced by GammaAnimation::Update().
UseMicrophone()
uint8_t UseMicrophone () static
Definition at line 76 of file SerialSync.cpp.
References data, and SerialSync::Data::microphone.
Referenced by GammaAnimation::Update().
Member Data Documentation
data
SerialSync::Data data static private
Definition at line 4 of file SerialSync.cpp.
Referenced by GetAccentBrightness(), GetBoop(), GetBrightness(), GetCurrentMenu(), GetDead(), GetFaceColor(), GetFaceSize(), GetFaceState(), GetMicLevel(), GetMode(), GetMouthMove(), GetRatio(), MirrorSpectrumAnalyzer(), Read(), Send(), SetAccentBrightness(), SetBoop(), SetBrightness(), SetCurrentMenu(), SetDead(), SetFaceColor(), SetFaceSize(), SetFaceState(), SetMicLevel(), SetMirrorSpectrumAnalyzer(), SetMode(), SetMouthMove(), SetRatio(), SetUseBoopSensor(), SetUseMicrophone(), UseBoopSensor(), and UseMicrophone().
dataTransfer
SerialTransfer dataTransfer static private
Definition at line 28 of file SerialSync.h.
Referenced by Initialize(), Read(), and Send().
The documentation for this class was generated from the following files:
SerialSync.h
SerialSync.cpp