MyntAnimation Class Reference
MyntAnimation Class Reference
#include <MyntAnimation.h>
Public Member Functions
MyntAnimation ()
void UpdateKeyFrameTracks ()
void Default ()
void Angry ()
void Dead ()
void Happy ()
void Love ()
void Sleepy ()
void SleepyZZZ ()
void SOSFace ()
void PacmanFace ()
void SpectrumAnalyzerFace ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
Object3D * GetObject ()
void UpdateFFTVisemes ()
void Update (float ratio) override
Private Member Functions
void LinkEasyEase ()
void LinkParameters ()
void ChangeInterpolationMethods ()
void SetMaterials ()
Private Attributes
MyntFace pM
MyntFood pacmanFood
MyntPacman pacman
MyntSOS sos
MyntZZZ zzz
Background background
EasyEaseAnimator< 30 > eEA = EasyEaseAnimator<30>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f)
RainbowNoise rainbowNoise
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0))
SimpleMaterial greenMaterial = SimpleMaterial(RGBColor(0, 255, 0))
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255))
SimpleMaterial yellowMaterial = SimpleMaterial(RGBColor(255, 255, 0))
SimpleMaterial pinkMaterial = SimpleMaterial(RGBColor(255, 0, 255))
SimpleMaterial tealMaterial = SimpleMaterial(RGBColor(34, 248, 251))
CombineMaterial< 5 > faceMaterial
SpectrumAnalyzer sA = SpectrumAnalyzer(Vector2D(250, 110), Vector2D(125, 60), true, true)
BlinkTrack< 1 > blink
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f)
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f)
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f)
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -3.5f, 3.5f, 2.3f)
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -3.5f, 3.5f, 2.7f)
FunctionGenerator fGenMatPacman = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 0.4f)
FunctionGenerator fGenMatScaleAnim = FunctionGenerator(FunctionGenerator::Sine, 1.0f, 2.0f, 1.3f)
FunctionGenerator fGenMatScalePacman = FunctionGenerator(FunctionGenerator::Sine, 1.0f, 1.2f, 2.8f)
BoopSensor boop
float redFaceMix = 0.0f
float pinkFaceMix = 0.0f
float blueFaceMix = 0.0f
uint8_t redFaceIndex = 51
uint8_t pinkFaceIndex = 52
uint8_t blueFaceIndex = 53
FFTVoiceDetection< 128 > voiceDetection
bool talk = true
bool hideFace = false
Detailed Description
Definition at line 28 of file MyntAnimation.h.
Constructor & Destructor Documentation
MyntAnimation()
MyntAnimation () inline
Definition at line 137 of file MyntAnimation.h.
References background, blueMaterial, boop, ChangeInterpolationMethods(), faceMaterial, MicrophoneFourier::Initialize(), LinkEasyEase(), LinkParameters(), pacman, pacmanFood, pM, sA, SetMaterials(), sos, tealMaterial, yellowMaterial, and zzz.
Member Function Documentation
Angry()
void Angry () inline
Definition at line 174 of file MyntAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, and redFaceIndex.
Referenced by Update().
ChangeInterpolationMethods()
void ChangeInterpolationMethods () inline private
Definition at line 110 of file MyntAnimation.h.
References blueFaceIndex, eEA, pinkFaceIndex, redFaceIndex, and EasyEaseAnimator< maxParameters >::SetInterpolationMethod().
Referenced by MyntAnimation().
Dead()
void Dead () inline
Definition at line 180 of file MyntAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), and redFaceIndex.
Referenced by Update().
Default()
void Default () inline
Definition at line 172 of file MyntAnimation.h.
Referenced by Update().
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 259 of file MyntAnimation.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 260 of file MyntAnimation.h.
GetObject()
Object3D * GetObject () inline
Definition at line 262 of file MyntAnimation.h.
References pM.
Happy()
void Happy () inline
Definition at line 187 of file MyntAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
Referenced by Update().
LinkEasyEase()
void LinkEasyEase () inline private
Definition at line 81 of file MyntAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameter(), blueFaceIndex, blueFaceMix, eEA, pinkFaceIndex, pinkFaceMix, pM, redFaceIndex, and redFaceMix.
Referenced by MyntAnimation().
LinkParameters()
void LinkParameters () inline private
Definition at line 106 of file MyntAnimation.h.
References AnimationTrack< maxParameters, maxKeyFrames >::AddParameter(), blink, and pM.
Referenced by MyntAnimation().
Love()
void Love () inline
Definition at line 192 of file MyntAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, and pinkFaceIndex.
Referenced by Update().
PacmanFace()
void PacmanFace () inline
Definition at line 234 of file MyntAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, hideFace, pacman, pacmanFood, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), and talk.
Referenced by Update().
SetMaterials()
void SetMaterials () inline private
Definition at line 128 of file MyntAnimation.h.
References Material::Add, CombineMaterial< materialCount >::AddMaterial(), blueMaterial, faceMaterial, greenMaterial, Material::Lighten, pinkMaterial, rainbowNoise, redMaterial, and Material::Replace.
Referenced by MyntAnimation().
Sleepy()
void Sleepy () inline
Definition at line 198 of file MyntAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, blueFaceIndex, eEA, and AnimationTrack< maxParameters, maxKeyFrames >::Pause().
Referenced by Update().
SleepyZZZ()
void SleepyZZZ () inline
Definition at line 205 of file MyntAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, blueFaceIndex, eEA, hideFace, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), talk, and zzz.
Referenced by Update().
SOSFace()
void SOSFace () inline
Definition at line 220 of file MyntAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, eEA, hideFace, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), sos, and talk.
Referenced by Update().
SpectrumAnalyzerFace()
void SpectrumAnalyzerFace () inline
Definition at line 250 of file MyntAnimation.h.
References background, blink, hideFace, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), pM, and talk.
Referenced by Update().
Update()
void Update (float ratio) inline override
Definition at line 287 of file MyntAnimation.h.
References Angry(), background, blink, blueFaceMix, boop, Dead(), Default(), eEA, faceMaterial, fGenMatPacman, fGenMatScaleAnim, fGenMatScalePacman, fGenMatXMove, fGenMatYMove, MicrophoneFourierBase::GetFourierFiltered(), Happy(), hideFace, Love(), pacman, PacmanFace(), pacmanFood, pinkFaceMix, AnimationTrack< maxParameters, maxKeyFrames >::Play(), pM, rainbowNoise, redFaceMix, sA, SpectrumAnalyzer::SetFlipYState(), SpectrumAnalyzer::SetHueAngle(), SpectrumAnalyzer::SetMirrorYState(), CombineMaterial< materialCount >::SetOpacity(), Sleepy(), SleepyZZZ(), sos, SOSFace(), SpectrumAnalyzerFace(), talk, MicrophoneFourier::Update(), FunctionGenerator::Update(), EasyEaseAnimator< maxParameters >::Update(), SpectrumAnalyzer::Update(), RainbowNoise::Update(), UpdateFFTVisemes(), UpdateKeyFrameTracks(), and zzz.
UpdateFFTVisemes()
void UpdateFFTVisemes () inline
Definition at line 266 of file MyntAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), Viseme::AH, Viseme::AR, Mathematics::Constrain(), Viseme::EE, eEA, Viseme::ER, MicrophoneFourierBase::GetCurrentMagnitude(), MicrophoneFourierBase::GetFourierFiltered(), MicrophoneFourierBase::GetSampleRate(), FFTVoiceDetection< peakCount >::GetViseme(), Viseme::OO, talk, Viseme::UH, FFTVoiceDetection< peakCount >::Update(), and voiceDetection.
Referenced by Update().
UpdateKeyFrameTracks()
void UpdateKeyFrameTracks () inline
Definition at line 168 of file MyntAnimation.h.
References blink, and AnimationTrack< maxParameters, maxKeyFrames >::Update().
Referenced by Update().
Member Data Documentation
background
Background background private
Definition at line 35 of file MyntAnimation.h.
Referenced by MyntAnimation(), SpectrumAnalyzerFace(), and Update().
blink
BlinkTrack<1> blink private
Definition at line 57 of file MyntAnimation.h.
Referenced by Dead(), LinkParameters(), PacmanFace(), Sleepy(), SleepyZZZ(), SOSFace(), SpectrumAnalyzerFace(), Update(), and UpdateKeyFrameTracks().
blueFaceIndex
uint8_t blueFaceIndex = 53 private
Definition at line 75 of file MyntAnimation.h.
Referenced by ChangeInterpolationMethods(), LinkEasyEase(), Sleepy(), and SleepyZZZ().
blueFaceMix
float blueFaceMix = 0.0f private
Definition at line 72 of file MyntAnimation.h.
Referenced by LinkEasyEase(), and Update().
blueMaterial
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255)) private
Definition at line 45 of file MyntAnimation.h.
Referenced by MyntAnimation(), and SetMaterials().
boop
BoopSensor boop private
Definition at line 69 of file MyntAnimation.h.
Referenced by MyntAnimation(), and Update().
eEA
EasyEaseAnimator<30> eEA = EasyEaseAnimator<30>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f) private
Definition at line 39 of file MyntAnimation.h.
Referenced by Angry(), ChangeInterpolationMethods(), Dead(), Happy(), LinkEasyEase(), Love(), PacmanFace(), Sleepy(), SleepyZZZ(), SOSFace(), Update(), and UpdateFFTVisemes().
faceMaterial
CombineMaterial<5> faceMaterial private
Definition at line 52 of file MyntAnimation.h.
Referenced by MyntAnimation(), SetMaterials(), and Update().
fGenMatPacman
FunctionGenerator fGenMatPacman = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 0.4f) private
Definition at line 65 of file MyntAnimation.h.
Referenced by Update().
fGenMatPos
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f) private
Definition at line 59 of file MyntAnimation.h.
fGenMatScaleAnim
FunctionGenerator fGenMatScaleAnim = FunctionGenerator(FunctionGenerator::Sine, 1.0f, 2.0f, 1.3f) private
Definition at line 66 of file MyntAnimation.h.
Referenced by Update().
fGenMatScalePacman
FunctionGenerator fGenMatScalePacman = FunctionGenerator(FunctionGenerator::Sine, 1.0f, 1.2f, 2.8f) private
Definition at line 67 of file MyntAnimation.h.
Referenced by Update().
fGenMatXMove
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -3.5f, 3.5f, 2.3f) private
Definition at line 62 of file MyntAnimation.h.
Referenced by Update().
fGenMatYMove
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -3.5f, 3.5f, 2.7f) private
Definition at line 63 of file MyntAnimation.h.
Referenced by Update().
fGenRotation
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f) private
Definition at line 60 of file MyntAnimation.h.
fGenScale
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f) private
Definition at line 61 of file MyntAnimation.h.
greenMaterial
SimpleMaterial greenMaterial = SimpleMaterial(RGBColor(0, 255, 0)) private
Definition at line 44 of file MyntAnimation.h.
Referenced by SetMaterials().
hideFace
bool hideFace = false private
Definition at line 79 of file MyntAnimation.h.
Referenced by PacmanFace(), SleepyZZZ(), SOSFace(), SpectrumAnalyzerFace(), and Update().
pacman
MyntPacman pacman private
Definition at line 32 of file MyntAnimation.h.
Referenced by MyntAnimation(), PacmanFace(), and Update().
pacmanFood
MyntFood pacmanFood private
Definition at line 31 of file MyntAnimation.h.
Referenced by MyntAnimation(), PacmanFace(), and Update().
pinkFaceIndex
uint8_t pinkFaceIndex = 52 private
Definition at line 74 of file MyntAnimation.h.
Referenced by ChangeInterpolationMethods(), LinkEasyEase(), and Love().
pinkFaceMix
float pinkFaceMix = 0.0f private
Definition at line 71 of file MyntAnimation.h.
Referenced by LinkEasyEase(), and Update().
pinkMaterial
SimpleMaterial pinkMaterial = SimpleMaterial(RGBColor(255, 0, 255)) private
Definition at line 47 of file MyntAnimation.h.
Referenced by SetMaterials().
pM
MyntFace pM private
Definition at line 30 of file MyntAnimation.h.
Referenced by GetObject(), LinkEasyEase(), LinkParameters(), MyntAnimation(), SpectrumAnalyzerFace(), and Update().
rainbowNoise
RainbowNoise rainbowNoise private
Definition at line 42 of file MyntAnimation.h.
Referenced by SetMaterials(), and Update().
redFaceIndex
uint8_t redFaceIndex = 51 private
Definition at line 73 of file MyntAnimation.h.
Referenced by Angry(), ChangeInterpolationMethods(), Dead(), and LinkEasyEase().
redFaceMix
float redFaceMix = 0.0f private
Definition at line 70 of file MyntAnimation.h.
Referenced by LinkEasyEase(), and Update().
redMaterial
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0)) private
Definition at line 43 of file MyntAnimation.h.
Referenced by SetMaterials().
sA
SpectrumAnalyzer sA = SpectrumAnalyzer(Vector2D(250, 110), Vector2D(125, 60), true, true) private
Definition at line 54 of file MyntAnimation.h.
Referenced by MyntAnimation(), and Update().
sos
MyntSOS sos private
Definition at line 33 of file MyntAnimation.h.
Referenced by MyntAnimation(), SOSFace(), and Update().
talk
bool talk = true private
Definition at line 78 of file MyntAnimation.h.
Referenced by PacmanFace(), SleepyZZZ(), SOSFace(), SpectrumAnalyzerFace(), Update(), and UpdateFFTVisemes().
tealMaterial
SimpleMaterial tealMaterial = SimpleMaterial(RGBColor(34, 248, 251)) private
Definition at line 50 of file MyntAnimation.h.
Referenced by MyntAnimation().
voiceDetection
FFTVoiceDetection<128> voiceDetection private
Definition at line 77 of file MyntAnimation.h.
Referenced by UpdateFFTVisemes().
yellowMaterial
SimpleMaterial yellowMaterial = SimpleMaterial(RGBColor(255, 255, 0)) private
Definition at line 46 of file MyntAnimation.h.
Referenced by MyntAnimation().
zzz
MyntZZZ zzz private
Definition at line 34 of file MyntAnimation.h.
Referenced by MyntAnimation(), SleepyZZZ(), and Update().
The documentation for this class was generated from the following file:
MyntAnimation.h