VectorRunningAverageFilter< memory > Class Template Reference
VectorRunningAverageFilter< memory > Class Template Reference
Applies running average filtering independently to each component of a 3D vector.
#include <VectorRunningAverageFilter.h>
Public Member Functions
VectorRunningAverageFilter ()
Default constructor for VectorRunningAverageFilter.
VectorRunningAverageFilter (float gain)
Constructs a VectorRunningAverageFilter with a specified gain.
Vector3D Filter (Vector3D input)
Filters a 3D vector input using the running average filter.
Private Attributes
RunningAverageFilter< memory > X
Running average filter for the X component of the vector.
RunningAverageFilter< memory > Y
Running average filter for the Y component of the vector.
RunningAverageFilter< memory > Z
Running average filter for the Z component of the vector.
Detailed Description
template<size_t memory>
class VectorRunningAverageFilter< memory >
Applies running average filtering independently to each component of a 3D vector.
The VectorRunningAverageFilter class uses three RunningAverageFilter instances to process the X, Y, and Z components of a Vector3D, providing a smoothed output for noisy 3D data.
Template Parameters
memory The size of the memory buffer used for the running average filter.
Definition at line 28 of file VectorRunningAverageFilter.h.
Constructor & Destructor Documentation
VectorRunningAverageFilter() [1/2]
template<size_t memory> VectorRunningAverageFilter ()
Default constructor for VectorRunningAverageFilter.
Initializes the running average filters for each component with default parameters.
Definition at line 4 of file VectorRunningAverageFilter.cpp.
VectorRunningAverageFilter() [2/2]
template<size_t memory> VectorRunningAverageFilter (float gain)
Constructs a VectorRunningAverageFilter with a specified gain.
Initializes the running average filters for each component with the given gain value.
Parameters
gain The smoothing gain for the running average filter (range 0.0 to 1.0).
Definition at line 11 of file VectorRunningAverageFilter.cpp.
Member Function Documentation
Filter()
template<size_t memory> Vector3D Filter (Vector3D input)
Filters a 3D vector input using the running average filter.
Applies running average filtering independently to the X, Y, and Z components of the input vector.
Parameters
input The input Vector3D to filter.
Returns
The filtered Vector3D.
Definition at line 18 of file VectorRunningAverageFilter.cpp.
Referenced by BNO055::GetLocalAccelerationFiltered(), BNO055::GetLocalAngularVelocityFiltered(), and BNO055::Update().
Member Data Documentation
X
template<size_t memory> RunningAverageFilter<memory> X private
Running average filter for the X component of the vector.
Definition at line 30 of file VectorRunningAverageFilter.h.
Y
template<size_t memory> RunningAverageFilter<memory> Y private
Running average filter for the Y component of the vector.
Definition at line 31 of file VectorRunningAverageFilter.h.
Z
template<size_t memory> RunningAverageFilter<memory> Z private
Running average filter for the Z component of the vector.
Definition at line 32 of file VectorRunningAverageFilter.h.
The documentation for this class was generated from the following files:
VectorRunningAverageFilter.h
VectorRunningAverageFilter.cpp