Crash Class Reference
Crash Class Reference
#include <Crash.h>
Public Member Functions
Crash ()
void FadeIn (float stepRatio)
void FadeOut (float stepRatio)
void Update (float ratio)
Private Attributes
Light lights [6]
Object3D * objects [7]
Object3D protoDRV1Obj = Object3D(protoDRV1String, 150, 150)
Object3D initObj = Object3D(initString, 100, 100)
Object3D runningKernelObj = Object3D(runningKernelString, 260, 260)
Object3D loadingModulesObj = Object3D(loadingModulesString, 260, 260)
Object3D doneObj = Object3D(doneBootString, 200, 200)
Object3D cursorObj = Object3D(cursorString, 10, 10)
Object3D planeObj = Object3D(planeString, 150, 250)
ObjectDeformer planeDeformer = ObjectDeformer(&planeObj)
const int frames = 1260
Detailed Description
Definition at line 8 of file Crash.h.
Constructor & Destructor Documentation
Crash()
Crash () inline
Definition at line 24 of file Crash.h.
References cursorObj, doneObj, initObj, lights, loadingModulesObj, objects, planeObj, protoDRV1Obj, runningKernelObj, and Light::Set().
Member Function Documentation
FadeIn()
void FadeIn (float stepRatio) inline
Definition at line 43 of file Crash.h.
References Mathematics::CosineInterpolation(), and objects.
FadeOut()
void FadeOut (float stepRatio) inline
Definition at line 52 of file Crash.h.
References Mathematics::CosineInterpolation(), and objects.
Update()
void Update (float ratio) inline
Definition at line 61 of file Crash.h.
References Mathematics::Constrain(), frames, objects, and Object3D::ResetVertices().
Member Data Documentation
cursorObj
Object3D cursorObj = Object3D(cursorString, 10, 10) private
Definition at line 17 of file Crash.h.
Referenced by Crash().
doneObj
Object3D doneObj = Object3D(doneBootString, 200, 200) private
Definition at line 16 of file Crash.h.
Referenced by Crash().
frames
const int frames = 1260 private
Definition at line 21 of file Crash.h.
Referenced by Update().
initObj
Object3D initObj = Object3D(initString, 100, 100) private
Definition at line 13 of file Crash.h.
Referenced by Crash().
lights
Light lights[6] private
Definition at line 10 of file Crash.h.
Referenced by Crash().
loadingModulesObj
Object3D loadingModulesObj = Object3D(loadingModulesString, 260, 260) private
Definition at line 15 of file Crash.h.
Referenced by Crash().
objects
Object3D* objects[7] private
Definition at line 11 of file Crash.h.
Referenced by Crash(), FadeIn(), FadeOut(), and Update().
planeDeformer
ObjectDeformer planeDeformer = ObjectDeformer(&planeObj) private
Definition at line 20 of file Crash.h.
planeObj
Object3D planeObj = Object3D(planeString, 150, 250) private
Definition at line 19 of file Crash.h.
Referenced by Crash().
protoDRV1Obj
Object3D protoDRV1Obj = Object3D(protoDRV1String, 150, 150) private
Definition at line 12 of file Crash.h.
Referenced by Crash().
runningKernelObj
Object3D runningKernelObj = Object3D(runningKernelString, 260, 260) private
Definition at line 14 of file Crash.h.
Referenced by Crash().
The documentation for this class was generated from the following file:
Crash.h