HUB75DeltaCameraManager Class Reference
HUB75DeltaCameraManager Class Reference
#include <HUB75Cameras.h>
Public Member Functions
HUB75DeltaCameraManager ()
HUB75DeltaCameraManager ()
Public Member Functions inherited from CameraManager
CameraManager (CameraBase **cameras, uint8_t count)
Constructs a CameraManager object.
CameraBase ** GetCameras ()
Retrieves the array of CameraBase objects.
uint8_t GetCameraCount ()
Retrieves the count of cameras managed by the CameraManager.
Private Attributes
CameraLayout cameraLayout = CameraLayout(CameraLayout::ZForward, CameraLayout::YUp)
Transform camTransform = Transform(Vector3D(), Vector3D(0, 0, -500.0f), Vector3D(1, 1, 1))
PixelGroup< 2048 > camPixels = PixelGroup<2048>(Vector2D(192.0f, 96.0f), Vector2D(0.0f, 0.0f), 64)
Camera< 2048 > camMain = Camera<2048>(&camTransform, &cameraLayout, &camPixels)
Transform camSideTransformL = Transform(Vector3D(), Vector3D(204.0f, 0, -500.0f), Vector3D(1, 1, 1))
Transform camSideTransformR = Transform(Vector3D(0, 0, 0), Vector3D(204.0f, 0, -500.0f), Vector3D(1, 1, 1))
PixelGroup< 88 > camSidePixelsL = PixelGroup<88>(DeltaDisplayL)
PixelGroup< 88 > camSidePixelsR = PixelGroup<88>(DeltaDisplayR)
Camera< 88 > camSidePanelsL = Camera<88>(&camSideTransformL, &cameraLayout, &camSidePixelsL)
Camera< 88 > camSidePanelsR = Camera<88>(&camSideTransformR, &cameraLayout, &camSidePixelsR)
Additional Inherited Members
Protected Attributes inherited from CameraManager
CameraBase ** cameras
Array of pointers to CameraBase objects.
uint8_t count
Number of CameraBase objects managed.
Detailed Description
Definition at line 9 of file HUB75Cameras.h.
Constructor & Destructor Documentation
HUB75DeltaCameraManager() [1/2]
HUB75DeltaCameraManager () inline
Definition at line 17 of file HUB75Cameras.h.
References camMain.
HUB75DeltaCameraManager() [2/2]
HUB75DeltaCameraManager () inline
Definition at line 24 of file HUB75DeltaCameras.h.
References camMain, camSidePanelsL, and camSidePanelsR.
Member Data Documentation
cameraLayout
CameraLayout cameraLayout = CameraLayout(CameraLayout::ZForward, CameraLayout::YUp) private
Definition at line 11 of file HUB75Cameras.h.
camMain
Camera< 2048 > camMain = Camera<2048>(&camTransform, &cameraLayout, &camPixels) private
Definition at line 14 of file HUB75Cameras.h.
Referenced by HUB75DeltaCameraManager().
camPixels
PixelGroup< 2048 > camPixels = PixelGroup<2048>(Vector2D(192.0f, 96.0f), Vector2D(0.0f, 0.0f), 64) private
Definition at line 13 of file HUB75Cameras.h.
camSidePanelsL
Camera<88> camSidePanelsL = Camera<88>(&camSideTransformL, &cameraLayout, &camSidePixelsL) private
Definition at line 20 of file HUB75DeltaCameras.h.
Referenced by HUB75DeltaCameraManager().
camSidePanelsR
Camera<88> camSidePanelsR = Camera<88>(&camSideTransformR, &cameraLayout, &camSidePixelsR) private
Definition at line 21 of file HUB75DeltaCameras.h.
Referenced by HUB75DeltaCameraManager().
camSidePixelsL
PixelGroup<88> camSidePixelsL = PixelGroup<88>(DeltaDisplayL) private
Definition at line 17 of file HUB75DeltaCameras.h.
camSidePixelsR
PixelGroup<88> camSidePixelsR = PixelGroup<88>(DeltaDisplayR) private
Definition at line 18 of file HUB75DeltaCameras.h.
camSideTransformL
Transform camSideTransformL = Transform(Vector3D(), Vector3D(204.0f, 0, -500.0f), Vector3D(1, 1, 1)) private
Definition at line 14 of file HUB75DeltaCameras.h.
camSideTransformR
Transform camSideTransformR = Transform(Vector3D(0, 0, 0), Vector3D(204.0f, 0, -500.0f), Vector3D(1, 1, 1)) private
Definition at line 15 of file HUB75DeltaCameras.h.
camTransform
Transform camTransform = Transform(Vector3D(), Vector3D(0, 0, -500.0f), Vector3D(1, 1, 1)) private
Definition at line 12 of file HUB75Cameras.h.
The documentation for this class was generated from the following files:
HUB75Cameras.h
HUB75DeltaCameras.h