HertzzAnimation Class Reference
HertzzAnimation Class Reference
#include <HertzzAnimation.h>
Public Member Functions
HertzzAnimation ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
Object3D * GetObject ()
void Update (float ratio) override
Private Member Functions
void LinkEasyEase ()
void LinkParameters ()
void ChangeInterpolationMethods ()
void SetMaterialLayers ()
void UpdateKeyFrameTracks ()
void Default ()
void Squint ()
void Surprised ()
void Happy ()
void Sad ()
void Whoop ()
void Angry ()
void Blush ()
void SpectrumAnalyzerFace ()
void AudioReactiveGradientFace ()
void OscilloscopeFace ()
void UpdateFFTVisemes ()
void SetMaterialColor ()
Private Attributes
ProtoV2 pM
Background background
EasyEaseAnimator< 21 > eEA = EasyEaseAnimator<21>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f)
RainbowNoise rainbowNoise
RainbowSpiral rainbowSpiral
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0))
SimpleMaterial orangeMaterial = SimpleMaterial(RGBColor(255, 165, 0))
SimpleMaterial whiteMaterial = SimpleMaterial(RGBColor(255, 255, 255))
SimpleMaterial greenMaterial = SimpleMaterial(RGBColor(0, 255, 0))
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255))
SimpleMaterial yellowMaterial = SimpleMaterial(RGBColor(255, 255, 0))
SimpleMaterial purpleMaterial = SimpleMaterial(RGBColor(255, 0, 255))
RGBColor gradientSpectrum [2] = {RGBColor(5, 162, 232), RGBColor(10, 170, 255)}
GradientMaterial< 2 > gradientMat = GradientMaterial<2>(gradientSpectrum, 350.0f, false)
MaterialAnimator< 10 > materialAnimator
MaterialAnimator< 4 > backgroundMaterial
SpectrumAnalyzer sA = SpectrumAnalyzer(Vector2D(200, 100), Vector2D(100, 50), true, true)
AudioReactiveGradient aRG = AudioReactiveGradient(Vector2D(160, 160), Vector2D(0, 0), true, true)
Oscilloscope oSC = Oscilloscope(Vector2D(200, 100), Vector2D(0, 0))
BlinkTrack< 1 > blink
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f)
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f)
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f)
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 5.3f)
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 6.7f)
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f)
FunctionGenerator fGenMatXMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 1.1f)
FunctionGenerator fGenMatYMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 2.7f)
FunctionGenerator fGenMatRMenu = FunctionGenerator(FunctionGenerator::Sine, -5.0f, 5.0f, 1.7f)
FunctionGenerator sineSidePanel = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 3.0f)
APDS9960 boop
SSD1306 oledDisplay
FFTVoiceDetection< 128 > voiceDetection
float offsetFace = 0.0f
float offsetFaceSA = 0.0f
float offsetFaceARG = 0.0f
float offsetFaceOSC = 0.0f
uint8_t offsetFaceInd = 50
uint8_t offsetFaceIndSA = 51
uint8_t offsetFaceIndARG = 52
uint8_t offsetFaceIndOSC = 53
Detailed Description
Definition at line 30 of file HertzzAnimation.h.
Constructor & Destructor Documentation
HertzzAnimation()
HertzzAnimation () inline
Definition at line 246 of file HertzzAnimation.h.
References background, backgroundMaterial, boop, ChangeInterpolationMethods(), Menu::Initialize(), APDS9960::Initialize(), LinkEasyEase(), LinkParameters(), materialAnimator, oledDisplay, pM, and SetMaterialLayers().
Member Function Documentation
Angry()
void Angry () inline private
Definition at line 175 of file HertzzAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, and oledDisplay.
Referenced by Update().
AudioReactiveGradientFace()
void AudioReactiveGradientFace () inline private
Definition at line 194 of file HertzzAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), aRG, backgroundMaterial, eEA, offsetFaceARG, offsetFaceInd, offsetFaceIndARG, and oledDisplay.
Referenced by Update().
Blush()
void Blush () inline private
Definition at line 181 of file HertzzAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, and oledDisplay.
Referenced by Update().
ChangeInterpolationMethods()
void ChangeInterpolationMethods () inline private
Definition at line 110 of file HertzzAnimation.h.
References eEA, and EasyEaseAnimator< maxParameters >::SetInterpolationMethod().
Referenced by HertzzAnimation().
Default()
void Default () inline private
Definition at line 140 of file HertzzAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, and oledDisplay.
Referenced by Update().
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 267 of file HertzzAnimation.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 268 of file HertzzAnimation.h.
GetObject()
Object3D * GetObject () inline
Definition at line 270 of file HertzzAnimation.h.
References pM.
Happy()
void Happy () inline private
Definition at line 157 of file HertzzAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, and oledDisplay.
Referenced by Update().
LinkEasyEase()
void LinkEasyEase () inline private
Definition at line 87 of file HertzzAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameter(), eEA, offsetFace, offsetFaceARG, offsetFaceInd, offsetFaceIndARG, offsetFaceIndOSC, offsetFaceIndSA, offsetFaceOSC, offsetFaceSA, and pM.
Referenced by HertzzAnimation().
LinkParameters()
void LinkParameters () inline private
Definition at line 106 of file HertzzAnimation.h.
References AnimationTrack< maxParameters, maxKeyFrames >::AddParameter(), blink, and pM.
Referenced by HertzzAnimation().
OscilloscopeFace()
void OscilloscopeFace () inline private
Definition at line 202 of file HertzzAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), backgroundMaterial, eEA, offsetFaceInd, offsetFaceIndOSC, offsetFaceOSC, oledDisplay, and oSC.
Referenced by Update().
Sad()
void Sad () inline private
Definition at line 163 of file HertzzAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, and oledDisplay.
Referenced by Update().
SetMaterialColor()
void SetMaterialColor () inline private
Definition at line 230 of file HertzzAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), blueMaterial, Menu::GetFaceColor(), greenMaterial, materialAnimator, orangeMaterial, purpleMaterial, rainbowNoise, rainbowSpiral, redMaterial, whiteMaterial, and yellowMaterial.
Referenced by Update().
SetMaterialLayers()
void SetMaterialLayers () inline private
Definition at line 117 of file HertzzAnimation.h.
References Material::Add, MaterialAnimator< materialCount >::AddMaterial(), aRG, backgroundMaterial, blueMaterial, Menu::GetMaterial(), gradientMat, greenMaterial, Material::Lighten, materialAnimator, orangeMaterial, oSC, purpleMaterial, rainbowNoise, rainbowSpiral, redMaterial, Material::Replace, sA, MaterialAnimator< materialCount >::SetBaseMaterial(), whiteMaterial, and yellowMaterial.
Referenced by HertzzAnimation().
SpectrumAnalyzerFace()
void SpectrumAnalyzerFace () inline private
Definition at line 186 of file HertzzAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), backgroundMaterial, eEA, offsetFaceInd, offsetFaceIndSA, offsetFaceSA, oledDisplay, and sA.
Referenced by Update().
Squint()
void Squint () inline private
Definition at line 145 of file HertzzAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, and oledDisplay.
Referenced by Update().
Surprised()
void Surprised () inline private
Definition at line 151 of file HertzzAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, and oledDisplay.
Referenced by Update().
Update()
void Update (float ratio) inline override
Definition at line 274 of file HertzzAnimation.h.
References Angry(), aRG, AudioReactiveGradientFace(), backgroundMaterial, Blush(), boop, Default(), eEA, fGenMatXMove, fGenMatYMove, Menu::GetFaceSize(), Menu::GetFaceState(), Menu::GetMicLevel(), Happy(), APDS9960::isBooped(), materialAnimator, Menu::MirrorSpectrumAnalyzer(), offsetFaceSA, oSC, OscilloscopeFace(), pM, rainbowNoise, rainbowSpiral, sA, Sad(), SpectrumAnalyzer::SetFlipYState(), AudioReactiveGradient::SetHueAngle(), Oscilloscope::SetHueAngle(), SpectrumAnalyzer::SetHueAngle(), SetMaterialColor(), SpectrumAnalyzer::SetMirrorYState(), AudioReactiveGradient::SetPosition(), Oscilloscope::SetPosition(), AudioReactiveGradient::SetRadius(), AudioReactiveGradient::SetRotation(), AudioReactiveGradient::SetSize(), Oscilloscope::SetSize(), FFTVoiceDetection< peakCount >::SetThreshold(), Menu::ShowMenu(), sineSidePanel, SpectrumAnalyzerFace(), Squint(), Surprised(), MaterialAnimator< materialCount >::Update(), FunctionGenerator::Update(), EasyEaseAnimator< maxParameters >::Update(), Oscilloscope::Update(), AudioReactiveGradient::Update(), SpectrumAnalyzer::Update(), Menu::Update(), RainbowNoise::Update(), RainbowSpiral::Update(), UpdateFFTVisemes(), UpdateKeyFrameTracks(), Menu::UseBoopSensor(), voiceDetection, and Whoop().
UpdateFFTVisemes()
void UpdateFFTVisemes () inline private
Definition at line 210 of file HertzzAnimation.h.
References Menu::UseMicrophone().
Referenced by Update().
UpdateKeyFrameTracks()
void UpdateKeyFrameTracks () inline private
Definition at line 135 of file HertzzAnimation.h.
References blink, and AnimationTrack< maxParameters, maxKeyFrames >::Update().
Referenced by Update().
Whoop()
void Whoop () inline private
Definition at line 169 of file HertzzAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, and oledDisplay.
Referenced by Update().
Member Data Documentation
aRG
AudioReactiveGradient aRG = AudioReactiveGradient(Vector2D(160, 160), Vector2D(0, 0), true, true) private
Definition at line 54 of file HertzzAnimation.h.
Referenced by AudioReactiveGradientFace(), SetMaterialLayers(), and Update().
background
Background background private
Definition at line 33 of file HertzzAnimation.h.
Referenced by HertzzAnimation().
backgroundMaterial
MaterialAnimator<4> backgroundMaterial private
Definition at line 51 of file HertzzAnimation.h.
Referenced by AudioReactiveGradientFace(), HertzzAnimation(), OscilloscopeFace(), SetMaterialLayers(), SpectrumAnalyzerFace(), and Update().
blink
BlinkTrack<1> blink private
Definition at line 58 of file HertzzAnimation.h.
Referenced by LinkParameters(), and UpdateKeyFrameTracks().
blueMaterial
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255)) private
Definition at line 43 of file HertzzAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
boop
APDS9960 boop private
Definition at line 72 of file HertzzAnimation.h.
Referenced by HertzzAnimation(), and Update().
eEA
EasyEaseAnimator<21> eEA = EasyEaseAnimator<21>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f) private
Definition at line 34 of file HertzzAnimation.h.
Referenced by Angry(), AudioReactiveGradientFace(), Blush(), ChangeInterpolationMethods(), Default(), Happy(), LinkEasyEase(), OscilloscopeFace(), Sad(), SpectrumAnalyzerFace(), Squint(), Surprised(), Update(), and Whoop().
fGenMatHue
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f) private
Definition at line 65 of file HertzzAnimation.h.
fGenMatPos
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f) private
Definition at line 60 of file HertzzAnimation.h.
fGenMatRMenu
FunctionGenerator fGenMatRMenu = FunctionGenerator(FunctionGenerator::Sine, -5.0f, 5.0f, 1.7f) private
Definition at line 69 of file HertzzAnimation.h.
fGenMatXMenu
FunctionGenerator fGenMatXMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 1.1f) private
Definition at line 67 of file HertzzAnimation.h.
fGenMatXMove
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 5.3f) private
Definition at line 63 of file HertzzAnimation.h.
Referenced by Update().
fGenMatYMenu
FunctionGenerator fGenMatYMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 2.7f) private
Definition at line 68 of file HertzzAnimation.h.
fGenMatYMove
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 6.7f) private
Definition at line 64 of file HertzzAnimation.h.
Referenced by Update().
fGenRotation
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f) private
Definition at line 61 of file HertzzAnimation.h.
fGenScale
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f) private
Definition at line 62 of file HertzzAnimation.h.
gradientMat
GradientMaterial<2> gradientMat = GradientMaterial<2>(gradientSpectrum, 350.0f, false) private
Definition at line 48 of file HertzzAnimation.h.
Referenced by SetMaterialLayers().
gradientSpectrum
RGBColor gradientSpectrum[2] = {RGBColor(5, 162, 232), RGBColor(10, 170, 255)} private
Definition at line 47 of file HertzzAnimation.h.
greenMaterial
SimpleMaterial greenMaterial = SimpleMaterial(RGBColor(0, 255, 0)) private
Definition at line 42 of file HertzzAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
materialAnimator
MaterialAnimator<10> materialAnimator private
Definition at line 50 of file HertzzAnimation.h.
Referenced by HertzzAnimation(), SetMaterialColor(), SetMaterialLayers(), and Update().
offsetFace
float offsetFace = 0.0f private
Definition at line 78 of file HertzzAnimation.h.
Referenced by LinkEasyEase().
offsetFaceARG
float offsetFaceARG = 0.0f private
Definition at line 80 of file HertzzAnimation.h.
Referenced by AudioReactiveGradientFace(), and LinkEasyEase().
offsetFaceInd
uint8_t offsetFaceInd = 50 private
Definition at line 82 of file HertzzAnimation.h.
Referenced by AudioReactiveGradientFace(), LinkEasyEase(), OscilloscopeFace(), and SpectrumAnalyzerFace().
offsetFaceIndARG
uint8_t offsetFaceIndARG = 52 private
Definition at line 84 of file HertzzAnimation.h.
Referenced by AudioReactiveGradientFace(), and LinkEasyEase().
offsetFaceIndOSC
uint8_t offsetFaceIndOSC = 53 private
Definition at line 85 of file HertzzAnimation.h.
Referenced by LinkEasyEase(), and OscilloscopeFace().
offsetFaceIndSA
uint8_t offsetFaceIndSA = 51 private
Definition at line 83 of file HertzzAnimation.h.
Referenced by LinkEasyEase(), and SpectrumAnalyzerFace().
offsetFaceOSC
float offsetFaceOSC = 0.0f private
Definition at line 81 of file HertzzAnimation.h.
Referenced by LinkEasyEase(), and OscilloscopeFace().
offsetFaceSA
float offsetFaceSA = 0.0f private
Definition at line 79 of file HertzzAnimation.h.
Referenced by LinkEasyEase(), SpectrumAnalyzerFace(), and Update().
oledDisplay
SSD1306 oledDisplay private
Definition at line 74 of file HertzzAnimation.h.
Referenced by Angry(), AudioReactiveGradientFace(), Blush(), Default(), Happy(), HertzzAnimation(), OscilloscopeFace(), Sad(), SpectrumAnalyzerFace(), Squint(), Surprised(), and Whoop().
orangeMaterial
SimpleMaterial orangeMaterial = SimpleMaterial(RGBColor(255, 165, 0)) private
Definition at line 40 of file HertzzAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
oSC
Oscilloscope oSC = Oscilloscope(Vector2D(200, 100), Vector2D(0, 0)) private
Definition at line 55 of file HertzzAnimation.h.
Referenced by OscilloscopeFace(), SetMaterialLayers(), and Update().
pM
ProtoV2 pM private
Definition at line 32 of file HertzzAnimation.h.
Referenced by GetObject(), HertzzAnimation(), LinkEasyEase(), LinkParameters(), and Update().
purpleMaterial
SimpleMaterial purpleMaterial = SimpleMaterial(RGBColor(255, 0, 255)) private
Definition at line 45 of file HertzzAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
rainbowNoise
RainbowNoise rainbowNoise private
Definition at line 37 of file HertzzAnimation.h.
Referenced by SetMaterialColor(), SetMaterialLayers(), and Update().
rainbowSpiral
RainbowSpiral rainbowSpiral private
Definition at line 38 of file HertzzAnimation.h.
Referenced by SetMaterialColor(), SetMaterialLayers(), and Update().
redMaterial
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0)) private
Definition at line 39 of file HertzzAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
sA
SpectrumAnalyzer sA = SpectrumAnalyzer(Vector2D(200, 100), Vector2D(100, 50), true, true) private
Definition at line 53 of file HertzzAnimation.h.
Referenced by SetMaterialLayers(), SpectrumAnalyzerFace(), and Update().
sineSidePanel
FunctionGenerator sineSidePanel = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 3.0f) private
Definition at line 71 of file HertzzAnimation.h.
Referenced by Update().
voiceDetection
FFTVoiceDetection<128> voiceDetection private
Definition at line 76 of file HertzzAnimation.h.
Referenced by Update().
whiteMaterial
SimpleMaterial whiteMaterial = SimpleMaterial(RGBColor(255, 255, 255)) private
Definition at line 41 of file HertzzAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
yellowMaterial
SimpleMaterial yellowMaterial = SimpleMaterial(RGBColor(255, 255, 0)) private
Definition at line 44 of file HertzzAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
The documentation for this class was generated from the following file:
HertzzAnimation.h