FFT< fftSize > Class Template Reference
FFT< fftSize > Class Template Reference
A templated class for performing Fast Fourier Transform (FFT) operations.
#include <FFT.h>
Static Public Member Functions
static void Radix2FFT (float *data)
Performs a Radix-2 FFT on the provided data.
static void ComplexMagnitude (float *complexData, float *magnitude)
Computes the magnitude of complex numbers from interleaved real and imaginary components.
Static Private Member Functions
static constexpr int CalculateBits (int size, int count=0)
Calculates the number of bits required for bit reversal based on FFT size.
static void BitReverseOrder (float *data)
Reorders the data array in bit-reversed order.
static int ReverseBits (int num)
Reverses the bits of an integer.
static void Swap (float *a, float *b)
Swaps two floating-point values.
Static Private Attributes
static const constexpr float twiddleCoefficients [fftSize *2]
Precomputed twiddle coefficients for the FFT.
static const constexpr int bitCount = CalculateBits(fftSize)
The number of bits needed for bit reversal for this FFT size.
Detailed Description
template<int fftSize>
class FFT< fftSize >
A templated class for performing Fast Fourier Transform (FFT) operations.
Template Parameters
fftSize The size of the FFT, must be a power of 2.
Definition at line 20 of file FFT.h.
Member Function Documentation
BitReverseOrder()
template<int fftSize> static void BitReverseOrder (float * data) static private
Reorders the data array in bit-reversed order.
Parameters
data The data array to reorder.
CalculateBits()
template<int fftSize> static constexpr int CalculateBits (int size, int count = 0) static constexpr private
Calculates the number of bits required for bit reversal based on FFT size.
Parameters
size The FFT size.
count Recursive parameter to count the bits.
Returns
The number of bits required.
ComplexMagnitude()
template<int fftSize> static void ComplexMagnitude (float * complexData, float * magnitude) static
Computes the magnitude of complex numbers from interleaved real and imaginary components.
Parameters
complexData The input array containing interleaved real and imaginary components.
magnitude The output array for storing computed magnitudes.
Referenced by MicrophoneFourier::Update(), and MicrophoneFourier::UpdateDMA().
Radix2FFT()
template<int fftSize> static void Radix2FFT (float * data) static
Performs a Radix-2 FFT on the provided data.
Parameters
data The input array containing interleaved real and imaginary components.
Referenced by MicrophoneFourier::Update(), and MicrophoneFourier::UpdateDMA().
ReverseBits()
template<int fftSize> static int ReverseBits (int num) static private
Reverses the bits of an integer.
Parameters
num The number whose bits are to be reversed.
Returns
The bit-reversed integer.
Swap()
template<int fftSize> static void Swap (float * a, float * b) static private
Swaps two floating-point values.
Parameters
a Pointer to the first value.
b Pointer to the second value.
Member Data Documentation
bitCount
template<int fftSize> const constexpr int bitCount = CalculateBits(fftSize) static constexpr private
The number of bits needed for bit reversal for this FFT size.
Definition at line 46 of file FFT.h.
twiddleCoefficients
template<int fftSize> const constexpr float twiddleCoefficients[fftSize *2] static constexpr private
Initial value:
= [] {
        float temp[fftSize * 2];
        for (int i = 0; i < fftSize * 2; ++i) {
            temp[i] = FFT<fftSize>::calculateCoefficient(i);
        }
        return temp;
    }()
Precomputed twiddle coefficients for the FFT.
Definition at line 25 of file FFT.h.
The documentation for this class was generated from the following file:
FFT.h