DisplayTest Class Reference
DisplayTest Class Reference
Provides static methods for testing and verifying camera displays.
#include <DisplayTest.h>
Static Public Member Functions
static void FillWhite (CameraBase *camera)
Fills the camera display entirely with white pixels.
static void FillAltWhiteBlack (CameraBase *camera)
Fills the camera display with an alternating pattern of white and black pixels.
Detailed Description
Provides static methods for testing and verifying camera displays.
Definition at line 22 of file DisplayTest.h.
Member Function Documentation
FillAltWhiteBlack()
void FillAltWhiteBlack (CameraBase * camera) static
Fills the camera display with an alternating pattern of white and black pixels.
Parameters
camera Pointer to the CameraBase object representing the camera.
Definition at line 13 of file DisplayTest.cpp.
References RGBColor::B, RGBColor::G, IPixelGroup::GetColor(), CameraBase::GetPixelGroup(), and RGBColor::R.
FillWhite()
void FillWhite (CameraBase * camera) static
Fills the camera display entirely with white pixels.
Parameters
camera Pointer to the CameraBase object representing the camera.
Definition at line 3 of file DisplayTest.cpp.
References RGBColor::B, RGBColor::G, IPixelGroup::GetColor(), CameraBase::GetPixelGroup(), and RGBColor::R.
Referenced by RenderingEngine::DisplayWhite().
The documentation for this class was generated from the following files:
DisplayTest.h
DisplayTest.cpp