ElGatoAnimation Class Reference
ElGatoAnimation Class Reference
#include <ElGatoAnimation.h>
Public Member Functions
ElGatoAnimation ()
void UpdateKeyFrameTracks ()
void Default ()
void Default2 ()
void Angry ()
void Sad ()
void Surprised ()
void Doubt ()
void LookUp ()
void LookDown ()
void SpectrumAnalyzerFace ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
Object3D * GetObject ()
void UpdateFFTVisemes ()
void Update (float ratio) override
Private Member Functions
void LinkEasyEase ()
void LinkParameters ()
void ChangeInterpolationMethods ()
void SetMaterials ()
Private Attributes
NukudeFace pM
Background background
EasyEaseAnimator< 25 > eEA = EasyEaseAnimator<25>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f)
RainbowNoise rainbowNoise
RainbowSpiral rainbowSpiral
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0))
SimpleMaterial greenMaterial = SimpleMaterial(RGBColor(0, 255, 0))
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255))
SimpleMaterial pinkMaterial = SimpleMaterial(RGBColor(255, 0, 255))
SimpleMaterial yellowMaterial = SimpleMaterial(RGBColor(255, 255, 0))
RGBColor gradientSpectrum [4] = {RGBColor(0, 0, 255), RGBColor(0, 255, 0), RGBColor(255, 0, 0), RGBColor(255, 255, 0)}
GradientMaterial< 4 > gradientMat = GradientMaterial<4>(gradientSpectrum, 180.0f, false, true)
CombineMaterial< 8 > faceMaterial
SpectrumAnalyzer sA = SpectrumAnalyzer(22, Vector2D(250, 200), Vector2D(120, 100), true, true)
BlinkTrack< 1 > blink
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f)
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f)
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f)
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.5f, 2.5f, 5.3f)
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.5f, 2.5f, 6.7f)
BoopSensor boop
float rainbowFaceMix = 0.0f
float redFaceMix = 0.0f
float greenFaceMix = 0.0f
float blueFaceMix = 0.0f
float pinkFaceMix = 0.0f
float customFaceMix = 0.0f
uint8_t rainbowFaceIndex = 50
uint8_t redFaceIndex = 51
uint8_t greenFaceIndex = 52
uint8_t blueFaceIndex = 53
uint8_t pinkFaceIndex = 54
uint8_t customFaceIndex = 55
FFTVoiceDetection< 128 > voiceDetection
Detailed Description
Definition at line 23 of file ElGatoAnimation.h.
Constructor & Destructor Documentation
ElGatoAnimation()
ElGatoAnimation () inline
Definition at line 140 of file ElGatoAnimation.h.
References background, boop, ChangeInterpolationMethods(), faceMaterial, LinkEasyEase(), LinkParameters(), pM, sA, and SetMaterials().
Member Function Documentation
Angry()
void Angry () inline
Definition at line 171 of file ElGatoAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, and redFaceIndex.
Referenced by Update().
ChangeInterpolationMethods()
void ChangeInterpolationMethods () inline private
Definition at line 108 of file ElGatoAnimation.h.
References blueFaceIndex, customFaceIndex, eEA, greenFaceIndex, pinkFaceIndex, rainbowFaceIndex, redFaceIndex, and EasyEaseAnimator< maxParameters >::SetInterpolationMethod().
Referenced by ElGatoAnimation().
Default()
void Default () inline
Definition at line 163 of file ElGatoAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blueFaceIndex, and eEA.
Referenced by Update().
Default2()
void Default2 () inline
Definition at line 167 of file ElGatoAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), customFaceIndex, and eEA.
Referenced by Update().
Doubt()
void Doubt () inline
Definition at line 188 of file ElGatoAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, and greenFaceIndex.
Referenced by Update().
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 209 of file ElGatoAnimation.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 210 of file ElGatoAnimation.h.
GetObject()
Object3D * GetObject () inline
Definition at line 212 of file ElGatoAnimation.h.
References pM.
LinkEasyEase()
void LinkEasyEase () inline private
Definition at line 76 of file ElGatoAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameter(), blueFaceIndex, blueFaceMix, customFaceIndex, customFaceMix, eEA, greenFaceIndex, greenFaceMix, pinkFaceIndex, pinkFaceMix, pM, rainbowFaceIndex, rainbowFaceMix, redFaceIndex, and redFaceMix.
Referenced by ElGatoAnimation().
LinkParameters()
void LinkParameters () inline private
Definition at line 104 of file ElGatoAnimation.h.
References AnimationTrack< maxParameters, maxKeyFrames >::AddParameter(), blink, and pM.
Referenced by ElGatoAnimation().
LookDown()
void LookDown () inline
Definition at line 200 of file ElGatoAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
LookUp()
void LookUp () inline
Definition at line 194 of file ElGatoAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, and pinkFaceIndex.
Referenced by Update().
Sad()
void Sad () inline
Definition at line 176 of file ElGatoAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blueFaceIndex, and eEA.
Referenced by Update().
SetMaterials()
void SetMaterials () inline private
Definition at line 128 of file ElGatoAnimation.h.
References Material::Add, CombineMaterial< materialCount >::AddMaterial(), blueMaterial, faceMaterial, gradientMat, greenMaterial, pinkMaterial, rainbowNoise, rainbowSpiral, redMaterial, Material::Replace, and yellowMaterial.
Referenced by ElGatoAnimation().
SpectrumAnalyzerFace()
void SpectrumAnalyzerFace () inline
Definition at line 204 of file ElGatoAnimation.h.
References background, and pM.
Referenced by Update().
Surprised()
void Surprised () inline
Definition at line 182 of file ElGatoAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, and rainbowFaceIndex.
Referenced by Update().
Update()
void Update (float ratio) inline override
Definition at line 234 of file ElGatoAnimation.h.
References Angry(), background, blueFaceMix, boop, customFaceMix, Default(), Default2(), Doubt(), eEA, faceMaterial, fGenMatXMove, fGenMatYMove, MicrophoneFourierBase::GetFourierFiltered(), greenFaceMix, LookUp(), pinkFaceMix, pM, rainbowFaceMix, rainbowNoise, rainbowSpiral, redFaceMix, sA, Sad(), SpectrumAnalyzer::SetFlipYState(), SpectrumAnalyzer::SetHueAngle(), SpectrumAnalyzer::SetMirrorYState(), CombineMaterial< materialCount >::SetOpacity(), SpectrumAnalyzerFace(), Surprised(), MicrophoneFourier::Update(), FunctionGenerator::Update(), EasyEaseAnimator< maxParameters >::Update(), SpectrumAnalyzer::Update(), RainbowNoise::Update(), RainbowSpiral::Update(), UpdateFFTVisemes(), and UpdateKeyFrameTracks().
UpdateFFTVisemes()
void UpdateFFTVisemes () inline
Definition at line 216 of file ElGatoAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), Viseme::AH, Viseme::AR, Viseme::EE, eEA, Viseme::ER, MicrophoneFourierBase::GetCurrentMagnitude(), MicrophoneFourierBase::GetFourierFiltered(), MicrophoneFourierBase::GetSampleRate(), FFTVoiceDetection< peakCount >::GetViseme(), Viseme::OO, Viseme::UH, FFTVoiceDetection< peakCount >::Update(), and voiceDetection.
Referenced by Update().
UpdateKeyFrameTracks()
void UpdateKeyFrameTracks () inline
Definition at line 159 of file ElGatoAnimation.h.
References blink, and AnimationTrack< maxParameters, maxKeyFrames >::Update().
Referenced by Update().
Member Data Documentation
background
Background background private
Definition at line 26 of file ElGatoAnimation.h.
Referenced by ElGatoAnimation(), SpectrumAnalyzerFace(), and Update().
blink
BlinkTrack<1> blink private
Definition at line 52 of file ElGatoAnimation.h.
Referenced by LinkParameters(), and UpdateKeyFrameTracks().
blueFaceIndex
uint8_t blueFaceIndex = 53 private
Definition at line 70 of file ElGatoAnimation.h.
Referenced by ChangeInterpolationMethods(), Default(), LinkEasyEase(), and Sad().
blueFaceMix
float blueFaceMix = 0.0f private
Definition at line 64 of file ElGatoAnimation.h.
Referenced by LinkEasyEase(), and Update().
blueMaterial
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255)) private
Definition at line 34 of file ElGatoAnimation.h.
Referenced by SetMaterials().
boop
BoopSensor boop private
Definition at line 60 of file ElGatoAnimation.h.
Referenced by ElGatoAnimation(), and Update().
customFaceIndex
uint8_t customFaceIndex = 55 private
Definition at line 72 of file ElGatoAnimation.h.
Referenced by ChangeInterpolationMethods(), Default2(), and LinkEasyEase().
customFaceMix
float customFaceMix = 0.0f private
Definition at line 66 of file ElGatoAnimation.h.
Referenced by LinkEasyEase(), and Update().
eEA
EasyEaseAnimator<25> eEA = EasyEaseAnimator<25>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f) private
Definition at line 27 of file ElGatoAnimation.h.
Referenced by Angry(), ChangeInterpolationMethods(), Default(), Default2(), Doubt(), LinkEasyEase(), LookDown(), LookUp(), Sad(), Surprised(), Update(), and UpdateFFTVisemes().
faceMaterial
CombineMaterial<8> faceMaterial private
Definition at line 47 of file ElGatoAnimation.h.
Referenced by ElGatoAnimation(), SetMaterials(), and Update().
fGenMatPos
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f) private
Definition at line 54 of file ElGatoAnimation.h.
fGenMatXMove
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.5f, 2.5f, 5.3f) private
Definition at line 57 of file ElGatoAnimation.h.
Referenced by Update().
fGenMatYMove
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.5f, 2.5f, 6.7f) private
Definition at line 58 of file ElGatoAnimation.h.
Referenced by Update().
fGenRotation
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f) private
Definition at line 55 of file ElGatoAnimation.h.
fGenScale
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f) private
Definition at line 56 of file ElGatoAnimation.h.
gradientMat
GradientMaterial<4> gradientMat = GradientMaterial<4>(gradientSpectrum, 180.0f, false, true) private
Definition at line 45 of file ElGatoAnimation.h.
Referenced by SetMaterials().
gradientSpectrum
RGBColor gradientSpectrum[4] = {RGBColor(0, 0, 255), RGBColor(0, 255, 0), RGBColor(255, 0, 0), RGBColor(255, 255, 0)} private
Definition at line 44 of file ElGatoAnimation.h.
greenFaceIndex
uint8_t greenFaceIndex = 52 private
Definition at line 69 of file ElGatoAnimation.h.
Referenced by ChangeInterpolationMethods(), Doubt(), and LinkEasyEase().
greenFaceMix
float greenFaceMix = 0.0f private
Definition at line 63 of file ElGatoAnimation.h.
Referenced by LinkEasyEase(), and Update().
greenMaterial
SimpleMaterial greenMaterial = SimpleMaterial(RGBColor(0, 255, 0)) private
Definition at line 33 of file ElGatoAnimation.h.
Referenced by SetMaterials().
pinkFaceIndex
uint8_t pinkFaceIndex = 54 private
Definition at line 71 of file ElGatoAnimation.h.
Referenced by ChangeInterpolationMethods(), LinkEasyEase(), and LookUp().
pinkFaceMix
float pinkFaceMix = 0.0f private
Definition at line 65 of file ElGatoAnimation.h.
Referenced by LinkEasyEase(), and Update().
pinkMaterial
SimpleMaterial pinkMaterial = SimpleMaterial(RGBColor(255, 0, 255)) private
Definition at line 35 of file ElGatoAnimation.h.
Referenced by SetMaterials().
pM
NukudeFace pM private
Definition at line 25 of file ElGatoAnimation.h.
Referenced by ElGatoAnimation(), GetObject(), LinkEasyEase(), LinkParameters(), SpectrumAnalyzerFace(), and Update().
rainbowFaceIndex
uint8_t rainbowFaceIndex = 50 private
Definition at line 67 of file ElGatoAnimation.h.
Referenced by ChangeInterpolationMethods(), LinkEasyEase(), and Surprised().
rainbowFaceMix
float rainbowFaceMix = 0.0f private
Definition at line 61 of file ElGatoAnimation.h.
Referenced by LinkEasyEase(), and Update().
rainbowNoise
RainbowNoise rainbowNoise private
Definition at line 30 of file ElGatoAnimation.h.
Referenced by SetMaterials(), and Update().
rainbowSpiral
RainbowSpiral rainbowSpiral private
Definition at line 31 of file ElGatoAnimation.h.
Referenced by SetMaterials(), and Update().
redFaceIndex
uint8_t redFaceIndex = 51 private
Definition at line 68 of file ElGatoAnimation.h.
Referenced by Angry(), ChangeInterpolationMethods(), and LinkEasyEase().
redFaceMix
float redFaceMix = 0.0f private
Definition at line 62 of file ElGatoAnimation.h.
Referenced by LinkEasyEase(), and Update().
redMaterial
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0)) private
Definition at line 32 of file ElGatoAnimation.h.
Referenced by SetMaterials().
sA
SpectrumAnalyzer sA = SpectrumAnalyzer(22, Vector2D(250, 200), Vector2D(120, 100), true, true) private
Definition at line 49 of file ElGatoAnimation.h.
Referenced by ElGatoAnimation(), and Update().
voiceDetection
FFTVoiceDetection<128> voiceDetection private
Definition at line 74 of file ElGatoAnimation.h.
Referenced by UpdateFFTVisemes().
yellowMaterial
SimpleMaterial yellowMaterial = SimpleMaterial(RGBColor(255, 255, 0)) private
Definition at line 36 of file ElGatoAnimation.h.
Referenced by SetMaterials().
The documentation for this class was generated from the following file:
ElGatoAnimation.h