AlphaAnimation Class Reference
AlphaAnimation Class Reference
#include <AlphaProject.h>
Public Member Functions
AlphaAnimation ()
void Initialize () override
void UpdateKeyFrameTracks ()
void Default ()
void OwO ()
void Sad ()
void Dead ()
void Heart ()
void OwO2 ()
void AlphaGenSquare ()
void AlphaGenCircle ()
void HideAll ()
void SpyroDisplay (float ratio, bool normal)
void AngryFace ()
void SpectrumAnalyzerDisplay ()
void AudioReactiveGradientDisplay ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
Object3D * GetObject ()
void UpdateFFTVisemes ()
void Update (float ratio) override
Public Attributes
float offset = 0.0f
Private Member Functions
void SetMaterialLayers ()
void LinkEasyEase ()
void LinkParameters ()
void AddBlinkKeyFrames ()
void AddTopFinKeyFrames ()
void AddMidFinKeyFrames ()
void AddBotFinKeyFrames ()
void AddMouthKeyFrames ()
Private Attributes
ProtoDR pM
Background background
Spyro spyro
EasyEaseAnimator< 30 > eEA = EasyEaseAnimator<30>(EasyEaseInterpolation::Cosine)
RGBColor gradientSpectrum [6] = {RGBColor(255, 0, 0), RGBColor(255, 255, 0), RGBColor(0, 255, 0), RGBColor(0, 255, 255), RGBColor(0, 0, 255), RGBColor(255, 0, 255)}
RainbowNoise rainbowNoise
RainbowSpiral rainbowSpiral
StripeMaterial stripe1 = StripeMaterial(6, gradientSpectrum, 200.0f, 160.0f, 20.0f)
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0))
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255))
SimpleMaterial blackMaterial = SimpleMaterial(RGBColor(0,0,0))
NormalMaterial normalMaterial
GradientMaterial< 6 > gradientMat = GradientMaterial<6>(gradientSpectrum, 350.0f, false)
MaterialAnimator< 7 > materialAnimator
SpectrumAnalyzer sA = SpectrumAnalyzer(Vector2D(430, 300), Vector2D(15, 120), true, true)
AudioReactiveGradient aRG = AudioReactiveGradient(Vector2D(250, 250), Vector2D(15, 120), true, true)
FunctionGenerator fGenMatSize = FunctionGenerator(FunctionGenerator::Sine, 450.0f, 550.0f, 2.1f)
FunctionGenerator fGenMatWidth = FunctionGenerator(FunctionGenerator::Sine, 150.0f, 500.0f, 4.0f)
FunctionGenerator fGenMatPeriod = FunctionGenerator(FunctionGenerator::Sine, 200.0f, 500.0f, 6.3f)
FunctionGenerator fGenMatAmplitude = FunctionGenerator(FunctionGenerator::Sine, -100.0f, 100.0f, 2.7f)
FunctionGenerator fGenMatOpacity = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 0.5f)
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f)
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f)
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f)
KeyFrameTrack< 1, 10 > blink = KeyFrameTrack<1, 10>(0.0f, 1.0f, KeyFrameInterpolation::Cosine)
KeyFrameTrack< 1, 5 > topFinOuter = KeyFrameTrack<1, 5>(0.0f, 1.0f, KeyFrameInterpolation::Cosine)
KeyFrameTrack< 1, 5 > topFinInner = KeyFrameTrack<1, 5>(0.0f, 1.0f, KeyFrameInterpolation::Cosine)
KeyFrameTrack< 1, 5 > topFinGap = KeyFrameTrack<1, 5>(0.0f, 1.0f, KeyFrameInterpolation::Cosine)
KeyFrameTrack< 1, 5 > midFin = KeyFrameTrack<1, 5>(0.0f, 1.0f, KeyFrameInterpolation::Cosine)
KeyFrameTrack< 1, 10 > botFinLR1 = KeyFrameTrack<1, 10>(0.0f, 1.0f, KeyFrameInterpolation::Cosine)
KeyFrameTrack< 1, 10 > botFinLR2 = KeyFrameTrack<1, 10>(0.0f, 1.0f, KeyFrameInterpolation::Cosine)
KeyFrameTrack< 1, 10 > botFinLR3 = KeyFrameTrack<1, 10>(0.0f, 1.0f, KeyFrameInterpolation::Cosine)
KeyFrameTrack< 1, 10 > botFinLR4 = KeyFrameTrack<1, 10>(0.0f, 1.0f, KeyFrameInterpolation::Cosine)
KeyFrameTrack< 1, 10 > botFinLR5 = KeyFrameTrack<1, 10>(0.0f, 1.0f, KeyFrameInterpolation::Cosine)
KeyFrameTrack< 1, 5 > mouth = KeyFrameTrack<1, 5>(0.0f, 1.0f, KeyFrameInterpolation::Cosine)
FFTVoiceDetection< 128 > voiceDetection
bool talk = true
Detailed Description
Definition at line 28 of file AlphaProject.h.
Constructor & Destructor Documentation
AlphaAnimation()
AlphaAnimation () inline
Definition at line 216 of file AlphaProject.h.
References AddBlinkKeyFrames(), AddBotFinKeyFrames(), AddMidFinKeyFrames(), AddMouthKeyFrames(), AddTopFinKeyFrames(), background, LinkEasyEase(), LinkParameters(), materialAnimator, pM, sA, SetMaterialLayers(), and spyro.
Member Function Documentation
AddBlinkKeyFrames()
void AddBlinkKeyFrames () inline private
Definition at line 133 of file AlphaProject.h.
References KeyFrameTrack< maxParameters, maxKeyFrames >::AddKeyFrame(), and blink.
Referenced by AlphaAnimation().
AddBotFinKeyFrames()
void AddBotFinKeyFrames () inline private
Definition at line 171 of file AlphaProject.h.
References KeyFrameTrack< maxParameters, maxKeyFrames >::AddKeyFrame(), botFinLR1, botFinLR2, botFinLR3, botFinLR4, and botFinLR5.
Referenced by AlphaAnimation().
AddMidFinKeyFrames()
void AddMidFinKeyFrames () inline private
Definition at line 165 of file AlphaProject.h.
References KeyFrameTrack< maxParameters, maxKeyFrames >::AddKeyFrame(), and midFin.
Referenced by AlphaAnimation().
AddMouthKeyFrames()
void AddMouthKeyFrames () inline private
Definition at line 209 of file AlphaProject.h.
References KeyFrameTrack< maxParameters, maxKeyFrames >::AddKeyFrame(), and mouth.
Referenced by AlphaAnimation().
AddTopFinKeyFrames()
void AddTopFinKeyFrames () inline private
Definition at line 147 of file AlphaProject.h.
References KeyFrameTrack< maxParameters, maxKeyFrames >::AddKeyFrame(), topFinGap, topFinInner, and topFinOuter.
Referenced by AlphaAnimation().
AlphaGenCircle()
void AlphaGenCircle () inline
Definition at line 447 of file AlphaProject.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, botFinLR1, botFinLR2, botFinLR3, botFinLR4, botFinLR5, eEA, midFin, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Pause(), pM, KeyFrameTrack< maxParameters, maxKeyFrames >::Reset(), talk, topFinGap, topFinInner, and topFinOuter.
AlphaGenSquare()
void AlphaGenSquare () inline
Definition at line 411 of file AlphaProject.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, botFinLR1, botFinLR2, botFinLR3, botFinLR4, botFinLR5, eEA, midFin, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Pause(), pM, KeyFrameTrack< maxParameters, maxKeyFrames >::Reset(), talk, topFinGap, topFinInner, and topFinOuter.
Referenced by Update().
AngryFace()
void AngryFace () inline
Definition at line 548 of file AlphaProject.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, botFinLR1, botFinLR2, botFinLR3, botFinLR4, botFinLR5, eEA, materialAnimator, midFin, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Pause(), pM, redMaterial, KeyFrameTrack< maxParameters, maxKeyFrames >::Reset(), talk, topFinGap, topFinInner, and topFinOuter.
Referenced by Update().
AudioReactiveGradientDisplay()
void AudioReactiveGradientDisplay () inline
Definition at line 627 of file AlphaProject.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), aRG, background, blackMaterial, blink, botFinLR1, botFinLR2, botFinLR3, botFinLR4, botFinLR5, eEA, materialAnimator, midFin, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Pause(), pM, KeyFrameTrack< maxParameters, maxKeyFrames >::Reset(), talk, topFinGap, topFinInner, and topFinOuter.
Referenced by Update().
Dead()
void Dead () inline
Definition at line 325 of file AlphaProject.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, botFinLR1, botFinLR2, botFinLR3, botFinLR4, botFinLR5, eEA, materialAnimator, midFin, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Pause(), KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, redMaterial, KeyFrameTrack< maxParameters, maxKeyFrames >::Reset(), talk, topFinGap, topFinInner, and topFinOuter.
Referenced by Update().
Default()
void Default () inline
Definition at line 258 of file AlphaProject.h.
References blink, botFinLR1, botFinLR2, botFinLR3, botFinLR4, botFinLR5, midFin, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, talk, topFinGap, topFinInner, and topFinOuter.
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 667 of file AlphaProject.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 668 of file AlphaProject.h.
GetObject()
Object3D * GetObject () inline
Definition at line 670 of file AlphaProject.h.
References pM.
Heart()
void Heart () inline
Definition at line 350 of file AlphaProject.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, botFinLR1, botFinLR2, botFinLR3, botFinLR4, botFinLR5, eEA, materialAnimator, midFin, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Pause(), KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, rainbowSpiral, KeyFrameTrack< maxParameters, maxKeyFrames >::Reset(), talk, topFinGap, topFinInner, and topFinOuter.
Referenced by Update().
HideAll()
void HideAll () inline
Definition at line 483 of file AlphaProject.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blackMaterial, blink, botFinLR1, botFinLR2, botFinLR3, botFinLR4, botFinLR5, eEA, materialAnimator, midFin, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Pause(), pM, KeyFrameTrack< maxParameters, maxKeyFrames >::Reset(), talk, topFinGap, topFinInner, and topFinOuter.
Referenced by Update().
Initialize()
void Initialize () inline override
Definition at line 236 of file AlphaProject.h.
References SerialSync::Initialize(), and MicrophoneFourier::Initialize().
LinkEasyEase()
void LinkEasyEase () inline private
Definition at line 88 of file AlphaProject.h.
References EasyEaseAnimator< maxParameters >::AddParameter(), eEA, and pM.
Referenced by AlphaAnimation().
LinkParameters()
void LinkParameters () inline private
Definition at line 113 of file AlphaProject.h.
References KeyFrameTrack< maxParameters, maxKeyFrames >::AddParameter(), blink, botFinLR1, botFinLR2, botFinLR3, botFinLR4, botFinLR5, midFin, mouth, pM, topFinGap, topFinInner, and topFinOuter.
Referenced by AlphaAnimation().
OwO()
void OwO () inline
Definition at line 276 of file AlphaProject.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, botFinLR1, botFinLR2, botFinLR3, botFinLR4, botFinLR5, eEA, midFin, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Pause(), KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, KeyFrameTrack< maxParameters, maxKeyFrames >::Reset(), talk, topFinGap, topFinInner, and topFinOuter.
Referenced by Update().
OwO2()
void OwO2 () inline
Definition at line 375 of file AlphaProject.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, botFinLR1, botFinLR2, botFinLR3, botFinLR4, botFinLR5, eEA, materialAnimator, midFin, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Pause(), pM, KeyFrameTrack< maxParameters, maxKeyFrames >::Reset(), stripe1, talk, topFinGap, topFinInner, and topFinOuter.
Referenced by Update().
Sad()
void Sad () inline
Definition at line 300 of file AlphaProject.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, blueMaterial, botFinLR1, botFinLR2, botFinLR3, botFinLR4, botFinLR5, eEA, materialAnimator, midFin, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Pause(), KeyFrameTrack< maxParameters, maxKeyFrames >::Play(), pM, KeyFrameTrack< maxParameters, maxKeyFrames >::Reset(), talk, topFinGap, topFinInner, and topFinOuter.
Referenced by Update().
SetMaterialLayers()
void SetMaterialLayers () inline private
Definition at line 78 of file AlphaProject.h.
References Material::Add, MaterialAnimator< materialCount >::AddMaterial(), blueMaterial, gradientMat, Material::Lighten, materialAnimator, normalMaterial, rainbowNoise, rainbowSpiral, redMaterial, Material::Replace, MaterialAnimator< materialCount >::SetBaseMaterial(), and stripe1.
Referenced by AlphaAnimation().
SpectrumAnalyzerDisplay()
void SpectrumAnalyzerDisplay () inline
Definition at line 587 of file AlphaProject.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), background, blackMaterial, blink, botFinLR1, botFinLR2, botFinLR3, botFinLR4, botFinLR5, eEA, materialAnimator, midFin, mouth, KeyFrameTrack< maxParameters, maxKeyFrames >::Pause(), pM, KeyFrameTrack< maxParameters, maxKeyFrames >::Reset(), sA, talk, topFinGap, topFinInner, and topFinOuter.
Referenced by Update().
SpyroDisplay()
void SpyroDisplay (float ratio, bool normal) inline
Definition at line 521 of file AlphaProject.h.
References EulerConstants::EulerOrderXZYS, fGenRotation, fGenScale, Rotation::GetQuaternion(), normalMaterial, pM, spyro, talk, and FunctionGenerator::Update().
Referenced by Update().
Update()
void Update (float ratio) inline override
MenuButtonHandler::MirrorSpectrumAnalyzer());
Definition at line 694 of file AlphaProject.h.
References AlphaGenSquare(), AngryFace(), aRG, AudioReactiveGradientDisplay(), background, Dead(), eEA, fGenMatAmplitude, fGenMatPeriod, fGenMatPos, fGenMatWidth, MicrophoneFourierBase::GetCurrentMagnitude(), MicrophoneFourierBase::GetFourierFiltered(), SerialSync::GetMode(), SerialSync::GetMouthMove(), SerialSync::GetRatio(), Heart(), HideAll(), Mathematics::Map(), materialAnimator, offset, OwO(), OwO2(), pM, rainbowNoise, rainbowSpiral, SerialSync::Read(), sA, Sad(), SerialSync::Send(), SpectrumAnalyzer::SetFlipYState(), AudioReactiveGradient::SetHueAngle(), SpectrumAnalyzer::SetHueAngle(), SpectrumAnalyzer::SetMirrorYState(), SerialSync::SetMode(), SerialSync::SetMouthMove(), AudioReactiveGradient::SetPosition(), StripeMaterial::SetPositionOffset(), SerialSync::SetRatio(), AudioReactiveGradient::SetRotation(), SpectrumAnalyzer::SetRotation(), StripeMaterial::SetRotationAngle(), StripeMaterial::SetStripeWidth(), StripeMaterial::SetWaveAmplitude(), StripeMaterial::SetWavePeriod(), SpectrumAnalyzerDisplay(), spyro, SpyroDisplay(), stripe1, MicrophoneFourier::Update(), MaterialAnimator< materialCount >::Update(), FunctionGenerator::Update(), EasyEaseAnimator< maxParameters >::Update(), AudioReactiveGradient::Update(), SpectrumAnalyzer::Update(), RainbowNoise::Update(), RainbowSpiral::Update(), UpdateFFTVisemes(), and UpdateKeyFrameTracks().
UpdateFFTVisemes()
void UpdateFFTVisemes () inline
Definition at line 676 of file AlphaProject.h.
References MicrophoneFourierBase::GetCurrentMagnitude(), MicrophoneFourierBase::GetFourierFiltered(), MicrophoneFourierBase::GetSampleRate(), FFTVoiceDetection< peakCount >::Update(), and voiceDetection.
Referenced by Update().
UpdateKeyFrameTracks()
void UpdateKeyFrameTracks () inline
Definition at line 244 of file AlphaProject.h.
References blink, botFinLR1, botFinLR2, botFinLR3, botFinLR4, botFinLR5, midFin, mouth, topFinGap, topFinInner, topFinOuter, and KeyFrameTrack< maxParameters, maxKeyFrames >::Update().
Referenced by Update().
Member Data Documentation
aRG
AudioReactiveGradient aRG = AudioReactiveGradient(Vector2D(250, 250), Vector2D(15, 120), true, true) private
Definition at line 51 of file AlphaProject.h.
Referenced by AudioReactiveGradientDisplay(), and Update().
background
Background background private
Definition at line 31 of file AlphaProject.h.
Referenced by AlphaAnimation(), AudioReactiveGradientDisplay(), SpectrumAnalyzerDisplay(), and Update().
blackMaterial
SimpleMaterial blackMaterial = SimpleMaterial(RGBColor(0,0,0)) private
Definition at line 43 of file AlphaProject.h.
Referenced by AudioReactiveGradientDisplay(), HideAll(), and SpectrumAnalyzerDisplay().
blink
KeyFrameTrack<1, 10> blink = KeyFrameTrack<1, 10>(0.0f, 1.0f, KeyFrameInterpolation::Cosine) private
Definition at line 62 of file AlphaProject.h.
Referenced by AddBlinkKeyFrames(), AlphaGenCircle(), AlphaGenSquare(), AngryFace(), AudioReactiveGradientDisplay(), Dead(), Default(), Heart(), HideAll(), LinkParameters(), OwO(), OwO2(), Sad(), SpectrumAnalyzerDisplay(), and UpdateKeyFrameTracks().
blueMaterial
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255)) private
Definition at line 42 of file AlphaProject.h.
Referenced by Sad(), and SetMaterialLayers().
botFinLR1
KeyFrameTrack<1, 10> botFinLR1 = KeyFrameTrack<1, 10>(0.0f, 1.0f, KeyFrameInterpolation::Cosine) private
Definition at line 67 of file AlphaProject.h.
Referenced by AddBotFinKeyFrames(), AlphaGenCircle(), AlphaGenSquare(), AngryFace(), AudioReactiveGradientDisplay(), Dead(), Default(), Heart(), HideAll(), LinkParameters(), OwO(), OwO2(), Sad(), SpectrumAnalyzerDisplay(), and UpdateKeyFrameTracks().
botFinLR2
KeyFrameTrack<1, 10> botFinLR2 = KeyFrameTrack<1, 10>(0.0f, 1.0f, KeyFrameInterpolation::Cosine) private
Definition at line 68 of file AlphaProject.h.
Referenced by AddBotFinKeyFrames(), AlphaGenCircle(), AlphaGenSquare(), AngryFace(), AudioReactiveGradientDisplay(), Dead(), Default(), Heart(), HideAll(), LinkParameters(), OwO(), OwO2(), Sad(), SpectrumAnalyzerDisplay(), and UpdateKeyFrameTracks().
botFinLR3
KeyFrameTrack<1, 10> botFinLR3 = KeyFrameTrack<1, 10>(0.0f, 1.0f, KeyFrameInterpolation::Cosine) private
Definition at line 69 of file AlphaProject.h.
Referenced by AddBotFinKeyFrames(), AlphaGenCircle(), AlphaGenSquare(), AngryFace(), AudioReactiveGradientDisplay(), Dead(), Default(), Heart(), HideAll(), LinkParameters(), OwO(), OwO2(), Sad(), SpectrumAnalyzerDisplay(), and UpdateKeyFrameTracks().
botFinLR4
KeyFrameTrack<1, 10> botFinLR4 = KeyFrameTrack<1, 10>(0.0f, 1.0f, KeyFrameInterpolation::Cosine) private
Definition at line 70 of file AlphaProject.h.
Referenced by AddBotFinKeyFrames(), AlphaGenCircle(), AlphaGenSquare(), AngryFace(), AudioReactiveGradientDisplay(), Dead(), Default(), Heart(), HideAll(), LinkParameters(), OwO(), OwO2(), Sad(), SpectrumAnalyzerDisplay(), and UpdateKeyFrameTracks().
botFinLR5
KeyFrameTrack<1, 10> botFinLR5 = KeyFrameTrack<1, 10>(0.0f, 1.0f, KeyFrameInterpolation::Cosine) private
Definition at line 71 of file AlphaProject.h.
Referenced by AddBotFinKeyFrames(), AlphaGenCircle(), AlphaGenSquare(), AngryFace(), AudioReactiveGradientDisplay(), Dead(), Default(), Heart(), HideAll(), LinkParameters(), OwO(), OwO2(), Sad(), SpectrumAnalyzerDisplay(), and UpdateKeyFrameTracks().
eEA
EasyEaseAnimator<30> eEA = EasyEaseAnimator<30>(EasyEaseInterpolation::Cosine) private
Definition at line 33 of file AlphaProject.h.
Referenced by AlphaGenCircle(), AlphaGenSquare(), AngryFace(), AudioReactiveGradientDisplay(), Dead(), Heart(), HideAll(), LinkEasyEase(), OwO(), OwO2(), Sad(), SpectrumAnalyzerDisplay(), and Update().
fGenMatAmplitude
FunctionGenerator fGenMatAmplitude = FunctionGenerator(FunctionGenerator::Sine, -100.0f, 100.0f, 2.7f) private
Definition at line 56 of file AlphaProject.h.
Referenced by Update().
fGenMatOpacity
FunctionGenerator fGenMatOpacity = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 0.5f) private
Definition at line 57 of file AlphaProject.h.
fGenMatPeriod
FunctionGenerator fGenMatPeriod = FunctionGenerator(FunctionGenerator::Sine, 200.0f, 500.0f, 6.3f) private
Definition at line 55 of file AlphaProject.h.
Referenced by Update().
fGenMatPos
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f) private
Definition at line 58 of file AlphaProject.h.
Referenced by Update().
fGenMatSize
FunctionGenerator fGenMatSize = FunctionGenerator(FunctionGenerator::Sine, 450.0f, 550.0f, 2.1f) private
Definition at line 53 of file AlphaProject.h.
fGenMatWidth
FunctionGenerator fGenMatWidth = FunctionGenerator(FunctionGenerator::Sine, 150.0f, 500.0f, 4.0f) private
Definition at line 54 of file AlphaProject.h.
Referenced by Update().
fGenRotation
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f) private
Definition at line 59 of file AlphaProject.h.
Referenced by SpyroDisplay().
fGenScale
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f) private
Definition at line 60 of file AlphaProject.h.
Referenced by SpyroDisplay().
gradientMat
GradientMaterial<6> gradientMat = GradientMaterial<6>(gradientSpectrum, 350.0f, false) private
Definition at line 46 of file AlphaProject.h.
Referenced by SetMaterialLayers().
gradientSpectrum
RGBColor gradientSpectrum[6] = {RGBColor(255, 0, 0), RGBColor(255, 255, 0), RGBColor(0, 255, 0), RGBColor(0, 255, 255), RGBColor(0, 0, 255), RGBColor(255, 0, 255)} private
Definition at line 36 of file AlphaProject.h.
materialAnimator
MaterialAnimator<7> materialAnimator private
Definition at line 48 of file AlphaProject.h.
Referenced by AlphaAnimation(), AngryFace(), AudioReactiveGradientDisplay(), Dead(), Heart(), HideAll(), OwO2(), Sad(), SetMaterialLayers(), SpectrumAnalyzerDisplay(), and Update().
midFin
KeyFrameTrack<1, 5> midFin = KeyFrameTrack<1, 5>(0.0f, 1.0f, KeyFrameInterpolation::Cosine) private
Definition at line 66 of file AlphaProject.h.
Referenced by AddMidFinKeyFrames(), AlphaGenCircle(), AlphaGenSquare(), AngryFace(), AudioReactiveGradientDisplay(), Dead(), Default(), Heart(), HideAll(), LinkParameters(), OwO(), OwO2(), Sad(), SpectrumAnalyzerDisplay(), and UpdateKeyFrameTracks().
mouth
KeyFrameTrack<1, 5> mouth = KeyFrameTrack<1, 5>(0.0f, 1.0f, KeyFrameInterpolation::Cosine) private
Definition at line 72 of file AlphaProject.h.
Referenced by AddMouthKeyFrames(), AlphaGenCircle(), AlphaGenSquare(), AngryFace(), AudioReactiveGradientDisplay(), Dead(), Default(), Heart(), HideAll(), LinkParameters(), OwO(), OwO2(), Sad(), SpectrumAnalyzerDisplay(), and UpdateKeyFrameTracks().
normalMaterial
NormalMaterial normalMaterial private
Definition at line 44 of file AlphaProject.h.
Referenced by SetMaterialLayers(), and SpyroDisplay().
offset
float offset = 0.0f
Definition at line 674 of file AlphaProject.h.
Referenced by Update().
pM
ProtoDR pM private
Definition at line 30 of file AlphaProject.h.
Referenced by AlphaAnimation(), AlphaGenCircle(), AlphaGenSquare(), AngryFace(), AudioReactiveGradientDisplay(), Dead(), Default(), GetObject(), Heart(), HideAll(), LinkEasyEase(), LinkParameters(), OwO(), OwO2(), Sad(), SpectrumAnalyzerDisplay(), SpyroDisplay(), and Update().
rainbowNoise
RainbowNoise rainbowNoise private
Definition at line 38 of file AlphaProject.h.
Referenced by SetMaterialLayers(), and Update().
rainbowSpiral
RainbowSpiral rainbowSpiral private
Definition at line 39 of file AlphaProject.h.
Referenced by Heart(), SetMaterialLayers(), and Update().
redMaterial
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0)) private
Definition at line 41 of file AlphaProject.h.
Referenced by AngryFace(), Dead(), and SetMaterialLayers().
sA
SpectrumAnalyzer sA = SpectrumAnalyzer(Vector2D(430, 300), Vector2D(15, 120), true, true) private
Definition at line 50 of file AlphaProject.h.
Referenced by AlphaAnimation(), SpectrumAnalyzerDisplay(), and Update().
spyro
Spyro spyro private
Definition at line 32 of file AlphaProject.h.
Referenced by AlphaAnimation(), SpyroDisplay(), and Update().
stripe1
StripeMaterial stripe1 = StripeMaterial(6, gradientSpectrum, 200.0f, 160.0f, 20.0f) private
Definition at line 40 of file AlphaProject.h.
Referenced by OwO2(), SetMaterialLayers(), and Update().
talk
bool talk = true private
Definition at line 76 of file AlphaProject.h.
Referenced by AlphaGenCircle(), AlphaGenSquare(), AngryFace(), AudioReactiveGradientDisplay(), Dead(), Default(), Heart(), HideAll(), OwO(), OwO2(), Sad(), SpectrumAnalyzerDisplay(), and SpyroDisplay().
topFinGap
KeyFrameTrack<1, 5> topFinGap = KeyFrameTrack<1, 5>(0.0f, 1.0f, KeyFrameInterpolation::Cosine) private
Definition at line 65 of file AlphaProject.h.
Referenced by AddTopFinKeyFrames(), AlphaGenCircle(), AlphaGenSquare(), AngryFace(), AudioReactiveGradientDisplay(), Dead(), Default(), Heart(), HideAll(), LinkParameters(), OwO(), OwO2(), Sad(), SpectrumAnalyzerDisplay(), and UpdateKeyFrameTracks().
topFinInner
KeyFrameTrack<1, 5> topFinInner = KeyFrameTrack<1, 5>(0.0f, 1.0f, KeyFrameInterpolation::Cosine) private
Definition at line 64 of file AlphaProject.h.
Referenced by AddTopFinKeyFrames(), AlphaGenCircle(), AlphaGenSquare(), AngryFace(), AudioReactiveGradientDisplay(), Dead(), Default(), Heart(), HideAll(), LinkParameters(), OwO(), OwO2(), Sad(), SpectrumAnalyzerDisplay(), and UpdateKeyFrameTracks().
topFinOuter
KeyFrameTrack<1, 5> topFinOuter = KeyFrameTrack<1, 5>(0.0f, 1.0f, KeyFrameInterpolation::Cosine) private
Definition at line 63 of file AlphaProject.h.
Referenced by AddTopFinKeyFrames(), AlphaGenCircle(), AlphaGenSquare(), AngryFace(), AudioReactiveGradientDisplay(), Dead(), Default(), Heart(), HideAll(), LinkParameters(), OwO(), OwO2(), Sad(), SpectrumAnalyzerDisplay(), and UpdateKeyFrameTracks().
voiceDetection
FFTVoiceDetection<128> voiceDetection private
Definition at line 74 of file AlphaProject.h.
Referenced by UpdateFFTVisemes().
The documentation for this class was generated from the following file:
AlphaProject.h