SpyroRotateAnimation Class Reference
SpyroRotateAnimation Class Reference
#include <SpyroRotateAnimation.h>
Public Member Functions
SpyroRotateAnimation ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
void Update (float ratio) override
Private Attributes
Spyro spyro
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 2.0f, 10.0f, 4.2f)
SimpleMaterial sM = SimpleMaterial(RGBColor(255, 255, 255))
Detailed Description
Definition at line 8 of file SpyroRotateAnimation.h.
Constructor & Destructor Documentation
SpyroRotateAnimation()
SpyroRotateAnimation () inline
Definition at line 15 of file SpyroRotateAnimation.h.
References SerialInterpreter::Initialize(), and spyro.
Member Function Documentation
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 23 of file SpyroRotateAnimation.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 24 of file SpyroRotateAnimation.h.
Update()
void Update (float ratio) inline override
Definition at line 26 of file SpyroRotateAnimation.h.
References fGenScale, SerialInterpreter::GetColor(), SerialInterpreter::GetOrientation(), SimpleMaterial::SetRGB(), sM, spyro, SerialInterpreter::Update(), and FunctionGenerator::Update().
Member Data Documentation
fGenScale
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 2.0f, 10.0f, 4.2f) private
Definition at line 11 of file SpyroRotateAnimation.h.
Referenced by Update().
sM
SimpleMaterial sM = SimpleMaterial(RGBColor(255, 255, 255)) private
Definition at line 12 of file SpyroRotateAnimation.h.
Referenced by Update().
spyro
Spyro spyro private
Definition at line 10 of file SpyroRotateAnimation.h.
Referenced by SpyroRotateAnimation(), and Update().
The documentation for this class was generated from the following file:
SpyroRotateAnimation.h