SergaliciousAnimation Class Reference
SergaliciousAnimation Class Reference
#include <SergaliciousAnimation.h>
Public Member Functions
SergaliciousAnimation ()
uint8_t GetAccentBrightness ()
uint8_t GetBrightness ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
Object3D * GetObject ()
void Update (float ratio) override
Private Member Functions
void LinkEasyEase ()
void LinkParameters ()
void ChangeInterpolationMethods ()
void SetMaterialLayers ()
void UpdateKeyFrameTracks ()
void Default ()
void Happy ()
void Idle ()
void OwO ()
void Squint ()
void BSOD ()
void Loading ()
void Sad ()
void Heart ()
void Question ()
void SpectrumAnalyzerFace ()
void AudioReactiveGradientFace ()
void OscilloscopeFace ()
void UpdateFFTVisemes ()
void SetMaterialColor ()
Private Attributes
SergaliciousFace pM
Background background
LEDStripBackground ledStripBackground
EasyEaseAnimator< 30 > eEA = EasyEaseAnimator<30>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f)
RainbowNoise rainbowNoise
RainbowSpiral rainbowSpiral
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0))
SimpleMaterial orangeMaterial = SimpleMaterial(RGBColor(255, 165, 0))
SimpleMaterial whiteMaterial = SimpleMaterial(RGBColor(255, 255, 255))
SimpleMaterial greenMaterial = SimpleMaterial(RGBColor(0, 255, 0))
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255))
SimpleMaterial yellowMaterial = SimpleMaterial(RGBColor(255, 255, 0))
SimpleMaterial purpleMaterial = SimpleMaterial(RGBColor(255, 0, 255))
RGBColor gradientSpectrum [2] = {RGBColor(20, 69, 252), RGBColor(34, 243, 254)}
GradientMaterial< 2 > gradientMat = GradientMaterial<2>(gradientSpectrum, 75.0f, false)
MaterialAnimator< 10 > materialAnimator
MaterialAnimator< 5 > backgroundMaterial
SpectrumAnalyzer sA = SpectrumAnalyzer(Vector2D(200, 100), Vector2D(100, 50), true, true)
AudioReactiveGradient aRG = AudioReactiveGradient(Vector2D(160, 160), Vector2D(0, 0), true, true)
Oscilloscope oSC = Oscilloscope(Vector2D(200, 100), Vector2D(0, 0))
BlinkTrack< 1 > blink
BlinkTrack< 1 > blinkIdle
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f)
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f)
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f)
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 5.3f)
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 6.7f)
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f)
FunctionGenerator fGenMatXMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 1.1f)
FunctionGenerator fGenMatYMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 2.7f)
FunctionGenerator fGenMatRMenu = FunctionGenerator(FunctionGenerator::Sine, -5.0f, 5.0f, 1.7f)
FunctionGenerator fGenMatM1Sleep = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 5.3f)
FunctionGenerator fGenMatM2Sleep = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 6.7f)
FunctionGenerator fGenMatS1Sleep = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 4.6f)
FunctionGenerator fGenLoadingRamp = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 8.3f)
APDS9960 boop
FFTVoiceDetection< 128 > voiceDetection
ObjectAlign objA = ObjectAlign(Vector2D(0.0f, 0.0f), Vector2D(189.0f, 93.0f), Quaternion())
float offsetFace = 0.0f
float offsetFaceSA = 0.0f
float offsetFaceARG = 0.0f
float offsetFaceOSC = 0.0f
float backgroundBSOD = 0.0f
uint8_t offsetFaceInd = 50
uint8_t offsetFaceIndSA = 51
uint8_t offsetFaceIndARG = 52
uint8_t offsetFaceIndOSC = 53
uint8_t backgroundBSODInd = 54
Detailed Description
Definition at line 27 of file SergaliciousAnimation.h.
Constructor & Destructor Documentation
SergaliciousAnimation()
SergaliciousAnimation () inline
Definition at line 279 of file SergaliciousAnimation.h.
References background, backgroundMaterial, boop, ChangeInterpolationMethods(), gradientMat, Menu::Initialize(), MicrophoneFourier::Initialize(), APDS9960::Initialize(), ledStripBackground, LinkEasyEase(), LinkParameters(), materialAnimator, objA, pM, ObjectAlign::SetJustification(), SetMaterialLayers(), ObjectAlign::SetMirrorX(), GradientMaterial< colorCount >::SetRotationAngle(), and ObjectAlign::Stretch.
Member Function Documentation
AudioReactiveGradientFace()
void AudioReactiveGradientFace () inline private
Definition at line 229 of file SergaliciousAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), aRG, backgroundMaterial, blinkIdle, eEA, offsetFaceARG, offsetFaceInd, offsetFaceIndARG, and AnimationTrack< maxParameters, maxKeyFrames >::Pause().
Referenced by Update().
BSOD()
void BSOD () inline private
Definition at line 184 of file SergaliciousAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), backgroundBSOD, backgroundBSODInd, backgroundMaterial, blink, blinkIdle, blueMaterial, eEA, materialAnimator, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), and whiteMaterial.
Referenced by Update().
ChangeInterpolationMethods()
void ChangeInterpolationMethods () inline private
Definition at line 121 of file SergaliciousAnimation.h.
References eEA, and EasyEaseAnimator< maxParameters >::SetInterpolationMethod().
Referenced by SergaliciousAnimation().
Default()
void Default () inline private
Definition at line 155 of file SergaliciousAnimation.h.
References blink, blinkIdle, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), and AnimationTrack< maxParameters, maxKeyFrames >::Play().
Referenced by Update().
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 315 of file SergaliciousAnimation.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 316 of file SergaliciousAnimation.h.
GetAccentBrightness()
uint8_t GetAccentBrightness () inline
Definition at line 307 of file SergaliciousAnimation.h.
References Menu::GetAccentBrightness().
GetBrightness()
uint8_t GetBrightness () inline
Definition at line 311 of file SergaliciousAnimation.h.
References Menu::GetBrightness().
GetObject()
Object3D * GetObject () inline
Definition at line 318 of file SergaliciousAnimation.h.
References pM.
Happy()
void Happy () inline private
Definition at line 160 of file SergaliciousAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, blinkIdle, eEA, and AnimationTrack< maxParameters, maxKeyFrames >::Pause().
Referenced by Update().
Heart()
void Heart () inline private
Definition at line 209 of file SergaliciousAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, blinkIdle, eEA, and AnimationTrack< maxParameters, maxKeyFrames >::Pause().
Referenced by Update().
Idle()
void Idle () inline private
Definition at line 166 of file SergaliciousAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, blinkIdle, eEA, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), and AnimationTrack< maxParameters, maxKeyFrames >::Play().
Referenced by Update().
LinkEasyEase()
void LinkEasyEase () inline private
Definition at line 93 of file SergaliciousAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameter(), backgroundBSOD, backgroundBSODInd, eEA, offsetFace, offsetFaceARG, offsetFaceInd, offsetFaceIndARG, offsetFaceIndOSC, offsetFaceIndSA, offsetFaceOSC, offsetFaceSA, and pM.
Referenced by SergaliciousAnimation().
LinkParameters()
void LinkParameters () inline private
Definition at line 116 of file SergaliciousAnimation.h.
References AnimationTrack< maxParameters, maxKeyFrames >::AddParameter(), blink, blinkIdle, and pM.
Referenced by SergaliciousAnimation().
Loading()
void Loading () inline private
Definition at line 194 of file SergaliciousAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), backgroundBSODInd, blink, blinkIdle, eEA, fGenLoadingRamp, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), and FunctionGenerator::Update().
Referenced by Update().
OscilloscopeFace()
void OscilloscopeFace () inline private
Definition at line 237 of file SergaliciousAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), backgroundMaterial, blinkIdle, eEA, offsetFaceInd, offsetFaceIndOSC, offsetFaceOSC, oSC, and AnimationTrack< maxParameters, maxKeyFrames >::Pause().
Referenced by Update().
OwO()
void OwO () inline private
Definition at line 172 of file SergaliciousAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, blinkIdle, eEA, and AnimationTrack< maxParameters, maxKeyFrames >::Pause().
Referenced by Update().
Question()
void Question () inline private
Definition at line 215 of file SergaliciousAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, blinkIdle, eEA, and AnimationTrack< maxParameters, maxKeyFrames >::Pause().
Referenced by Update().
Sad()
void Sad () inline private
Definition at line 203 of file SergaliciousAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, blinkIdle, eEA, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), and AnimationTrack< maxParameters, maxKeyFrames >::Play().
SetMaterialColor()
void SetMaterialColor () inline private
Definition at line 263 of file SergaliciousAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), blueMaterial, Menu::GetFaceColor(), greenMaterial, materialAnimator, orangeMaterial, purpleMaterial, rainbowNoise, rainbowSpiral, redMaterial, whiteMaterial, and yellowMaterial.
Referenced by Update().
SetMaterialLayers()
void SetMaterialLayers () inline private
Definition at line 131 of file SergaliciousAnimation.h.
References Material::Add, MaterialAnimator< materialCount >::AddMaterial(), aRG, backgroundMaterial, blueMaterial, Menu::GetMaterial(), gradientMat, greenMaterial, Material::Lighten, materialAnimator, orangeMaterial, oSC, purpleMaterial, rainbowNoise, rainbowSpiral, redMaterial, Material::Replace, sA, MaterialAnimator< materialCount >::SetBaseMaterial(), whiteMaterial, and yellowMaterial.
Referenced by SergaliciousAnimation().
SpectrumAnalyzerFace()
void SpectrumAnalyzerFace () inline private
Definition at line 221 of file SergaliciousAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), backgroundMaterial, blinkIdle, eEA, offsetFaceInd, offsetFaceIndSA, offsetFaceSA, AnimationTrack< maxParameters, maxKeyFrames >::Pause(), and sA.
Referenced by Update().
Squint()
void Squint () inline private
Definition at line 178 of file SergaliciousAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), blink, blinkIdle, eEA, and AnimationTrack< maxParameters, maxKeyFrames >::Pause().
Referenced by Update().
Update()
void Update (float ratio) inline override
Definition at line 322 of file SergaliciousAnimation.h.
References ObjectAlign::AlignObjects(), aRG, AudioReactiveGradientFace(), backgroundMaterial, boop, BSOD(), Default(), eEA, fGenMatXMove, fGenMatYMove, Menu::GetFaceSize(), Menu::GetFaceState(), MicrophoneFourierBase::GetFourierFiltered(), Menu::GetMicLevel(), MicrophoneFourierBase::GetSamples(), Happy(), Heart(), Idle(), APDS9960::isBooped(), Loading(), materialAnimator, Menu::MirrorSpectrumAnalyzer(), objA, offsetFace, oSC, OscilloscopeFace(), OwO(), pM, Question(), rainbowNoise, rainbowSpiral, sA, ObjectAlign::SetCameraMax(), ObjectAlign::SetEdgeMargin(), SpectrumAnalyzer::SetFlipYState(), AudioReactiveGradient::SetHueAngle(), Oscilloscope::SetHueAngle(), SpectrumAnalyzer::SetHueAngle(), SetMaterialColor(), SpectrumAnalyzer::SetMirrorYState(), AudioReactiveGradient::SetPosition(), Oscilloscope::SetPosition(), AudioReactiveGradient::SetRadius(), AudioReactiveGradient::SetRotation(), AudioReactiveGradient::SetSize(), Oscilloscope::SetSize(), FFTVoiceDetection< peakCount >::SetThreshold(), Menu::ShowMenu(), SpectrumAnalyzerFace(), Squint(), MicrophoneFourier::Update(), MaterialAnimator< materialCount >::Update(), FunctionGenerator::Update(), EasyEaseAnimator< maxParameters >::Update(), Oscilloscope::Update(), AudioReactiveGradient::Update(), SpectrumAnalyzer::Update(), Menu::Update(), RainbowNoise::Update(), RainbowSpiral::Update(), UpdateFFTVisemes(), UpdateKeyFrameTracks(), Menu::UseBoopSensor(), and voiceDetection.
UpdateFFTVisemes()
void UpdateFFTVisemes () inline private
Definition at line 245 of file SergaliciousAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), Viseme::EE, eEA, MicrophoneFourierBase::GetCurrentMagnitude(), MicrophoneFourierBase::GetFourierFiltered(), MicrophoneFourierBase::GetSampleRate(), FFTVoiceDetection< peakCount >::GetViseme(), Viseme::OO, FFTVoiceDetection< peakCount >::Update(), Menu::UseMicrophone(), and voiceDetection.
Referenced by Update().
UpdateKeyFrameTracks()
void UpdateKeyFrameTracks () inline private
Definition at line 150 of file SergaliciousAnimation.h.
References blink, blinkIdle, and AnimationTrack< maxParameters, maxKeyFrames >::Update().
Referenced by Update().
Member Data Documentation
aRG
AudioReactiveGradient aRG = AudioReactiveGradient(Vector2D(160, 160), Vector2D(0, 0), true, true) private
Definition at line 52 of file SergaliciousAnimation.h.
Referenced by AudioReactiveGradientFace(), SetMaterialLayers(), and Update().
background
Background background private
Definition at line 30 of file SergaliciousAnimation.h.
Referenced by SergaliciousAnimation().
backgroundBSOD
float backgroundBSOD = 0.0f private
Definition at line 86 of file SergaliciousAnimation.h.
Referenced by BSOD(), and LinkEasyEase().
backgroundBSODInd
uint8_t backgroundBSODInd = 54 private
Definition at line 91 of file SergaliciousAnimation.h.
Referenced by BSOD(), LinkEasyEase(), and Loading().
backgroundMaterial
MaterialAnimator<5> backgroundMaterial private
Definition at line 49 of file SergaliciousAnimation.h.
Referenced by AudioReactiveGradientFace(), BSOD(), OscilloscopeFace(), SergaliciousAnimation(), SetMaterialLayers(), SpectrumAnalyzerFace(), and Update().
blink
BlinkTrack<1> blink private
Definition at line 56 of file SergaliciousAnimation.h.
Referenced by BSOD(), Default(), Happy(), Heart(), Idle(), LinkParameters(), Loading(), OwO(), Question(), Sad(), Squint(), and UpdateKeyFrameTracks().
blinkIdle
BlinkTrack<1> blinkIdle private
Definition at line 57 of file SergaliciousAnimation.h.
Referenced by AudioReactiveGradientFace(), BSOD(), Default(), Happy(), Heart(), Idle(), LinkParameters(), Loading(), OscilloscopeFace(), OwO(), Question(), Sad(), SpectrumAnalyzerFace(), Squint(), and UpdateKeyFrameTracks().
blueMaterial
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255)) private
Definition at line 41 of file SergaliciousAnimation.h.
Referenced by BSOD(), SetMaterialColor(), and SetMaterialLayers().
boop
APDS9960 boop private
Definition at line 76 of file SergaliciousAnimation.h.
Referenced by SergaliciousAnimation(), and Update().
eEA
EasyEaseAnimator<30> eEA = EasyEaseAnimator<30>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f) private
Definition at line 32 of file SergaliciousAnimation.h.
Referenced by AudioReactiveGradientFace(), BSOD(), ChangeInterpolationMethods(), Happy(), Heart(), Idle(), LinkEasyEase(), Loading(), OscilloscopeFace(), OwO(), Question(), Sad(), SpectrumAnalyzerFace(), Squint(), Update(), and UpdateFFTVisemes().
fGenLoadingRamp
FunctionGenerator fGenLoadingRamp = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 8.3f) private
Definition at line 74 of file SergaliciousAnimation.h.
Referenced by Loading().
fGenMatHue
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f) private
Definition at line 64 of file SergaliciousAnimation.h.
fGenMatM1Sleep
FunctionGenerator fGenMatM1Sleep = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 5.3f) private
Definition at line 70 of file SergaliciousAnimation.h.
fGenMatM2Sleep
FunctionGenerator fGenMatM2Sleep = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 6.7f) private
Definition at line 71 of file SergaliciousAnimation.h.
fGenMatPos
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f) private
Definition at line 59 of file SergaliciousAnimation.h.
fGenMatRMenu
FunctionGenerator fGenMatRMenu = FunctionGenerator(FunctionGenerator::Sine, -5.0f, 5.0f, 1.7f) private
Definition at line 68 of file SergaliciousAnimation.h.
fGenMatS1Sleep
FunctionGenerator fGenMatS1Sleep = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 4.6f) private
Definition at line 72 of file SergaliciousAnimation.h.
fGenMatXMenu
FunctionGenerator fGenMatXMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 1.1f) private
Definition at line 66 of file SergaliciousAnimation.h.
fGenMatXMove
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 5.3f) private
Definition at line 62 of file SergaliciousAnimation.h.
Referenced by Update().
fGenMatYMenu
FunctionGenerator fGenMatYMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 2.7f) private
Definition at line 67 of file SergaliciousAnimation.h.
fGenMatYMove
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 6.7f) private
Definition at line 63 of file SergaliciousAnimation.h.
Referenced by Update().
fGenRotation
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f) private
Definition at line 60 of file SergaliciousAnimation.h.
fGenScale
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f) private
Definition at line 61 of file SergaliciousAnimation.h.
gradientMat
GradientMaterial<2> gradientMat = GradientMaterial<2>(gradientSpectrum, 75.0f, false) private
Definition at line 46 of file SergaliciousAnimation.h.
Referenced by SergaliciousAnimation(), and SetMaterialLayers().
gradientSpectrum
RGBColor gradientSpectrum[2] = {RGBColor(20, 69, 252), RGBColor(34, 243, 254)} private
Definition at line 45 of file SergaliciousAnimation.h.
greenMaterial
SimpleMaterial greenMaterial = SimpleMaterial(RGBColor(0, 255, 0)) private
Definition at line 40 of file SergaliciousAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
ledStripBackground
LEDStripBackground ledStripBackground private
Definition at line 31 of file SergaliciousAnimation.h.
Referenced by SergaliciousAnimation().
materialAnimator
MaterialAnimator<10> materialAnimator private
Definition at line 48 of file SergaliciousAnimation.h.
Referenced by BSOD(), SergaliciousAnimation(), SetMaterialColor(), SetMaterialLayers(), and Update().
objA
ObjectAlign objA = ObjectAlign(Vector2D(0.0f, 0.0f), Vector2D(189.0f, 93.0f), Quaternion()) private
Definition at line 80 of file SergaliciousAnimation.h.
Referenced by SergaliciousAnimation(), and Update().
offsetFace
float offsetFace = 0.0f private
Definition at line 82 of file SergaliciousAnimation.h.
Referenced by LinkEasyEase(), and Update().
offsetFaceARG
float offsetFaceARG = 0.0f private
Definition at line 84 of file SergaliciousAnimation.h.
Referenced by AudioReactiveGradientFace(), and LinkEasyEase().
offsetFaceInd
uint8_t offsetFaceInd = 50 private
Definition at line 87 of file SergaliciousAnimation.h.
Referenced by AudioReactiveGradientFace(), LinkEasyEase(), OscilloscopeFace(), and SpectrumAnalyzerFace().
offsetFaceIndARG
uint8_t offsetFaceIndARG = 52 private
Definition at line 89 of file SergaliciousAnimation.h.
Referenced by AudioReactiveGradientFace(), and LinkEasyEase().
offsetFaceIndOSC
uint8_t offsetFaceIndOSC = 53 private
Definition at line 90 of file SergaliciousAnimation.h.
Referenced by LinkEasyEase(), and OscilloscopeFace().
offsetFaceIndSA
uint8_t offsetFaceIndSA = 51 private
Definition at line 88 of file SergaliciousAnimation.h.
Referenced by LinkEasyEase(), and SpectrumAnalyzerFace().
offsetFaceOSC
float offsetFaceOSC = 0.0f private
Definition at line 85 of file SergaliciousAnimation.h.
Referenced by LinkEasyEase(), and OscilloscopeFace().
offsetFaceSA
float offsetFaceSA = 0.0f private
Definition at line 83 of file SergaliciousAnimation.h.
Referenced by LinkEasyEase(), and SpectrumAnalyzerFace().
orangeMaterial
SimpleMaterial orangeMaterial = SimpleMaterial(RGBColor(255, 165, 0)) private
Definition at line 38 of file SergaliciousAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
oSC
Oscilloscope oSC = Oscilloscope(Vector2D(200, 100), Vector2D(0, 0)) private
Definition at line 53 of file SergaliciousAnimation.h.
Referenced by OscilloscopeFace(), SetMaterialLayers(), and Update().
pM
SergaliciousFace pM private
Definition at line 29 of file SergaliciousAnimation.h.
Referenced by GetObject(), LinkEasyEase(), LinkParameters(), SergaliciousAnimation(), and Update().
purpleMaterial
SimpleMaterial purpleMaterial = SimpleMaterial(RGBColor(255, 0, 255)) private
Definition at line 43 of file SergaliciousAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
rainbowNoise
RainbowNoise rainbowNoise private
Definition at line 35 of file SergaliciousAnimation.h.
Referenced by SetMaterialColor(), SetMaterialLayers(), and Update().
rainbowSpiral
RainbowSpiral rainbowSpiral private
Definition at line 36 of file SergaliciousAnimation.h.
Referenced by SetMaterialColor(), SetMaterialLayers(), and Update().
redMaterial
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0)) private
Definition at line 37 of file SergaliciousAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
sA
SpectrumAnalyzer sA = SpectrumAnalyzer(Vector2D(200, 100), Vector2D(100, 50), true, true) private
Definition at line 51 of file SergaliciousAnimation.h.
Referenced by SetMaterialLayers(), SpectrumAnalyzerFace(), and Update().
voiceDetection
FFTVoiceDetection<128> voiceDetection private
Definition at line 78 of file SergaliciousAnimation.h.
Referenced by Update(), and UpdateFFTVisemes().
whiteMaterial
SimpleMaterial whiteMaterial = SimpleMaterial(RGBColor(255, 255, 255)) private
Definition at line 39 of file SergaliciousAnimation.h.
Referenced by BSOD(), SetMaterialColor(), and SetMaterialLayers().
yellowMaterial
SimpleMaterial yellowMaterial = SimpleMaterial(RGBColor(255, 255, 0)) private
Definition at line 42 of file SergaliciousAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
The documentation for this class was generated from the following file:
SergaliciousAnimation.h