CameraManager Class Reference
CameraManager Class Reference
Manages multiple CameraBase objects.
#include <CameraManager.h>
Public Member Functions
CameraManager (CameraBase **cameras, uint8_t count)
Constructs a CameraManager object.
CameraBase ** GetCameras ()
Retrieves the array of CameraBase objects.
uint8_t GetCameraCount ()
Retrieves the count of cameras managed by the CameraManager.
Protected Attributes
CameraBase ** cameras
Array of pointers to CameraBase objects.
uint8_t count
Number of CameraBase objects managed.
Detailed Description
Manages multiple CameraBase objects.
The CameraManager class provides a centralized interface for handling multiple camera instances, including retrieval of camera data and count.
Definition at line 23 of file CameraManager.h.
Constructor & Destructor Documentation
CameraManager()
CameraManager (CameraBase ** cameras, uint8_t count)
Constructs a CameraManager object.
Parameters
cameras Pointer to an array of CameraBase objects.
count The number of cameras in the array.
Definition at line 3 of file CameraManager.cpp.
References cameras, and count.
Member Function Documentation
GetCameraCount()
uint8_t GetCameraCount ()
Retrieves the count of cameras managed by the CameraManager.
Returns
The number of CameraBase objects.
Definition at line 12 of file CameraManager.cpp.
References count.
Referenced by RenderingEngine::DisplayWhite(), and RenderingEngine::Rasterize().
GetCameras()
CameraBase ** GetCameras ()
Retrieves the array of CameraBase objects.
Returns
A pointer to the array of CameraBase objects.
Definition at line 8 of file CameraManager.cpp.
References cameras.
Referenced by APA102Controller::Display(), HUB75Controller::Display(), HUB75ControllerSplit::Display(), HUB75ControllerSquare::Display(), WS35BetaController::Display(), WS35Controller::Display(), RenderingEngine::DisplayWhite(), and RenderingEngine::Rasterize().
Member Data Documentation
cameras
CameraBase** cameras protected
Array of pointers to CameraBase objects.
Definition at line 25 of file CameraManager.h.
Referenced by CameraManager(), and GetCameras().
count
uint8_t count protected
Number of CameraBase objects managed.
Definition at line 26 of file CameraManager.h.
Referenced by CameraManager(), and GetCameraCount().
The documentation for this class was generated from the following files:
CameraManager.h
CameraManager.cpp