FullScreenAnimation Class Reference
FullScreenAnimation Class Reference
#include <FullScreenAnimation.h>
Public Member Functions
FullScreenAnimation ()
void Initialize () override
uint8_t GetAccentBrightness ()
uint8_t GetBrightness ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
void Reset ()
void Update (float ratio) override
Private Attributes
SolidCube cube
FunctionGenerator fGenSelection = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 1.0f, 20.0f)
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 1.5f)
FunctionGenerator fGenMatSize = FunctionGenerator(FunctionGenerator::Sine, 400.0f, 550.0f, 2.1f)
FunctionGenerator fGenMatRot = FunctionGenerator(FunctionGenerator::Sine, -5.0f, 5.0f, 3.2f)
FunctionGenerator fGenMatWidth = FunctionGenerator(FunctionGenerator::Sine, 150.0f, 500.0f, 4.0f)
FunctionGenerator fGenMatPeriod = FunctionGenerator(FunctionGenerator::Sine, 200.0f, 500.0f, 6.3f)
FunctionGenerator fGenMatAmplitude = FunctionGenerator(FunctionGenerator::Sine, -100.0f, 100.0f, 2.7f)
FunctionGenerator fGenMatBend = FunctionGenerator(FunctionGenerator::Sine, 0.1f, 1.0f, 6.7f)
FunctionGenerator fGenMatOpacity = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 0.5f)
RGBColor spectrum1 [6] = {RGBColor(255, 255, 0), RGBColor(0, 0, 0), RGBColor(0, 255, 255), RGBColor(0, 0, 0), RGBColor(255, 0, 255), RGBColor(0, 0, 0)}
RGBColor spectrum2 [6] = {RGBColor(255, 0, 0), RGBColor(0, 0, 0), RGBColor(0, 255, 0), RGBColor(0, 0, 0), RGBColor(0, 0, 255), RGBColor(0, 0, 0)}
RGBColor spectrum3 [6] = {RGBColor(255, 0, 0), RGBColor(255, 255, 0), RGBColor(0, 255, 0), RGBColor(0, 255, 255), RGBColor(0, 0, 255), RGBColor(255, 0, 255)}
StripeMaterial stripe1 = StripeMaterial(6, spectrum1, 200.0f, 160.0f, 20.0f)
StripeMaterial stripe2 = StripeMaterial(6, spectrum2, 200.0f, 160.0f, 20.0f)
SpiralMaterial spiral = SpiralMaterial(6, spectrum3, 2.0f, 7.0f)
Detailed Description
Definition at line 15 of file FullScreenAnimation.h.
Constructor & Destructor Documentation
FullScreenAnimation()
FullScreenAnimation () inline
Definition at line 41 of file FullScreenAnimation.h.
References cube, and spiral.
Member Function Documentation
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 59 of file FullScreenAnimation.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 60 of file FullScreenAnimation.h.
GetAccentBrightness()
uint8_t GetAccentBrightness () inline
Definition at line 51 of file FullScreenAnimation.h.
GetBrightness()
uint8_t GetBrightness () inline
Definition at line 55 of file FullScreenAnimation.h.
Initialize()
void Initialize () inline override
Definition at line 47 of file FullScreenAnimation.h.
Reset()
void Reset () inline
Definition at line 62 of file FullScreenAnimation.h.
Update()
void Update (float ratio) inline override
Definition at line 66 of file FullScreenAnimation.h.
References cube, fGenMatAmplitude, fGenMatBend, fGenMatPeriod, fGenMatPos, fGenMatWidth, SpiralMaterial::SetBend(), SpiralMaterial::SetPositionOffset(), StripeMaterial::SetPositionOffset(), SpiralMaterial::SetRotationAngle(), StripeMaterial::SetRotationAngle(), StripeMaterial::SetStripeWidth(), StripeMaterial::SetWaveAmplitude(), StripeMaterial::SetWavePeriod(), spiral, stripe1, and FunctionGenerator::Update().
Member Data Documentation
cube
SolidCube cube private
Definition at line 17 of file FullScreenAnimation.h.
Referenced by FullScreenAnimation(), and Update().
fGenMatAmplitude
FunctionGenerator fGenMatAmplitude = FunctionGenerator(FunctionGenerator::Sine, -100.0f, 100.0f, 2.7f) private
Definition at line 24 of file FullScreenAnimation.h.
Referenced by Update().
fGenMatBend
FunctionGenerator fGenMatBend = FunctionGenerator(FunctionGenerator::Sine, 0.1f, 1.0f, 6.7f) private
Definition at line 25 of file FullScreenAnimation.h.
Referenced by Update().
fGenMatOpacity
FunctionGenerator fGenMatOpacity = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 0.5f) private
Definition at line 26 of file FullScreenAnimation.h.
fGenMatPeriod
FunctionGenerator fGenMatPeriod = FunctionGenerator(FunctionGenerator::Sine, 200.0f, 500.0f, 6.3f) private
Definition at line 23 of file FullScreenAnimation.h.
Referenced by Update().
fGenMatPos
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 1.5f) private
Definition at line 19 of file FullScreenAnimation.h.
Referenced by Update().
fGenMatRot
FunctionGenerator fGenMatRot = FunctionGenerator(FunctionGenerator::Sine, -5.0f, 5.0f, 3.2f) private
Definition at line 21 of file FullScreenAnimation.h.
fGenMatSize
FunctionGenerator fGenMatSize = FunctionGenerator(FunctionGenerator::Sine, 400.0f, 550.0f, 2.1f) private
Definition at line 20 of file FullScreenAnimation.h.
fGenMatWidth
FunctionGenerator fGenMatWidth = FunctionGenerator(FunctionGenerator::Sine, 150.0f, 500.0f, 4.0f) private
Definition at line 22 of file FullScreenAnimation.h.
Referenced by Update().
fGenSelection
FunctionGenerator fGenSelection = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 1.0f, 20.0f) private
Definition at line 18 of file FullScreenAnimation.h.
spectrum1
RGBColor spectrum1[6] = {RGBColor(255, 255, 0), RGBColor(0, 0, 0), RGBColor(0, 255, 255), RGBColor(0, 0, 0), RGBColor(255, 0, 255), RGBColor(0, 0, 0)} private
Definition at line 30 of file FullScreenAnimation.h.
spectrum2
RGBColor spectrum2[6] = {RGBColor(255, 0, 0), RGBColor(0, 0, 0), RGBColor(0, 255, 0), RGBColor(0, 0, 0), RGBColor(0, 0, 255), RGBColor(0, 0, 0)} private
Definition at line 31 of file FullScreenAnimation.h.
spectrum3
RGBColor spectrum3[6] = {RGBColor(255, 0, 0), RGBColor(255, 255, 0), RGBColor(0, 255, 0), RGBColor(0, 255, 255), RGBColor(0, 0, 255), RGBColor(255, 0, 255)} private
Definition at line 32 of file FullScreenAnimation.h.
spiral
SpiralMaterial spiral = SpiralMaterial(6, spectrum3, 2.0f, 7.0f) private
Definition at line 35 of file FullScreenAnimation.h.
Referenced by FullScreenAnimation(), and Update().
stripe1
StripeMaterial stripe1 = StripeMaterial(6, spectrum1, 200.0f, 160.0f, 20.0f) private
Definition at line 33 of file FullScreenAnimation.h.
Referenced by Update().
stripe2
StripeMaterial stripe2 = StripeMaterial(6, spectrum2, 200.0f, 160.0f, 20.0f) private
Definition at line 34 of file FullScreenAnimation.h.
The documentation for this class was generated from the following file:
FullScreenAnimation.h