GammaControllerBack Class Reference
GammaControllerBack Class Reference
#include <GammaControllerBack.h>
Public Member Functions
GammaControllerBack (uint8_t maxBrightness)
void Initialize () override
Initializes the controller.
void Display () override
Updates and displays content on the lighting system.
void SetPixels (uint8_t strip, uint16_t led, RGBColor rgb)
Public Member Functions inherited from Controller
uint8_t GetBrightness ()
Retrieves the current brightness level.
uint8_t GetAccentBrightness ()
Retrieves the current accent brightness level.
virtual void SetBrightness (uint8_t maxBrightness)=0
Sets the maximum brightness for the controller.
virtual void SetAccentBrightness (uint8_t maxAccentBrightness)=0
Sets the maximum accent brightness for the controller.
Private Attributes
CameraLayout cameraLayout = CameraLayout(CameraLayout::ZForward, CameraLayout::YUp)
Transform camTopTransform = Transform(Vector3D(0.0f, 0.0f, 40.94f), Vector3D(-301.609f, 260.205f, -500.0f), Vector3D(1, 1, 1))
Transform camBotTransform = Transform(Vector3D(0.0f, 180.0f, 180.0f), Vector3D(-348.159f, 129.804f, -500.0f), Vector3D(1, 1, 1))
PixelGroup< 571 > camTopPixels = PixelGroup<571>(KaiborgV1Pixels, IPixelGroup::ZEROTOMAX)
PixelGroup< 571 > camBotPixels = PixelGroup<571>(KaiborgV1Pixels, IPixelGroup::MAXTOZERO)
Camera< 571 > camTop = Camera<571>(&camTopTransform, &cameraLayout, &camTopPixels)
Camera< 571 > camBot = Camera<571>(&camBotTransform, &cameraLayout, &camBotPixels)
CameraBase * cameras [2] = { &camTop, &camBot }
Additional Inherited Members
Protected Member Functions inherited from Controller
Controller (CameraManager *cameras, uint8_t maxBrightness, uint8_t maxAccentBrightness)
Constructs a Controller with specified parameters.
void UpdateBrightness ()
Updates the brightness based on internal logic.
Protected Attributes inherited from Controller
CameraManager * cameras
Pointer to the CameraManager for managing camera data.
uint8_t brightness
Current brightness level.
uint8_t accentBrightness
Current accent brightness level.
uint8_t maxBrightness
Maximum allowed brightness level.
uint8_t maxAccentBrightness
Maximum allowed accent brightness level.
bool isOn = false
Indicates if the controller is active.
bool startTime = false
Indicates if the start time has been recorded.
Detailed Description
Definition at line 15 of file GammaControllerBack.h.
Constructor & Destructor Documentation
GammaControllerBack()
GammaControllerBack (uint8_t maxBrightness) inline
Definition at line 31 of file GammaControllerBack.h.
Member Function Documentation
Display()
void Display () inline override virtual
Updates and displays content on the lighting system.
Implements Controller.
Definition at line 38 of file GammaControllerBack.h.
References RGBColor::B, Controller::brightness, camBotPixels, camTopPixels, RGBColor::G, PixelGroup< pixelCount >::GetColor(), leds(), RGBColor::R, and RGBColor::Scale().
Initialize()
void Initialize () inline override virtual
Initializes the controller.
Implements Controller.
Definition at line 33 of file GammaControllerBack.h.
References leds().
SetPixels()
void SetPixels (uint8_t strip, uint16_t led, RGBColor rgb) inline
Definition at line 78 of file GammaControllerBack.h.
References RGBColor::B, RGBColor::G, leds(), and RGBColor::R.
Member Data Documentation
camBot
Camera<571> camBot = Camera<571>(&camBotTransform, &cameraLayout, &camBotPixels) private
Definition at line 26 of file GammaControllerBack.h.
camBotPixels
PixelGroup<571> camBotPixels = PixelGroup<571>(KaiborgV1Pixels, IPixelGroup::MAXTOZERO) private
Definition at line 23 of file GammaControllerBack.h.
Referenced by Display().
camBotTransform
Transform camBotTransform = Transform(Vector3D(0.0f, 180.0f, 180.0f), Vector3D(-348.159f, 129.804f, -500.0f), Vector3D(1, 1, 1)) private
Definition at line 20 of file GammaControllerBack.h.
cameraLayout
CameraLayout cameraLayout = CameraLayout(CameraLayout::ZForward, CameraLayout::YUp) private
Definition at line 17 of file GammaControllerBack.h.
cameras
CameraBase* cameras[2] = { &camTop, &camBot } private
Definition at line 28 of file GammaControllerBack.h.
camTop
Camera<571> camTop = Camera<571>(&camTopTransform, &cameraLayout, &camTopPixels) private
Definition at line 25 of file GammaControllerBack.h.
camTopPixels
PixelGroup<571> camTopPixels = PixelGroup<571>(KaiborgV1Pixels, IPixelGroup::ZEROTOMAX) private
Definition at line 22 of file GammaControllerBack.h.
Referenced by Display().
camTopTransform
Transform camTopTransform = Transform(Vector3D(0.0f, 0.0f, 40.94f), Vector3D(-301.609f, 260.205f, -500.0f), Vector3D(1, 1, 1)) private
Definition at line 19 of file GammaControllerBack.h.
The documentation for this class was generated from the following file:
GammaControllerBack.h