MicrophoneFourierBase Class Reference
MicrophoneFourierBase Class Reference
Base class for FFT-based microphone signal processing.
#include <MicrophoneFourierBase.h>
Static Public Member Functions
static float AverageMagnitude (uint16_t binL, uint16_t binH)
Calculates the average magnitude of the specified FFT bins.
static bool IsInitialized ()
Checks if the microphone system is initialized.
static float GetSampleRate ()
Retrieves the current sampling rate.
static float * GetSamples ()
Retrieves the raw input samples.
static float * GetFourier ()
Retrieves the FFT output data.
static float * GetFourierFiltered ()
Retrieves the filtered FFT output data.
static float GetCurrentMagnitude ()
Retrieves the current signal magnitude.
Static Protected Attributes
static const uint16_t FFTSize = 256
Size of the FFT (number of samples).
static const uint16_t OutputBins = 128
Number of output bins from FFT processing.
static uint16_t sampleRate = 8000
Sampling rate in Hz.
static uint8_t pin = 0
Pin number for microphone input.
static float minDB = 50.0f
Minimum decibel value for normalization.
static float maxDB = 120.0f
Maximum decibel value for normalization.
static float threshold = 400.0f
Threshold value for processing.
static float currentValue = 0.0f
Current magnitude of the microphone signal.
static bool isInitialized = false
Flag indicating if the system is initialized.
static DerivativeFilter peakFilterRate
Filter for peak rate detection.
static float inputSamp [FFTSize *2]
Raw input samples for FFT.
static float inputStorage [FFTSize]
Storage for processed input samples.
static float outputMagn [FFTSize]
Magnitude output from FFT.
static float outputData [OutputBins]
Processed FFT data for output bins.
static float outputDataFilt [OutputBins]
Filtered FFT data for output bins.
static FFTFilter fftFilters [OutputBins]
Array of FFT filters for post-processing.
static FFT< FFTSize > fft
FFT processor instance.
Detailed Description
Base class for FFT-based microphone signal processing.
The MicrophoneFourierBase class provides foundational support for microphone signal processing, including FFT transformations, signal normalization, and filtering. Derived classes can extend its functionality for specific applications.
Definition at line 29 of file MicrophoneFourierBase.h.
Member Function Documentation
AverageMagnitude()
float AverageMagnitude (uint16_t binL, uint16_t binH) static
Calculates the average magnitude of the specified FFT bins.
Parameters
binL The lower bound of the bin range (inclusive).
binH The upper bound of the bin range (inclusive).
Returns
The average magnitude within the specified range.
Definition at line 23 of file MicrophoneFourierBase.cpp.
References FFTSize, and outputMagn.
Referenced by MicrophoneFourier::Update(), and MicrophoneFourier::UpdateDMA().
GetCurrentMagnitude()
float GetCurrentMagnitude () static
Retrieves the current signal magnitude.
Returns
The current magnitude value.
Definition at line 54 of file MicrophoneFourierBase.cpp.
References threshold.
Referenced by AlphaAnimation::Update(), ArtleckAnimationV2::UpdateFFTVisemes(), ElGatoAnimation::UpdateFFTVisemes(), LeonHuskyAnimation::UpdateFFTVisemes(), MyntAnimation::UpdateFFTVisemes(), ProtobottAnimation::UpdateFFTVisemes(), SergaliciousAnimation::UpdateFFTVisemes(), TechSaneAnimation::UpdateFFTVisemes(), VesperAnimation::UpdateFFTVisemes(), WaffleDaProtoAnimation::UpdateFFTVisemes(), WarzoneAnimation::UpdateFFTVisemes(), AlphaAnimation::UpdateFFTVisemes(), and ProtogenProject::UpdateFFTVisemes().
GetFourier()
float * GetFourier () static
Retrieves the FFT output data.
Returns
Pointer to the array of FFT output data.
Definition at line 46 of file MicrophoneFourierBase.cpp.
References outputData.
GetFourierFiltered()
float * GetFourierFiltered () static
Retrieves the filtered FFT output data.
Returns
Pointer to the array of filtered FFT output data.
Definition at line 50 of file MicrophoneFourierBase.cpp.
References outputDataFilt.
Referenced by ProtogenProject::AudioReactiveGradientFace(), ProtogenProject::SpectrumAnalyzerFace(), ArtleckAnimationV2::Update(), ElGatoAnimation::Update(), LeonHuskyAnimation::Update(), MyntAnimation::Update(), ProtobottAnimation::Update(), SergaliciousAnimation::Update(), TechSaneAnimation::Update(), VesperAnimation::Update(), WaffleDaProtoAnimation::Update(), WarzoneAnimation::Update(), AlphaAnimation::Update(), ArtleckAnimationV2::UpdateFFTVisemes(), ElGatoAnimation::UpdateFFTVisemes(), LeonHuskyAnimation::UpdateFFTVisemes(), MyntAnimation::UpdateFFTVisemes(), ProtobottAnimation::UpdateFFTVisemes(), SergaliciousAnimation::UpdateFFTVisemes(), TechSaneAnimation::UpdateFFTVisemes(), VesperAnimation::UpdateFFTVisemes(), WaffleDaProtoAnimation::UpdateFFTVisemes(), WarzoneAnimation::UpdateFFTVisemes(), AlphaAnimation::UpdateFFTVisemes(), and ProtogenProject::UpdateFFTVisemes().
GetSampleRate()
float GetSampleRate () static
Retrieves the current sampling rate.
Returns
The sampling rate in Hz.
Definition at line 38 of file MicrophoneFourierBase.cpp.
References sampleRate.
Referenced by ArtleckAnimationV2::UpdateFFTVisemes(), ElGatoAnimation::UpdateFFTVisemes(), LeonHuskyAnimation::UpdateFFTVisemes(), MyntAnimation::UpdateFFTVisemes(), ProtobottAnimation::UpdateFFTVisemes(), SergaliciousAnimation::UpdateFFTVisemes(), TechSaneAnimation::UpdateFFTVisemes(), VesperAnimation::UpdateFFTVisemes(), WaffleDaProtoAnimation::UpdateFFTVisemes(), WarzoneAnimation::UpdateFFTVisemes(), AlphaAnimation::UpdateFFTVisemes(), and ProtogenProject::UpdateFFTVisemes().
GetSamples()
float * GetSamples () static
Retrieves the raw input samples.
Returns
Pointer to the array of raw input samples.
Definition at line 42 of file MicrophoneFourierBase.cpp.
References inputStorage.
Referenced by ProtogenProject::OscilloscopeFace(), SergaliciousAnimation::Update(), and TechSaneAnimation::Update().
IsInitialized()
bool IsInitialized () static
Checks if the microphone system is initialized.
Returns
True if initialized, false otherwise.
Definition at line 34 of file MicrophoneFourierBase.cpp.
References isInitialized.
Member Data Documentation
currentValue
float currentValue = 0.0f static protected
Current magnitude of the microphone signal.
Definition at line 38 of file MicrophoneFourierBase.h.
fft
FFT< MicrophoneFourierBase::FFTSize > fft static protected
FFT processor instance.
Definition at line 50 of file MicrophoneFourierBase.h.
Referenced by MicrophoneFourier::Update(), and MicrophoneFourier::UpdateDMA().
fftFilters
FFTFilter fftFilters static protected
Array of FFT filters for post-processing.
Definition at line 48 of file MicrophoneFourierBase.h.
Referenced by MicrophoneFourier::Update(), and MicrophoneFourier::UpdateDMA().
FFTSize
const uint16_t FFTSize = 256 static protected
Size of the FFT (number of samples).
Definition at line 31 of file MicrophoneFourierBase.h.
Referenced by AverageMagnitude(), MicrophoneFourier::Initialize(), MicrophoneFourier::Reset(), and MicrophoneFourier::SamplerCallback().
inputSamp
float inputSamp static protected
Raw input samples for FFT.
Definition at line 43 of file MicrophoneFourierBase.h.
Referenced by MicrophoneFourier::Reset(), MicrophoneFourier::SamplerCallback(), MicrophoneFourier::SamplerCallback(), MicrophoneFourier::Update(), and MicrophoneFourier::UpdateDMA().
inputStorage
float inputStorage static protected
Storage for processed input samples.
Definition at line 44 of file MicrophoneFourierBase.h.
Referenced by GetSamples(), MicrophoneFourier::SamplerCallback(), MicrophoneFourier::SamplerCallback(), MicrophoneFourier::Update(), and MicrophoneFourier::UpdateDMA().
isInitialized
bool isInitialized = false static protected
Flag indicating if the system is initialized.
Definition at line 39 of file MicrophoneFourierBase.h.
Referenced by MicrophoneFourier::Initialize(), MicrophoneFourier::Initialize(), MicrophoneFourier::Initialize(), and IsInitialized().
maxDB
float maxDB = 120.0f static protected
Maximum decibel value for normalization.
Definition at line 36 of file MicrophoneFourierBase.h.
Referenced by MicrophoneFourier::Initialize(), MicrophoneFourier::Initialize(), MicrophoneFourier::Initialize(), MicrophoneFourier::Update(), and MicrophoneFourier::UpdateDMA().
minDB
float minDB = 50.0f static protected
Minimum decibel value for normalization.
Definition at line 35 of file MicrophoneFourierBase.h.
Referenced by MicrophoneFourier::Initialize(), MicrophoneFourier::Initialize(), MicrophoneFourier::Initialize(), MicrophoneFourier::Update(), and MicrophoneFourier::UpdateDMA().
OutputBins
const uint16_t OutputBins = 128 static protected
Number of output bins from FFT processing.
Definition at line 32 of file MicrophoneFourierBase.h.
Referenced by MicrophoneFourier::Initialize(), MicrophoneFourier::Update(), and MicrophoneFourier::UpdateDMA().
outputData
float outputData static protected
Processed FFT data for output bins.
Definition at line 46 of file MicrophoneFourierBase.h.
Referenced by GetFourier(), MicrophoneFourier::Update(), and MicrophoneFourier::UpdateDMA().
outputDataFilt
float outputDataFilt static protected
Filtered FFT data for output bins.
Definition at line 47 of file MicrophoneFourierBase.h.
Referenced by GetFourierFiltered(), MicrophoneFourier::Update(), and MicrophoneFourier::UpdateDMA().
outputMagn
float outputMagn static protected
Magnitude output from FFT.
Definition at line 45 of file MicrophoneFourierBase.h.
Referenced by AverageMagnitude(), MicrophoneFourier::Update(), and MicrophoneFourier::UpdateDMA().
peakFilterRate
DerivativeFilter peakFilterRate static protected
Filter for peak rate detection.
Definition at line 41 of file MicrophoneFourierBase.h.
Referenced by MicrophoneFourier::Update(), and MicrophoneFourier::UpdateDMA().
pin
uint8_t pin = 0 static protected
Pin number for microphone input.
Definition at line 34 of file MicrophoneFourierBase.h.
Referenced by MicrophoneFourier::Initialize(), MicrophoneFourier::Initialize(), MicrophoneFourier::Initialize(), and MicrophoneFourier::SamplerCallback().
sampleRate
uint16_t sampleRate = 8000 static protected
Sampling rate in Hz.
Definition at line 33 of file MicrophoneFourierBase.h.
Referenced by GetSampleRate(), MicrophoneFourier::Initialize(), MicrophoneFourier::Initialize(), MicrophoneFourier::Initialize(), MicrophoneFourier::setSamplingRate(), and MicrophoneFourier::StartSampler().
threshold
float threshold = 400.0f static protected
Threshold value for processing.
Definition at line 37 of file MicrophoneFourierBase.h.
Referenced by GetCurrentMagnitude(), MicrophoneFourier::Update(), and MicrophoneFourier::UpdateDMA().
The documentation for this class was generated from the following files:
MicrophoneFourierBase.h
MicrophoneFourierBase.cpp