ProtoDRController Class Reference
ProtoDRController Class Reference
#include <ProtoDRController.h>
Public Types
enum Side { LEFT , RIGHT }
Public Member Functions
ProtoDRController (uint8_t maxBrightness, Side side)
void Initialize () override
Initializes the controller.
void Display () override
Updates and displays content on the lighting system.
Public Member Functions inherited from Controller
uint8_t GetBrightness ()
Retrieves the current brightness level.
uint8_t GetAccentBrightness ()
Retrieves the current accent brightness level.
virtual void SetBrightness (uint8_t maxBrightness)=0
Sets the maximum brightness for the controller.
virtual void SetAccentBrightness (uint8_t maxAccentBrightness)=0
Sets the maximum accent brightness for the controller.
Private Attributes
CameraLayout cameraLayout = CameraLayout(CameraLayout::ZForward, CameraLayout::YUp)
Transform camFronTopTransform = Transform(Vector3D(35.25f, -2.25f, 216.5f), Vector3D(68.25f, 210.75f, 31.0f - 5000.0f), Vector3D(-1, 1, 1))
Transform camRearTopTransform = Transform(Vector3D(-36.5f, 14.0f, 45.0f), Vector3D(15.5f, 117.5f, -43.5f - 5000.0f), Vector3D(-1, 1, 1))
Transform camFronBotTransform = Transform(Vector3D(20.25f, 7.0f, 1.0f), Vector3D(0, 0, 0 - 5000.0f), Vector3D(1, 1, 1))
Transform camRearBotTransform = Transform(Vector3D(-20.75f, -16.5f, 177.5f), Vector3D(17, 122, -42 - 5000.0f), Vector3D(1, 1, 1))
Transform camRearMidTransform
Transform camFronMidTransform
PixelGroup< 306 > camFronTopPixels = PixelGroup<306>(ProtoDRCamera)
PixelGroup< 306 > camRearTopPixels = PixelGroup<306>(ProtoDRCamera)
PixelGroup< 306 > camFronBotPixels = PixelGroup<306>(ProtoDRCamera)
PixelGroup< 306 > camRearBotPixels = PixelGroup<306>(ProtoDRCamera)
PixelGroup< 89 > camRearMidPixels = PixelGroup<89>(ProtoDRMini)
PixelGroup< 89 > camFronMidPixels = PixelGroup<89>(ProtoDRMini)
Camera< 306 > camFronTop = Camera<306>(&camFronTopTransform, &cameraLayout, &camFronTopPixels)
Camera< 306 > camRearTop = Camera<306>(&camRearTopTransform, &cameraLayout, &camRearTopPixels)
Camera< 306 > camFronBot = Camera<306>(&camFronBotTransform, &cameraLayout, &camFronBotPixels)
Camera< 306 > camRearBot = Camera<306>(&camRearBotTransform, &cameraLayout, &camRearBotPixels)
Camera< 89 > camRearMid = Camera<89>(&camRearMidTransform, &cameraLayout, &camRearMidPixels)
Camera< 89 > camFronMid = Camera<89>(&camFronMidTransform, &cameraLayout, &camFronMidPixels)
CameraBase * cameras [6] = { &camFronTop, &camRearTop, &camFronBot, &camRearBot, &camRearMid, &camFronMid }
Additional Inherited Members
Protected Member Functions inherited from Controller
Controller (CameraManager *cameras, uint8_t maxBrightness, uint8_t maxAccentBrightness)
Constructs a Controller with specified parameters.
void UpdateBrightness ()
Updates the brightness based on internal logic.
Protected Attributes inherited from Controller
CameraManager * cameras
Pointer to the CameraManager for managing camera data.
uint8_t brightness
Current brightness level.
uint8_t accentBrightness
Current accent brightness level.
uint8_t maxBrightness
Maximum allowed brightness level.
uint8_t maxAccentBrightness
Maximum allowed accent brightness level.
bool isOn = false
Indicates if the controller is active.
bool startTime = false
Indicates if the start time has been recorded.
Detailed Description
Definition at line 17 of file ProtoDRController.h.
Member Enumeration Documentation
Side
enum Side
Enumerator
LEFT
RIGHT
Definition at line 19 of file ProtoDRController.h.
Constructor & Destructor Documentation
ProtoDRController()
ProtoDRController (uint8_t maxBrightness, Side side) inline
Definition at line 52 of file ProtoDRController.h.
References camFronMidTransform, camRearMidTransform, LEFT, and RIGHT.
Member Function Documentation
Display()
void Display () inline override virtual
Updates and displays content on the lighting system.
Implements Controller.
Definition at line 72 of file ProtoDRController.h.
References RGBColor::B, Controller::brightness, camFronBotPixels, camFronMidPixels, camFronTopPixels, camRearBotPixels, camRearMidPixels, camRearTopPixels, RGBColor::G, PixelGroup< pixelCount >::GetColor(), leds(), RGBColor::R, and RGBColor::Scale().
Initialize()
void Initialize () inline override virtual
Initializes the controller.
Implements Controller.
Definition at line 67 of file ProtoDRController.h.
References leds().
Member Data Documentation
cameraLayout
CameraLayout cameraLayout = CameraLayout(CameraLayout::ZForward, CameraLayout::YUp) private
Definition at line 25 of file ProtoDRController.h.
cameras
CameraBase* cameras[6] = { &camFronTop, &camRearTop, &camFronBot, &camRearBot, &camRearMid, &camFronMid } private
Definition at line 49 of file ProtoDRController.h.
camFronBot
Camera<306> camFronBot = Camera<306>(&camFronBotTransform, &cameraLayout, &camFronBotPixels) private
Definition at line 44 of file ProtoDRController.h.
camFronBotPixels
PixelGroup<306> camFronBotPixels = PixelGroup<306>(ProtoDRCamera) private
Definition at line 37 of file ProtoDRController.h.
Referenced by Display().
camFronBotTransform
Transform camFronBotTransform = Transform(Vector3D(20.25f, 7.0f, 1.0f), Vector3D(0, 0, 0 - 5000.0f), Vector3D(1, 1, 1)) private
Definition at line 29 of file ProtoDRController.h.
camFronMid
Camera<89> camFronMid = Camera<89>(&camFronMidTransform, &cameraLayout, &camFronMidPixels) private
Definition at line 47 of file ProtoDRController.h.
camFronMidPixels
PixelGroup<89> camFronMidPixels = PixelGroup<89>(ProtoDRMini) private
Definition at line 40 of file ProtoDRController.h.
Referenced by Display().
camFronMidTransform
Transform camFronMidTransform private
Definition at line 33 of file ProtoDRController.h.
Referenced by ProtoDRController().
camFronTop
Camera<306> camFronTop = Camera<306>(&camFronTopTransform, &cameraLayout, &camFronTopPixels) private
Definition at line 42 of file ProtoDRController.h.
camFronTopPixels
PixelGroup<306> camFronTopPixels = PixelGroup<306>(ProtoDRCamera) private
Definition at line 35 of file ProtoDRController.h.
Referenced by Display().
camFronTopTransform
Transform camFronTopTransform = Transform(Vector3D(35.25f, -2.25f, 216.5f), Vector3D(68.25f, 210.75f, 31.0f - 5000.0f), Vector3D(-1, 1, 1)) private
Definition at line 27 of file ProtoDRController.h.
camRearBot
Camera<306> camRearBot = Camera<306>(&camRearBotTransform, &cameraLayout, &camRearBotPixels) private
Definition at line 45 of file ProtoDRController.h.
camRearBotPixels
PixelGroup<306> camRearBotPixels = PixelGroup<306>(ProtoDRCamera) private
Definition at line 38 of file ProtoDRController.h.
Referenced by Display().
camRearBotTransform
Transform camRearBotTransform = Transform(Vector3D(-20.75f, -16.5f, 177.5f), Vector3D(17, 122, -42 - 5000.0f), Vector3D(1, 1, 1)) private
Definition at line 30 of file ProtoDRController.h.
camRearMid
Camera<89> camRearMid = Camera<89>(&camRearMidTransform, &cameraLayout, &camRearMidPixels) private
Definition at line 46 of file ProtoDRController.h.
camRearMidPixels
PixelGroup<89> camRearMidPixels = PixelGroup<89>(ProtoDRMini) private
Definition at line 39 of file ProtoDRController.h.
Referenced by Display().
camRearMidTransform
Transform camRearMidTransform private
Definition at line 32 of file ProtoDRController.h.
Referenced by ProtoDRController().
camRearTop
Camera<306> camRearTop = Camera<306>(&camRearTopTransform, &cameraLayout, &camRearTopPixels) private
Definition at line 43 of file ProtoDRController.h.
camRearTopPixels
PixelGroup<306> camRearTopPixels = PixelGroup<306>(ProtoDRCamera) private
Definition at line 36 of file ProtoDRController.h.
Referenced by Display().
camRearTopTransform
Transform camRearTopTransform = Transform(Vector3D(-36.5f, 14.0f, 45.0f), Vector3D(15.5f, 117.5f, -43.5f - 5000.0f), Vector3D(-1, 1, 1)) private
Definition at line 28 of file ProtoDRController.h.
The documentation for this class was generated from the following file:
ProtoDRController.h