BasilGardenAnimation Class Reference
BasilGardenAnimation Class Reference
#include <BasilGardenAnimation.h>
Public Member Functions
BasilGardenAnimation ()
uint8_t GetAccentBrightness ()
uint8_t GetBrightness ()
void FadeIn (float stepRatio) override
void FadeOut (float stepRatio) override
Object3D * GetObject ()
void Update (float ratio) override
Private Member Functions
void LinkEasyEase ()
void LinkParameters ()
void ChangeInterpolationMethods ()
void SetMaterialLayers ()
void UpdateKeyFrameTracks ()
void Default ()
void Angry ()
void Sad ()
void Rage ()
void Smirk ()
void Disappointed ()
void Grimace ()
void Whoops ()
void Crabby ()
void ForReal ()
void SpectrumAnalyzerFace ()
void AudioReactiveGradientFace ()
void OscilloscopeFace ()
void UpdateFFTVisemes ()
void SetMaterialColor ()
Private Attributes
BasilGarden pM
Background background
LEDStripBackground ledStripBackground
EasyEaseAnimator< 25 > eEA = EasyEaseAnimator<25>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f)
RainbowNoise rainbowNoise
RainbowSpiral rainbowSpiral
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0))
SimpleMaterial orangeMaterial = SimpleMaterial(RGBColor(255, 165, 0))
SimpleMaterial whiteMaterial = SimpleMaterial(RGBColor(255, 255, 255))
SimpleMaterial greenMaterial = SimpleMaterial(RGBColor(0, 255, 0))
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255))
SimpleMaterial yellowMaterial = SimpleMaterial(RGBColor(255, 255, 0))
SimpleMaterial purpleMaterial = SimpleMaterial(RGBColor(255, 0, 255))
RGBColor gradientSpectrum [2] = {RGBColor(252, 145, 34), RGBColor(252, 80, 15)}
GradientMaterial< 2 > gradientMat = GradientMaterial<2>(gradientSpectrum, 350.0f, false)
MaterialAnimator< 10 > materialAnimator
MaterialAnimator< 4 > backgroundMaterial
SpectrumAnalyzer sA = SpectrumAnalyzer(Vector2D(200, 100), Vector2D(100, 50), true, true)
AudioReactiveGradient aRG = AudioReactiveGradient(Vector2D(160, 160), Vector2D(0, 0), true, true)
Oscilloscope oSC = Oscilloscope(Vector2D(200, 100), Vector2D(0, 0))
BlinkTrack< 1 > blink
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f)
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f)
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f)
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 5.3f)
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 6.7f)
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f)
FunctionGenerator fGenMatXMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 1.1f)
FunctionGenerator fGenMatYMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 2.7f)
FunctionGenerator fGenMatRMenu = FunctionGenerator(FunctionGenerator::Sine, -5.0f, 5.0f, 1.7f)
FunctionGenerator fGenBlur = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 1.5f)
APDS9960 boop
FFTVoiceDetection< 128 > voiceDetection
ObjectAlign objA = ObjectAlign(Vector2D(0.0f, 0.0f), Vector2D(189.0f, 93.0f), Quaternion())
Fisheye fisheye = Fisheye()
GlitchX glitchX = GlitchX(30)
HorizontalBlur blurH = HorizontalBlur(8)
VerticalBlur blurV = VerticalBlur(8)
Magnet magnet = Magnet()
RadialBlur blurR = RadialBlur(8)
PhaseOffsetX phaseX = PhaseOffsetX(8)
PhaseOffsetY phaseY = PhaseOffsetY(8)
PhaseOffsetR phaseR = PhaseOffsetR(8)
ShiftR shiftR = ShiftR(8)
Overflow overflow = Overflow(8)
float offsetFace = 0.0f
float offsetFaceSA = 0.0f
float offsetFaceARG = 0.0f
float offsetFaceOSC = 0.0f
uint8_t offsetFaceInd = 50
uint8_t offsetFaceIndSA = 51
uint8_t offsetFaceIndARG = 52
uint8_t offsetFaceIndOSC = 53
Static Private Attributes
static const uint8_t faceCount = 9
Detailed Description
Definition at line 42 of file BasilGardenAnimation.h.
Constructor & Destructor Documentation
BasilGardenAnimation()
BasilGardenAnimation () inline
Definition at line 283 of file BasilGardenAnimation.h.
References background, backgroundMaterial, boop, ChangeInterpolationMethods(), Menu::Initialize(), APDS9960::Initialize(), ledStripBackground, LinkEasyEase(), LinkParameters(), materialAnimator, objA, pM, ObjectAlign::SetJustification(), SetMaterialLayers(), ObjectAlign::SetMirrorX(), and ObjectAlign::Stretch.
Member Function Documentation
Angry()
void Angry () inline private
Definition at line 185 of file BasilGardenAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, materialAnimator, and redMaterial.
Referenced by Update().
AudioReactiveGradientFace()
void AudioReactiveGradientFace () inline private
Definition at line 235 of file BasilGardenAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), aRG, backgroundMaterial, eEA, offsetFaceARG, offsetFaceInd, and offsetFaceIndARG.
Referenced by Update().
ChangeInterpolationMethods()
void ChangeInterpolationMethods () inline private
Definition at line 145 of file BasilGardenAnimation.h.
References eEA, and EasyEaseAnimator< maxParameters >::SetInterpolationMethod().
Referenced by BasilGardenAnimation().
Crabby()
void Crabby () inline private
Definition at line 219 of file BasilGardenAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
Referenced by Update().
Default()
void Default () inline private
Definition at line 180 of file BasilGardenAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
Referenced by Update().
Disappointed()
void Disappointed () inline private
Definition at line 207 of file BasilGardenAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
Referenced by Update().
FadeIn()
void FadeIn (float stepRatio) inline override
Definition at line 317 of file BasilGardenAnimation.h.
FadeOut()
void FadeOut (float stepRatio) inline override
Definition at line 318 of file BasilGardenAnimation.h.
ForReal()
void ForReal () inline private
Definition at line 223 of file BasilGardenAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, materialAnimator, and rainbowNoise.
Referenced by Update().
GetAccentBrightness()
uint8_t GetAccentBrightness () inline
Definition at line 309 of file BasilGardenAnimation.h.
References Menu::GetAccentBrightness().
GetBrightness()
uint8_t GetBrightness () inline
Definition at line 313 of file BasilGardenAnimation.h.
References Menu::GetBrightness().
GetObject()
Object3D * GetObject () inline
Definition at line 320 of file BasilGardenAnimation.h.
References pM.
Grimace()
void Grimace () inline private
Definition at line 211 of file BasilGardenAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
Referenced by Update().
LinkEasyEase()
void LinkEasyEase () inline private
Definition at line 114 of file BasilGardenAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameter(), eEA, offsetFace, offsetFaceARG, offsetFaceInd, offsetFaceIndARG, offsetFaceIndOSC, offsetFaceIndSA, offsetFaceOSC, offsetFaceSA, and pM.
Referenced by BasilGardenAnimation().
LinkParameters()
void LinkParameters () inline private
Definition at line 141 of file BasilGardenAnimation.h.
References AnimationTrack< maxParameters, maxKeyFrames >::AddParameter(), blink, and pM.
Referenced by BasilGardenAnimation().
OscilloscopeFace()
void OscilloscopeFace () inline private
Definition at line 242 of file BasilGardenAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), backgroundMaterial, eEA, offsetFaceInd, offsetFaceIndOSC, offsetFaceOSC, and oSC.
Referenced by Update().
Rage()
void Rage () inline private
Definition at line 195 of file BasilGardenAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), eEA, glitchX, materialAnimator, and redMaterial.
Referenced by Update().
Sad()
void Sad () inline private
Definition at line 190 of file BasilGardenAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), blueMaterial, eEA, and materialAnimator.
Referenced by Update().
SetMaterialColor()
void SetMaterialColor () inline private
Definition at line 267 of file BasilGardenAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), blueMaterial, Menu::GetFaceColor(), greenMaterial, materialAnimator, orangeMaterial, purpleMaterial, rainbowNoise, rainbowSpiral, redMaterial, whiteMaterial, and yellowMaterial.
Referenced by Update().
SetMaterialLayers()
void SetMaterialLayers () inline private
Definition at line 158 of file BasilGardenAnimation.h.
References Material::Add, MaterialAnimator< materialCount >::AddMaterial(), aRG, backgroundMaterial, blueMaterial, Menu::GetMaterial(), gradientMat, greenMaterial, materialAnimator, orangeMaterial, oSC, purpleMaterial, rainbowNoise, rainbowSpiral, redMaterial, Material::Replace, sA, MaterialAnimator< materialCount >::SetBaseMaterial(), whiteMaterial, and yellowMaterial.
Referenced by BasilGardenAnimation().
Smirk()
void Smirk () inline private
Definition at line 203 of file BasilGardenAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
SpectrumAnalyzerFace()
void SpectrumAnalyzerFace () inline private
Definition at line 228 of file BasilGardenAnimation.h.
References MaterialAnimator< materialCount >::AddMaterialFrame(), EasyEaseAnimator< maxParameters >::AddParameterFrame(), backgroundMaterial, eEA, offsetFaceInd, offsetFaceIndSA, offsetFaceSA, and sA.
Referenced by Update().
Update()
void Update (float ratio) inline override
Definition at line 324 of file BasilGardenAnimation.h.
References ObjectAlign::AlignObjects(), Angry(), aRG, AudioReactiveGradientFace(), backgroundMaterial, blurH, blurR, blurV, boop, Crabby(), Default(), Disappointed(), eEA, fGenBlur, fGenMatXMove, fGenMatYMove, fisheye, ForReal(), Menu::GetFaceSize(), Menu::GetFaceState(), Menu::GetMicLevel(), EasyEaseAnimator< maxParameters >::GetValue(), glitchX, Grimace(), APDS9960::isBooped(), magnet, materialAnimator, Menu::MirrorSpectrumAnalyzer(), objA, offsetFace, oSC, OscilloscopeFace(), phaseR, phaseX, phaseY, pM, Rage(), rainbowNoise, rainbowSpiral, sA, Sad(), ObjectAlign::SetCameraMax(), ObjectAlign::SetEdgeMargin(), SpectrumAnalyzer::SetFlipYState(), AudioReactiveGradient::SetHueAngle(), Oscilloscope::SetHueAngle(), SpectrumAnalyzer::SetHueAngle(), SetMaterialColor(), SpectrumAnalyzer::SetMirrorYState(), ObjectAlign::SetPlaneOffsetAngle(), AudioReactiveGradient::SetPosition(), Oscilloscope::SetPosition(), AudioReactiveGradient::SetRadius(), Effect::SetRatio(), AudioReactiveGradient::SetRotation(), AudioReactiveGradient::SetSize(), Oscilloscope::SetSize(), FFTVoiceDetection< peakCount >::SetThreshold(), shiftR, Menu::ShowMenu(), SpectrumAnalyzerFace(), MaterialAnimator< materialCount >::Update(), FunctionGenerator::Update(), EasyEaseAnimator< maxParameters >::Update(), Oscilloscope::Update(), AudioReactiveGradient::Update(), SpectrumAnalyzer::Update(), Menu::Update(), RainbowNoise::Update(), RainbowSpiral::Update(), UpdateFFTVisemes(), UpdateKeyFrameTracks(), Menu::UseBoopSensor(), voiceDetection, and Whoops().
UpdateFFTVisemes()
void UpdateFFTVisemes () inline private
Definition at line 249 of file BasilGardenAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), Viseme::AH, Viseme::AR, Viseme::EE, eEA, Viseme::ER, FFTVoiceDetection< peakCount >::GetViseme(), Viseme::OO, Viseme::UH, FFTVoiceDetection< peakCount >::Update(), Menu::UseMicrophone(), and voiceDetection.
Referenced by Update().
UpdateKeyFrameTracks()
void UpdateKeyFrameTracks () inline private
Definition at line 176 of file BasilGardenAnimation.h.
References blink, and AnimationTrack< maxParameters, maxKeyFrames >::Update().
Referenced by Update().
Whoops()
void Whoops () inline private
Definition at line 215 of file BasilGardenAnimation.h.
References EasyEaseAnimator< maxParameters >::AddParameterFrame(), and eEA.
Referenced by Update().
Member Data Documentation
aRG
AudioReactiveGradient aRG = AudioReactiveGradient(Vector2D(160, 160), Vector2D(0, 0), true, true) private
Definition at line 68 of file BasilGardenAnimation.h.
Referenced by AudioReactiveGradientFace(), SetMaterialLayers(), and Update().
background
Background background private
Definition at line 46 of file BasilGardenAnimation.h.
Referenced by BasilGardenAnimation().
backgroundMaterial
MaterialAnimator<4> backgroundMaterial private
Definition at line 65 of file BasilGardenAnimation.h.
Referenced by AudioReactiveGradientFace(), BasilGardenAnimation(), OscilloscopeFace(), SetMaterialLayers(), SpectrumAnalyzerFace(), and Update().
blink
BlinkTrack<1> blink private
Definition at line 72 of file BasilGardenAnimation.h.
Referenced by LinkParameters(), and UpdateKeyFrameTracks().
blueMaterial
SimpleMaterial blueMaterial = SimpleMaterial(RGBColor(0, 0, 255)) private
Definition at line 57 of file BasilGardenAnimation.h.
Referenced by Sad(), SetMaterialColor(), and SetMaterialLayers().
blurH
HorizontalBlur blurH = HorizontalBlur(8) private
Definition at line 95 of file BasilGardenAnimation.h.
Referenced by Update().
blurR
RadialBlur blurR = RadialBlur(8) private
Definition at line 98 of file BasilGardenAnimation.h.
Referenced by Update().
blurV
VerticalBlur blurV = VerticalBlur(8) private
Definition at line 96 of file BasilGardenAnimation.h.
Referenced by Update().
boop
APDS9960 boop private
Definition at line 87 of file BasilGardenAnimation.h.
Referenced by BasilGardenAnimation(), and Update().
eEA
EasyEaseAnimator<25> eEA = EasyEaseAnimator<25>(EasyEaseInterpolation::Overshoot, 1.0f, 0.35f) private
Definition at line 48 of file BasilGardenAnimation.h.
Referenced by Angry(), AudioReactiveGradientFace(), ChangeInterpolationMethods(), Crabby(), Default(), Disappointed(), ForReal(), Grimace(), LinkEasyEase(), OscilloscopeFace(), Rage(), Sad(), Smirk(), SpectrumAnalyzerFace(), Update(), UpdateFFTVisemes(), and Whoops().
faceCount
const uint8_t faceCount = 9 static private
Definition at line 44 of file BasilGardenAnimation.h.
fGenBlur
FunctionGenerator fGenBlur = FunctionGenerator(FunctionGenerator::Sine, 0.0f, 1.0f, 1.5f) private
Definition at line 85 of file BasilGardenAnimation.h.
Referenced by Update().
fGenMatHue
FunctionGenerator fGenMatHue = FunctionGenerator(FunctionGenerator::Triangle, 0.0f, 360.0f, 17.3f) private
Definition at line 79 of file BasilGardenAnimation.h.
fGenMatPos
FunctionGenerator fGenMatPos = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 4.0f) private
Definition at line 74 of file BasilGardenAnimation.h.
fGenMatRMenu
FunctionGenerator fGenMatRMenu = FunctionGenerator(FunctionGenerator::Sine, -5.0f, 5.0f, 1.7f) private
Definition at line 83 of file BasilGardenAnimation.h.
fGenMatXMenu
FunctionGenerator fGenMatXMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 1.1f) private
Definition at line 81 of file BasilGardenAnimation.h.
fGenMatXMove
FunctionGenerator fGenMatXMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 5.3f) private
Definition at line 77 of file BasilGardenAnimation.h.
Referenced by Update().
fGenMatYMenu
FunctionGenerator fGenMatYMenu = FunctionGenerator(FunctionGenerator::Sine, -10.0f, 10.0f, 2.7f) private
Definition at line 82 of file BasilGardenAnimation.h.
fGenMatYMove
FunctionGenerator fGenMatYMove = FunctionGenerator(FunctionGenerator::Sine, -2.0f, 2.0f, 6.7f) private
Definition at line 78 of file BasilGardenAnimation.h.
Referenced by Update().
fGenRotation
FunctionGenerator fGenRotation = FunctionGenerator(FunctionGenerator::Sine, -30.0f, 30.0f, 2.6f) private
Definition at line 75 of file BasilGardenAnimation.h.
fGenScale
FunctionGenerator fGenScale = FunctionGenerator(FunctionGenerator::Sine, 3.0f, 8.0f, 4.2f) private
Definition at line 76 of file BasilGardenAnimation.h.
fisheye
Fisheye fisheye = Fisheye() private
Definition at line 93 of file BasilGardenAnimation.h.
Referenced by Update().
glitchX
GlitchX glitchX = GlitchX(30) private
Definition at line 94 of file BasilGardenAnimation.h.
Referenced by Rage(), and Update().
gradientMat
GradientMaterial<2> gradientMat = GradientMaterial<2>(gradientSpectrum, 350.0f, false) private
Definition at line 62 of file BasilGardenAnimation.h.
Referenced by SetMaterialLayers().
gradientSpectrum
RGBColor gradientSpectrum[2] = {RGBColor(252, 145, 34), RGBColor(252, 80, 15)} private
Definition at line 61 of file BasilGardenAnimation.h.
greenMaterial
SimpleMaterial greenMaterial = SimpleMaterial(RGBColor(0, 255, 0)) private
Definition at line 56 of file BasilGardenAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
ledStripBackground
LEDStripBackground ledStripBackground private
Definition at line 47 of file BasilGardenAnimation.h.
Referenced by BasilGardenAnimation().
magnet
Magnet magnet = Magnet() private
Definition at line 97 of file BasilGardenAnimation.h.
Referenced by Update().
materialAnimator
MaterialAnimator<10> materialAnimator private
Definition at line 64 of file BasilGardenAnimation.h.
Referenced by Angry(), BasilGardenAnimation(), ForReal(), Rage(), Sad(), SetMaterialColor(), SetMaterialLayers(), and Update().
objA
ObjectAlign objA = ObjectAlign(Vector2D(0.0f, 0.0f), Vector2D(189.0f, 93.0f), Quaternion()) private
Definition at line 91 of file BasilGardenAnimation.h.
Referenced by BasilGardenAnimation(), and Update().
offsetFace
float offsetFace = 0.0f private
Definition at line 105 of file BasilGardenAnimation.h.
Referenced by LinkEasyEase(), and Update().
offsetFaceARG
float offsetFaceARG = 0.0f private
Definition at line 107 of file BasilGardenAnimation.h.
Referenced by AudioReactiveGradientFace(), and LinkEasyEase().
offsetFaceInd
uint8_t offsetFaceInd = 50 private
Definition at line 109 of file BasilGardenAnimation.h.
Referenced by AudioReactiveGradientFace(), LinkEasyEase(), OscilloscopeFace(), and SpectrumAnalyzerFace().
offsetFaceIndARG
uint8_t offsetFaceIndARG = 52 private
Definition at line 111 of file BasilGardenAnimation.h.
Referenced by AudioReactiveGradientFace(), and LinkEasyEase().
offsetFaceIndOSC
uint8_t offsetFaceIndOSC = 53 private
Definition at line 112 of file BasilGardenAnimation.h.
Referenced by LinkEasyEase(), and OscilloscopeFace().
offsetFaceIndSA
uint8_t offsetFaceIndSA = 51 private
Definition at line 110 of file BasilGardenAnimation.h.
Referenced by LinkEasyEase(), and SpectrumAnalyzerFace().
offsetFaceOSC
float offsetFaceOSC = 0.0f private
Definition at line 108 of file BasilGardenAnimation.h.
Referenced by LinkEasyEase(), and OscilloscopeFace().
offsetFaceSA
float offsetFaceSA = 0.0f private
Definition at line 106 of file BasilGardenAnimation.h.
Referenced by LinkEasyEase(), and SpectrumAnalyzerFace().
orangeMaterial
SimpleMaterial orangeMaterial = SimpleMaterial(RGBColor(255, 165, 0)) private
Definition at line 54 of file BasilGardenAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
oSC
Oscilloscope oSC = Oscilloscope(Vector2D(200, 100), Vector2D(0, 0)) private
Definition at line 69 of file BasilGardenAnimation.h.
Referenced by OscilloscopeFace(), SetMaterialLayers(), and Update().
overflow
Overflow overflow = Overflow(8) private
Definition at line 103 of file BasilGardenAnimation.h.
phaseR
PhaseOffsetR phaseR = PhaseOffsetR(8) private
Definition at line 101 of file BasilGardenAnimation.h.
Referenced by Update().
phaseX
PhaseOffsetX phaseX = PhaseOffsetX(8) private
Definition at line 99 of file BasilGardenAnimation.h.
Referenced by Update().
phaseY
PhaseOffsetY phaseY = PhaseOffsetY(8) private
Definition at line 100 of file BasilGardenAnimation.h.
Referenced by Update().
pM
BasilGarden pM private
Definition at line 45 of file BasilGardenAnimation.h.
Referenced by BasilGardenAnimation(), GetObject(), LinkEasyEase(), LinkParameters(), and Update().
purpleMaterial
SimpleMaterial purpleMaterial = SimpleMaterial(RGBColor(255, 0, 255)) private
Definition at line 59 of file BasilGardenAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
rainbowNoise
RainbowNoise rainbowNoise private
Definition at line 51 of file BasilGardenAnimation.h.
Referenced by ForReal(), SetMaterialColor(), SetMaterialLayers(), and Update().
rainbowSpiral
RainbowSpiral rainbowSpiral private
Definition at line 52 of file BasilGardenAnimation.h.
Referenced by SetMaterialColor(), SetMaterialLayers(), and Update().
redMaterial
SimpleMaterial redMaterial = SimpleMaterial(RGBColor(255, 0, 0)) private
Definition at line 53 of file BasilGardenAnimation.h.
Referenced by Angry(), Rage(), SetMaterialColor(), and SetMaterialLayers().
sA
SpectrumAnalyzer sA = SpectrumAnalyzer(Vector2D(200, 100), Vector2D(100, 50), true, true) private
Definition at line 67 of file BasilGardenAnimation.h.
Referenced by SetMaterialLayers(), SpectrumAnalyzerFace(), and Update().
shiftR
ShiftR shiftR = ShiftR(8) private
Definition at line 102 of file BasilGardenAnimation.h.
Referenced by Update().
voiceDetection
FFTVoiceDetection<128> voiceDetection private
Definition at line 89 of file BasilGardenAnimation.h.
Referenced by Update(), and UpdateFFTVisemes().
whiteMaterial
SimpleMaterial whiteMaterial = SimpleMaterial(RGBColor(255, 255, 255)) private
Definition at line 55 of file BasilGardenAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
yellowMaterial
SimpleMaterial yellowMaterial = SimpleMaterial(RGBColor(255, 255, 0)) private
Definition at line 58 of file BasilGardenAnimation.h.
Referenced by SetMaterialColor(), and SetMaterialLayers().
The documentation for this class was generated from the following file:
BasilGardenAnimation.h