var dir_3f49632ff66cf04c85d53f31be26607f =
[
    [ "DerivativeFilter.cpp", "DerivativeFilter_8cpp.html", null ],
    [ "DerivativeFilter.h", "DerivativeFilter_8h.html", "DerivativeFilter_8h" ],
    [ "FFTFilter.cpp", "FFTFilter_8cpp.html", null ],
    [ "FFTFilter.h", "FFTFilter_8h.html", "FFTFilter_8h" ],
    [ "KalmanFilter.h", "KalmanFilter_8h.html", "KalmanFilter_8h" ],
    [ "KalmanFilter.tpp", "KalmanFilter_8tpp.html", null ],
    [ "MaxFilter.h", "MaxFilter_8h.html", "MaxFilter_8h" ],
    [ "MaxFilter.tpp", "MaxFilter_8tpp.html", null ],
    [ "MinFilter.h", "MinFilter_8h.html", "MinFilter_8h" ],
    [ "MinFilter.tpp", "MinFilter_8tpp.html", null ],
    [ "PeakDetection.h", "PeakDetection_8h.html", "PeakDetection_8h" ],
    [ "PeakDetection.tpp", "PeakDetection_8tpp.html", null ],
    [ "QuaternionKalmanFilter.cpp", "QuaternionKalmanFilter_8cpp.html", null ],
    [ "QuaternionKalmanFilter.h", "QuaternionKalmanFilter_8h.html", "QuaternionKalmanFilter_8h" ],
    [ "RampFilter.cpp", "RampFilter_8cpp.html", null ],
    [ "RampFilter.h", "RampFilter_8h.html", "RampFilter_8h" ],
    [ "RunningAverageFilter.h", "RunningAverageFilter_8h.html", "RunningAverageFilter_8h" ],
    [ "RunningAverageFilter.tpp", "RunningAverageFilter_8tpp.html", null ],
    [ "VectorKalmanFilter.cpp", "VectorKalmanFilter_8cpp.html", null ],
    [ "VectorKalmanFilter.h", "VectorKalmanFilter_8h.html", "VectorKalmanFilter_8h" ],
    [ "VectorRunningAverageFilter.cpp", "VectorRunningAverageFilter_8cpp.html", null ],
    [ "VectorRunningAverageFilter.h", "VectorRunningAverageFilter_8h.html", "VectorRunningAverageFilter_8h" ]
];