var dir_bd13b5af5b51d8b72e43c09f8539fa9b =
[
    [ "Effect.cpp", "Effect_8cpp.html", null ],
    [ "Effect.h", "Effect_8h.html", "Effect_8h" ],
    [ "Fisheye.cpp", "Fisheye_8cpp.html", null ],
    [ "Fisheye.h", "Fisheye_8h.html", "Fisheye_8h" ],
    [ "GlitchX.cpp", "GlitchX_8cpp.html", null ],
    [ "GlitchX.h", "GlitchX_8h.html", "GlitchX_8h" ],
    [ "HorizontalBlur.cpp", "HorizontalBlur_8cpp.html", null ],
    [ "HorizontalBlur.h", "HorizontalBlur_8h.html", "HorizontalBlur_8h" ],
    [ "Magnet.cpp", "Magnet_8cpp.html", null ],
    [ "Magnet.h", "Magnet_8h.html", "Magnet_8h" ],
    [ "Overflow.cpp", "Overflow_8cpp.html", null ],
    [ "Overflow.h", "Overflow_8h.html", "Overflow_8h" ],
    [ "Passthrough.cpp", "Passthrough_8cpp.html", null ],
    [ "Passthrough.h", "Passthrough_8h.html", "Passthrough_8h" ],
    [ "PhaseOffsetR.cpp", "PhaseOffsetR_8cpp.html", null ],
    [ "PhaseOffsetR.h", "PhaseOffsetR_8h.html", "PhaseOffsetR_8h" ],
    [ "PhaseOffsetX.cpp", "PhaseOffsetX_8cpp.html", null ],
    [ "PhaseOffsetX.h", "PhaseOffsetX_8h.html", "PhaseOffsetX_8h" ],
    [ "PhaseOffsetY.cpp", "PhaseOffsetY_8cpp.html", null ],
    [ "PhaseOffsetY.h", "PhaseOffsetY_8h.html", "PhaseOffsetY_8h" ],
    [ "RadialBlur.cpp", "RadialBlur_8cpp.html", null ],
    [ "RadialBlur.h", "RadialBlur_8h.html", "RadialBlur_8h" ],
    [ "ShiftR.cpp", "ShiftR_8cpp.html", null ],
    [ "ShiftR.h", "ShiftR_8h.html", "ShiftR_8h" ],
    [ "Test.cpp", "Test_8cpp.html", null ],
    [ "Test.h", "Test_8h.html", "Test_8h" ],
    [ "VerticalBlur.cpp", "VerticalBlur_8cpp.html", null ],
    [ "VerticalBlur.h", "VerticalBlur_8h.html", "VerticalBlur_8h" ]
];