var hierarchy =
[
    [ "Animation", null, [
      [ "AlphaAnimation", "classAlphaAnimation.html", null ],
      [ "AphoriAnimation", "classAphoriAnimation.html", null ],
      [ "ArtisansAnimation", "classArtisansAnimation.html", null ],
      [ "ArtleckAnimationV2", "classArtleckAnimationV2.html", null ],
      [ "BasilGardenAnimation", "classBasilGardenAnimation.html", null ],
      [ "BeeAnimation", "classBeeAnimation.html", null ],
      [ "BroookAnimation", "classBroookAnimation.html", null ],
      [ "ClockAnimation", "classClockAnimation.html", null ],
      [ "CoelaBonkAnimation", "classCoelaBonkAnimation.html", null ],
      [ "CoelaNerdAnimation", "classCoelaNerdAnimation.html", null ],
      [ "Crash", "classCrash.html", null ],
      [ "CubeAnimation", "classCubeAnimation.html", null ],
      [ "ElGatoAnimation", "classElGatoAnimation.html", null ],
      [ "FullScreenAnimation", "classFullScreenAnimation.html", null ],
      [ "GalaxyAnimation", "classGalaxyAnimation.html", null ],
      [ "GammaAnimation", "classGammaAnimation.html", null ],
      [ "HUB75AnimationSplit", "classHUB75AnimationSplit.html", null ],
      [ "HertzzAnimation", "classHertzzAnimation.html", null ],
      [ "InfraredAnimation", "classInfraredAnimation.html", null ],
      [ "LeonHuskyAnimation", "classLeonHuskyAnimation.html", null ],
      [ "MyntAnimation", "classMyntAnimation.html", null ],
      [ "NukudeFaceAnimation", "classNukudeFaceAnimation.html", null ],
      [ "PikachuAnimation", "classPikachuAnimation.html", null ],
      [ "ProtobottAnimation", "classProtobottAnimation.html", null ],
      [ "ProtogenArtleckAnimation", "classProtogenArtleckAnimation.html", null ],
      [ "RocksAnimation", "classRocksAnimation.html", null ],
      [ "SammyAnimation", "classSammyAnimation.html", null ],
      [ "SergaliciousAnimation", "classSergaliciousAnimation.html", null ],
      [ "SpyroRotateAnimation", "classSpyroRotateAnimation.html", null ],
      [ "StrawberryAnimation", "classStrawberryAnimation.html", null ],
      [ "TamamoAnimation", "classTamamoAnimation.html", null ],
      [ "TechSaneAnimation", "classTechSaneAnimation.html", null ],
      [ "VectorFieldAnimation", "classVectorFieldAnimation.html", null ],
      [ "VesperAnimation", "classVesperAnimation.html", null ],
      [ "WS35AnimationSplit", "classWS35AnimationSplit.html", null ],
      [ "WaffleDaProtoAnimation", "classWaffleDaProtoAnimation.html", null ],
      [ "WaffleDaProtoAnimation", "classWaffleDaProtoAnimation.html", null ],
      [ "Warzone2Animation", "classWarzone2Animation.html", null ],
      [ "WarzoneAnimation", "classWarzoneAnimation.html", null ],
      [ "XenraxAnimation", "classXenraxAnimation.html", null ]
    ] ],
    [ "AnimationTrack< maxParameters, maxKeyFrames >", "classAnimationTrack.html", null ],
    [ "AnimationTrack< parameters, 10 >", "classAnimationTrack.html", [
      [ "BlinkTrack< 1 >", "classBlinkTrack.html", null ],
      [ "BlinkTrack< 2 >", "classBlinkTrack.html", null ],
      [ "EyeMoveTrack< 1 >", "classEyeMoveTrack.html", null ],
      [ "BlinkTrack< parameters >", "classBlinkTrack.html", null ],
      [ "EyeMoveTrack< parameters >", "classEyeMoveTrack.html", null ]
    ] ],
    [ "AnimationTrack< parameters, 5 >", "classAnimationTrack.html", [
      [ "EffectChangeTrack< 1 >", "classEffectChangeTrack.html", null ],
      [ "EffectChangeTrack< parameters >", "classEffectChangeTrack.html", null ],
      [ "MouthTrack< parameters >", "classMouthTrack.html", null ]
    ] ],
    [ "APDS9960", "classAPDS9960.html", null ],
    [ "AxisAngle", "classAxisAngle.html", null ],
    [ "BNO055", "classBNO055.html", null ],
    [ "BouncePhysics", "classBouncePhysics.html", null ],
    [ "BoundaryCube", "classBoundaryCube.html", null ],
    [ "BoundaryMotionSimulator", "classBoundaryMotionSimulator.html", null ],
    [ "BoundarySphere", "classBoundarySphere.html", null ],
    [ "BoundingBox2D", "classBoundingBox2D.html", null ],
    [ "ButtonHandler", "classButtonHandler.html", null ],
    [ "CameraBase", "classCameraBase.html", [
      [ "Camera< 88 >", "classCamera.html", null ],
      [ "Camera< 571 >", "classCamera.html", null ],
      [ "Camera< 2048 >", "classCamera.html", null ],
      [ "Camera< 27 >", "classCamera.html", null ],
      [ "Camera< 36 >", "classCamera.html", null ],
      [ "Camera< 306 >", "classCamera.html", null ],
      [ "Camera< 89 >", "classCamera.html", null ],
      [ "Camera< pixelCount >", "classCamera.html", null ]
    ] ],
    [ "CameraLayout", "classCameraLayout.html", null ],
    [ "CameraManager", "classCameraManager.html", [
      [ "APA102CamerasV1", "classAPA102CamerasV1.html", null ],
      [ "DualP3HUB75CameraManager", "classDualP3HUB75CameraManager.html", null ],
      [ "DualP3HUB75CameraManager", "classDualP3HUB75CameraManager.html", null ],
      [ "HUB75DeltaCameraManager", "classHUB75DeltaCameraManager.html", null ],
      [ "HUB75DeltaCameraManager", "classHUB75DeltaCameraManager.html", null ],
      [ "WS35BetaCameraManager", "classWS35BetaCameraManager.html", null ],
      [ "WS35CameraManager", "classWS35CameraManager.html", null ],
      [ "WS35SplitCameraManager", "classWS35SplitCameraManager.html", null ]
    ] ],
    [ "Characters", "classCharacters.html", null ],
    [ "Color< T >", "classColor.html", null ],
    [ "Controller", "classController.html", [
      [ "APA102Controller", "classAPA102Controller.html", null ],
      [ "BetaProtoController", "classBetaProtoController.html", null ],
      [ "ESP32DevKitV1", "classESP32DevKitV1.html", null ],
      [ "GammaControllerBack", "classGammaControllerBack.html", null ],
      [ "GammaControllerFront", "classGammaControllerFront.html", null ],
      [ "HUB75Controller", "classHUB75Controller.html", null ],
      [ "HUB75ControllerSplit", "classHUB75ControllerSplit.html", null ],
      [ "HUB75ControllerSquare", "classHUB75ControllerSquare.html", null ],
      [ "KaiborgV1Controller", "classKaiborgV1Controller.html", null ],
      [ "KaiborgV1D1Controller", "classKaiborgV1D1Controller.html", null ],
      [ "ProtoDRController", "classProtoDRController.html", null ],
      [ "ProtoV2Controller", "classProtoV2Controller.html", null ],
      [ "WS35BetaController", "classWS35BetaController.html", null ],
      [ "WS35Controller", "classWS35Controller.html", null ]
    ] ],
    [ "DampedSpring", "classDampedSpring.html", null ],
    [ "Data", "structSerialSync_1_1Data.html", null ],
    [ "Debug", "classDebug.html", null ],
    [ "DerivativeFilter", "classDerivativeFilter.html", null ],
    [ "DirectionAngle", "classDirectionAngle.html", null ],
    [ "DisplayTest", "classDisplayTest.html", null ],
    [ "Effect", "classEffect.html", [
      [ "Fisheye", "classFisheye.html", null ],
      [ "GlitchX", "classGlitchX.html", null ],
      [ "HeadsUpDisplay", "classHeadsUpDisplay.html", null ],
      [ "HorizontalBlur", "classHorizontalBlur.html", null ],
      [ "Magnet", "classMagnet.html", null ],
      [ "Overflow", "classOverflow.html", null ],
      [ "Passthrough", "classPassthrough.html", null ],
      [ "PhaseOffsetR", "classPhaseOffsetR.html", null ],
      [ "PhaseOffsetX", "classPhaseOffsetX.html", null ],
      [ "PhaseOffsetY", "classPhaseOffsetY.html", null ],
      [ "RadialBlur", "classRadialBlur.html", null ],
      [ "ShiftR", "classShiftR.html", null ],
      [ "Test", "classTest.html", null ],
      [ "VerticalBlur", "classVerticalBlur.html", null ]
    ] ],
    [ "ESP32Data", "structSerialInterpreter_1_1ESP32Data.html", null ],
    [ "EulerAngles", "classEulerAngles.html", null ],
    [ "EulerOrder", "classEulerOrder.html", null ],
    [ "FanController", "classFanController.html", null ],
    [ "FFT< fftSize >", "classFFT.html", null ],
    [ "FFT< FFTSize >", "classFFT.html", null ],
    [ "FFTFilter", "classFFTFilter.html", null ],
    [ "FunctionGenerator", "classFunctionGenerator.html", null ],
    [ "HardwareTest", "classHardwareTest.html", null ],
    [ "IEasyEaseAnimator", "classIEasyEaseAnimator.html", [
      [ "EasyEaseAnimator< materialCount >", "classEasyEaseAnimator.html", null ],
      [ "EasyEaseAnimator< 30 >", "classEasyEaseAnimator.html", null ],
      [ "EasyEaseAnimator< 25 >", "classEasyEaseAnimator.html", null ],
      [ "EasyEaseAnimator< 20 >", "classEasyEaseAnimator.html", null ],
      [ "EasyEaseAnimator< 21 >", "classEasyEaseAnimator.html", null ],
      [ "EasyEaseAnimator< 60 >", "classEasyEaseAnimator.html", null ],
      [ "EasyEaseAnimator< maxParameters >", "classEasyEaseAnimator.html", null ]
    ] ],
    [ "IndexGroup", "classIndexGroup.html", null ],
    [ "IPixelGroup", "classIPixelGroup.html", [
      [ "PixelGroup< 88 >", "classPixelGroup.html", null ],
      [ "PixelGroup< 571 >", "classPixelGroup.html", null ],
      [ "PixelGroup< 2048 >", "classPixelGroup.html", null ],
      [ "PixelGroup< 27 >", "classPixelGroup.html", null ],
      [ "PixelGroup< 36 >", "classPixelGroup.html", null ],
      [ "PixelGroup< 306 >", "classPixelGroup.html", null ],
      [ "PixelGroup< 89 >", "classPixelGroup.html", null ],
      [ "PixelGroup< pixelCount >", "classPixelGroup.html", null ]
    ] ],
    [ "IStaticTriangleGroup", "classIStaticTriangleGroup.html", [
      [ "StaticTriangleGroup< vertexCount, triangleCount >", "classStaticTriangleGroup.html", null ]
    ] ],
    [ "ITriangleGroup", "classITriangleGroup.html", [
      [ "TriangleGroup< vertexCount, triangleCount >", "classTriangleGroup.html", null ]
    ] ],
    [ "KalmanFilter< T >", "classKalmanFilter.html", null ],
    [ "KalmanFilter< 25 >", "classKalmanFilter.html", null ],
    [ "KeyFrame", "classKeyFrame.html", null ],
    [ "KeyFrameInterpolation", "classKeyFrameInterpolation.html", [
      [ "KeyFrameTrack< 1, 10 >", "classKeyFrameTrack.html", null ],
      [ "KeyFrameTrack< 1, 5 >", "classKeyFrameTrack.html", null ],
      [ "KeyFrameTrack< maxParameters, maxKeyFrames >", "classKeyFrameTrack.html", null ]
    ] ],
    [ "Light", "classLight.html", null ],
    [ "Material", "classMaterial.html", [
      [ "CombineMaterial< 6 >", "classCombineMaterial.html", null ],
      [ "CombineMaterial< 2 >", "classCombineMaterial.html", null ],
      [ "CombineMaterial< 4 >", "classCombineMaterial.html", null ],
      [ "CombineMaterial< 8 >", "classCombineMaterial.html", null ],
      [ "CombineMaterial< 5 >", "classCombineMaterial.html", null ],
      [ "CombineMaterial< 3 >", "classCombineMaterial.html", null ],
      [ "GradientMaterial< 6 >", "classGradientMaterial.html", null ],
      [ "GradientMaterial< 2 >", "classGradientMaterial.html", null ],
      [ "GradientMaterial< 4 >", "classGradientMaterial.html", null ],
      [ "GradientMaterial< colors >", "classGradientMaterial.html", null ],
      [ "GradientMaterial< 5 >", "classGradientMaterial.html", null ],
      [ "GradientMaterial< 10 >", "classGradientMaterial.html", null ],
      [ "GradientMaterial< 3 >", "classGradientMaterial.html", null ],
      [ "LightMaterial< 6 >", "classLightMaterial.html", null ],
      [ "MaterialAnimator< 2 >", "classMaterialAnimator.html", null ],
      [ "MaterialAnimator< 7 >", "classMaterialAnimator.html", null ],
      [ "MaterialAnimator< 15 >", "classMaterialAnimator.html", null ],
      [ "MaterialAnimator< 4 >", "classMaterialAnimator.html", null ],
      [ "MaterialAnimator< 10 >", "classMaterialAnimator.html", null ],
      [ "MaterialAnimator< 5 >", "classMaterialAnimator.html", null ],
      [ "MaterialAnimator< 20 >", "classMaterialAnimator.html", null ],
      [ "SimplexNoise< 2 >", "classSimplexNoise.html", null ],
      [ "SimplexNoise< 4 >", "classSimplexNoise.html", null ],
      [ "SimplexNoise< 5 >", "classSimplexNoise.html", null ],
      [ "TextEngine< 3, 12 >", "classTextEngine.html", null ],
      [ "TextEngine< menuRows, menuLength *menuCountEng >", "classTextEngine.html", null ],
      [ "AnimatedMaterial", "classAnimatedMaterial.html", [
        [ "FlowNoise", "classFlowNoise.html", null ],
        [ "HorizontalRainbow", "classHorizontalRainbow.html", null ],
        [ "RainbowNoise", "classRainbowNoise.html", null ],
        [ "RainbowNoise2", "classRainbowNoise2.html", null ],
        [ "RainbowSpiral", "classRainbowSpiral.html", null ],
        [ "TVStatic", "classTVStatic.html", null ]
      ] ],
      [ "AudioReactiveGradient", "classAudioReactiveGradient.html", null ],
      [ "Clock", "classClock.html", null ],
      [ "CombineMaterial< materialCount >", "classCombineMaterial.html", null ],
      [ "DepthMaterial", "classDepthMaterial.html", null ],
      [ "GradientMaterial< colorCount >", "classGradientMaterial.html", null ],
      [ "Image", "classImage.html", [
        [ "UVMap", "classUVMap.html", null ]
      ] ],
      [ "LightMaterial< lightCount >", "classLightMaterial.html", null ],
      [ "MaterialAnimator< materialCount >", "classMaterialAnimator.html", null ],
      [ "MaterialMask", "classMaterialMask.html", null ],
      [ "NormalMaterial", "classNormalMaterial.html", null ],
      [ "Oscilloscope", "classOscilloscope.html", null ],
      [ "SimpleMaterial", "classSimpleMaterial.html", null ],
      [ "SimplexNoise< colors >", "classSimplexNoise.html", null ],
      [ "SpectrumAnalyzer", "classSpectrumAnalyzer.html", null ],
      [ "SpiralMaterial", "classSpiralMaterial.html", null ],
      [ "StripeMaterial", "classStripeMaterial.html", null ],
      [ "TextEngine< lineCount, characterWidth >", "classTextEngine.html", null ],
      [ "VectorField2D", "classVectorField2D.html", null ]
    ] ],
    [ "Mathematics", "classMathematics.html", null ],
    [ "MaxFilter< memory >", "classMaxFilter.html", null ],
    [ "MaxFilter< 40 >", "classMaxFilter.html", null ],
    [ "Menu", "classMenu.html", null ],
    [ "MenuHandler< menuCount >", "classMenuHandler.html", null ],
    [ "MicrophoneFourierBase", "classMicrophoneFourierBase.html", [
      [ "MicrophoneFourier", "classMicrophoneFourier.html", null ],
      [ "MicrophoneFourier", "classMicrophoneFourier.html", null ]
    ] ],
    [ "MicrophoneSimple", "classMicrophoneSimple.html", null ],
    [ "MinFilter< memory >", "classMinFilter.html", null ],
    [ "MinFilter< 10 >", "classMinFilter.html", null ],
    [ "MinFilter< 100 >", "classMinFilter.html", null ],
    [ "MinFilter< 40 >", "classMinFilter.html", null ],
    [ "MMC56X3", "classMMC56X3.html", null ],
    [ "MorphTransform< maxMorphs >", "classMorphTransform.html", null ],
    [ "MorphTransform< 5 >", "classMorphTransform.html", null ],
    [ "Node", "classNode.html", null ],
    [ "Object3D", "classObject3D.html", null ],
    [ "ObjectAlign", "classObjectAlign.html", null ],
    [ "ObjectDeformer", "classObjectDeformer.html", null ],
    [ "PeakDetection< sampleSize >", "classPeakDetection.html", null ],
    [ "PeakDetection< peakCount >", "classPeakDetection.html", null ],
    [ "PhysicsSimulator", "classPhysicsSimulator.html", null ],
    [ "PID", "classPID.html", null ],
    [ "Pixel", "classPixel.html", null ],
    [ "Plane", "classPlane.html", null ],
    [ "Project", "classProject.html", [
      [ "Boot", "classBoot.html", null ],
      [ "CreeperAnimation", "classCreeperAnimation.html", null ],
      [ "ProtogenProject", "classProtogenProject.html", [
        [ "AceAnimation", "classAceAnimation.html", null ],
        [ "ArrowAnimation", "classArrowAnimation.html", null ],
        [ "BetaProject", "classBetaProject.html", null ],
        [ "DrGonzoProject", "classDrGonzoProject.html", null ],
        [ "DrGonzoTest", "classDrGonzoTest.html", null ],
        [ "FursuitEyesV1", "classFursuitEyesV1.html", null ],
        [ "ProtogenHUB75Project", "classProtogenHUB75Project.html", null ],
        [ "ProtogenWS35Project", "classProtogenWS35Project.html", null ],
        [ "SageAnimation", "classSageAnimation.html", null ],
        [ "SplatAnimation", "classSplatAnimation.html", null ],
        [ "UnicornZhenjaAnimation", "classUnicornZhenjaAnimation.html", null ]
      ] ],
      [ "SpyroAnimation", "classSpyroAnimation.html", null ],
      [ "VerifyEngine", "classVerifyEngine.html", null ]
    ] ],
    [ "QuadTree", "classQuadTree.html", null ],
    [ "Quaternion", "classQuaternion.html", null ],
    [ "QuaternionKalmanFilter", "classQuaternionKalmanFilter.html", null ],
    [ "RampFilter", "classRampFilter.html", null ],
    [ "Rasterizer", "classRasterizer.html", null ],
    [ "RenderingEngine", "classRenderingEngine.html", null ],
    [ "RGBColor", "classRGBColor.html", null ],
    [ "Rotation", "classRotation.html", null ],
    [ "RotationMatrix", "classRotationMatrix.html", null ],
    [ "RunningAverageFilter< memory >", "classRunningAverageFilter.html", null ],
    [ "RunningAverageFilter< 10 >", "classRunningAverageFilter.html", null ],
    [ "RunningAverageFilter< 20 >", "classRunningAverageFilter.html", null ],
    [ "RunningAverageFilter< 25 >", "classRunningAverageFilter.html", null ],
    [ "RunningAverageFilter< 40 >", "classRunningAverageFilter.html", null ],
    [ "RunningAverageFilter< 5 >", "classRunningAverageFilter.html", null ],
    [ "RunningAverageFilter< 50 >", "classRunningAverageFilter.html", null ],
    [ "Scene", "classScene.html", null ],
    [ "SerialInterpreter", "classSerialInterpreter.html", null ],
    [ "SerialSync", "classSerialSync.html", null ],
    [ "Shape", "classShape.html", [
      [ "Circle", "classCircle.html", null ],
      [ "Ellipse", "classEllipse.html", null ],
      [ "Rectangle", "classRectangle.html", null ]
    ] ],
    [ "SHARPGP2Y", "classSHARPGP2Y.html", null ],
    [ "TimeStep", "classTimeStep.html", null ],
    [ "Transform", "classTransform.html", null ],
    [ "Triangle2D", "classTriangle2D.html", null ],
    [ "Triangle3D", "classTriangle3D.html", null ],
    [ "TriangleGroupDeformer", "classTriangleGroupDeformer.html", null ],
    [ "Vector2D", "classVector2D.html", null ],
    [ "Vector3D", "classVector3D.html", null ],
    [ "VectorKalmanFilter< T >", "classVectorKalmanFilter.html", null ],
    [ "VectorRunningAverageFilter< memory >", "classVectorRunningAverageFilter.html", null ],
    [ "VectorRunningAverageFilter< 10 >", "classVectorRunningAverageFilter.html", null ],
    [ "Viseme", "classViseme.html", [
      [ "FFTVoiceDetection< 128 >", "classFFTVoiceDetection.html", null ],
      [ "FFTVoiceDetection< peakCount >", "classFFTVoiceDetection.html", null ]
    ] ],
    [ "Wait", "classWait.html", null ],
    [ "YawPitchRoll", "classYawPitchRoll.html", null ]
];