KaiborgV1D1Xenrax.h File Reference
KaiborgV1D1Xenrax.h File Reference
#include <Arduino.h>
#include <OctoWS2811.h>
#include "Controller.h"
#include "Render/Camera.h"
#include "Flash/PixelGroups/KaiborgV1Pixels.h"
#include "Flash/PixelGroups/XenraxStrip.h"
#include "Flash/PixelGroups/XenraxSquare.h"
#include "Flash/PixelGroups/XenraxRing.h"
Classes
class KaiborgV1D1Controller
Functions
OctoWS2811 leds (ledsPerStrip, displayMemory, drawingMemory, config)
Variables
const int ledsPerStrip = 346
DMAMEM int displayMemory [346 *6]
int drawingMemory [346 *6]
const int config = WS2811_GRB | WS2811_800kHz
Function Documentation
leds()
OctoWS2811 leds (ledsPerStrip , displayMemory , drawingMemory , config)
Referenced by KaiborgV1D1Controller::Display(), KaiborgV1D1Controller::Initialize(), and KaiborgV1D1Controller::SetPixels().
Variable Documentation
config
const int config = WS2811_GRB | WS2811_800kHz
Definition at line 14 of file KaiborgV1D1Xenrax.h.
displayMemory
DMAMEM int displayMemory[346 *6]
Definition at line 12 of file KaiborgV1D1Xenrax.h.
drawingMemory
int drawingMemory[346 *6]
Definition at line 13 of file KaiborgV1D1Xenrax.h.
ledsPerStrip
const int ledsPerStrip = 346
Definition at line 11 of file KaiborgV1D1Xenrax.h.