MicrophoneFourier_DMA.cpp File Reference
MicrophoneFourier_DMA.cpp File Reference
#include "MicrophoneFourier_DMA.h"
Functions
static DMAMEM volatile uint16_t __attribute__ ((aligned(32))) adc_buffer1[256]
AnalogBufferDMA adc_dma_instance (adc_buffer1, 256, adc_buffer2, 256)
const int16_t MicrophoneFourier::Hanning256[] __attribute__ ((aligned(4)))
Variables
ADC * adc = new ADC()
Function Documentation
__attribute__() [1/2]
static DMAMEM volatile uint16_t __attribute__ ((aligned(32))) static
__attribute__() [2/2]
const int16_t MicrophoneFourier::Hanning256[] __attribute__ ((aligned(4)))
adc_dma_instance()
AnalogBufferDMA adc_dma_instance (adc_buffer1 , 256 , adc_buffer2 , 256)
Referenced by MicrophoneFourier::Initialize(), MicrophoneFourier::Initialize(), and MicrophoneFourier::UpdateDMA().
Variable Documentation
adc
ADC* adc = new ADC()
Definition at line 3 of file MicrophoneFourier_DMA.cpp.
Referenced by MicrophoneFourier::Initialize(), MicrophoneFourier::Initialize(), and MicrophoneFourier::setSamplingRate().