EulerConstants Namespace Reference
EulerConstants Namespace Reference
A collection of predefined constants for Euler rotation orders.
Variables
const EulerOrder EulerOrderXYZS {EulerOrder::Axis::XYZ, EulerOrder::AxisFrame::Static, Vector3D(0, 1, 2)}
Order: X → Y → Z, static frame.
const EulerOrder EulerOrderXZYS {EulerOrder::Axis::XZY, EulerOrder::AxisFrame::Static, Vector3D(0, 2, 1)}
Order: X → Z → Y, static frame.
const EulerOrder EulerOrderYXZS {EulerOrder::Axis::YXZ, EulerOrder::AxisFrame::Static, Vector3D(1, 2, 0)}
Order: Y → X → Z, static frame.
const EulerOrder EulerOrderYZXS {EulerOrder::Axis::YZX, EulerOrder::AxisFrame::Static, Vector3D(1, 0, 2)}
Order: Y → Z → X, static frame.
const EulerOrder EulerOrderZXYS {EulerOrder::Axis::ZXY, EulerOrder::AxisFrame::Static, Vector3D(2, 0, 1)}
Order: Z → X → Y, static frame.
const EulerOrder EulerOrderZYXS {EulerOrder::Axis::ZYX, EulerOrder::AxisFrame::Static, Vector3D(2, 1, 0)}
Order: Z → Y → X, static frame.
const EulerOrder EulerOrderZYXR {EulerOrder::Axis::XYZ, EulerOrder::AxisFrame::Rotating, Vector3D(0, 1, 2)}
Order: Z → Y → X, rotating frame.
const EulerOrder EulerOrderYZXR {EulerOrder::Axis::XZY, EulerOrder::AxisFrame::Rotating, Vector3D(0, 2, 1)}
Order: Y → Z → X, rotating frame.
const EulerOrder EulerOrderXZYR {EulerOrder::Axis::YXZ, EulerOrder::AxisFrame::Rotating, Vector3D(1, 2, 0)}
Order: X → Z → Y, rotating frame.
const EulerOrder EulerOrderZXYR {EulerOrder::Axis::YZX, EulerOrder::AxisFrame::Rotating, Vector3D(1, 0, 2)}
Order: Z → X → Y, rotating frame.
const EulerOrder EulerOrderYXZR {EulerOrder::Axis::ZXY, EulerOrder::AxisFrame::Rotating, Vector3D(2, 0, 1)}
Order: Y → X → Z, rotating frame.
const EulerOrder EulerOrderXYZR {EulerOrder::Axis::ZYX, EulerOrder::AxisFrame::Rotating, Vector3D(2, 1, 0)}
Order: X → Y → Z, rotating frame.
Detailed Description
A collection of predefined constants for Euler rotation orders.
The EulerConstants namespace contains a variety of EulerOrder configurations commonly used in 3D rotations. These orders are grouped into two categories:
Static frame of reference (inertial).
Rotating frame of reference (non-inertial).
Variable Documentation
EulerOrderXYZR
const EulerOrder EulerOrderXYZR {EulerOrder::Axis::ZYX, EulerOrder::AxisFrame::Rotating, Vector3D(2, 1, 0)}
Order: X → Y → Z, rotating frame.
Definition at line 19 of file EulerConstants.cpp.
EulerOrderXYZS
const EulerOrder EulerOrderXYZS {EulerOrder::Axis::XYZ, EulerOrder::AxisFrame::Static, Vector3D(0, 1, 2)}
Order: X → Y → Z, static frame.
Definition at line 6 of file EulerConstants.cpp.
Referenced by ObjectAlign::GetPlaneNormal(), ObjectAlign::GetPlaneOrientation(), SpiralMaterial::GetRGB(), Transform::Rotate(), Transform::SetRotation(), Transform::ToString(), Transform::Transform(), and Transform::Transform().
EulerOrderXZYR
const EulerOrder EulerOrderXZYR {EulerOrder::Axis::YXZ, EulerOrder::AxisFrame::Rotating, Vector3D(1, 2, 0)}
Order: X → Z → Y, rotating frame.
Definition at line 16 of file EulerConstants.cpp.
EulerOrderXZYS
const EulerOrder EulerOrderXZYS {EulerOrder::Axis::XZY, EulerOrder::AxisFrame::Static, Vector3D(0, 2, 1)}
Order: X → Z → Y, static frame.
Definition at line 7 of file EulerConstants.cpp.
Referenced by AlphaAnimation::SpyroDisplay(), ArtisansAnimation::Update(), BeeAnimation::Update(), CoelaBonkAnimation::Update(), CoelaNerdAnimation::Update(), CreeperAnimation::Update(), CubeAnimation::Update(), PikachuAnimation::Update(), RocksAnimation::Update(), and SpyroAnimation::Update().
EulerOrderYXZR
const EulerOrder EulerOrderYXZR {EulerOrder::Axis::ZXY, EulerOrder::AxisFrame::Rotating, Vector3D(2, 0, 1)}
Order: Y → X → Z, rotating frame.
Definition at line 18 of file EulerConstants.cpp.
EulerOrderYXZS
const EulerOrder EulerOrderYXZS {EulerOrder::Axis::YXZ, EulerOrder::AxisFrame::Static, Vector3D(1, 2, 0)}
Order: Y → X → Z, static frame.
Definition at line 8 of file EulerConstants.cpp.
EulerOrderYZXR
const EulerOrder EulerOrderYZXR {EulerOrder::Axis::XZY, EulerOrder::AxisFrame::Rotating, Vector3D(0, 2, 1)}
Order: Y → Z → X, rotating frame.
Definition at line 15 of file EulerConstants.cpp.
EulerOrderYZXS
const EulerOrder EulerOrderYZXS {EulerOrder::Axis::YZX, EulerOrder::AxisFrame::Static, Vector3D(1, 0, 2)}
Order: Y → Z → X, static frame.
Definition at line 9 of file EulerConstants.cpp.
EulerOrderZXYR
const EulerOrder EulerOrderZXYR {EulerOrder::Axis::YZX, EulerOrder::AxisFrame::Rotating, Vector3D(1, 0, 2)}
Order: Z → X → Y, rotating frame.
Definition at line 17 of file EulerConstants.cpp.
EulerOrderZXYS
const EulerOrder EulerOrderZXYS {EulerOrder::Axis::ZXY, EulerOrder::AxisFrame::Static, Vector3D(2, 0, 1)}
Order: Z → X → Y, static frame.
Definition at line 10 of file EulerConstants.cpp.
EulerOrderZYXR
const EulerOrder EulerOrderZYXR {EulerOrder::Axis::XYZ, EulerOrder::AxisFrame::Rotating, Vector3D(0, 1, 2)}
Order: Z → Y → X, rotating frame.
Definition at line 14 of file EulerConstants.cpp.
EulerOrderZYXS
const EulerOrder EulerOrderZYXS {EulerOrder::Axis::ZYX, EulerOrder::AxisFrame::Static, Vector3D(2, 1, 0)}
Order: Z → Y → X, static frame.
Definition at line 11 of file EulerConstants.cpp.